<#if CONFIG_USE_TEST_HARNESS == true>
<#--
  Number of Library Instances:
-->
<#assign lib_instances = [ CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX0,
                           CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX1,
                           CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX2,
                           CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX3,
                           CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX4,
                           CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX5,
                           CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX6,
                           CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX7,
                           CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX8,
                           CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX9,
                           CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX10,
                           CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX11,
                           CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX12,
                           CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX13,
                           CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX14,
                           CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX15 ]>
<#--
  Task Function Names:
-->
<#assign func_name =  [ CONFIG_TEST_LIBRARY_IDX0_TASKS_IDX0,
                        CONFIG_TEST_LIBRARY_IDX0_TASKS_IDX1,
                        CONFIG_TEST_LIBRARY_IDX0_TASKS_IDX2,
                        CONFIG_TEST_LIBRARY_IDX0_TASKS_IDX3,
                        CONFIG_TEST_LIBRARY_IDX0_TASKS_IDX4,
                     
                        CONFIG_TEST_LIBRARY_IDX1_TASKS_IDX0,
                        CONFIG_TEST_LIBRARY_IDX1_TASKS_IDX1,
                        CONFIG_TEST_LIBRARY_IDX1_TASKS_IDX2,
                        CONFIG_TEST_LIBRARY_IDX1_TASKS_IDX3,
                        CONFIG_TEST_LIBRARY_IDX1_TASKS_IDX4,
                     
                        CONFIG_TEST_LIBRARY_IDX2_TASKS_IDX0,
                        CONFIG_TEST_LIBRARY_IDX2_TASKS_IDX1,
                        CONFIG_TEST_LIBRARY_IDX2_TASKS_IDX2,
                        CONFIG_TEST_LIBRARY_IDX2_TASKS_IDX3,
                        CONFIG_TEST_LIBRARY_IDX2_TASKS_IDX4,
                     
                        CONFIG_TEST_LIBRARY_IDX3_TASKS_IDX0,
                        CONFIG_TEST_LIBRARY_IDX3_TASKS_IDX1,
                        CONFIG_TEST_LIBRARY_IDX3_TASKS_IDX2,
                        CONFIG_TEST_LIBRARY_IDX3_TASKS_IDX3,
                        CONFIG_TEST_LIBRARY_IDX3_TASKS_IDX4,
                     
                        CONFIG_TEST_LIBRARY_IDX4_TASKS_IDX0,
                        CONFIG_TEST_LIBRARY_IDX4_TASKS_IDX1,
                        CONFIG_TEST_LIBRARY_IDX4_TASKS_IDX2,
                        CONFIG_TEST_LIBRARY_IDX4_TASKS_IDX3,
                        CONFIG_TEST_LIBRARY_IDX4_TASKS_IDX4,
                     
                        CONFIG_TEST_LIBRARY_IDX5_TASKS_IDX0,
                        CONFIG_TEST_LIBRARY_IDX5_TASKS_IDX1,
                        CONFIG_TEST_LIBRARY_IDX5_TASKS_IDX2,
                        CONFIG_TEST_LIBRARY_IDX5_TASKS_IDX3,
                        CONFIG_TEST_LIBRARY_IDX5_TASKS_IDX4,
                     
                        CONFIG_TEST_LIBRARY_IDX6_TASKS_IDX0,
                        CONFIG_TEST_LIBRARY_IDX6_TASKS_IDX1,
                        CONFIG_TEST_LIBRARY_IDX6_TASKS_IDX2,
                        CONFIG_TEST_LIBRARY_IDX6_TASKS_IDX3,
                        CONFIG_TEST_LIBRARY_IDX6_TASKS_IDX4,
                     
                        CONFIG_TEST_LIBRARY_IDX7_TASKS_IDX0,
                        CONFIG_TEST_LIBRARY_IDX7_TASKS_IDX1,
                        CONFIG_TEST_LIBRARY_IDX7_TASKS_IDX2,
                        CONFIG_TEST_LIBRARY_IDX7_TASKS_IDX3,
                        CONFIG_TEST_LIBRARY_IDX7_TASKS_IDX4,
                     
                        CONFIG_TEST_LIBRARY_IDX8_TASKS_IDX0,
                        CONFIG_TEST_LIBRARY_IDX8_TASKS_IDX1,
                        CONFIG_TEST_LIBRARY_IDX8_TASKS_IDX2,
                        CONFIG_TEST_LIBRARY_IDX8_TASKS_IDX3,
                        CONFIG_TEST_LIBRARY_IDX8_TASKS_IDX4,
                     
                        CONFIG_TEST_LIBRARY_IDX9_TASKS_IDX0,
                        CONFIG_TEST_LIBRARY_IDX9_TASKS_IDX1,
                        CONFIG_TEST_LIBRARY_IDX9_TASKS_IDX2,
                        CONFIG_TEST_LIBRARY_IDX9_TASKS_IDX3,
                        CONFIG_TEST_LIBRARY_IDX9_TASKS_IDX4,
                     
                        CONFIG_TEST_LIBRARY_IDX10_TASKS_IDX0,
                        CONFIG_TEST_LIBRARY_IDX10_TASKS_IDX1,
                        CONFIG_TEST_LIBRARY_IDX10_TASKS_IDX2,
                        CONFIG_TEST_LIBRARY_IDX10_TASKS_IDX3,
                        CONFIG_TEST_LIBRARY_IDX10_TASKS_IDX4,
                     
                        CONFIG_TEST_LIBRARY_IDX11_TASKS_IDX0,
                        CONFIG_TEST_LIBRARY_IDX11_TASKS_IDX1,
                        CONFIG_TEST_LIBRARY_IDX11_TASKS_IDX2,
                        CONFIG_TEST_LIBRARY_IDX11_TASKS_IDX3,
                        CONFIG_TEST_LIBRARY_IDX11_TASKS_IDX4,
                     
                        CONFIG_TEST_LIBRARY_IDX12_TASKS_IDX0,
                        CONFIG_TEST_LIBRARY_IDX12_TASKS_IDX1,
                        CONFIG_TEST_LIBRARY_IDX12_TASKS_IDX2,
                        CONFIG_TEST_LIBRARY_IDX12_TASKS_IDX3,
                        CONFIG_TEST_LIBRARY_IDX12_TASKS_IDX4,
                     
                        CONFIG_TEST_LIBRARY_IDX13_TASKS_IDX0,
                        CONFIG_TEST_LIBRARY_IDX13_TASKS_IDX1,
                        CONFIG_TEST_LIBRARY_IDX13_TASKS_IDX2,
                        CONFIG_TEST_LIBRARY_IDX13_TASKS_IDX3,
                        CONFIG_TEST_LIBRARY_IDX13_TASKS_IDX4,
                     
                        CONFIG_TEST_LIBRARY_IDX14_TASKS_IDX0,
                        CONFIG_TEST_LIBRARY_IDX14_TASKS_IDX1,
                        CONFIG_TEST_LIBRARY_IDX14_TASKS_IDX2,
                        CONFIG_TEST_LIBRARY_IDX14_TASKS_IDX3,
                        CONFIG_TEST_LIBRARY_IDX14_TASKS_IDX4,
                     
                        CONFIG_TEST_LIBRARY_IDX15_TASKS_IDX0,
                        CONFIG_TEST_LIBRARY_IDX15_TASKS_IDX1,
                        CONFIG_TEST_LIBRARY_IDX15_TASKS_IDX2,
                        CONFIG_TEST_LIBRARY_IDX15_TASKS_IDX3,
                        CONFIG_TEST_LIBRARY_IDX15_TASKS_IDX4 ]>
<#--
  Task Interrupt Driven (boolean):
-->
<#assign func_ints  = [ CONFIG_TEST_LIBRARY_IDX0_TASKS_IDX0_INTERRUPT,
                        CONFIG_TEST_LIBRARY_IDX0_TASKS_IDX1_INTERRUPT,
                        CONFIG_TEST_LIBRARY_IDX0_TASKS_IDX2_INTERRUPT,
                        CONFIG_TEST_LIBRARY_IDX0_TASKS_IDX3_INTERRUPT,
                        CONFIG_TEST_LIBRARY_IDX0_TASKS_IDX4_INTERRUPT,
                     
                        CONFIG_TEST_LIBRARY_IDX1_TASKS_IDX0_INTERRUPT,
                        CONFIG_TEST_LIBRARY_IDX1_TASKS_IDX1_INTERRUPT,
                        CONFIG_TEST_LIBRARY_IDX1_TASKS_IDX2_INTERRUPT,
                        CONFIG_TEST_LIBRARY_IDX1_TASKS_IDX3_INTERRUPT,
                        CONFIG_TEST_LIBRARY_IDX1_TASKS_IDX4_INTERRUPT,
                     
                        CONFIG_TEST_LIBRARY_IDX2_TASKS_IDX0_INTERRUPT,
                        CONFIG_TEST_LIBRARY_IDX2_TASKS_IDX1_INTERRUPT,
                        CONFIG_TEST_LIBRARY_IDX2_TASKS_IDX2_INTERRUPT,
                        CONFIG_TEST_LIBRARY_IDX2_TASKS_IDX3_INTERRUPT,
                        CONFIG_TEST_LIBRARY_IDX2_TASKS_IDX4_INTERRUPT,
                     
                        CONFIG_TEST_LIBRARY_IDX3_TASKS_IDX0_INTERRUPT,
                        CONFIG_TEST_LIBRARY_IDX3_TASKS_IDX1_INTERRUPT,
                        CONFIG_TEST_LIBRARY_IDX3_TASKS_IDX2_INTERRUPT,
                        CONFIG_TEST_LIBRARY_IDX3_TASKS_IDX3_INTERRUPT,
                        CONFIG_TEST_LIBRARY_IDX3_TASKS_IDX4_INTERRUPT,
                     
                        CONFIG_TEST_LIBRARY_IDX4_TASKS_IDX0_INTERRUPT,
                        CONFIG_TEST_LIBRARY_IDX4_TASKS_IDX1_INTERRUPT,
                        CONFIG_TEST_LIBRARY_IDX4_TASKS_IDX2_INTERRUPT,
                        CONFIG_TEST_LIBRARY_IDX4_TASKS_IDX3_INTERRUPT,
                        CONFIG_TEST_LIBRARY_IDX4_TASKS_IDX4_INTERRUPT,
                     
                        CONFIG_TEST_LIBRARY_IDX5_TASKS_IDX0_INTERRUPT,
                        CONFIG_TEST_LIBRARY_IDX5_TASKS_IDX1_INTERRUPT,
                        CONFIG_TEST_LIBRARY_IDX5_TASKS_IDX2_INTERRUPT,
                        CONFIG_TEST_LIBRARY_IDX5_TASKS_IDX3_INTERRUPT,
                        CONFIG_TEST_LIBRARY_IDX5_TASKS_IDX4_INTERRUPT,
                     
                        CONFIG_TEST_LIBRARY_IDX6_TASKS_IDX0_INTERRUPT,
                        CONFIG_TEST_LIBRARY_IDX6_TASKS_IDX1_INTERRUPT,
                        CONFIG_TEST_LIBRARY_IDX6_TASKS_IDX2_INTERRUPT,
                        CONFIG_TEST_LIBRARY_IDX6_TASKS_IDX3_INTERRUPT,
                        CONFIG_TEST_LIBRARY_IDX6_TASKS_IDX4_INTERRUPT,
                     
                        CONFIG_TEST_LIBRARY_IDX7_TASKS_IDX0_INTERRUPT,
                        CONFIG_TEST_LIBRARY_IDX7_TASKS_IDX1_INTERRUPT,
                        CONFIG_TEST_LIBRARY_IDX7_TASKS_IDX2_INTERRUPT,
                        CONFIG_TEST_LIBRARY_IDX7_TASKS_IDX3_INTERRUPT,
                        CONFIG_TEST_LIBRARY_IDX7_TASKS_IDX4_INTERRUPT,
                     
                        CONFIG_TEST_LIBRARY_IDX8_TASKS_IDX0_INTERRUPT,
                        CONFIG_TEST_LIBRARY_IDX8_TASKS_IDX1_INTERRUPT,
                        CONFIG_TEST_LIBRARY_IDX8_TASKS_IDX2_INTERRUPT,
                        CONFIG_TEST_LIBRARY_IDX8_TASKS_IDX3_INTERRUPT,
                        CONFIG_TEST_LIBRARY_IDX8_TASKS_IDX4_INTERRUPT,
                     
                        CONFIG_TEST_LIBRARY_IDX9_TASKS_IDX0_INTERRUPT,
                        CONFIG_TEST_LIBRARY_IDX9_TASKS_IDX1_INTERRUPT,
                        CONFIG_TEST_LIBRARY_IDX9_TASKS_IDX2_INTERRUPT,
                        CONFIG_TEST_LIBRARY_IDX9_TASKS_IDX3_INTERRUPT,
                        CONFIG_TEST_LIBRARY_IDX9_TASKS_IDX4_INTERRUPT,
                     
                        CONFIG_TEST_LIBRARY_IDX10_TASKS_IDX0_INTERRUPT,
                        CONFIG_TEST_LIBRARY_IDX10_TASKS_IDX1_INTERRUPT,
                        CONFIG_TEST_LIBRARY_IDX10_TASKS_IDX2_INTERRUPT,
                        CONFIG_TEST_LIBRARY_IDX10_TASKS_IDX3_INTERRUPT,
                        CONFIG_TEST_LIBRARY_IDX10_TASKS_IDX4_INTERRUPT,
                     
                        CONFIG_TEST_LIBRARY_IDX11_TASKS_IDX0_INTERRUPT,
                        CONFIG_TEST_LIBRARY_IDX11_TASKS_IDX1_INTERRUPT,
                        CONFIG_TEST_LIBRARY_IDX11_TASKS_IDX2_INTERRUPT,
                        CONFIG_TEST_LIBRARY_IDX11_TASKS_IDX3_INTERRUPT,
                        CONFIG_TEST_LIBRARY_IDX11_TASKS_IDX4_INTERRUPT,
                     
                        CONFIG_TEST_LIBRARY_IDX12_TASKS_IDX0_INTERRUPT,
                        CONFIG_TEST_LIBRARY_IDX12_TASKS_IDX1_INTERRUPT,
                        CONFIG_TEST_LIBRARY_IDX12_TASKS_IDX2_INTERRUPT,
                        CONFIG_TEST_LIBRARY_IDX12_TASKS_IDX3_INTERRUPT,
                        CONFIG_TEST_LIBRARY_IDX12_TASKS_IDX4_INTERRUPT,
                     
                        CONFIG_TEST_LIBRARY_IDX13_TASKS_IDX0_INTERRUPT,
                        CONFIG_TEST_LIBRARY_IDX13_TASKS_IDX1_INTERRUPT,
                        CONFIG_TEST_LIBRARY_IDX13_TASKS_IDX2_INTERRUPT,
                        CONFIG_TEST_LIBRARY_IDX13_TASKS_IDX3_INTERRUPT,
                        CONFIG_TEST_LIBRARY_IDX13_TASKS_IDX4_INTERRUPT,
                     
                        CONFIG_TEST_LIBRARY_IDX14_TASKS_IDX0_INTERRUPT,
                        CONFIG_TEST_LIBRARY_IDX14_TASKS_IDX1_INTERRUPT,
                        CONFIG_TEST_LIBRARY_IDX14_TASKS_IDX2_INTERRUPT,
                        CONFIG_TEST_LIBRARY_IDX14_TASKS_IDX3_INTERRUPT,
                        CONFIG_TEST_LIBRARY_IDX14_TASKS_IDX4_INTERRUPT,
                     
                        CONFIG_TEST_LIBRARY_IDX15_TASKS_IDX0_INTERRUPT,
                        CONFIG_TEST_LIBRARY_IDX15_TASKS_IDX1_INTERRUPT,
                        CONFIG_TEST_LIBRARY_IDX15_TASKS_IDX2_INTERRUPT,
                        CONFIG_TEST_LIBRARY_IDX15_TASKS_IDX3_INTERRUPT,
                        CONFIG_TEST_LIBRARY_IDX15_TASKS_IDX4_INTERRUPT ]>
<#--
  Task Priority:
-->
<#assign priority   = [ CONFIG_TEST_LIBRARY_0_INSTANCE_0_TASKS_0_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_0_INSTANCE_0_TASKS_1_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_0_INSTANCE_0_TASKS_2_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_0_INSTANCE_0_TASKS_3_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_0_INSTANCE_0_TASKS_4_RTOS_TASK_PRIORITY,

                        CONFIG_TEST_LIBRARY_0_INSTANCE_1_TASKS_0_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_0_INSTANCE_1_TASKS_1_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_0_INSTANCE_1_TASKS_2_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_0_INSTANCE_1_TASKS_3_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_0_INSTANCE_1_TASKS_4_RTOS_TASK_PRIORITY,

                        CONFIG_TEST_LIBRARY_0_INSTANCE_2_TASKS_0_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_0_INSTANCE_2_TASKS_1_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_0_INSTANCE_2_TASKS_2_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_0_INSTANCE_2_TASKS_3_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_0_INSTANCE_2_TASKS_4_RTOS_TASK_PRIORITY,

                        CONFIG_TEST_LIBRARY_1_INSTANCE_0_TASKS_0_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_1_INSTANCE_0_TASKS_1_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_1_INSTANCE_0_TASKS_2_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_1_INSTANCE_0_TASKS_3_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_1_INSTANCE_0_TASKS_4_RTOS_TASK_PRIORITY,

                        CONFIG_TEST_LIBRARY_1_INSTANCE_1_TASKS_0_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_1_INSTANCE_1_TASKS_1_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_1_INSTANCE_1_TASKS_2_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_1_INSTANCE_1_TASKS_3_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_1_INSTANCE_1_TASKS_4_RTOS_TASK_PRIORITY,

                        CONFIG_TEST_LIBRARY_1_INSTANCE_2_TASKS_0_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_1_INSTANCE_2_TASKS_1_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_1_INSTANCE_2_TASKS_2_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_1_INSTANCE_2_TASKS_3_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_1_INSTANCE_2_TASKS_4_RTOS_TASK_PRIORITY,

                        CONFIG_TEST_LIBRARY_2_INSTANCE_0_TASKS_0_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_2_INSTANCE_0_TASKS_1_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_2_INSTANCE_0_TASKS_2_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_2_INSTANCE_0_TASKS_3_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_2_INSTANCE_0_TASKS_4_RTOS_TASK_PRIORITY,
                                                        
                        CONFIG_TEST_LIBRARY_2_INSTANCE_1_TASKS_0_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_2_INSTANCE_1_TASKS_1_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_2_INSTANCE_1_TASKS_2_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_2_INSTANCE_1_TASKS_3_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_2_INSTANCE_1_TASKS_4_RTOS_TASK_PRIORITY,
                                                        
                        CONFIG_TEST_LIBRARY_2_INSTANCE_2_TASKS_0_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_2_INSTANCE_2_TASKS_1_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_2_INSTANCE_2_TASKS_2_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_2_INSTANCE_2_TASKS_3_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_2_INSTANCE_2_TASKS_4_RTOS_TASK_PRIORITY,

                        CONFIG_TEST_LIBRARY_3_INSTANCE_0_TASKS_0_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_3_INSTANCE_0_TASKS_1_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_3_INSTANCE_0_TASKS_2_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_3_INSTANCE_0_TASKS_3_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_3_INSTANCE_0_TASKS_4_RTOS_TASK_PRIORITY,
                                                        
                        CONFIG_TEST_LIBRARY_3_INSTANCE_1_TASKS_0_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_3_INSTANCE_1_TASKS_1_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_3_INSTANCE_1_TASKS_2_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_3_INSTANCE_1_TASKS_3_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_3_INSTANCE_1_TASKS_4_RTOS_TASK_PRIORITY,
                                                        
                        CONFIG_TEST_LIBRARY_3_INSTANCE_2_TASKS_0_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_3_INSTANCE_2_TASKS_1_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_3_INSTANCE_2_TASKS_2_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_3_INSTANCE_2_TASKS_3_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_3_INSTANCE_2_TASKS_4_RTOS_TASK_PRIORITY,

                        CONFIG_TEST_LIBRARY_4_INSTANCE_0_TASKS_0_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_4_INSTANCE_0_TASKS_1_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_4_INSTANCE_0_TASKS_2_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_4_INSTANCE_0_TASKS_3_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_4_INSTANCE_0_TASKS_4_RTOS_TASK_PRIORITY,
                                                        
                        CONFIG_TEST_LIBRARY_4_INSTANCE_1_TASKS_0_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_4_INSTANCE_1_TASKS_1_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_4_INSTANCE_1_TASKS_2_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_4_INSTANCE_1_TASKS_3_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_4_INSTANCE_1_TASKS_4_RTOS_TASK_PRIORITY,
                                                        
                        CONFIG_TEST_LIBRARY_4_INSTANCE_2_TASKS_0_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_4_INSTANCE_2_TASKS_1_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_4_INSTANCE_2_TASKS_2_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_4_INSTANCE_2_TASKS_3_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_4_INSTANCE_2_TASKS_4_RTOS_TASK_PRIORITY,

                        CONFIG_TEST_LIBRARY_5_INSTANCE_0_TASKS_0_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_5_INSTANCE_0_TASKS_1_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_5_INSTANCE_0_TASKS_2_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_5_INSTANCE_0_TASKS_3_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_5_INSTANCE_0_TASKS_4_RTOS_TASK_PRIORITY,
                                                        
                        CONFIG_TEST_LIBRARY_5_INSTANCE_1_TASKS_0_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_5_INSTANCE_1_TASKS_1_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_5_INSTANCE_1_TASKS_2_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_5_INSTANCE_1_TASKS_3_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_5_INSTANCE_1_TASKS_4_RTOS_TASK_PRIORITY,
                                                        
                        CONFIG_TEST_LIBRARY_5_INSTANCE_2_TASKS_0_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_5_INSTANCE_2_TASKS_1_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_5_INSTANCE_2_TASKS_2_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_5_INSTANCE_2_TASKS_3_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_5_INSTANCE_2_TASKS_4_RTOS_TASK_PRIORITY,

                        CONFIG_TEST_LIBRARY_6_INSTANCE_0_TASKS_0_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_6_INSTANCE_0_TASKS_1_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_6_INSTANCE_0_TASKS_2_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_6_INSTANCE_0_TASKS_3_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_6_INSTANCE_0_TASKS_4_RTOS_TASK_PRIORITY,
                                                        
                        CONFIG_TEST_LIBRARY_6_INSTANCE_1_TASKS_0_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_6_INSTANCE_1_TASKS_1_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_6_INSTANCE_1_TASKS_2_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_6_INSTANCE_1_TASKS_3_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_6_INSTANCE_1_TASKS_4_RTOS_TASK_PRIORITY,
                                                        
                        CONFIG_TEST_LIBRARY_6_INSTANCE_2_TASKS_0_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_6_INSTANCE_2_TASKS_1_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_6_INSTANCE_2_TASKS_2_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_6_INSTANCE_2_TASKS_3_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_6_INSTANCE_2_TASKS_4_RTOS_TASK_PRIORITY,
                                                        
                        CONFIG_TEST_LIBRARY_7_INSTANCE_0_TASKS_0_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_7_INSTANCE_0_TASKS_1_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_7_INSTANCE_0_TASKS_2_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_7_INSTANCE_0_TASKS_3_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_7_INSTANCE_0_TASKS_4_RTOS_TASK_PRIORITY,
                                                        
                        CONFIG_TEST_LIBRARY_7_INSTANCE_1_TASKS_0_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_7_INSTANCE_1_TASKS_1_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_7_INSTANCE_1_TASKS_2_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_7_INSTANCE_1_TASKS_3_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_7_INSTANCE_1_TASKS_4_RTOS_TASK_PRIORITY,
                                                        
                        CONFIG_TEST_LIBRARY_7_INSTANCE_2_TASKS_0_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_7_INSTANCE_2_TASKS_1_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_7_INSTANCE_2_TASKS_2_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_7_INSTANCE_2_TASKS_3_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_7_INSTANCE_2_TASKS_4_RTOS_TASK_PRIORITY,
                                                        
                        CONFIG_TEST_LIBRARY_8_INSTANCE_0_TASKS_0_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_8_INSTANCE_0_TASKS_1_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_8_INSTANCE_0_TASKS_2_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_8_INSTANCE_0_TASKS_3_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_8_INSTANCE_0_TASKS_4_RTOS_TASK_PRIORITY,
                                                        
                        CONFIG_TEST_LIBRARY_8_INSTANCE_1_TASKS_0_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_8_INSTANCE_1_TASKS_1_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_8_INSTANCE_1_TASKS_2_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_8_INSTANCE_1_TASKS_3_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_8_INSTANCE_1_TASKS_4_RTOS_TASK_PRIORITY,
                                                        
                        CONFIG_TEST_LIBRARY_8_INSTANCE_2_TASKS_0_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_8_INSTANCE_2_TASKS_1_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_8_INSTANCE_2_TASKS_2_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_8_INSTANCE_2_TASKS_3_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_8_INSTANCE_2_TASKS_4_RTOS_TASK_PRIORITY,
                                                        
                        CONFIG_TEST_LIBRARY_9_INSTANCE_0_TASKS_0_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_9_INSTANCE_0_TASKS_1_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_9_INSTANCE_0_TASKS_2_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_9_INSTANCE_0_TASKS_3_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_9_INSTANCE_0_TASKS_4_RTOS_TASK_PRIORITY,
                                                        
                        CONFIG_TEST_LIBRARY_9_INSTANCE_1_TASKS_0_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_9_INSTANCE_1_TASKS_1_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_9_INSTANCE_1_TASKS_2_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_9_INSTANCE_1_TASKS_3_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_9_INSTANCE_1_TASKS_4_RTOS_TASK_PRIORITY,
                                                        
                        CONFIG_TEST_LIBRARY_9_INSTANCE_2_TASKS_0_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_9_INSTANCE_2_TASKS_1_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_9_INSTANCE_2_TASKS_2_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_9_INSTANCE_2_TASKS_3_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_9_INSTANCE_2_TASKS_4_RTOS_TASK_PRIORITY,

                        CONFIG_TEST_LIBRARY_10_INSTANCE_0_TASKS_0_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_10_INSTANCE_0_TASKS_1_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_10_INSTANCE_0_TASKS_2_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_10_INSTANCE_0_TASKS_3_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_10_INSTANCE_0_TASKS_4_RTOS_TASK_PRIORITY,
                                                         
                        CONFIG_TEST_LIBRARY_10_INSTANCE_1_TASKS_0_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_10_INSTANCE_1_TASKS_1_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_10_INSTANCE_1_TASKS_2_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_10_INSTANCE_1_TASKS_3_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_10_INSTANCE_1_TASKS_4_RTOS_TASK_PRIORITY,
                                                         
                        CONFIG_TEST_LIBRARY_10_INSTANCE_2_TASKS_0_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_10_INSTANCE_2_TASKS_1_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_10_INSTANCE_2_TASKS_2_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_10_INSTANCE_2_TASKS_3_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_10_INSTANCE_2_TASKS_4_RTOS_TASK_PRIORITY,
                                                         
                        CONFIG_TEST_LIBRARY_11_INSTANCE_0_TASKS_0_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_11_INSTANCE_0_TASKS_1_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_11_INSTANCE_0_TASKS_2_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_11_INSTANCE_0_TASKS_3_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_11_INSTANCE_0_TASKS_4_RTOS_TASK_PRIORITY,
                                                         
                        CONFIG_TEST_LIBRARY_11_INSTANCE_1_TASKS_0_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_11_INSTANCE_1_TASKS_1_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_11_INSTANCE_1_TASKS_2_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_11_INSTANCE_1_TASKS_3_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_11_INSTANCE_1_TASKS_4_RTOS_TASK_PRIORITY,
                                                         
                        CONFIG_TEST_LIBRARY_11_INSTANCE_2_TASKS_0_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_11_INSTANCE_2_TASKS_1_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_11_INSTANCE_2_TASKS_2_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_11_INSTANCE_2_TASKS_3_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_11_INSTANCE_2_TASKS_4_RTOS_TASK_PRIORITY,
                                                         
                        CONFIG_TEST_LIBRARY_12_INSTANCE_0_TASKS_0_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_12_INSTANCE_0_TASKS_1_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_12_INSTANCE_0_TASKS_2_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_12_INSTANCE_0_TASKS_3_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_12_INSTANCE_0_TASKS_4_RTOS_TASK_PRIORITY,
                                                         
                        CONFIG_TEST_LIBRARY_12_INSTANCE_1_TASKS_0_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_12_INSTANCE_1_TASKS_1_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_12_INSTANCE_1_TASKS_2_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_12_INSTANCE_1_TASKS_3_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_12_INSTANCE_1_TASKS_4_RTOS_TASK_PRIORITY,
                                                         
                        CONFIG_TEST_LIBRARY_12_INSTANCE_2_TASKS_0_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_12_INSTANCE_2_TASKS_1_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_12_INSTANCE_2_TASKS_2_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_12_INSTANCE_2_TASKS_3_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_12_INSTANCE_2_TASKS_4_RTOS_TASK_PRIORITY,
                                                         
                        CONFIG_TEST_LIBRARY_13_INSTANCE_0_TASKS_0_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_13_INSTANCE_0_TASKS_1_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_13_INSTANCE_0_TASKS_2_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_13_INSTANCE_0_TASKS_3_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_13_INSTANCE_0_TASKS_4_RTOS_TASK_PRIORITY,
                                                         
                        CONFIG_TEST_LIBRARY_13_INSTANCE_1_TASKS_0_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_13_INSTANCE_1_TASKS_1_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_13_INSTANCE_1_TASKS_2_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_13_INSTANCE_1_TASKS_3_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_13_INSTANCE_1_TASKS_4_RTOS_TASK_PRIORITY,
                                                         
                        CONFIG_TEST_LIBRARY_13_INSTANCE_2_TASKS_0_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_13_INSTANCE_2_TASKS_1_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_13_INSTANCE_2_TASKS_2_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_13_INSTANCE_2_TASKS_3_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_13_INSTANCE_2_TASKS_4_RTOS_TASK_PRIORITY,
                                                         
                        CONFIG_TEST_LIBRARY_14_INSTANCE_0_TASKS_0_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_14_INSTANCE_0_TASKS_1_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_14_INSTANCE_0_TASKS_2_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_14_INSTANCE_0_TASKS_3_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_14_INSTANCE_0_TASKS_4_RTOS_TASK_PRIORITY,
                                                         
                        CONFIG_TEST_LIBRARY_14_INSTANCE_1_TASKS_0_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_14_INSTANCE_1_TASKS_1_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_14_INSTANCE_1_TASKS_2_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_14_INSTANCE_1_TASKS_3_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_14_INSTANCE_1_TASKS_4_RTOS_TASK_PRIORITY,
                                                         
                        CONFIG_TEST_LIBRARY_14_INSTANCE_2_TASKS_0_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_14_INSTANCE_2_TASKS_1_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_14_INSTANCE_2_TASKS_2_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_14_INSTANCE_2_TASKS_3_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_14_INSTANCE_2_TASKS_4_RTOS_TASK_PRIORITY,
                                                         
                        CONFIG_TEST_LIBRARY_15_INSTANCE_0_TASKS_0_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_15_INSTANCE_0_TASKS_1_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_15_INSTANCE_0_TASKS_2_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_15_INSTANCE_0_TASKS_3_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_15_INSTANCE_0_TASKS_4_RTOS_TASK_PRIORITY,
                                                         
                        CONFIG_TEST_LIBRARY_15_INSTANCE_1_TASKS_0_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_15_INSTANCE_1_TASKS_1_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_15_INSTANCE_1_TASKS_2_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_15_INSTANCE_1_TASKS_3_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_15_INSTANCE_1_TASKS_4_RTOS_TASK_PRIORITY,
                                                         
                        CONFIG_TEST_LIBRARY_15_INSTANCE_2_TASKS_0_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_15_INSTANCE_2_TASKS_1_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_15_INSTANCE_2_TASKS_2_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_15_INSTANCE_2_TASKS_3_RTOS_TASK_PRIORITY,
                        CONFIG_TEST_LIBRARY_15_INSTANCE_2_TASKS_4_RTOS_TASK_PRIORITY ]>
<#--
  Task Stack Size:
-->
<#assign stack_size = [ CONFIG_TEST_LIBRARY_0_INSTANCE_0_TASKS_0_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_0_INSTANCE_0_TASKS_1_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_0_INSTANCE_0_TASKS_2_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_0_INSTANCE_0_TASKS_3_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_0_INSTANCE_0_TASKS_4_RTOS_TASK_SIZE,

                        CONFIG_TEST_LIBRARY_0_INSTANCE_1_TASKS_0_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_0_INSTANCE_1_TASKS_1_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_0_INSTANCE_1_TASKS_2_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_0_INSTANCE_1_TASKS_3_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_0_INSTANCE_1_TASKS_4_RTOS_TASK_SIZE,

                        CONFIG_TEST_LIBRARY_0_INSTANCE_2_TASKS_0_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_0_INSTANCE_2_TASKS_1_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_0_INSTANCE_2_TASKS_2_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_0_INSTANCE_2_TASKS_3_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_0_INSTANCE_2_TASKS_4_RTOS_TASK_SIZE,

                        CONFIG_TEST_LIBRARY_1_INSTANCE_0_TASKS_0_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_1_INSTANCE_0_TASKS_1_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_1_INSTANCE_0_TASKS_2_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_1_INSTANCE_0_TASKS_3_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_1_INSTANCE_0_TASKS_4_RTOS_TASK_SIZE,

                        CONFIG_TEST_LIBRARY_1_INSTANCE_1_TASKS_0_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_1_INSTANCE_1_TASKS_1_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_1_INSTANCE_1_TASKS_2_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_1_INSTANCE_1_TASKS_3_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_1_INSTANCE_1_TASKS_4_RTOS_TASK_SIZE,

                        CONFIG_TEST_LIBRARY_1_INSTANCE_2_TASKS_0_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_1_INSTANCE_2_TASKS_1_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_1_INSTANCE_2_TASKS_2_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_1_INSTANCE_2_TASKS_3_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_1_INSTANCE_2_TASKS_4_RTOS_TASK_SIZE,

                        CONFIG_TEST_LIBRARY_2_INSTANCE_0_TASKS_0_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_2_INSTANCE_0_TASKS_1_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_2_INSTANCE_0_TASKS_2_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_2_INSTANCE_0_TASKS_3_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_2_INSTANCE_0_TASKS_4_RTOS_TASK_SIZE,
                                                        
                        CONFIG_TEST_LIBRARY_2_INSTANCE_1_TASKS_0_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_2_INSTANCE_1_TASKS_1_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_2_INSTANCE_1_TASKS_2_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_2_INSTANCE_1_TASKS_3_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_2_INSTANCE_1_TASKS_4_RTOS_TASK_SIZE,
                                                        
                        CONFIG_TEST_LIBRARY_2_INSTANCE_2_TASKS_0_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_2_INSTANCE_2_TASKS_1_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_2_INSTANCE_2_TASKS_2_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_2_INSTANCE_2_TASKS_3_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_2_INSTANCE_2_TASKS_4_RTOS_TASK_SIZE,

                        CONFIG_TEST_LIBRARY_3_INSTANCE_0_TASKS_0_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_3_INSTANCE_0_TASKS_1_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_3_INSTANCE_0_TASKS_2_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_3_INSTANCE_0_TASKS_3_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_3_INSTANCE_0_TASKS_4_RTOS_TASK_SIZE,
                                                        
                        CONFIG_TEST_LIBRARY_3_INSTANCE_1_TASKS_0_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_3_INSTANCE_1_TASKS_1_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_3_INSTANCE_1_TASKS_2_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_3_INSTANCE_1_TASKS_3_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_3_INSTANCE_1_TASKS_4_RTOS_TASK_SIZE,
                                                        
                        CONFIG_TEST_LIBRARY_3_INSTANCE_2_TASKS_0_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_3_INSTANCE_2_TASKS_1_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_3_INSTANCE_2_TASKS_2_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_3_INSTANCE_2_TASKS_3_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_3_INSTANCE_2_TASKS_4_RTOS_TASK_SIZE,

                        CONFIG_TEST_LIBRARY_4_INSTANCE_0_TASKS_0_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_4_INSTANCE_0_TASKS_1_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_4_INSTANCE_0_TASKS_2_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_4_INSTANCE_0_TASKS_3_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_4_INSTANCE_0_TASKS_4_RTOS_TASK_SIZE,
                                                        
                        CONFIG_TEST_LIBRARY_4_INSTANCE_1_TASKS_0_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_4_INSTANCE_1_TASKS_1_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_4_INSTANCE_1_TASKS_2_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_4_INSTANCE_1_TASKS_3_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_4_INSTANCE_1_TASKS_4_RTOS_TASK_SIZE,
                                                        
                        CONFIG_TEST_LIBRARY_4_INSTANCE_2_TASKS_0_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_4_INSTANCE_2_TASKS_1_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_4_INSTANCE_2_TASKS_2_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_4_INSTANCE_2_TASKS_3_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_4_INSTANCE_2_TASKS_4_RTOS_TASK_SIZE,

                        CONFIG_TEST_LIBRARY_5_INSTANCE_0_TASKS_0_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_5_INSTANCE_0_TASKS_1_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_5_INSTANCE_0_TASKS_2_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_5_INSTANCE_0_TASKS_3_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_5_INSTANCE_0_TASKS_4_RTOS_TASK_SIZE,
                                                        
                        CONFIG_TEST_LIBRARY_5_INSTANCE_1_TASKS_0_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_5_INSTANCE_1_TASKS_1_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_5_INSTANCE_1_TASKS_2_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_5_INSTANCE_1_TASKS_3_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_5_INSTANCE_1_TASKS_4_RTOS_TASK_SIZE,
                                                        
                        CONFIG_TEST_LIBRARY_5_INSTANCE_2_TASKS_0_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_5_INSTANCE_2_TASKS_1_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_5_INSTANCE_2_TASKS_2_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_5_INSTANCE_2_TASKS_3_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_5_INSTANCE_2_TASKS_4_RTOS_TASK_SIZE,

                        CONFIG_TEST_LIBRARY_6_INSTANCE_0_TASKS_0_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_6_INSTANCE_0_TASKS_1_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_6_INSTANCE_0_TASKS_2_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_6_INSTANCE_0_TASKS_3_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_6_INSTANCE_0_TASKS_4_RTOS_TASK_SIZE,
                                                        
                        CONFIG_TEST_LIBRARY_6_INSTANCE_1_TASKS_0_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_6_INSTANCE_1_TASKS_1_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_6_INSTANCE_1_TASKS_2_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_6_INSTANCE_1_TASKS_3_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_6_INSTANCE_1_TASKS_4_RTOS_TASK_SIZE,
                                                        
                        CONFIG_TEST_LIBRARY_6_INSTANCE_2_TASKS_0_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_6_INSTANCE_2_TASKS_1_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_6_INSTANCE_2_TASKS_2_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_6_INSTANCE_2_TASKS_3_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_6_INSTANCE_2_TASKS_4_RTOS_TASK_SIZE,
                                                        
                        CONFIG_TEST_LIBRARY_7_INSTANCE_0_TASKS_0_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_7_INSTANCE_0_TASKS_1_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_7_INSTANCE_0_TASKS_2_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_7_INSTANCE_0_TASKS_3_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_7_INSTANCE_0_TASKS_4_RTOS_TASK_SIZE,
                                                        
                        CONFIG_TEST_LIBRARY_7_INSTANCE_1_TASKS_0_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_7_INSTANCE_1_TASKS_1_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_7_INSTANCE_1_TASKS_2_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_7_INSTANCE_1_TASKS_3_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_7_INSTANCE_1_TASKS_4_RTOS_TASK_SIZE,
                                                        
                        CONFIG_TEST_LIBRARY_7_INSTANCE_2_TASKS_0_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_7_INSTANCE_2_TASKS_1_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_7_INSTANCE_2_TASKS_2_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_7_INSTANCE_2_TASKS_3_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_7_INSTANCE_2_TASKS_4_RTOS_TASK_SIZE,
                                                        
                        CONFIG_TEST_LIBRARY_8_INSTANCE_0_TASKS_0_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_8_INSTANCE_0_TASKS_1_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_8_INSTANCE_0_TASKS_2_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_8_INSTANCE_0_TASKS_3_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_8_INSTANCE_0_TASKS_4_RTOS_TASK_SIZE,
                                                        
                        CONFIG_TEST_LIBRARY_8_INSTANCE_1_TASKS_0_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_8_INSTANCE_1_TASKS_1_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_8_INSTANCE_1_TASKS_2_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_8_INSTANCE_1_TASKS_3_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_8_INSTANCE_1_TASKS_4_RTOS_TASK_SIZE,
                                                        
                        CONFIG_TEST_LIBRARY_8_INSTANCE_2_TASKS_0_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_8_INSTANCE_2_TASKS_1_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_8_INSTANCE_2_TASKS_2_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_8_INSTANCE_2_TASKS_3_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_8_INSTANCE_2_TASKS_4_RTOS_TASK_SIZE,
                                                        
                        CONFIG_TEST_LIBRARY_9_INSTANCE_0_TASKS_0_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_9_INSTANCE_0_TASKS_1_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_9_INSTANCE_0_TASKS_2_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_9_INSTANCE_0_TASKS_3_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_9_INSTANCE_0_TASKS_4_RTOS_TASK_SIZE,
                                                        
                        CONFIG_TEST_LIBRARY_9_INSTANCE_1_TASKS_0_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_9_INSTANCE_1_TASKS_1_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_9_INSTANCE_1_TASKS_2_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_9_INSTANCE_1_TASKS_3_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_9_INSTANCE_1_TASKS_4_RTOS_TASK_SIZE,
                                                        
                        CONFIG_TEST_LIBRARY_9_INSTANCE_2_TASKS_0_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_9_INSTANCE_2_TASKS_1_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_9_INSTANCE_2_TASKS_2_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_9_INSTANCE_2_TASKS_3_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_9_INSTANCE_2_TASKS_4_RTOS_TASK_SIZE,

                        CONFIG_TEST_LIBRARY_10_INSTANCE_0_TASKS_0_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_10_INSTANCE_0_TASKS_1_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_10_INSTANCE_0_TASKS_2_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_10_INSTANCE_0_TASKS_3_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_10_INSTANCE_0_TASKS_4_RTOS_TASK_SIZE,
                                                         
                        CONFIG_TEST_LIBRARY_10_INSTANCE_1_TASKS_0_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_10_INSTANCE_1_TASKS_1_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_10_INSTANCE_1_TASKS_2_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_10_INSTANCE_1_TASKS_3_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_10_INSTANCE_1_TASKS_4_RTOS_TASK_SIZE,
                                                         
                        CONFIG_TEST_LIBRARY_10_INSTANCE_2_TASKS_0_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_10_INSTANCE_2_TASKS_1_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_10_INSTANCE_2_TASKS_2_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_10_INSTANCE_2_TASKS_3_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_10_INSTANCE_2_TASKS_4_RTOS_TASK_SIZE,
                                                         
                        CONFIG_TEST_LIBRARY_11_INSTANCE_0_TASKS_0_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_11_INSTANCE_0_TASKS_1_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_11_INSTANCE_0_TASKS_2_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_11_INSTANCE_0_TASKS_3_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_11_INSTANCE_0_TASKS_4_RTOS_TASK_SIZE,
                                                         
                        CONFIG_TEST_LIBRARY_11_INSTANCE_1_TASKS_0_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_11_INSTANCE_1_TASKS_1_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_11_INSTANCE_1_TASKS_2_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_11_INSTANCE_1_TASKS_3_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_11_INSTANCE_1_TASKS_4_RTOS_TASK_SIZE,
                                                         
                        CONFIG_TEST_LIBRARY_11_INSTANCE_2_TASKS_0_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_11_INSTANCE_2_TASKS_1_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_11_INSTANCE_2_TASKS_2_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_11_INSTANCE_2_TASKS_3_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_11_INSTANCE_2_TASKS_4_RTOS_TASK_SIZE,
                                                         
                        CONFIG_TEST_LIBRARY_12_INSTANCE_0_TASKS_0_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_12_INSTANCE_0_TASKS_1_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_12_INSTANCE_0_TASKS_2_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_12_INSTANCE_0_TASKS_3_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_12_INSTANCE_0_TASKS_4_RTOS_TASK_SIZE,
                                                         
                        CONFIG_TEST_LIBRARY_12_INSTANCE_1_TASKS_0_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_12_INSTANCE_1_TASKS_1_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_12_INSTANCE_1_TASKS_2_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_12_INSTANCE_1_TASKS_3_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_12_INSTANCE_1_TASKS_4_RTOS_TASK_SIZE,
                                                         
                        CONFIG_TEST_LIBRARY_12_INSTANCE_2_TASKS_0_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_12_INSTANCE_2_TASKS_1_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_12_INSTANCE_2_TASKS_2_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_12_INSTANCE_2_TASKS_3_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_12_INSTANCE_2_TASKS_4_RTOS_TASK_SIZE,
                                                         
                        CONFIG_TEST_LIBRARY_13_INSTANCE_0_TASKS_0_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_13_INSTANCE_0_TASKS_1_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_13_INSTANCE_0_TASKS_2_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_13_INSTANCE_0_TASKS_3_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_13_INSTANCE_0_TASKS_4_RTOS_TASK_SIZE,
                                                         
                        CONFIG_TEST_LIBRARY_13_INSTANCE_1_TASKS_0_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_13_INSTANCE_1_TASKS_1_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_13_INSTANCE_1_TASKS_2_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_13_INSTANCE_1_TASKS_3_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_13_INSTANCE_1_TASKS_4_RTOS_TASK_SIZE,
                                                         
                        CONFIG_TEST_LIBRARY_13_INSTANCE_2_TASKS_0_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_13_INSTANCE_2_TASKS_1_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_13_INSTANCE_2_TASKS_2_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_13_INSTANCE_2_TASKS_3_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_13_INSTANCE_2_TASKS_4_RTOS_TASK_SIZE,
                                                         
                        CONFIG_TEST_LIBRARY_14_INSTANCE_0_TASKS_0_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_14_INSTANCE_0_TASKS_1_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_14_INSTANCE_0_TASKS_2_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_14_INSTANCE_0_TASKS_3_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_14_INSTANCE_0_TASKS_4_RTOS_TASK_SIZE,
                                                         
                        CONFIG_TEST_LIBRARY_14_INSTANCE_1_TASKS_0_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_14_INSTANCE_1_TASKS_1_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_14_INSTANCE_1_TASKS_2_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_14_INSTANCE_1_TASKS_3_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_14_INSTANCE_1_TASKS_4_RTOS_TASK_SIZE,
                                                         
                        CONFIG_TEST_LIBRARY_14_INSTANCE_2_TASKS_0_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_14_INSTANCE_2_TASKS_1_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_14_INSTANCE_2_TASKS_2_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_14_INSTANCE_2_TASKS_3_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_14_INSTANCE_2_TASKS_4_RTOS_TASK_SIZE,
                                                         
                        CONFIG_TEST_LIBRARY_15_INSTANCE_0_TASKS_0_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_15_INSTANCE_0_TASKS_1_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_15_INSTANCE_0_TASKS_2_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_15_INSTANCE_0_TASKS_3_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_15_INSTANCE_0_TASKS_4_RTOS_TASK_SIZE,
                                                         
                        CONFIG_TEST_LIBRARY_15_INSTANCE_1_TASKS_0_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_15_INSTANCE_1_TASKS_1_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_15_INSTANCE_1_TASKS_2_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_15_INSTANCE_1_TASKS_3_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_15_INSTANCE_1_TASKS_4_RTOS_TASK_SIZE,
                                                         
                        CONFIG_TEST_LIBRARY_15_INSTANCE_2_TASKS_0_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_15_INSTANCE_2_TASKS_1_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_15_INSTANCE_2_TASKS_2_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_15_INSTANCE_2_TASKS_3_RTOS_TASK_SIZE,
                        CONFIG_TEST_LIBRARY_15_INSTANCE_2_TASKS_4_RTOS_TASK_SIZE ]>
<#--
  Test Tasks Stack Size:
-->
<#assign tsize    = [ CONFIG_TEST_TASKS_0_RTOS_TASK_SIZE,
                      CONFIG_TEST_TASKS_1_RTOS_TASK_SIZE,
                      CONFIG_TEST_TASKS_2_RTOS_TASK_SIZE,
                      CONFIG_TEST_TASKS_3_RTOS_TASK_SIZE,
                      CONFIG_TEST_TASKS_4_RTOS_TASK_SIZE ]>
<#--
  Test Tasks Priority:
-->
<#assign tprio    = [ CONFIG_TEST_TASKS_0_RTOS_TASK_PRIORITY,
                      CONFIG_TEST_TASKS_1_RTOS_TASK_PRIORITY,
                      CONFIG_TEST_TASKS_2_RTOS_TASK_PRIORITY,
                      CONFIG_TEST_TASKS_3_RTOS_TASK_PRIORITY,
                      CONFIG_TEST_TASKS_4_RTOS_TASK_PRIORITY ]>
<#--
  Test Task Creation Generation Loop:
-->
<#list 0..CONFIG_TEST_HARNESS_MAX_NUM_TASKS?number-1 as number>
  <@RTOS_TASK_CREATE RTOS_NAME=CONFIG_3RDPARTY_RTOS_USED TASK_FUNC_NAME="_TEST_Tasks${number}" TASK_NAME="TEST Tasks ${number}" TASK_PRI=tprio[number] TASK_STK_SZ=tsize[number] />
</#list>
<#--
  Library Under Test Task Creation Generation Loop:
-->
<#assign index_libraries = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]>
<#assign index_tasks     = [0, 1, 2, 3, 4]>
<#assign index_instances = [0, 1, 2]>
<#list index_libraries as num_lib>
  <#list index_tasks as num_task>
    <#list index_instances as num_inst>
      <#assign index = 15 * num_lib + 5 * num_inst + num_task>
      <#assign index_func = 5 * num_lib + num_task>
      <#if func_ints[index_func] == false && func_name[index_func]?has_content && func_name[index_func] != "NULL">
        <#if lib_instances[num_lib]?has_content && num_inst lt lib_instances[num_lib]?number>
          <@RTOS_TASK_CREATE RTOS_NAME=CONFIG_3RDPARTY_RTOS_USED TASK_FUNC_NAME="_TEST_Library${num_lib}Instance${num_inst}Tasks${num_task}" TASK_NAME="TEST Library ${num_lib} Instance ${num_inst} Tasks ${num_task}" TASK_PRI=priority[index] TASK_STK_SZ=stack_size[index]/>
        </#if>
      </#if>
    </#list>
  </#list>
</#list>
<@RTOS_TASK_CREATE RTOS_NAME=CONFIG_3RDPARTY_RTOS_USED TASK_FUNC_NAME="_TEST_HarnessTasks" TASK_NAME="Test Harness" TASK_PRI=CONFIG_TEST_RTOS_TASK_PRIORITY TASK_STK_SZ=CONFIG_TEST_RTOS_TASK_SIZE/>
</#if>
