<#--
/*******************************************************************************
  MPLAB Harmony Sample Library Module Freemarker Template File

  Company:
    Microchip Technology Inc.

  File Name:
    system_init.data.c.ftl

  Summary:
    MPLAB Harmony Sample Library Module Freemarker Template File for
    system_init.c data definitions.

  Description:
    This file defines the template for the system initialization data definition
    entries inserted into the system_init.c file when the sample library module 
    is used.
 *******************************************************************************/

/*******************************************************************************
Copyright (c) 2014-2015 released Microchip Technology Inc.  All rights reserved.

Microchip licenses to you the right to use, modify, copy and distribute
Software only when embedded on a Microchip microcontroller or digital signal
controller that is integrated into your product or third party product
(pursuant to the sublicense terms in the accompanying license agreement).

You should refer to the license agreement accompanying this Software for
additional information regarding your rights and obligations.

SOFTWARE AND DOCUMENTATION ARE PROVIDED AS IS WITHOUT WARRANTY OF ANY KIND,
EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION, ANY WARRANTY OF
MERCHANTABILITY, TITLE, NON-INFRINGEMENT AND FITNESS FOR A PARTICULAR PURPOSE.
IN NO EVENT SHALL MICROCHIP OR ITS LICENSORS BE LIABLE OR OBLIGATED UNDER
CONTRACT, NEGLIGENCE, STRICT LIABILITY, CONTRIBUTION, BREACH OF WARRANTY, OR
OTHER LEGAL EQUITABLE THEORY ANY DIRECT OR INDIRECT DAMAGES OR EXPENSES
INCLUDING BUT NOT LIMITED TO ANY INCIDENTAL, SPECIAL, INDIRECT, PUNITIVE OR
CONSEQUENTIAL DAMAGES, LOST PROFITS OR LOST DATA, COST OF PROCUREMENT OF
SUBSTITUTE GOODS, TECHNOLOGY, SERVICES, OR ANY CLAIMS BY THIRD PARTIES
(INCLUDING BUT NOT LIMITED TO ANY DEFENSE THEREOF), OR OTHER SIMILAR COSTS.
 *******************************************************************************/
 -->
<#-- Local Macros -->
<#macro add_test used next name initialize tasks0 tasks1 tasks2 tasks3 tasks4 start status index data library num_tasks>
  <#if used == true>
    {
        .name       = "${name}",
        .initialize = ${initialize},
        .tasks      = {
                      <#if num_tasks gte 1>
                        ${tasks0},
                      </#if>
                      <#if num_tasks gte 2>
                        ${tasks1},
                      </#if>
                      <#if num_tasks gte 3>
                        ${tasks2},
                      </#if>
                      <#if num_tasks gte 4>
                        ${tasks3},
                      </#if>
                      <#if num_tasks gte 5>
                        ${tasks1},
                      </#if>
                      },
        .start      = ${start},
        .status     = ${status},
        .index      = ${index},
        .initData   = (SYS_MODULE_INIT *)<#if data != "NULL">&</#if>${data},
        .library    = &${library}
    }<#if next == true>,</#if>
  </#if>
</#macro>
<#macro add_library used name initialize reinitialize deinitialize status num_instances num_tasks tasks data>
<#if used == true>
static LIBRARY_UNDER_TEST ${name} = 
{
    .initialize         = ${initialize},
    .reinitialize       = ${reinitialize},
    .deinitialize       = ${deinitialize},
    .status             = ${status},
    .numberOfInstances  = ${num_instances},
    .numberOfTasks      = ${num_tasks},
    .tasks              = {
                            <#list tasks as task>
                              ${task}<#if task_has_next>,</#if>
                            </#list>
                          },
    .initData           = {
                            <#list data as d>
                              <#if d?has_content>
                                <#if d == "NULL">
                              (SYS_MODULE_INIT *)${d}<#if d_has_next>,</#if>
                                <#else>
                              (SYS_MODULE_INIT *)&${d}<#if d_has_next>,</#if>
                                </#if>
                              </#if>
                            </#list>
                          }
};

</#if>
</#macro>
<#-- Translating individual variables into sequences through which the above macro can iterate. -->
<#assign lib0tasks  = [CONFIG_TEST_LIBRARY_IDX0_TASKS_IDX0,  CONFIG_TEST_LIBRARY_IDX0_TASKS_IDX1,  CONFIG_TEST_LIBRARY_IDX0_TASKS_IDX2,  CONFIG_TEST_LIBRARY_IDX0_TASKS_IDX3,  CONFIG_TEST_LIBRARY_IDX0_TASKS_IDX4] >
<#assign lib1tasks  = [CONFIG_TEST_LIBRARY_IDX1_TASKS_IDX0,  CONFIG_TEST_LIBRARY_IDX1_TASKS_IDX1,  CONFIG_TEST_LIBRARY_IDX1_TASKS_IDX2,  CONFIG_TEST_LIBRARY_IDX1_TASKS_IDX3,  CONFIG_TEST_LIBRARY_IDX1_TASKS_IDX4] >
<#assign lib2tasks  = [CONFIG_TEST_LIBRARY_IDX2_TASKS_IDX0,  CONFIG_TEST_LIBRARY_IDX2_TASKS_IDX1,  CONFIG_TEST_LIBRARY_IDX2_TASKS_IDX2,  CONFIG_TEST_LIBRARY_IDX2_TASKS_IDX3,  CONFIG_TEST_LIBRARY_IDX2_TASKS_IDX4] >
<#assign lib3tasks  = [CONFIG_TEST_LIBRARY_IDX3_TASKS_IDX0,  CONFIG_TEST_LIBRARY_IDX3_TASKS_IDX1,  CONFIG_TEST_LIBRARY_IDX3_TASKS_IDX2,  CONFIG_TEST_LIBRARY_IDX3_TASKS_IDX3,  CONFIG_TEST_LIBRARY_IDX3_TASKS_IDX4] >
<#assign lib4tasks  = [CONFIG_TEST_LIBRARY_IDX4_TASKS_IDX0,  CONFIG_TEST_LIBRARY_IDX4_TASKS_IDX1,  CONFIG_TEST_LIBRARY_IDX4_TASKS_IDX2,  CONFIG_TEST_LIBRARY_IDX4_TASKS_IDX3,  CONFIG_TEST_LIBRARY_IDX4_TASKS_IDX4] >
<#assign lib5tasks  = [CONFIG_TEST_LIBRARY_IDX5_TASKS_IDX0,  CONFIG_TEST_LIBRARY_IDX5_TASKS_IDX1,  CONFIG_TEST_LIBRARY_IDX5_TASKS_IDX2,  CONFIG_TEST_LIBRARY_IDX5_TASKS_IDX3,  CONFIG_TEST_LIBRARY_IDX5_TASKS_IDX4] >
<#assign lib6tasks  = [CONFIG_TEST_LIBRARY_IDX6_TASKS_IDX0,  CONFIG_TEST_LIBRARY_IDX6_TASKS_IDX1,  CONFIG_TEST_LIBRARY_IDX6_TASKS_IDX2,  CONFIG_TEST_LIBRARY_IDX6_TASKS_IDX3,  CONFIG_TEST_LIBRARY_IDX6_TASKS_IDX4] >
<#assign lib7tasks  = [CONFIG_TEST_LIBRARY_IDX7_TASKS_IDX0,  CONFIG_TEST_LIBRARY_IDX7_TASKS_IDX1,  CONFIG_TEST_LIBRARY_IDX7_TASKS_IDX2,  CONFIG_TEST_LIBRARY_IDX7_TASKS_IDX3,  CONFIG_TEST_LIBRARY_IDX7_TASKS_IDX4] >
<#assign lib8tasks  = [CONFIG_TEST_LIBRARY_IDX8_TASKS_IDX0,  CONFIG_TEST_LIBRARY_IDX8_TASKS_IDX1,  CONFIG_TEST_LIBRARY_IDX8_TASKS_IDX2,  CONFIG_TEST_LIBRARY_IDX8_TASKS_IDX3,  CONFIG_TEST_LIBRARY_IDX8_TASKS_IDX4] >
<#assign lib9tasks  = [CONFIG_TEST_LIBRARY_IDX9_TASKS_IDX0,  CONFIG_TEST_LIBRARY_IDX9_TASKS_IDX1,  CONFIG_TEST_LIBRARY_IDX9_TASKS_IDX2,  CONFIG_TEST_LIBRARY_IDX9_TASKS_IDX3,  CONFIG_TEST_LIBRARY_IDX9_TASKS_IDX4] >
<#assign lib10tasks = [CONFIG_TEST_LIBRARY_IDX10_TASKS_IDX0, CONFIG_TEST_LIBRARY_IDX10_TASKS_IDX1, CONFIG_TEST_LIBRARY_IDX10_TASKS_IDX2, CONFIG_TEST_LIBRARY_IDX10_TASKS_IDX3, CONFIG_TEST_LIBRARY_IDX10_TASKS_IDX4]>
<#assign lib11tasks = [CONFIG_TEST_LIBRARY_IDX11_TASKS_IDX0, CONFIG_TEST_LIBRARY_IDX11_TASKS_IDX1, CONFIG_TEST_LIBRARY_IDX11_TASKS_IDX2, CONFIG_TEST_LIBRARY_IDX11_TASKS_IDX3, CONFIG_TEST_LIBRARY_IDX11_TASKS_IDX4]>
<#assign lib12tasks = [CONFIG_TEST_LIBRARY_IDX12_TASKS_IDX0, CONFIG_TEST_LIBRARY_IDX12_TASKS_IDX1, CONFIG_TEST_LIBRARY_IDX12_TASKS_IDX2, CONFIG_TEST_LIBRARY_IDX12_TASKS_IDX3, CONFIG_TEST_LIBRARY_IDX12_TASKS_IDX4]>
<#assign lib13tasks = [CONFIG_TEST_LIBRARY_IDX13_TASKS_IDX0, CONFIG_TEST_LIBRARY_IDX13_TASKS_IDX1, CONFIG_TEST_LIBRARY_IDX13_TASKS_IDX2, CONFIG_TEST_LIBRARY_IDX13_TASKS_IDX3, CONFIG_TEST_LIBRARY_IDX13_TASKS_IDX4]>
<#assign lib14tasks = [CONFIG_TEST_LIBRARY_IDX14_TASKS_IDX0, CONFIG_TEST_LIBRARY_IDX14_TASKS_IDX1, CONFIG_TEST_LIBRARY_IDX14_TASKS_IDX2, CONFIG_TEST_LIBRARY_IDX14_TASKS_IDX3, CONFIG_TEST_LIBRARY_IDX14_TASKS_IDX4]>
<#assign lib15tasks = [CONFIG_TEST_LIBRARY_IDX15_TASKS_IDX0, CONFIG_TEST_LIBRARY_IDX15_TASKS_IDX1, CONFIG_TEST_LIBRARY_IDX15_TASKS_IDX2, CONFIG_TEST_LIBRARY_IDX15_TASKS_IDX3, CONFIG_TEST_LIBRARY_IDX15_TASKS_IDX4]>
<#assign lib0data   = [CONFIG_TEST_LIBRARY_IDX0_INITDATA_IDX0,  CONFIG_TEST_LIBRARY_IDX0_INITDATA_IDX1,  CONFIG_TEST_LIBRARY_IDX0_INITDATA_IDX2] >
<#assign lib1data   = [CONFIG_TEST_LIBRARY_IDX1_INITDATA_IDX0,  CONFIG_TEST_LIBRARY_IDX1_INITDATA_IDX1,  CONFIG_TEST_LIBRARY_IDX1_INITDATA_IDX2] >
<#assign lib2data   = [CONFIG_TEST_LIBRARY_IDX2_INITDATA_IDX0,  CONFIG_TEST_LIBRARY_IDX2_INITDATA_IDX1,  CONFIG_TEST_LIBRARY_IDX2_INITDATA_IDX2] >
<#assign lib3data   = [CONFIG_TEST_LIBRARY_IDX3_INITDATA_IDX0,  CONFIG_TEST_LIBRARY_IDX3_INITDATA_IDX1,  CONFIG_TEST_LIBRARY_IDX3_INITDATA_IDX2] >
<#assign lib4data   = [CONFIG_TEST_LIBRARY_IDX4_INITDATA_IDX0,  CONFIG_TEST_LIBRARY_IDX4_INITDATA_IDX1,  CONFIG_TEST_LIBRARY_IDX4_INITDATA_IDX2] >
<#assign lib5data   = [CONFIG_TEST_LIBRARY_IDX5_INITDATA_IDX0,  CONFIG_TEST_LIBRARY_IDX5_INITDATA_IDX1,  CONFIG_TEST_LIBRARY_IDX5_INITDATA_IDX2] >
<#assign lib6data   = [CONFIG_TEST_LIBRARY_IDX6_INITDATA_IDX0,  CONFIG_TEST_LIBRARY_IDX6_INITDATA_IDX1,  CONFIG_TEST_LIBRARY_IDX6_INITDATA_IDX2] >
<#assign lib7data   = [CONFIG_TEST_LIBRARY_IDX7_INITDATA_IDX0,  CONFIG_TEST_LIBRARY_IDX7_INITDATA_IDX1,  CONFIG_TEST_LIBRARY_IDX7_INITDATA_IDX2] >
<#assign lib8data   = [CONFIG_TEST_LIBRARY_IDX8_INITDATA_IDX0,  CONFIG_TEST_LIBRARY_IDX8_INITDATA_IDX1,  CONFIG_TEST_LIBRARY_IDX8_INITDATA_IDX2] >
<#assign lib9data   = [CONFIG_TEST_LIBRARY_IDX9_INITDATA_IDX0,  CONFIG_TEST_LIBRARY_IDX9_INITDATA_IDX1,  CONFIG_TEST_LIBRARY_IDX9_INITDATA_IDX2] >
<#assign lib10data  = [CONFIG_TEST_LIBRARY_IDX10_INITDATA_IDX0, CONFIG_TEST_LIBRARY_IDX10_INITDATA_IDX1, CONFIG_TEST_LIBRARY_IDX10_INITDATA_IDX2]>
<#assign lib11data  = [CONFIG_TEST_LIBRARY_IDX11_INITDATA_IDX0, CONFIG_TEST_LIBRARY_IDX11_INITDATA_IDX1, CONFIG_TEST_LIBRARY_IDX11_INITDATA_IDX2]>
<#assign lib12data  = [CONFIG_TEST_LIBRARY_IDX12_INITDATA_IDX0, CONFIG_TEST_LIBRARY_IDX12_INITDATA_IDX1, CONFIG_TEST_LIBRARY_IDX12_INITDATA_IDX2]>
<#assign lib13data  = [CONFIG_TEST_LIBRARY_IDX13_INITDATA_IDX0, CONFIG_TEST_LIBRARY_IDX13_INITDATA_IDX1, CONFIG_TEST_LIBRARY_IDX13_INITDATA_IDX2]>
<#assign lib14data  = [CONFIG_TEST_LIBRARY_IDX14_INITDATA_IDX0, CONFIG_TEST_LIBRARY_IDX14_INITDATA_IDX1, CONFIG_TEST_LIBRARY_IDX14_INITDATA_IDX2]>
<#assign lib15data  = [CONFIG_TEST_LIBRARY_IDX15_INITDATA_IDX0, CONFIG_TEST_LIBRARY_IDX15_INITDATA_IDX1, CONFIG_TEST_LIBRARY_IDX15_INITDATA_IDX2]>
<#-- Generated Code -->
<#if CONFIG_USE_TEST_HARNESS == true>
/******************************************************************************
  Test Harness Initialization Data
  
  <editor-fold defaultstate="collapsed"
   desc="Test Harness Initialization Data">
*/

/* Library Under Test Data */
<@add_library used=CONFIG_TEST_LIBRARY_IDX0  name=CONFIG_TEST_LIBRARY_STRUCT_NAME_IDX0  initialize=CONFIG_TEST_LIBRARY_FUNC_INITIALIZE_IDX0  reinitialize=CONFIG_TEST_LIBRARY_FUNC_REINITIALIZE_IDX0  deinitialize=CONFIG_TEST_LIBRARY_FUNC_DEINITIALIZE_IDX0  status=CONFIG_TEST_LIBRARY_FUNC_STATUS_IDX0  num_instances=CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX0  num_tasks=CONFIG_TEST_LIBRARY_NUMBER_OF_TASKS_IDX0  tasks=lib0tasks  data=lib0data  />
<@add_library used=CONFIG_TEST_LIBRARY_IDX1  name=CONFIG_TEST_LIBRARY_STRUCT_NAME_IDX1  initialize=CONFIG_TEST_LIBRARY_FUNC_INITIALIZE_IDX1  reinitialize=CONFIG_TEST_LIBRARY_FUNC_REINITIALIZE_IDX1  deinitialize=CONFIG_TEST_LIBRARY_FUNC_DEINITIALIZE_IDX1  status=CONFIG_TEST_LIBRARY_FUNC_STATUS_IDX1  num_instances=CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX1  num_tasks=CONFIG_TEST_LIBRARY_NUMBER_OF_TASKS_IDX1  tasks=lib1tasks  data=lib1data  />
<@add_library used=CONFIG_TEST_LIBRARY_IDX2  name=CONFIG_TEST_LIBRARY_STRUCT_NAME_IDX2  initialize=CONFIG_TEST_LIBRARY_FUNC_INITIALIZE_IDX2  reinitialize=CONFIG_TEST_LIBRARY_FUNC_REINITIALIZE_IDX2  deinitialize=CONFIG_TEST_LIBRARY_FUNC_DEINITIALIZE_IDX2  status=CONFIG_TEST_LIBRARY_FUNC_STATUS_IDX2  num_instances=CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX2  num_tasks=CONFIG_TEST_LIBRARY_NUMBER_OF_TASKS_IDX2  tasks=lib2tasks  data=lib2data  />
<@add_library used=CONFIG_TEST_LIBRARY_IDX3  name=CONFIG_TEST_LIBRARY_STRUCT_NAME_IDX3  initialize=CONFIG_TEST_LIBRARY_FUNC_INITIALIZE_IDX3  reinitialize=CONFIG_TEST_LIBRARY_FUNC_REINITIALIZE_IDX3  deinitialize=CONFIG_TEST_LIBRARY_FUNC_DEINITIALIZE_IDX3  status=CONFIG_TEST_LIBRARY_FUNC_STATUS_IDX3  num_instances=CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX3  num_tasks=CONFIG_TEST_LIBRARY_NUMBER_OF_TASKS_IDX3  tasks=lib3tasks  data=lib3data  />
<@add_library used=CONFIG_TEST_LIBRARY_IDX4  name=CONFIG_TEST_LIBRARY_STRUCT_NAME_IDX4  initialize=CONFIG_TEST_LIBRARY_FUNC_INITIALIZE_IDX4  reinitialize=CONFIG_TEST_LIBRARY_FUNC_REINITIALIZE_IDX4  deinitialize=CONFIG_TEST_LIBRARY_FUNC_DEINITIALIZE_IDX4  status=CONFIG_TEST_LIBRARY_FUNC_STATUS_IDX4  num_instances=CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX4  num_tasks=CONFIG_TEST_LIBRARY_NUMBER_OF_TASKS_IDX4  tasks=lib4tasks  data=lib4data  />
<@add_library used=CONFIG_TEST_LIBRARY_IDX5  name=CONFIG_TEST_LIBRARY_STRUCT_NAME_IDX5  initialize=CONFIG_TEST_LIBRARY_FUNC_INITIALIZE_IDX5  reinitialize=CONFIG_TEST_LIBRARY_FUNC_REINITIALIZE_IDX5  deinitialize=CONFIG_TEST_LIBRARY_FUNC_DEINITIALIZE_IDX5  status=CONFIG_TEST_LIBRARY_FUNC_STATUS_IDX5  num_instances=CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX5  num_tasks=CONFIG_TEST_LIBRARY_NUMBER_OF_TASKS_IDX5  tasks=lib5tasks  data=lib5data  />
<@add_library used=CONFIG_TEST_LIBRARY_IDX6  name=CONFIG_TEST_LIBRARY_STRUCT_NAME_IDX6  initialize=CONFIG_TEST_LIBRARY_FUNC_INITIALIZE_IDX6  reinitialize=CONFIG_TEST_LIBRARY_FUNC_REINITIALIZE_IDX6  deinitialize=CONFIG_TEST_LIBRARY_FUNC_DEINITIALIZE_IDX6  status=CONFIG_TEST_LIBRARY_FUNC_STATUS_IDX6  num_instances=CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX6  num_tasks=CONFIG_TEST_LIBRARY_NUMBER_OF_TASKS_IDX6  tasks=lib6tasks  data=lib6data  />
<@add_library used=CONFIG_TEST_LIBRARY_IDX7  name=CONFIG_TEST_LIBRARY_STRUCT_NAME_IDX7  initialize=CONFIG_TEST_LIBRARY_FUNC_INITIALIZE_IDX7  reinitialize=CONFIG_TEST_LIBRARY_FUNC_REINITIALIZE_IDX7  deinitialize=CONFIG_TEST_LIBRARY_FUNC_DEINITIALIZE_IDX7  status=CONFIG_TEST_LIBRARY_FUNC_STATUS_IDX7  num_instances=CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX7  num_tasks=CONFIG_TEST_LIBRARY_NUMBER_OF_TASKS_IDX7  tasks=lib7tasks  data=lib7data  />
<@add_library used=CONFIG_TEST_LIBRARY_IDX8  name=CONFIG_TEST_LIBRARY_STRUCT_NAME_IDX8  initialize=CONFIG_TEST_LIBRARY_FUNC_INITIALIZE_IDX8  reinitialize=CONFIG_TEST_LIBRARY_FUNC_REINITIALIZE_IDX8  deinitialize=CONFIG_TEST_LIBRARY_FUNC_DEINITIALIZE_IDX8  status=CONFIG_TEST_LIBRARY_FUNC_STATUS_IDX8  num_instances=CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX8  num_tasks=CONFIG_TEST_LIBRARY_NUMBER_OF_TASKS_IDX8  tasks=lib8tasks  data=lib8data  />
<@add_library used=CONFIG_TEST_LIBRARY_IDX9  name=CONFIG_TEST_LIBRARY_STRUCT_NAME_IDX9  initialize=CONFIG_TEST_LIBRARY_FUNC_INITIALIZE_IDX9  reinitialize=CONFIG_TEST_LIBRARY_FUNC_REINITIALIZE_IDX9  deinitialize=CONFIG_TEST_LIBRARY_FUNC_DEINITIALIZE_IDX9  status=CONFIG_TEST_LIBRARY_FUNC_STATUS_IDX9  num_instances=CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX9  num_tasks=CONFIG_TEST_LIBRARY_NUMBER_OF_TASKS_IDX9  tasks=lib9tasks  data=lib9data  />
<@add_library used=CONFIG_TEST_LIBRARY_IDX10 name=CONFIG_TEST_LIBRARY_STRUCT_NAME_IDX10 initialize=CONFIG_TEST_LIBRARY_FUNC_INITIALIZE_IDX10 reinitialize=CONFIG_TEST_LIBRARY_FUNC_REINITIALIZE_IDX10 deinitialize=CONFIG_TEST_LIBRARY_FUNC_DEINITIALIZE_IDX10 status=CONFIG_TEST_LIBRARY_FUNC_STATUS_IDX10 num_instances=CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX10 num_tasks=CONFIG_TEST_LIBRARY_NUMBER_OF_TASKS_IDX10 tasks=lib10tasks data=lib10data />
<@add_library used=CONFIG_TEST_LIBRARY_IDX11 name=CONFIG_TEST_LIBRARY_STRUCT_NAME_IDX11 initialize=CONFIG_TEST_LIBRARY_FUNC_INITIALIZE_IDX11 reinitialize=CONFIG_TEST_LIBRARY_FUNC_REINITIALIZE_IDX11 deinitialize=CONFIG_TEST_LIBRARY_FUNC_DEINITIALIZE_IDX11 status=CONFIG_TEST_LIBRARY_FUNC_STATUS_IDX11 num_instances=CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX11 num_tasks=CONFIG_TEST_LIBRARY_NUMBER_OF_TASKS_IDX11 tasks=lib11tasks data=lib11data />
<@add_library used=CONFIG_TEST_LIBRARY_IDX12 name=CONFIG_TEST_LIBRARY_STRUCT_NAME_IDX12 initialize=CONFIG_TEST_LIBRARY_FUNC_INITIALIZE_IDX12 reinitialize=CONFIG_TEST_LIBRARY_FUNC_REINITIALIZE_IDX12 deinitialize=CONFIG_TEST_LIBRARY_FUNC_DEINITIALIZE_IDX12 status=CONFIG_TEST_LIBRARY_FUNC_STATUS_IDX12 num_instances=CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX12 num_tasks=CONFIG_TEST_LIBRARY_NUMBER_OF_TASKS_IDX12 tasks=lib12tasks data=lib12data />
<@add_library used=CONFIG_TEST_LIBRARY_IDX13 name=CONFIG_TEST_LIBRARY_STRUCT_NAME_IDX13 initialize=CONFIG_TEST_LIBRARY_FUNC_INITIALIZE_IDX13 reinitialize=CONFIG_TEST_LIBRARY_FUNC_REINITIALIZE_IDX13 deinitialize=CONFIG_TEST_LIBRARY_FUNC_DEINITIALIZE_IDX13 status=CONFIG_TEST_LIBRARY_FUNC_STATUS_IDX13 num_instances=CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX13 num_tasks=CONFIG_TEST_LIBRARY_NUMBER_OF_TASKS_IDX13 tasks=lib13tasks data=lib13data />
<@add_library used=CONFIG_TEST_LIBRARY_IDX14 name=CONFIG_TEST_LIBRARY_STRUCT_NAME_IDX14 initialize=CONFIG_TEST_LIBRARY_FUNC_INITIALIZE_IDX14 reinitialize=CONFIG_TEST_LIBRARY_FUNC_REINITIALIZE_IDX14 deinitialize=CONFIG_TEST_LIBRARY_FUNC_DEINITIALIZE_IDX14 status=CONFIG_TEST_LIBRARY_FUNC_STATUS_IDX14 num_instances=CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX14 num_tasks=CONFIG_TEST_LIBRARY_NUMBER_OF_TASKS_IDX14 tasks=lib14tasks data=lib14data />
<@add_library used=CONFIG_TEST_LIBRARY_IDX15 name=CONFIG_TEST_LIBRARY_STRUCT_NAME_IDX15 initialize=CONFIG_TEST_LIBRARY_FUNC_INITIALIZE_IDX15 reinitialize=CONFIG_TEST_LIBRARY_FUNC_REINITIALIZE_IDX15 deinitialize=CONFIG_TEST_LIBRARY_FUNC_DEINITIALIZE_IDX15 status=CONFIG_TEST_LIBRARY_FUNC_STATUS_IDX15 num_instances=CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX15 num_tasks=CONFIG_TEST_LIBRARY_NUMBER_OF_TASKS_IDX15 tasks=lib15tasks data=lib15data />
<#if CONFIG_USE_SAMPLE_FUNC_TEST == true>
<#include "/framework/test/templates/system_init.c.sample_func.ftl">
</#if>
<#-- ***** Add New Library Under Test Data Structure Include Statements Here. ***** -->
/* Test List */
static TEST_DATA testList[] = 
{
  <@add_test used=CONFIG_TEST_NUMBER_0  next=CONFIG_TEST_NUMBER_1  name=CONFIG_TEST_NAME_IDX0  initialize=CONFIG_TEST_FUNC_INITIALIZE_IDX0  tasks0=CONFIG_TEST_0_FUNC_TASKS_0  tasks1=CONFIG_TEST_0_FUNC_TASKS_1  tasks2=CONFIG_TEST_0_FUNC_TASKS_2  tasks3=CONFIG_TEST_0_FUNC_TASKS_3  tasks4=CONFIG_TEST_0_FUNC_TASKS_4  start=CONFIG_TEST_FUNC_START_IDX0  status=CONFIG_TEST_FUNC_STATUS_IDX0  index=CONFIG_TEST_INSTANCE_INDEX_IDX0  data=CONFIG_TEST_INSTANCE_INIT_DATA_IDX0  library=CONFIG_TEST_LIBRARY_STRUCT_NAME_IDX0  num_tasks=CONFIG_TEST_HARNESS_MAX_NUM_TASKS?number />
  <@add_test used=CONFIG_TEST_NUMBER_1  next=CONFIG_TEST_NUMBER_2  name=CONFIG_TEST_NAME_IDX1  initialize=CONFIG_TEST_FUNC_INITIALIZE_IDX1  tasks0=CONFIG_TEST_1_FUNC_TASKS_0  tasks1=CONFIG_TEST_1_FUNC_TASKS_1  tasks2=CONFIG_TEST_1_FUNC_TASKS_2  tasks3=CONFIG_TEST_1_FUNC_TASKS_3  tasks4=CONFIG_TEST_1_FUNC_TASKS_4  start=CONFIG_TEST_FUNC_START_IDX1  status=CONFIG_TEST_FUNC_STATUS_IDX1  index=CONFIG_TEST_INSTANCE_INDEX_IDX1  data=CONFIG_TEST_INSTANCE_INIT_DATA_IDX1  library=CONFIG_TEST_LIBRARY_STRUCT_NAME_IDX1  num_tasks=CONFIG_TEST_HARNESS_MAX_NUM_TASKS?number />
  <@add_test used=CONFIG_TEST_NUMBER_2  next=CONFIG_TEST_NUMBER_3  name=CONFIG_TEST_NAME_IDX2  initialize=CONFIG_TEST_FUNC_INITIALIZE_IDX2  tasks0=CONFIG_TEST_2_FUNC_TASKS_0  tasks1=CONFIG_TEST_2_FUNC_TASKS_1  tasks2=CONFIG_TEST_2_FUNC_TASKS_2  tasks3=CONFIG_TEST_2_FUNC_TASKS_3  tasks4=CONFIG_TEST_2_FUNC_TASKS_4  start=CONFIG_TEST_FUNC_START_IDX2  status=CONFIG_TEST_FUNC_STATUS_IDX2  index=CONFIG_TEST_INSTANCE_INDEX_IDX2  data=CONFIG_TEST_INSTANCE_INIT_DATA_IDX2  library=CONFIG_TEST_LIBRARY_STRUCT_NAME_IDX2  num_tasks=CONFIG_TEST_HARNESS_MAX_NUM_TASKS?number />
  <@add_test used=CONFIG_TEST_NUMBER_3  next=CONFIG_TEST_NUMBER_4  name=CONFIG_TEST_NAME_IDX3  initialize=CONFIG_TEST_FUNC_INITIALIZE_IDX3  tasks0=CONFIG_TEST_3_FUNC_TASKS_0  tasks1=CONFIG_TEST_3_FUNC_TASKS_1  tasks2=CONFIG_TEST_3_FUNC_TASKS_2  tasks3=CONFIG_TEST_3_FUNC_TASKS_3  tasks4=CONFIG_TEST_3_FUNC_TASKS_4  start=CONFIG_TEST_FUNC_START_IDX3  status=CONFIG_TEST_FUNC_STATUS_IDX3  index=CONFIG_TEST_INSTANCE_INDEX_IDX3  data=CONFIG_TEST_INSTANCE_INIT_DATA_IDX3  library=CONFIG_TEST_LIBRARY_STRUCT_NAME_IDX3  num_tasks=CONFIG_TEST_HARNESS_MAX_NUM_TASKS?number />
  <@add_test used=CONFIG_TEST_NUMBER_4  next=CONFIG_TEST_NUMBER_5  name=CONFIG_TEST_NAME_IDX4  initialize=CONFIG_TEST_FUNC_INITIALIZE_IDX4  tasks0=CONFIG_TEST_4_FUNC_TASKS_0  tasks1=CONFIG_TEST_4_FUNC_TASKS_1  tasks2=CONFIG_TEST_4_FUNC_TASKS_2  tasks3=CONFIG_TEST_4_FUNC_TASKS_3  tasks4=CONFIG_TEST_4_FUNC_TASKS_4  start=CONFIG_TEST_FUNC_START_IDX4  status=CONFIG_TEST_FUNC_STATUS_IDX4  index=CONFIG_TEST_INSTANCE_INDEX_IDX4  data=CONFIG_TEST_INSTANCE_INIT_DATA_IDX4  library=CONFIG_TEST_LIBRARY_STRUCT_NAME_IDX4  num_tasks=CONFIG_TEST_HARNESS_MAX_NUM_TASKS?number />
  <@add_test used=CONFIG_TEST_NUMBER_5  next=CONFIG_TEST_NUMBER_6  name=CONFIG_TEST_NAME_IDX5  initialize=CONFIG_TEST_FUNC_INITIALIZE_IDX5  tasks0=CONFIG_TEST_5_FUNC_TASKS_0  tasks1=CONFIG_TEST_5_FUNC_TASKS_1  tasks2=CONFIG_TEST_5_FUNC_TASKS_2  tasks3=CONFIG_TEST_5_FUNC_TASKS_3  tasks4=CONFIG_TEST_5_FUNC_TASKS_4  start=CONFIG_TEST_FUNC_START_IDX5  status=CONFIG_TEST_FUNC_STATUS_IDX5  index=CONFIG_TEST_INSTANCE_INDEX_IDX5  data=CONFIG_TEST_INSTANCE_INIT_DATA_IDX5  library=CONFIG_TEST_LIBRARY_STRUCT_NAME_IDX5  num_tasks=CONFIG_TEST_HARNESS_MAX_NUM_TASKS?number />
  <@add_test used=CONFIG_TEST_NUMBER_6  next=CONFIG_TEST_NUMBER_7  name=CONFIG_TEST_NAME_IDX6  initialize=CONFIG_TEST_FUNC_INITIALIZE_IDX6  tasks0=CONFIG_TEST_6_FUNC_TASKS_0  tasks1=CONFIG_TEST_6_FUNC_TASKS_1  tasks2=CONFIG_TEST_6_FUNC_TASKS_2  tasks3=CONFIG_TEST_6_FUNC_TASKS_3  tasks4=CONFIG_TEST_6_FUNC_TASKS_4  start=CONFIG_TEST_FUNC_START_IDX6  status=CONFIG_TEST_FUNC_STATUS_IDX6  index=CONFIG_TEST_INSTANCE_INDEX_IDX6  data=CONFIG_TEST_INSTANCE_INIT_DATA_IDX5  library=CONFIG_TEST_LIBRARY_STRUCT_NAME_IDX6  num_tasks=CONFIG_TEST_HARNESS_MAX_NUM_TASKS?number />
  <@add_test used=CONFIG_TEST_NUMBER_7  next=CONFIG_TEST_NUMBER_8  name=CONFIG_TEST_NAME_IDX7  initialize=CONFIG_TEST_FUNC_INITIALIZE_IDX7  tasks0=CONFIG_TEST_7_FUNC_TASKS_0  tasks1=CONFIG_TEST_7_FUNC_TASKS_1  tasks2=CONFIG_TEST_7_FUNC_TASKS_2  tasks3=CONFIG_TEST_7_FUNC_TASKS_3  tasks4=CONFIG_TEST_7_FUNC_TASKS_4  start=CONFIG_TEST_FUNC_START_IDX7  status=CONFIG_TEST_FUNC_STATUS_IDX7  index=CONFIG_TEST_INSTANCE_INDEX_IDX7  data=CONFIG_TEST_INSTANCE_INIT_DATA_IDX7  library=CONFIG_TEST_LIBRARY_STRUCT_NAME_IDX7  num_tasks=CONFIG_TEST_HARNESS_MAX_NUM_TASKS?number />
  <@add_test used=CONFIG_TEST_NUMBER_8  next=CONFIG_TEST_NUMBER_9  name=CONFIG_TEST_NAME_IDX8  initialize=CONFIG_TEST_FUNC_INITIALIZE_IDX8  tasks0=CONFIG_TEST_8_FUNC_TASKS_0  tasks1=CONFIG_TEST_8_FUNC_TASKS_1  tasks2=CONFIG_TEST_8_FUNC_TASKS_2  tasks3=CONFIG_TEST_8_FUNC_TASKS_3  tasks4=CONFIG_TEST_8_FUNC_TASKS_4  start=CONFIG_TEST_FUNC_START_IDX8  status=CONFIG_TEST_FUNC_STATUS_IDX8  index=CONFIG_TEST_INSTANCE_INDEX_IDX8  data=CONFIG_TEST_INSTANCE_INIT_DATA_IDX8  library=CONFIG_TEST_LIBRARY_STRUCT_NAME_IDX8  num_tasks=CONFIG_TEST_HARNESS_MAX_NUM_TASKS?number />
  <@add_test used=CONFIG_TEST_NUMBER_9  next=CONFIG_TEST_NUMBER_10 name=CONFIG_TEST_NAME_IDX9  initialize=CONFIG_TEST_FUNC_INITIALIZE_IDX9  tasks0=CONFIG_TEST_9_FUNC_TASKS_0  tasks1=CONFIG_TEST_9_FUNC_TASKS_1  tasks2=CONFIG_TEST_9_FUNC_TASKS_2  tasks3=CONFIG_TEST_9_FUNC_TASKS_3  tasks4=CONFIG_TEST_9_FUNC_TASKS_4  start=CONFIG_TEST_FUNC_START_IDX9  status=CONFIG_TEST_FUNC_STATUS_IDX9  index=CONFIG_TEST_INSTANCE_INDEX_IDX9  data=CONFIG_TEST_INSTANCE_INIT_DATA_IDX9  library=CONFIG_TEST_LIBRARY_STRUCT_NAME_IDX9  num_tasks=CONFIG_TEST_HARNESS_MAX_NUM_TASKS?number />
  <@add_test used=CONFIG_TEST_NUMBER_10 next=CONFIG_TEST_NUMBER_11 name=CONFIG_TEST_NAME_IDX10 initialize=CONFIG_TEST_FUNC_INITIALIZE_IDX10 tasks0=CONFIG_TEST_10_FUNC_TASKS_0 tasks1=CONFIG_TEST_10_FUNC_TASKS_1 tasks2=CONFIG_TEST_10_FUNC_TASKS_2 tasks3=CONFIG_TEST_10_FUNC_TASKS_3 tasks4=CONFIG_TEST_10_FUNC_TASKS_4 start=CONFIG_TEST_FUNC_START_IDX10 status=CONFIG_TEST_FUNC_STATUS_IDX10 index=CONFIG_TEST_INSTANCE_INDEX_IDX10 data=CONFIG_TEST_INSTANCE_INIT_DATA_IDX10 library=CONFIG_TEST_LIBRARY_STRUCT_NAME_IDX10 num_tasks=CONFIG_TEST_HARNESS_MAX_NUM_TASKS?number />
  <@add_test used=CONFIG_TEST_NUMBER_11 next=CONFIG_TEST_NUMBER_12 name=CONFIG_TEST_NAME_IDX11 initialize=CONFIG_TEST_FUNC_INITIALIZE_IDX11 tasks0=CONFIG_TEST_11_FUNC_TASKS_0 tasks1=CONFIG_TEST_11_FUNC_TASKS_1 tasks2=CONFIG_TEST_11_FUNC_TASKS_2 tasks3=CONFIG_TEST_11_FUNC_TASKS_3 tasks4=CONFIG_TEST_11_FUNC_TASKS_4 start=CONFIG_TEST_FUNC_START_IDX11 status=CONFIG_TEST_FUNC_STATUS_IDX11 index=CONFIG_TEST_INSTANCE_INDEX_IDX11 data=CONFIG_TEST_INSTANCE_INIT_DATA_IDX11 library=CONFIG_TEST_LIBRARY_STRUCT_NAME_IDX11 num_tasks=CONFIG_TEST_HARNESS_MAX_NUM_TASKS?number />
  <@add_test used=CONFIG_TEST_NUMBER_12 next=CONFIG_TEST_NUMBER_13 name=CONFIG_TEST_NAME_IDX12 initialize=CONFIG_TEST_FUNC_INITIALIZE_IDX12 tasks0=CONFIG_TEST_12_FUNC_TASKS_0 tasks1=CONFIG_TEST_12_FUNC_TASKS_1 tasks2=CONFIG_TEST_12_FUNC_TASKS_2 tasks3=CONFIG_TEST_12_FUNC_TASKS_3 tasks4=CONFIG_TEST_12_FUNC_TASKS_4 start=CONFIG_TEST_FUNC_START_IDX12 status=CONFIG_TEST_FUNC_STATUS_IDX12 index=CONFIG_TEST_INSTANCE_INDEX_IDX12 data=CONFIG_TEST_INSTANCE_INIT_DATA_IDX12 library=CONFIG_TEST_LIBRARY_STRUCT_NAME_IDX12 num_tasks=CONFIG_TEST_HARNESS_MAX_NUM_TASKS?number />
  <@add_test used=CONFIG_TEST_NUMBER_13 next=CONFIG_TEST_NUMBER_14 name=CONFIG_TEST_NAME_IDX13 initialize=CONFIG_TEST_FUNC_INITIALIZE_IDX13 tasks0=CONFIG_TEST_13_FUNC_TASKS_0 tasks1=CONFIG_TEST_13_FUNC_TASKS_1 tasks2=CONFIG_TEST_13_FUNC_TASKS_2 tasks3=CONFIG_TEST_13_FUNC_TASKS_3 tasks4=CONFIG_TEST_13_FUNC_TASKS_4 start=CONFIG_TEST_FUNC_START_IDX13 status=CONFIG_TEST_FUNC_STATUS_IDX13 index=CONFIG_TEST_INSTANCE_INDEX_IDX13 data=CONFIG_TEST_INSTANCE_INIT_DATA_IDX13 library=CONFIG_TEST_LIBRARY_STRUCT_NAME_IDX13 num_tasks=CONFIG_TEST_HARNESS_MAX_NUM_TASKS?number />
  <@add_test used=CONFIG_TEST_NUMBER_14 next=CONFIG_TEST_NUMBER_15 name=CONFIG_TEST_NAME_IDX14 initialize=CONFIG_TEST_FUNC_INITIALIZE_IDX14 tasks0=CONFIG_TEST_14_FUNC_TASKS_0 tasks1=CONFIG_TEST_14_FUNC_TASKS_1 tasks2=CONFIG_TEST_14_FUNC_TASKS_2 tasks3=CONFIG_TEST_14_FUNC_TASKS_3 tasks4=CONFIG_TEST_14_FUNC_TASKS_4 start=CONFIG_TEST_FUNC_START_IDX14 status=CONFIG_TEST_FUNC_STATUS_IDX14 index=CONFIG_TEST_INSTANCE_INDEX_IDX14 data=CONFIG_TEST_INSTANCE_INIT_DATA_IDX14 library=CONFIG_TEST_LIBRARY_STRUCT_NAME_IDX14 num_tasks=CONFIG_TEST_HARNESS_MAX_NUM_TASKS?number />
  <@add_test used=CONFIG_TEST_NUMBER_15 next=false                 name=CONFIG_TEST_NAME_IDX15 initialize=CONFIG_TEST_FUNC_INITIALIZE_IDX15 tasks0=CONFIG_TEST_15_FUNC_TASKS_0 tasks1=CONFIG_TEST_15_FUNC_TASKS_1 tasks2=CONFIG_TEST_15_FUNC_TASKS_2 tasks3=CONFIG_TEST_15_FUNC_TASKS_3 tasks4=CONFIG_TEST_15_FUNC_TASKS_4 start=CONFIG_TEST_FUNC_START_IDX15 status=CONFIG_TEST_FUNC_STATUS_IDX15 index=CONFIG_TEST_INSTANCE_INDEX_IDX15 data=CONFIG_TEST_INSTANCE_INIT_DATA_IDX15 library=CONFIG_TEST_LIBRARY_STRUCT_NAME_IDX15 num_tasks=CONFIG_TEST_HARNESS_MAX_NUM_TASKS?number />
};

/* Test Harness Initialization Structure */
static const TEST_INIT_DATA testData =
{
    .numberOfTests  = sizeof(testList)/sizeof(TEST_DATA),
    .tests          = testList
};

// </editor-fold>


</#if>
<#--
/*******************************************************************************
 End of File
*/
-->
