<#-- Test index 0 - Library Instance 0 -->
<#if CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX0?has_content>
  <#if CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX0?number gte 1>
    <#if CONFIG_TEST_LIBRARY_IDX0_TASKS_IDX0 != "NULL" && CONFIG_TEST_LIBRARY_IDX0_TASKS_IDX0_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_0, TEST_LUT_INDEX_0, ${CONFIG_TEST_LIBRARY_IDX0_TASKS_IDX0});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX0_TASKS_IDX1 != "NULL" && CONFIG_TEST_LIBRARY_IDX0_TASKS_IDX1_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_0, TEST_LUT_INDEX_0, ${CONFIG_TEST_LIBRARY_IDX0_TASKS_IDX1});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX0_TASKS_IDX2 != "NULL" && CONFIG_TEST_LIBRARY_IDX0_TASKS_IDX2_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_0, TEST_LUT_INDEX_0, ${CONFIG_TEST_LIBRARY_IDX0_TASKS_IDX2});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX0_TASKS_IDX3 != "NULL" && CONFIG_TEST_LIBRARY_IDX0_TASKS_IDX3_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_0, TEST_LUT_INDEX_0, ${CONFIG_TEST_LIBRARY_IDX0_TASKS_IDX3});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX0_TASKS_IDX4 != "NULL" && CONFIG_TEST_LIBRARY_IDX0_TASKS_IDX4_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_0, TEST_LUT_INDEX_0, ${CONFIG_TEST_LIBRARY_IDX0_TASKS_IDX4});
    </#if>
  </#if>
</#if>
<#-- Test index 0 - Library Instance 1 -->
<#if CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX0?has_content>
  <#if CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX0?number gte 2>
    <#if CONFIG_TEST_LIBRARY_IDX0_TASKS_IDX0 != "NULL" && CONFIG_TEST_LIBRARY_IDX0_TASKS_IDX0_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_0, TEST_LUT_INDEX_1, ${CONFIG_TEST_LIBRARY_IDX0_TASKS_IDX0});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX0_TASKS_IDX1 != "NULL" && CONFIG_TEST_LIBRARY_IDX0_TASKS_IDX1_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_0, TEST_LUT_INDEX_1, ${CONFIG_TEST_LIBRARY_IDX0_TASKS_IDX1});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX0_TASKS_IDX2 != "NULL" && CONFIG_TEST_LIBRARY_IDX0_TASKS_IDX2_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_0, TEST_LUT_INDEX_1, ${CONFIG_TEST_LIBRARY_IDX0_TASKS_IDX2});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX0_TASKS_IDX3 != "NULL" && CONFIG_TEST_LIBRARY_IDX0_TASKS_IDX3_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_0, TEST_LUT_INDEX_1, ${CONFIG_TEST_LIBRARY_IDX0_TASKS_IDX3});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX0_TASKS_IDX4 != "NULL" && CONFIG_TEST_LIBRARY_IDX0_TASKS_IDX4_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_0, TEST_LUT_INDEX_1, ${CONFIG_TEST_LIBRARY_IDX0_TASKS_IDX4});
    </#if>
  </#if>
</#if>
<#-- Test index 0 - Library Instance 2 -->
<#if CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX0?has_content>
  <#if CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX0?number gte 3>
    <#if CONFIG_TEST_LIBRARY_IDX0_TASKS_IDX0 != "NULL" && CONFIG_TEST_LIBRARY_IDX0_TASKS_IDX0_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_0, TEST_LUT_INDEX_2, ${CONFIG_TEST_LIBRARY_IDX0_TASKS_IDX0});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX0_TASKS_IDX1 != "NULL" && CONFIG_TEST_LIBRARY_IDX0_TASKS_IDX1_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_0, TEST_LUT_INDEX_2, ${CONFIG_TEST_LIBRARY_IDX0_TASKS_IDX1});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX0_TASKS_IDX2 != "NULL" && CONFIG_TEST_LIBRARY_IDX0_TASKS_IDX2_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_0, TEST_LUT_INDEX_2, ${CONFIG_TEST_LIBRARY_IDX0_TASKS_IDX2});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX0_TASKS_IDX3 != "NULL" && CONFIG_TEST_LIBRARY_IDX0_TASKS_IDX3_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_0, TEST_LUT_INDEX_2, ${CONFIG_TEST_LIBRARY_IDX0_TASKS_IDX3});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX0_TASKS_IDX4 != "NULL" && CONFIG_TEST_LIBRARY_IDX0_TASKS_IDX4_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_0, TEST_LUT_INDEX_2, ${CONFIG_TEST_LIBRARY_IDX0_TASKS_IDX4});
    </#if>
  </#if>
</#if>
<#-- Test index 1 - Library Instance 0 -->
<#if CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX1?has_content>
  <#if CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX1?number gte 1>
    <#if CONFIG_TEST_LIBRARY_IDX1_TASKS_IDX0 != "NULL" && CONFIG_TEST_LIBRARY_IDX1_TASKS_IDX0_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_1, TEST_LUT_INDEX_0, ${CONFIG_TEST_LIBRARY_IDX1_TASKS_IDX0});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX1_TASKS_IDX1 != "NULL" && CONFIG_TEST_LIBRARY_IDX1_TASKS_IDX1_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_1, TEST_LUT_INDEX_0, ${CONFIG_TEST_LIBRARY_IDX1_TASKS_IDX1});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX1_TASKS_IDX2 != "NULL" && CONFIG_TEST_LIBRARY_IDX1_TASKS_IDX2_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_1, TEST_LUT_INDEX_0, ${CONFIG_TEST_LIBRARY_IDX1_TASKS_IDX2});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX1_TASKS_IDX3 != "NULL" && CONFIG_TEST_LIBRARY_IDX1_TASKS_IDX3_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_1, TEST_LUT_INDEX_0, ${CONFIG_TEST_LIBRARY_IDX1_TASKS_IDX3});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX1_TASKS_IDX4 != "NULL" && CONFIG_TEST_LIBRARY_IDX1_TASKS_IDX4_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_1, TEST_LUT_INDEX_0, ${CONFIG_TEST_LIBRARY_IDX1_TASKS_IDX4});
    </#if>
  </#if>
</#if>
<#-- Test index 1 - Library Instance 1 -->
<#if CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX1?has_content>
  <#if CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX1?number gte 2>
    <#if CONFIG_TEST_LIBRARY_IDX1_TASKS_IDX0 != "NULL" && CONFIG_TEST_LIBRARY_IDX1_TASKS_IDX0_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_1, TEST_LUT_INDEX_1, ${CONFIG_TEST_LIBRARY_IDX1_TASKS_IDX0});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX1_TASKS_IDX1 != "NULL" && CONFIG_TEST_LIBRARY_IDX1_TASKS_IDX1_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_1, TEST_LUT_INDEX_1, ${CONFIG_TEST_LIBRARY_IDX1_TASKS_IDX1});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX1_TASKS_IDX2 != "NULL" && CONFIG_TEST_LIBRARY_IDX1_TASKS_IDX2_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_1, TEST_LUT_INDEX_1, ${CONFIG_TEST_LIBRARY_IDX1_TASKS_IDX2});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX1_TASKS_IDX3 != "NULL" && CONFIG_TEST_LIBRARY_IDX1_TASKS_IDX3_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_1, TEST_LUT_INDEX_1, ${CONFIG_TEST_LIBRARY_IDX1_TASKS_IDX3});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX1_TASKS_IDX4 != "NULL" && CONFIG_TEST_LIBRARY_IDX1_TASKS_IDX4_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_1, TEST_LUT_INDEX_1, ${CONFIG_TEST_LIBRARY_IDX1_TASKS_IDX4});
    </#if>
  </#if>
</#if>
<#-- Test index 1 - Library Instance 2 -->
<#if CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX1?has_content>
  <#if CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX1?number gte 3>
    <#if CONFIG_TEST_LIBRARY_IDX1_TASKS_IDX0 != "NULL" && CONFIG_TEST_LIBRARY_IDX1_TASKS_IDX0_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_1, TEST_LUT_INDEX_2, ${CONFIG_TEST_LIBRARY_IDX1_TASKS_IDX0});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX1_TASKS_IDX1 != "NULL" && CONFIG_TEST_LIBRARY_IDX1_TASKS_IDX1_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_1, TEST_LUT_INDEX_2, ${CONFIG_TEST_LIBRARY_IDX1_TASKS_IDX1});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX1_TASKS_IDX2 != "NULL" && CONFIG_TEST_LIBRARY_IDX1_TASKS_IDX2_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_1, TEST_LUT_INDEX_2, ${CONFIG_TEST_LIBRARY_IDX1_TASKS_IDX2});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX1_TASKS_IDX3 != "NULL" && CONFIG_TEST_LIBRARY_IDX1_TASKS_IDX3_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_1, TEST_LUT_INDEX_2, ${CONFIG_TEST_LIBRARY_IDX1_TASKS_IDX3});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX1_TASKS_IDX4 != "NULL" && CONFIG_TEST_LIBRARY_IDX1_TASKS_IDX4_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_1, TEST_LUT_INDEX_2, ${CONFIG_TEST_LIBRARY_IDX1_TASKS_IDX4});
    </#if>
  </#if>
</#if>
<#-- Test index 2 - Library Instance 0 -->
<#if CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX2?has_content>
  <#if CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX2?number gte 1>
    <#if CONFIG_TEST_LIBRARY_IDX2_TASKS_IDX0 != "NULL" && CONFIG_TEST_LIBRARY_IDX2_TASKS_IDX0_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_2, TEST_LUT_INDEX_0, ${CONFIG_TEST_LIBRARY_IDX2_TASKS_IDX0});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX2_TASKS_IDX1 != "NULL" && CONFIG_TEST_LIBRARY_IDX2_TASKS_IDX1_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_2, TEST_LUT_INDEX_0, ${CONFIG_TEST_LIBRARY_IDX2_TASKS_IDX1});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX2_TASKS_IDX2 != "NULL" && CONFIG_TEST_LIBRARY_IDX2_TASKS_IDX2_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_2, TEST_LUT_INDEX_0, ${CONFIG_TEST_LIBRARY_IDX2_TASKS_IDX2});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX2_TASKS_IDX3 != "NULL" && CONFIG_TEST_LIBRARY_IDX2_TASKS_IDX3_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_2, TEST_LUT_INDEX_0, ${CONFIG_TEST_LIBRARY_IDX2_TASKS_IDX3});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX2_TASKS_IDX4 != "NULL" && CONFIG_TEST_LIBRARY_IDX2_TASKS_IDX4_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_2, TEST_LUT_INDEX_0, ${CONFIG_TEST_LIBRARY_IDX2_TASKS_IDX4});
    </#if>
  </#if>
</#if>
<#-- Test index 2 - Library Instance 1 -->
<#if CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX2?has_content>
  <#if CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX2?number gte 2>
    <#if CONFIG_TEST_LIBRARY_IDX2_TASKS_IDX0 != "NULL" && CONFIG_TEST_LIBRARY_IDX2_TASKS_IDX0_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_2, TEST_LUT_INDEX_1, ${CONFIG_TEST_LIBRARY_IDX2_TASKS_IDX0});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX2_TASKS_IDX1 != "NULL" && CONFIG_TEST_LIBRARY_IDX2_TASKS_IDX1_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_2, TEST_LUT_INDEX_1, ${CONFIG_TEST_LIBRARY_IDX2_TASKS_IDX1});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX2_TASKS_IDX2 != "NULL" && CONFIG_TEST_LIBRARY_IDX2_TASKS_IDX2_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_2, TEST_LUT_INDEX_1, ${CONFIG_TEST_LIBRARY_IDX2_TASKS_IDX2});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX2_TASKS_IDX3 != "NULL" && CONFIG_TEST_LIBRARY_IDX2_TASKS_IDX3_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_2, TEST_LUT_INDEX_1, ${CONFIG_TEST_LIBRARY_IDX2_TASKS_IDX3});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX2_TASKS_IDX4 != "NULL" && CONFIG_TEST_LIBRARY_IDX2_TASKS_IDX4_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_2, TEST_LUT_INDEX_1, ${CONFIG_TEST_LIBRARY_IDX2_TASKS_IDX4});
    </#if>
  </#if>
</#if>
<#-- Test index 2 - Library Instance 2 -->
<#if CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX2?has_content>
  <#if CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX2?number gte 3>
    <#if CONFIG_TEST_LIBRARY_IDX2_TASKS_IDX0 != "NULL" && CONFIG_TEST_LIBRARY_IDX2_TASKS_IDX0_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_2, TEST_LUT_INDEX_2, ${CONFIG_TEST_LIBRARY_IDX2_TASKS_IDX0});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX2_TASKS_IDX1 != "NULL" && CONFIG_TEST_LIBRARY_IDX2_TASKS_IDX1_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_2, TEST_LUT_INDEX_2, ${CONFIG_TEST_LIBRARY_IDX2_TASKS_IDX1});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX2_TASKS_IDX2 != "NULL" && CONFIG_TEST_LIBRARY_IDX2_TASKS_IDX2_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_2, TEST_LUT_INDEX_2, ${CONFIG_TEST_LIBRARY_IDX2_TASKS_IDX2});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX2_TASKS_IDX3 != "NULL" && CONFIG_TEST_LIBRARY_IDX2_TASKS_IDX3_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_2, TEST_LUT_INDEX_2, ${CONFIG_TEST_LIBRARY_IDX2_TASKS_IDX3});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX2_TASKS_IDX4 != "NULL" && CONFIG_TEST_LIBRARY_IDX2_TASKS_IDX4_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_2, TEST_LUT_INDEX_2, ${CONFIG_TEST_LIBRARY_IDX2_TASKS_IDX4});
    </#if>
  </#if>
</#if>
<#-- Test index 3 - Library Instance 0 -->
<#if CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX3?has_content>
  <#if CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX3?number gte 1>
    <#if CONFIG_TEST_LIBRARY_IDX3_TASKS_IDX0 != "NULL" && CONFIG_TEST_LIBRARY_IDX3_TASKS_IDX0_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_3, TEST_LUT_INDEX_0, ${CONFIG_TEST_LIBRARY_IDX3_TASKS_IDX0});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX3_TASKS_IDX1 != "NULL" && CONFIG_TEST_LIBRARY_IDX3_TASKS_IDX1_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_3, TEST_LUT_INDEX_0, ${CONFIG_TEST_LIBRARY_IDX3_TASKS_IDX1});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX3_TASKS_IDX2 != "NULL" && CONFIG_TEST_LIBRARY_IDX3_TASKS_IDX2_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_3, TEST_LUT_INDEX_0, ${CONFIG_TEST_LIBRARY_IDX3_TASKS_IDX2});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX3_TASKS_IDX3 != "NULL" && CONFIG_TEST_LIBRARY_IDX3_TASKS_IDX4_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_3, TEST_LUT_INDEX_0, ${CONFIG_TEST_LIBRARY_IDX3_TASKS_IDX3});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX3_TASKS_IDX4 != "NULL" && CONFIG_TEST_LIBRARY_IDX3_TASKS_IDX5_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_3, TEST_LUT_INDEX_0, ${CONFIG_TEST_LIBRARY_IDX3_TASKS_IDX4});
    </#if>
  </#if>
</#if>
<#-- Test index 3 - Library Instance 1 -->
<#if CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX3?has_content>
  <#if CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX3?number gte 2>
    <#if CONFIG_TEST_LIBRARY_IDX3_TASKS_IDX0 != "NULL" && CONFIG_TEST_LIBRARY_IDX3_TASKS_IDX0_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_3, TEST_LUT_INDEX_1, ${CONFIG_TEST_LIBRARY_IDX3_TASKS_IDX0});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX3_TASKS_IDX1 != "NULL" && CONFIG_TEST_LIBRARY_IDX3_TASKS_IDX1_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_3, TEST_LUT_INDEX_1, ${CONFIG_TEST_LIBRARY_IDX3_TASKS_IDX1});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX3_TASKS_IDX2 != "NULL" && CONFIG_TEST_LIBRARY_IDX3_TASKS_IDX2_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_3, TEST_LUT_INDEX_1, ${CONFIG_TEST_LIBRARY_IDX3_TASKS_IDX2});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX3_TASKS_IDX3 != "NULL" && CONFIG_TEST_LIBRARY_IDX3_TASKS_IDX3_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_3, TEST_LUT_INDEX_1, ${CONFIG_TEST_LIBRARY_IDX3_TASKS_IDX3});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX3_TASKS_IDX4 != "NULL" && CONFIG_TEST_LIBRARY_IDX3_TASKS_IDX4_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_3, TEST_LUT_INDEX_1, ${CONFIG_TEST_LIBRARY_IDX3_TASKS_IDX4});
    </#if>
  </#if>
</#if>
<#-- Test index 3 - Library Instance 2 -->
<#if CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX3?has_content>
  <#if CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX3?number gte 3>
    <#if CONFIG_TEST_LIBRARY_IDX3_TASKS_IDX0 != "NULL" && CONFIG_TEST_LIBRARY_IDX3_TASKS_IDX0_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_3, TEST_LUT_INDEX_2, ${CONFIG_TEST_LIBRARY_IDX3_TASKS_IDX0});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX3_TASKS_IDX1 != "NULL" && CONFIG_TEST_LIBRARY_IDX3_TASKS_IDX1_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_3, TEST_LUT_INDEX_2, ${CONFIG_TEST_LIBRARY_IDX3_TASKS_IDX1});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX3_TASKS_IDX2 != "NULL" && CONFIG_TEST_LIBRARY_IDX3_TASKS_IDX2_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_3, TEST_LUT_INDEX_2, ${CONFIG_TEST_LIBRARY_IDX3_TASKS_IDX2});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX3_TASKS_IDX3 != "NULL" && CONFIG_TEST_LIBRARY_IDX3_TASKS_IDX3_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_3, TEST_LUT_INDEX_2, ${CONFIG_TEST_LIBRARY_IDX3_TASKS_IDX3});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX3_TASKS_IDX4 != "NULL" && CONFIG_TEST_LIBRARY_IDX3_TASKS_IDX4_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_3, TEST_LUT_INDEX_2, ${CONFIG_TEST_LIBRARY_IDX3_TASKS_IDX4});
    </#if>
  </#if>
</#if>
<#-- Test index 4 - Library Instance 0 -->
<#if CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX4?has_content>
  <#if CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX4?number gte 1>
    <#if CONFIG_TEST_LIBRARY_IDX4_TASKS_IDX0 != "NULL" && CONFIG_TEST_LIBRARY_IDX4_TASKS_IDX0_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_4, TEST_LUT_INDEX_0, ${CONFIG_TEST_LIBRARY_IDX4_TASKS_IDX0});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX4_TASKS_IDX1 != "NULL" && CONFIG_TEST_LIBRARY_IDX4_TASKS_IDX1_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_4, TEST_LUT_INDEX_0, ${CONFIG_TEST_LIBRARY_IDX4_TASKS_IDX1});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX4_TASKS_IDX2 != "NULL" && CONFIG_TEST_LIBRARY_IDX4_TASKS_IDX2_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_4, TEST_LUT_INDEX_0, ${CONFIG_TEST_LIBRARY_IDX4_TASKS_IDX2});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX4_TASKS_IDX3 != "NULL" && CONFIG_TEST_LIBRARY_IDX4_TASKS_IDX3_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_4, TEST_LUT_INDEX_0, ${CONFIG_TEST_LIBRARY_IDX4_TASKS_IDX3});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX4_TASKS_IDX4 != "NULL" && CONFIG_TEST_LIBRARY_IDX4_TASKS_IDX4_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_4, TEST_LUT_INDEX_0, ${CONFIG_TEST_LIBRARY_IDX4_TASKS_IDX4});
    </#if>
  </#if>
</#if>
<#-- Test index 4 - Library Instance 1 -->
<#if CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX4?has_content>
  <#if CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX4?number gte 2>
    <#if CONFIG_TEST_LIBRARY_IDX4_TASKS_IDX0 != "NULL" && CONFIG_TEST_LIBRARY_IDX4_TASKS_IDX0_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_4, TEST_LUT_INDEX_1, ${CONFIG_TEST_LIBRARY_IDX4_TASKS_IDX0});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX4_TASKS_IDX1 != "NULL" && CONFIG_TEST_LIBRARY_IDX4_TASKS_IDX1_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_4, TEST_LUT_INDEX_1, ${CONFIG_TEST_LIBRARY_IDX4_TASKS_IDX1});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX4_TASKS_IDX2 != "NULL" && CONFIG_TEST_LIBRARY_IDX4_TASKS_IDX2_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_4, TEST_LUT_INDEX_1, ${CONFIG_TEST_LIBRARY_IDX4_TASKS_IDX2});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX4_TASKS_IDX3 != "NULL" && CONFIG_TEST_LIBRARY_IDX4_TASKS_IDX3_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_4, TEST_LUT_INDEX_1, ${CONFIG_TEST_LIBRARY_IDX4_TASKS_IDX3});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX4_TASKS_IDX4 != "NULL" && CONFIG_TEST_LIBRARY_IDX4_TASKS_IDX4_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_4, TEST_LUT_INDEX_1, ${CONFIG_TEST_LIBRARY_IDX4_TASKS_IDX4});
    </#if>
  </#if>
</#if>
<#-- Test index 4 - Library Instance 2 -->
<#if CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX4?has_content>
  <#if CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX4?number gte 3>
    <#if CONFIG_TEST_LIBRARY_IDX4_TASKS_IDX0 != "NULL" && CONFIG_TEST_LIBRARY_IDX4_TASKS_IDX0_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_4, TEST_LUT_INDEX_2, ${CONFIG_TEST_LIBRARY_IDX4_TASKS_IDX0});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX4_TASKS_IDX1 != "NULL" && CONFIG_TEST_LIBRARY_IDX4_TASKS_IDX1_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_4, TEST_LUT_INDEX_2, ${CONFIG_TEST_LIBRARY_IDX4_TASKS_IDX1});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX4_TASKS_IDX2 != "NULL" && CONFIG_TEST_LIBRARY_IDX4_TASKS_IDX2_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_4, TEST_LUT_INDEX_2, ${CONFIG_TEST_LIBRARY_IDX4_TASKS_IDX2});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX4_TASKS_IDX3 != "NULL" && CONFIG_TEST_LIBRARY_IDX4_TASKS_IDX3_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_4, TEST_LUT_INDEX_2, ${CONFIG_TEST_LIBRARY_IDX4_TASKS_IDX3});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX4_TASKS_IDX4 != "NULL" && CONFIG_TEST_LIBRARY_IDX4_TASKS_IDX4_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_4, TEST_LUT_INDEX_2, ${CONFIG_TEST_LIBRARY_IDX4_TASKS_IDX4});
    </#if>
  </#if>
</#if>
<#-- Test index 5 - Library Instance 0 -->
<#if CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX5?has_content>
  <#if CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX5?number gte 1>
    <#if CONFIG_TEST_LIBRARY_IDX5_TASKS_IDX0 != "NULL" && CONFIG_TEST_LIBRARY_IDX5_TASKS_IDX0_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_5, TEST_LUT_INDEX_0, ${CONFIG_TEST_LIBRARY_IDX5_TASKS_IDX0});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX5_TASKS_IDX1 != "NULL" && CONFIG_TEST_LIBRARY_IDX5_TASKS_IDX1_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_5, TEST_LUT_INDEX_0, ${CONFIG_TEST_LIBRARY_IDX5_TASKS_IDX1});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX5_TASKS_IDX2 != "NULL" && CONFIG_TEST_LIBRARY_IDX5_TASKS_IDX2_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_5, TEST_LUT_INDEX_0, ${CONFIG_TEST_LIBRARY_IDX5_TASKS_IDX2});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX5_TASKS_IDX3 != "NULL" && CONFIG_TEST_LIBRARY_IDX5_TASKS_IDX3_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_5, TEST_LUT_INDEX_0, ${CONFIG_TEST_LIBRARY_IDX5_TASKS_IDX3});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX5_TASKS_IDX4 != "NULL" && CONFIG_TEST_LIBRARY_IDX5_TASKS_IDX4_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_5, TEST_LUT_INDEX_0, ${CONFIG_TEST_LIBRARY_IDX5_TASKS_IDX4});
    </#if>
  </#if>
</#if>
<#-- Test index 5 - Library Instance 1 -->
<#if CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX5?has_content>
  <#if CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX5?number gte 2>
    <#if CONFIG_TEST_LIBRARY_IDX5_TASKS_IDX0 != "NULL" && CONFIG_TEST_LIBRARY_IDX5_TASKS_IDX0_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_5, TEST_LUT_INDEX_1, ${CONFIG_TEST_LIBRARY_IDX5_TASKS_IDX0});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX5_TASKS_IDX1 != "NULL" && CONFIG_TEST_LIBRARY_IDX5_TASKS_IDX1_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_5, TEST_LUT_INDEX_1, ${CONFIG_TEST_LIBRARY_IDX5_TASKS_IDX1});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX5_TASKS_IDX2 != "NULL" && CONFIG_TEST_LIBRARY_IDX5_TASKS_IDX2_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_5, TEST_LUT_INDEX_1, ${CONFIG_TEST_LIBRARY_IDX5_TASKS_IDX2});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX5_TASKS_IDX3 != "NULL" && CONFIG_TEST_LIBRARY_IDX5_TASKS_IDX3_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_5, TEST_LUT_INDEX_1, ${CONFIG_TEST_LIBRARY_IDX5_TASKS_IDX3});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX5_TASKS_IDX4 != "NULL" && CONFIG_TEST_LIBRARY_IDX5_TASKS_IDX4_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_5, TEST_LUT_INDEX_1, ${CONFIG_TEST_LIBRARY_IDX5_TASKS_IDX4});
    </#if>
  </#if>
</#if>
<#-- Test index 5 - Library Instance 2 -->
<#if CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX5?has_content>
  <#if CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX5?number gte 3>
    <#if CONFIG_TEST_LIBRARY_IDX5_TASKS_IDX0 != "NULL" && CONFIG_TEST_LIBRARY_IDX5_TASKS_IDX0_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_5, TEST_LUT_INDEX_2, ${CONFIG_TEST_LIBRARY_IDX5_TASKS_IDX0});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX5_TASKS_IDX1 != "NULL" && CONFIG_TEST_LIBRARY_IDX5_TASKS_IDX1_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_5, TEST_LUT_INDEX_2, ${CONFIG_TEST_LIBRARY_IDX5_TASKS_IDX1});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX5_TASKS_IDX2 != "NULL" && CONFIG_TEST_LIBRARY_IDX5_TASKS_IDX2_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_5, TEST_LUT_INDEX_2, ${CONFIG_TEST_LIBRARY_IDX5_TASKS_IDX2});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX5_TASKS_IDX3 != "NULL" && CONFIG_TEST_LIBRARY_IDX5_TASKS_IDX3_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_5, TEST_LUT_INDEX_2, ${CONFIG_TEST_LIBRARY_IDX5_TASKS_IDX3});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX5_TASKS_IDX4 != "NULL" && CONFIG_TEST_LIBRARY_IDX5_TASKS_IDX4_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_5, TEST_LUT_INDEX_2, ${CONFIG_TEST_LIBRARY_IDX5_TASKS_IDX4});
    </#if>
  </#if>
</#if>
<#-- Test index 6 - Library Instance 0 -->
<#if CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX6?has_content>
  <#if CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX6?number gte 1>
    <#if CONFIG_TEST_LIBRARY_IDX6_TASKS_IDX0 != "NULL" && CONFIG_TEST_LIBRARY_IDX6_TASKS_IDX0_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_6, TEST_LUT_INDEX_0, ${CONFIG_TEST_LIBRARY_IDX6_TASKS_IDX0});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX6_TASKS_IDX1 != "NULL" && CONFIG_TEST_LIBRARY_IDX6_TASKS_IDX1_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_6, TEST_LUT_INDEX_0, ${CONFIG_TEST_LIBRARY_IDX6_TASKS_IDX1});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX6_TASKS_IDX2 != "NULL" && CONFIG_TEST_LIBRARY_IDX6_TASKS_IDX2_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_6, TEST_LUT_INDEX_0, ${CONFIG_TEST_LIBRARY_IDX6_TASKS_IDX2});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX6_TASKS_IDX3 != "NULL" && CONFIG_TEST_LIBRARY_IDX6_TASKS_IDX3_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_6, TEST_LUT_INDEX_0, ${CONFIG_TEST_LIBRARY_IDX6_TASKS_IDX3});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX6_TASKS_IDX4 != "NULL" && CONFIG_TEST_LIBRARY_IDX6_TASKS_IDX4_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_6, TEST_LUT_INDEX_0, ${CONFIG_TEST_LIBRARY_IDX6_TASKS_IDX4});
    </#if>
  </#if>
</#if>
<#-- Test index 6 - Library Instance 1 -->
<#if CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX6?has_content>
  <#if CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX6?number gte 2>
    <#if CONFIG_TEST_LIBRARY_IDX6_TASKS_IDX0 != "NULL" && CONFIG_TEST_LIBRARY_IDX6_TASKS_IDX0_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_6, TEST_LUT_INDEX_1, ${CONFIG_TEST_LIBRARY_IDX6_TASKS_IDX0});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX6_TASKS_IDX1 != "NULL" && CONFIG_TEST_LIBRARY_IDX6_TASKS_IDX1_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_6, TEST_LUT_INDEX_1, ${CONFIG_TEST_LIBRARY_IDX6_TASKS_IDX1});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX6_TASKS_IDX2 != "NULL" && CONFIG_TEST_LIBRARY_IDX6_TASKS_IDX2_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_6, TEST_LUT_INDEX_1, ${CONFIG_TEST_LIBRARY_IDX6_TASKS_IDX2});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX6_TASKS_IDX3 != "NULL" && CONFIG_TEST_LIBRARY_IDX6_TASKS_IDX3_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_6, TEST_LUT_INDEX_1, ${CONFIG_TEST_LIBRARY_IDX6_TASKS_IDX3});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX6_TASKS_IDX4 != "NULL" && CONFIG_TEST_LIBRARY_IDX6_TASKS_IDX4_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_6, TEST_LUT_INDEX_1, ${CONFIG_TEST_LIBRARY_IDX6_TASKS_IDX4});
    </#if>
  </#if>
</#if>
<#-- Test index 6 - Library Instance 2 -->
<#if CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX6?has_content>
  <#if CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX6?number gte 3>
    <#if CONFIG_TEST_LIBRARY_IDX6_TASKS_IDX0 != "NULL" && CONFIG_TEST_LIBRARY_IDX6_TASKS_IDX0_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_6, TEST_LUT_INDEX_2, ${CONFIG_TEST_LIBRARY_IDX6_TASKS_IDX0});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX6_TASKS_IDX1 != "NULL" && CONFIG_TEST_LIBRARY_IDX6_TASKS_IDX1_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_6, TEST_LUT_INDEX_2, ${CONFIG_TEST_LIBRARY_IDX6_TASKS_IDX1});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX6_TASKS_IDX2 != "NULL" && CONFIG_TEST_LIBRARY_IDX6_TASKS_IDX2_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_6, TEST_LUT_INDEX_2, ${CONFIG_TEST_LIBRARY_IDX6_TASKS_IDX2});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX6_TASKS_IDX3 != "NULL" && CONFIG_TEST_LIBRARY_IDX6_TASKS_IDX3_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_6, TEST_LUT_INDEX_2, ${CONFIG_TEST_LIBRARY_IDX6_TASKS_IDX3});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX6_TASKS_IDX4 != "NULL" && CONFIG_TEST_LIBRARY_IDX6_TASKS_IDX4_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_6, TEST_LUT_INDEX_2, ${CONFIG_TEST_LIBRARY_IDX6_TASKS_IDX4});
    </#if>
  </#if>
</#if>
<#-- Test index 7 - Library Instance 0 -->
<#if CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX7?has_content>
  <#if CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX7?number gte 1>
    <#if CONFIG_TEST_LIBRARY_IDX7_TASKS_IDX0 != "NULL" && CONFIG_TEST_LIBRARY_IDX7_TASKS_IDX0_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_7, TEST_LUT_INDEX_0, ${CONFIG_TEST_LIBRARY_IDX7_TASKS_IDX0});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX7_TASKS_IDX1 != "NULL" && CONFIG_TEST_LIBRARY_IDX7_TASKS_IDX1_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_7, TEST_LUT_INDEX_0, ${CONFIG_TEST_LIBRARY_IDX7_TASKS_IDX1});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX7_TASKS_IDX2 != "NULL" && CONFIG_TEST_LIBRARY_IDX7_TASKS_IDX2_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_7, TEST_LUT_INDEX_0, ${CONFIG_TEST_LIBRARY_IDX7_TASKS_IDX2});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX7_TASKS_IDX3 != "NULL" && CONFIG_TEST_LIBRARY_IDX7_TASKS_IDX3_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_7, TEST_LUT_INDEX_0, ${CONFIG_TEST_LIBRARY_IDX7_TASKS_IDX3});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX7_TASKS_IDX4 != "NULL" && CONFIG_TEST_LIBRARY_IDX7_TASKS_IDX4_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_7, TEST_LUT_INDEX_0, ${CONFIG_TEST_LIBRARY_IDX7_TASKS_IDX4});
    </#if>
  </#if>
</#if>
<#-- Test index 7 - Library Instance 1 -->
<#if CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX7?has_content>
  <#if CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX7?number gte 2>
    <#if CONFIG_TEST_LIBRARY_IDX7_TASKS_IDX0 != "NULL" && CONFIG_TEST_LIBRARY_IDX7_TASKS_IDX0_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_7, TEST_LUT_INDEX_1, ${CONFIG_TEST_LIBRARY_IDX7_TASKS_IDX0});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX7_TASKS_IDX1 != "NULL" && CONFIG_TEST_LIBRARY_IDX7_TASKS_IDX1_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_7, TEST_LUT_INDEX_1, ${CONFIG_TEST_LIBRARY_IDX7_TASKS_IDX1});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX7_TASKS_IDX2 != "NULL" && CONFIG_TEST_LIBRARY_IDX7_TASKS_IDX2_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_7, TEST_LUT_INDEX_1, ${CONFIG_TEST_LIBRARY_IDX7_TASKS_IDX2});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX7_TASKS_IDX3 != "NULL" && CONFIG_TEST_LIBRARY_IDX7_TASKS_IDX3_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_7, TEST_LUT_INDEX_1, ${CONFIG_TEST_LIBRARY_IDX7_TASKS_IDX3});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX7_TASKS_IDX4 != "NULL" && CONFIG_TEST_LIBRARY_IDX7_TASKS_IDX4_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_7, TEST_LUT_INDEX_1, ${CONFIG_TEST_LIBRARY_IDX7_TASKS_IDX4});
    </#if>
  </#if>
</#if>
<#-- Test index 7 - Library Instance 2 -->
<#if CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX7?has_content>
  <#if CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX7?number gte 3>
    <#if CONFIG_TEST_LIBRARY_IDX7_TASKS_IDX0 != "NULL" && CONFIG_TEST_LIBRARY_IDX7_TASKS_IDX0_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_7, TEST_LUT_INDEX_2, ${CONFIG_TEST_LIBRARY_IDX7_TASKS_IDX0});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX7_TASKS_IDX1 != "NULL" && CONFIG_TEST_LIBRARY_IDX7_TASKS_IDX1_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_7, TEST_LUT_INDEX_2, ${CONFIG_TEST_LIBRARY_IDX7_TASKS_IDX1});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX7_TASKS_IDX2 != "NULL" && CONFIG_TEST_LIBRARY_IDX7_TASKS_IDX2_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_7, TEST_LUT_INDEX_2, ${CONFIG_TEST_LIBRARY_IDX7_TASKS_IDX2});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX7_TASKS_IDX3 != "NULL" && CONFIG_TEST_LIBRARY_IDX7_TASKS_IDX3_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_7, TEST_LUT_INDEX_2, ${CONFIG_TEST_LIBRARY_IDX7_TASKS_IDX3});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX7_TASKS_IDX4 != "NULL" && CONFIG_TEST_LIBRARY_IDX7_TASKS_IDX4_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_7, TEST_LUT_INDEX_2, ${CONFIG_TEST_LIBRARY_IDX7_TASKS_IDX4});
    </#if>
  </#if>
</#if>
<#-- Test index 8 - Library Instance 0 -->
<#if CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX8?has_content>
  <#if CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX8?number gte 1>
    <#if CONFIG_TEST_LIBRARY_IDX8_TASKS_IDX0 != "NULL" && CONFIG_TEST_LIBRARY_IDX8_TASKS_IDX0_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_8, TEST_LUT_INDEX_0, ${CONFIG_TEST_LIBRARY_IDX8_TASKS_IDX0});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX8_TASKS_IDX1 != "NULL" && CONFIG_TEST_LIBRARY_IDX8_TASKS_IDX1_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_8, TEST_LUT_INDEX_0, ${CONFIG_TEST_LIBRARY_IDX8_TASKS_IDX1});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX8_TASKS_IDX2 != "NULL" && CONFIG_TEST_LIBRARY_IDX8_TASKS_IDX2_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_8, TEST_LUT_INDEX_0, ${CONFIG_TEST_LIBRARY_IDX8_TASKS_IDX2});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX8_TASKS_IDX3 != "NULL" && CONFIG_TEST_LIBRARY_IDX8_TASKS_IDX3_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_8, TEST_LUT_INDEX_0, ${CONFIG_TEST_LIBRARY_IDX8_TASKS_IDX3});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX8_TASKS_IDX4 != "NULL" && CONFIG_TEST_LIBRARY_IDX8_TASKS_IDX4_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_8, TEST_LUT_INDEX_0, ${CONFIG_TEST_LIBRARY_IDX8_TASKS_IDX4});
    </#if>
  </#if>
</#if>
<#-- Test index 8 - Library Instance 1 -->
<#if CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX8?has_content>
  <#if CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX8?number gte 2>
    <#if CONFIG_TEST_LIBRARY_IDX8_TASKS_IDX0 != "NULL" && CONFIG_TEST_LIBRARY_IDX8_TASKS_IDX0_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_8, TEST_LUT_INDEX_1, ${CONFIG_TEST_LIBRARY_IDX8_TASKS_IDX0});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX8_TASKS_IDX1 != "NULL" && CONFIG_TEST_LIBRARY_IDX8_TASKS_IDX1_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_8, TEST_LUT_INDEX_1, ${CONFIG_TEST_LIBRARY_IDX8_TASKS_IDX1});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX8_TASKS_IDX2 != "NULL" && CONFIG_TEST_LIBRARY_IDX8_TASKS_IDX2_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_8, TEST_LUT_INDEX_1, ${CONFIG_TEST_LIBRARY_IDX8_TASKS_IDX2});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX8_TASKS_IDX3 != "NULL" && CONFIG_TEST_LIBRARY_IDX8_TASKS_IDX3_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_8, TEST_LUT_INDEX_1, ${CONFIG_TEST_LIBRARY_IDX8_TASKS_IDX3});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX8_TASKS_IDX4 != "NULL" && CONFIG_TEST_LIBRARY_IDX8_TASKS_IDX4_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_8, TEST_LUT_INDEX_1, ${CONFIG_TEST_LIBRARY_IDX8_TASKS_IDX4});
    </#if>
  </#if>
</#if>
<#-- Test index 8 - Library Instance 2 -->
<#if CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX8?has_content>
  <#if CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX8?number gte 3>
    <#if CONFIG_TEST_LIBRARY_IDX8_TASKS_IDX0 != "NULL" && CONFIG_TEST_LIBRARY_IDX8_TASKS_IDX0_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_8, TEST_LUT_INDEX_2, ${CONFIG_TEST_LIBRARY_IDX8_TASKS_IDX0});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX8_TASKS_IDX1 != "NULL" && CONFIG_TEST_LIBRARY_IDX8_TASKS_IDX1_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_8, TEST_LUT_INDEX_2, ${CONFIG_TEST_LIBRARY_IDX8_TASKS_IDX1});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX8_TASKS_IDX2 != "NULL" && CONFIG_TEST_LIBRARY_IDX8_TASKS_IDX2_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_8, TEST_LUT_INDEX_2, ${CONFIG_TEST_LIBRARY_IDX8_TASKS_IDX2});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX8_TASKS_IDX3 != "NULL" && CONFIG_TEST_LIBRARY_IDX8_TASKS_IDX3_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_8, TEST_LUT_INDEX_2, ${CONFIG_TEST_LIBRARY_IDX8_TASKS_IDX3});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX8_TASKS_IDX4 != "NULL" && CONFIG_TEST_LIBRARY_IDX8_TASKS_IDX4_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_8, TEST_LUT_INDEX_2, ${CONFIG_TEST_LIBRARY_IDX8_TASKS_IDX4});
    </#if>
  </#if>
</#if>
<#-- Test index 9 - Library Instance 0 -->
<#if CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX9?has_content>
  <#if CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX9?number gte 1>
    <#if CONFIG_TEST_LIBRARY_IDX9_TASKS_IDX0 != "NULL" && CONFIG_TEST_LIBRARY_IDX9_TASKS_IDX0_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_9, TEST_LUT_INDEX_0, ${CONFIG_TEST_LIBRARY_IDX9_TASKS_IDX0});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX9_TASKS_IDX1 != "NULL" && CONFIG_TEST_LIBRARY_IDX9_TASKS_IDX1_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_9, TEST_LUT_INDEX_0, ${CONFIG_TEST_LIBRARY_IDX9_TASKS_IDX1});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX9_TASKS_IDX2 != "NULL" && CONFIG_TEST_LIBRARY_IDX9_TASKS_IDX2_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_9, TEST_LUT_INDEX_0, ${CONFIG_TEST_LIBRARY_IDX9_TASKS_IDX2});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX9_TASKS_IDX3 != "NULL" && CONFIG_TEST_LIBRARY_IDX9_TASKS_IDX3_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_9, TEST_LUT_INDEX_0, ${CONFIG_TEST_LIBRARY_IDX9_TASKS_IDX3});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX9_TASKS_IDX4 != "NULL" && CONFIG_TEST_LIBRARY_IDX9_TASKS_IDX4_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_9, TEST_LUT_INDEX_0, ${CONFIG_TEST_LIBRARY_IDX9_TASKS_IDX4});
    </#if>
  </#if>
</#if>
<#-- Test index 9 - Library Instance 1 -->
<#if CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX9?has_content>
  <#if CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX9?number gte 2>
    <#if CONFIG_TEST_LIBRARY_IDX9_TASKS_IDX0 != "NULL" && CONFIG_TEST_LIBRARY_IDX9_TASKS_IDX0_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_9, TEST_LUT_INDEX_1, ${CONFIG_TEST_LIBRARY_IDX9_TASKS_IDX0});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX9_TASKS_IDX1 != "NULL" && CONFIG_TEST_LIBRARY_IDX9_TASKS_IDX1_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_9, TEST_LUT_INDEX_1, ${CONFIG_TEST_LIBRARY_IDX9_TASKS_IDX1});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX9_TASKS_IDX2 != "NULL" && CONFIG_TEST_LIBRARY_IDX9_TASKS_IDX2_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_9, TEST_LUT_INDEX_1, ${CONFIG_TEST_LIBRARY_IDX9_TASKS_IDX2});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX9_TASKS_IDX3 != "NULL" && CONFIG_TEST_LIBRARY_IDX9_TASKS_IDX3_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_9, TEST_LUT_INDEX_1, ${CONFIG_TEST_LIBRARY_IDX9_TASKS_IDX3});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX9_TASKS_IDX4 != "NULL" && CONFIG_TEST_LIBRARY_IDX9_TASKS_IDX4_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_9, TEST_LUT_INDEX_1, ${CONFIG_TEST_LIBRARY_IDX9_TASKS_IDX4});
    </#if>
  </#if>
</#if>
<#-- Test index 9 - Library Instance 2 -->
<#if CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX9?has_content>
  <#if CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX9?number gte 3>
    <#if CONFIG_TEST_LIBRARY_IDX9_TASKS_IDX0 != "NULL" && CONFIG_TEST_LIBRARY_IDX9_TASKS_IDX0_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_9, TEST_LUT_INDEX_2, ${CONFIG_TEST_LIBRARY_IDX9_TASKS_IDX0});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX9_TASKS_IDX1 != "NULL" && CONFIG_TEST_LIBRARY_IDX9_TASKS_IDX1_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_9, TEST_LUT_INDEX_2, ${CONFIG_TEST_LIBRARY_IDX9_TASKS_IDX1});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX9_TASKS_IDX2 != "NULL" && CONFIG_TEST_LIBRARY_IDX9_TASKS_IDX2_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_9, TEST_LUT_INDEX_2, ${CONFIG_TEST_LIBRARY_IDX9_TASKS_IDX2});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX9_TASKS_IDX3 != "NULL" && CONFIG_TEST_LIBRARY_IDX9_TASKS_IDX3_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_9, TEST_LUT_INDEX_2, ${CONFIG_TEST_LIBRARY_IDX9_TASKS_IDX3});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX9_TASKS_IDX4 != "NULL" && CONFIG_TEST_LIBRARY_IDX9_TASKS_IDX4_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_9, TEST_LUT_INDEX_2, ${CONFIG_TEST_LIBRARY_IDX9_TASKS_IDX4});
    </#if>
  </#if>
</#if>
<#-- Test index 10 - Library Instance 0 -->
<#if CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX10?has_content>
  <#if CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX10?number gte 1>
    <#if CONFIG_TEST_LIBRARY_IDX10_TASKS_IDX0 != "NULL" && CONFIG_TEST_LIBRARY_IDX10_TASKS_IDX0_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_10, TEST_LUT_INDEX_0, ${CONFIG_TEST_LIBRARY_IDX10_TASKS_IDX0});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX10_TASKS_IDX1 != "NULL" && CONFIG_TEST_LIBRARY_IDX10_TASKS_IDX1_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_10, TEST_LUT_INDEX_0, ${CONFIG_TEST_LIBRARY_IDX10_TASKS_IDX1});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX10_TASKS_IDX2 != "NULL" && CONFIG_TEST_LIBRARY_IDX10_TASKS_IDX2_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_10, TEST_LUT_INDEX_0, ${CONFIG_TEST_LIBRARY_IDX10_TASKS_IDX2});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX10_TASKS_IDX3 != "NULL" && CONFIG_TEST_LIBRARY_IDX10_TASKS_IDX3_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_10, TEST_LUT_INDEX_0, ${CONFIG_TEST_LIBRARY_IDX10_TASKS_IDX3});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX10_TASKS_IDX4 != "NULL" && CONFIG_TEST_LIBRARY_IDX10_TASKS_IDX4_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_10, TEST_LUT_INDEX_0, ${CONFIG_TEST_LIBRARY_IDX10_TASKS_IDX4});
    </#if>
  </#if>
</#if>
<#-- Test index 10 - Library Instance 1 -->
<#if CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX10?has_content>
  <#if CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX10?number gte 2>
    <#if CONFIG_TEST_LIBRARY_IDX10_TASKS_IDX0 != "NULL" && CONFIG_TEST_LIBRARY_IDX10_TASKS_IDX0_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_10, TEST_LUT_INDEX_1, ${CONFIG_TEST_LIBRARY_IDX10_TASKS_IDX0});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX10_TASKS_IDX1 != "NULL" && CONFIG_TEST_LIBRARY_IDX10_TASKS_IDX1_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_10, TEST_LUT_INDEX_1, ${CONFIG_TEST_LIBRARY_IDX10_TASKS_IDX1});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX10_TASKS_IDX2 != "NULL" && CONFIG_TEST_LIBRARY_IDX10_TASKS_IDX2_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_10, TEST_LUT_INDEX_1, ${CONFIG_TEST_LIBRARY_IDX10_TASKS_IDX2});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX10_TASKS_IDX3 != "NULL" && CONFIG_TEST_LIBRARY_IDX10_TASKS_IDX3_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_10, TEST_LUT_INDEX_1, ${CONFIG_TEST_LIBRARY_IDX10_TASKS_IDX3});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX10_TASKS_IDX4 != "NULL" && CONFIG_TEST_LIBRARY_IDX10_TASKS_IDX4_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_10, TEST_LUT_INDEX_1, ${CONFIG_TEST_LIBRARY_IDX10_TASKS_IDX4});
    </#if>
  </#if>
</#if>
<#-- Test index 10 - Library Instance 2 -->
<#if CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX10?has_content>
  <#if CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX10?number gte 3>
    <#if CONFIG_TEST_LIBRARY_IDX10_TASKS_IDX0 != "NULL" && CONFIG_TEST_LIBRARY_IDX10_TASKS_IDX0_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_10, TEST_LUT_INDEX_2, ${CONFIG_TEST_LIBRARY_IDX10_TASKS_IDX0});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX10_TASKS_IDX1 != "NULL" && CONFIG_TEST_LIBRARY_IDX10_TASKS_IDX1_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_10, TEST_LUT_INDEX_2, ${CONFIG_TEST_LIBRARY_IDX10_TASKS_IDX1});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX10_TASKS_IDX2 != "NULL" && CONFIG_TEST_LIBRARY_IDX10_TASKS_IDX2_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_10, TEST_LUT_INDEX_2, ${CONFIG_TEST_LIBRARY_IDX10_TASKS_IDX2});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX10_TASKS_IDX3 != "NULL" && CONFIG_TEST_LIBRARY_IDX10_TASKS_IDX3_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_10, TEST_LUT_INDEX_2, ${CONFIG_TEST_LIBRARY_IDX10_TASKS_IDX3});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX10_TASKS_IDX4 != "NULL" && CONFIG_TEST_LIBRARY_IDX10_TASKS_IDX4_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_10, TEST_LUT_INDEX_2, ${CONFIG_TEST_LIBRARY_IDX10_TASKS_IDX4});
    </#if>
  </#if>
</#if>
<#-- Test index 11 - Library Instance 0 -->
<#if CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX11?has_content>
  <#if CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX11?number gte 1>
    <#if CONFIG_TEST_LIBRARY_IDX11_TASKS_IDX0 != "NULL" && CONFIG_TEST_LIBRARY_IDX11_TASKS_IDX0_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_11, TEST_LUT_INDEX_0, ${CONFIG_TEST_LIBRARY_IDX11_TASKS_IDX0});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX11_TASKS_IDX1 != "NULL" && CONFIG_TEST_LIBRARY_IDX11_TASKS_IDX1_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_11, TEST_LUT_INDEX_0, ${CONFIG_TEST_LIBRARY_IDX11_TASKS_IDX1});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX11_TASKS_IDX2 != "NULL" && CONFIG_TEST_LIBRARY_IDX11_TASKS_IDX2_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_11, TEST_LUT_INDEX_0, ${CONFIG_TEST_LIBRARY_IDX11_TASKS_IDX2});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX11_TASKS_IDX3 != "NULL" && CONFIG_TEST_LIBRARY_IDX11_TASKS_IDX3_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_11, TEST_LUT_INDEX_0, ${CONFIG_TEST_LIBRARY_IDX11_TASKS_IDX3});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX11_TASKS_IDX4 != "NULL" && CONFIG_TEST_LIBRARY_IDX11_TASKS_IDX4_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_11, TEST_LUT_INDEX_0, ${CONFIG_TEST_LIBRARY_IDX11_TASKS_IDX4});
    </#if>
  </#if>
</#if>
<#-- Test index 11 - Library Instance 1 -->
<#if CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX11?has_content>
  <#if CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX11?number gte 2>
    <#if CONFIG_TEST_LIBRARY_IDX11_TASKS_IDX0 != "NULL" && CONFIG_TEST_LIBRARY_IDX11_TASKS_IDX0_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_11, TEST_LUT_INDEX_1, ${CONFIG_TEST_LIBRARY_IDX11_TASKS_IDX0});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX11_TASKS_IDX1 != "NULL" && CONFIG_TEST_LIBRARY_IDX11_TASKS_IDX1_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_11, TEST_LUT_INDEX_1, ${CONFIG_TEST_LIBRARY_IDX11_TASKS_IDX1});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX11_TASKS_IDX2 != "NULL" && CONFIG_TEST_LIBRARY_IDX11_TASKS_IDX2_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_11, TEST_LUT_INDEX_1, ${CONFIG_TEST_LIBRARY_IDX11_TASKS_IDX2});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX11_TASKS_IDX3 != "NULL" && CONFIG_TEST_LIBRARY_IDX11_TASKS_IDX3_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_11, TEST_LUT_INDEX_1, ${CONFIG_TEST_LIBRARY_IDX11_TASKS_IDX3});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX11_TASKS_IDX4 != "NULL" && CONFIG_TEST_LIBRARY_IDX11_TASKS_IDX4_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_11, TEST_LUT_INDEX_1, ${CONFIG_TEST_LIBRARY_IDX11_TASKS_IDX4});
    </#if>
  </#if>
</#if>
<#-- Test index 11 - Library Instance 2 -->
<#if CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX11?has_content>
  <#if CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX11?number gte 3>
    <#if CONFIG_TEST_LIBRARY_IDX11_TASKS_IDX0 != "NULL" && CONFIG_TEST_LIBRARY_IDX11_TASKS_IDX0_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_11, TEST_LUT_INDEX_2, ${CONFIG_TEST_LIBRARY_IDX11_TASKS_IDX0});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX11_TASKS_IDX1 != "NULL" && CONFIG_TEST_LIBRARY_IDX11_TASKS_IDX1_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_11, TEST_LUT_INDEX_2, ${CONFIG_TEST_LIBRARY_IDX11_TASKS_IDX1});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX11_TASKS_IDX2 != "NULL" && CONFIG_TEST_LIBRARY_IDX11_TASKS_IDX2_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_11, TEST_LUT_INDEX_2, ${CONFIG_TEST_LIBRARY_IDX11_TASKS_IDX2});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX11_TASKS_IDX3 != "NULL" && CONFIG_TEST_LIBRARY_IDX11_TASKS_IDX3_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_11, TEST_LUT_INDEX_2, ${CONFIG_TEST_LIBRARY_IDX11_TASKS_IDX3});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX11_TASKS_IDX4 != "NULL" && CONFIG_TEST_LIBRARY_IDX11_TASKS_IDX4_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_11, TEST_LUT_INDEX_2, ${CONFIG_TEST_LIBRARY_IDX11_TASKS_IDX4});
    </#if>
  </#if>
</#if>
<#-- Test index 12 - Library Instance 0 -->
<#if CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX12?has_content>
  <#if CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX12?number gte 1>
    <#if CONFIG_TEST_LIBRARY_IDX12_TASKS_IDX0 != "NULL" && CONFIG_TEST_LIBRARY_IDX12_TASKS_IDX0_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_12, TEST_LUT_INDEX_0, ${CONFIG_TEST_LIBRARY_IDX12_TASKS_IDX0});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX12_TASKS_IDX1 != "NULL" && CONFIG_TEST_LIBRARY_IDX12_TASKS_IDX1_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_12, TEST_LUT_INDEX_0, ${CONFIG_TEST_LIBRARY_IDX12_TASKS_IDX1});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX12_TASKS_IDX2 != "NULL" && CONFIG_TEST_LIBRARY_IDX12_TASKS_IDX2_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_12, TEST_LUT_INDEX_0, ${CONFIG_TEST_LIBRARY_IDX12_TASKS_IDX2});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX12_TASKS_IDX3 != "NULL" && CONFIG_TEST_LIBRARY_IDX12_TASKS_IDX3_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_12, TEST_LUT_INDEX_0, ${CONFIG_TEST_LIBRARY_IDX12_TASKS_IDX3});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX12_TASKS_IDX4 != "NULL" && CONFIG_TEST_LIBRARY_IDX12_TASKS_IDX4_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_12, TEST_LUT_INDEX_0, ${CONFIG_TEST_LIBRARY_IDX12_TASKS_IDX4});
    </#if>
  </#if>
</#if>
<#-- Test index 12 - Library Instance 1 -->
<#if CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX12?has_content>
  <#if CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX12?number gte 2>
    <#if CONFIG_TEST_LIBRARY_IDX12_TASKS_IDX0 != "NULL" && CONFIG_TEST_LIBRARY_IDX12_TASKS_IDX0_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_12, TEST_LUT_INDEX_1, ${CONFIG_TEST_LIBRARY_IDX12_TASKS_IDX0});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX12_TASKS_IDX1 != "NULL" && CONFIG_TEST_LIBRARY_IDX12_TASKS_IDX1_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_12, TEST_LUT_INDEX_1, ${CONFIG_TEST_LIBRARY_IDX12_TASKS_IDX1});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX12_TASKS_IDX2 != "NULL" && CONFIG_TEST_LIBRARY_IDX12_TASKS_IDX2_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_12, TEST_LUT_INDEX_1, ${CONFIG_TEST_LIBRARY_IDX12_TASKS_IDX2});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX12_TASKS_IDX3 != "NULL" && CONFIG_TEST_LIBRARY_IDX12_TASKS_IDX3_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_12, TEST_LUT_INDEX_1, ${CONFIG_TEST_LIBRARY_IDX12_TASKS_IDX3});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX12_TASKS_IDX4 != "NULL" && CONFIG_TEST_LIBRARY_IDX12_TASKS_IDX4_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_12, TEST_LUT_INDEX_1, ${CONFIG_TEST_LIBRARY_IDX12_TASKS_IDX4});
    </#if>
  </#if>
</#if>
<#-- Test index 12 - Library Instance 2 -->
<#if CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX12?has_content>
  <#if CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX12?number gte 3>
    <#if CONFIG_TEST_LIBRARY_IDX12_TASKS_IDX0 != "NULL" && CONFIG_TEST_LIBRARY_IDX12_TASKS_IDX0_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_12, TEST_LUT_INDEX_2, ${CONFIG_TEST_LIBRARY_IDX12_TASKS_IDX0});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX12_TASKS_IDX1 != "NULL" && CONFIG_TEST_LIBRARY_IDX12_TASKS_IDX1_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_12, TEST_LUT_INDEX_2, ${CONFIG_TEST_LIBRARY_IDX12_TASKS_IDX1});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX12_TASKS_IDX2 != "NULL" && CONFIG_TEST_LIBRARY_IDX12_TASKS_IDX2_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_12, TEST_LUT_INDEX_2, ${CONFIG_TEST_LIBRARY_IDX12_TASKS_IDX2});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX12_TASKS_IDX3 != "NULL" && CONFIG_TEST_LIBRARY_IDX12_TASKS_IDX3_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_12, TEST_LUT_INDEX_2, ${CONFIG_TEST_LIBRARY_IDX12_TASKS_IDX3});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX12_TASKS_IDX4 != "NULL" && CONFIG_TEST_LIBRARY_IDX12_TASKS_IDX4_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_12, TEST_LUT_INDEX_2, ${CONFIG_TEST_LIBRARY_IDX12_TASKS_IDX4});
    </#if>
  </#if>
</#if>
<#-- Test index 13 - Library Instance 0 -->
<#if CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX13?has_content>
  <#if CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX13?number gte 1>
    <#if CONFIG_TEST_LIBRARY_IDX3_TASKS_IDX0 != "NULL" && CONFIG_TEST_LIBRARY_IDX13_TASKS_IDX0_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_13, TEST_LUT_INDEX_0, ${CONFIG_TEST_LIBRARY_IDX13_TASKS_IDX0});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX3_TASKS_IDX1 != "NULL" && CONFIG_TEST_LIBRARY_IDX13_TASKS_IDX1_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_13, TEST_LUT_INDEX_0, ${CONFIG_TEST_LIBRARY_IDX13_TASKS_IDX1});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX3_TASKS_IDX2 != "NULL" && CONFIG_TEST_LIBRARY_IDX13_TASKS_IDX2_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_13, TEST_LUT_INDEX_0, ${CONFIG_TEST_LIBRARY_IDX13_TASKS_IDX2});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX3_TASKS_IDX3 != "NULL" && CONFIG_TEST_LIBRARY_IDX13_TASKS_IDX3_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_13, TEST_LUT_INDEX_0, ${CONFIG_TEST_LIBRARY_IDX13_TASKS_IDX3});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX3_TASKS_IDX4 != "NULL" && CONFIG_TEST_LIBRARY_IDX13_TASKS_IDX4_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_13, TEST_LUT_INDEX_0, ${CONFIG_TEST_LIBRARY_IDX13_TASKS_IDX4});
    </#if>
  </#if>
</#if>
<#-- Test index 13 - Library Instance 1 -->
<#if CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX13?has_content>
  <#if CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX13?number gte 2>
    <#if CONFIG_TEST_LIBRARY_IDX13_TASKS_IDX0 != "NULL" && CONFIG_TEST_LIBRARY_IDX13_TASKS_IDX0_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_13, TEST_LUT_INDEX_1, ${CONFIG_TEST_LIBRARY_IDX13_TASKS_IDX0});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX13_TASKS_IDX1 != "NULL" && CONFIG_TEST_LIBRARY_IDX13_TASKS_IDX1_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_13, TEST_LUT_INDEX_1, ${CONFIG_TEST_LIBRARY_IDX13_TASKS_IDX1});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX13_TASKS_IDX2 != "NULL" && CONFIG_TEST_LIBRARY_IDX13_TASKS_IDX2_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_13, TEST_LUT_INDEX_1, ${CONFIG_TEST_LIBRARY_IDX13_TASKS_IDX2});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX13_TASKS_IDX3 != "NULL" && CONFIG_TEST_LIBRARY_IDX13_TASKS_IDX3_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_13, TEST_LUT_INDEX_1, ${CONFIG_TEST_LIBRARY_IDX13_TASKS_IDX3});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX13_TASKS_IDX4 != "NULL" && CONFIG_TEST_LIBRARY_IDX13_TASKS_IDX4_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_13, TEST_LUT_INDEX_1, ${CONFIG_TEST_LIBRARY_IDX13_TASKS_IDX4});
    </#if>
  </#if>
</#if>
<#-- Test index 13 - Library Instance 2 -->
<#if CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX13?has_content>
  <#if CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX13?number gte 3>
    <#if CONFIG_TEST_LIBRARY_IDX13_TASKS_IDX0 != "NULL" && CONFIG_TEST_LIBRARY_IDX13_TASKS_IDX0_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_13, TEST_LUT_INDEX_2, ${CONFIG_TEST_LIBRARY_IDX13_TASKS_IDX0});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX13_TASKS_IDX1 != "NULL" && CONFIG_TEST_LIBRARY_IDX13_TASKS_IDX1_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_13, TEST_LUT_INDEX_2, ${CONFIG_TEST_LIBRARY_IDX13_TASKS_IDX1});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX13_TASKS_IDX2 != "NULL" && CONFIG_TEST_LIBRARY_IDX13_TASKS_IDX2_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_13, TEST_LUT_INDEX_2, ${CONFIG_TEST_LIBRARY_IDX13_TASKS_IDX2});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX13_TASKS_IDX3 != "NULL" && CONFIG_TEST_LIBRARY_IDX13_TASKS_IDX3_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_13, TEST_LUT_INDEX_2, ${CONFIG_TEST_LIBRARY_IDX13_TASKS_IDX3});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX13_TASKS_IDX4 != "NULL" && CONFIG_TEST_LIBRARY_IDX13_TASKS_IDX4_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_13, TEST_LUT_INDEX_2, ${CONFIG_TEST_LIBRARY_IDX13_TASKS_IDX4});
    </#if>
  </#if>
</#if>
<#-- Test index 14 - Library Instance 0 -->
<#if CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX14?has_content>
  <#if CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX14?number gte 1>
    <#if CONFIG_TEST_LIBRARY_IDX14_TASKS_IDX0 != "NULL" && CONFIG_TEST_LIBRARY_IDX14_TASKS_IDX0_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_14, TEST_LUT_INDEX_0, ${CONFIG_TEST_LIBRARY_IDX14_TASKS_IDX0});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX14_TASKS_IDX1 != "NULL" && CONFIG_TEST_LIBRARY_IDX14_TASKS_IDX1_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_14, TEST_LUT_INDEX_0, ${CONFIG_TEST_LIBRARY_IDX14_TASKS_IDX1});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX14_TASKS_IDX2 != "NULL" && CONFIG_TEST_LIBRARY_IDX14_TASKS_IDX2_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_14, TEST_LUT_INDEX_0, ${CONFIG_TEST_LIBRARY_IDX14_TASKS_IDX2});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX14_TASKS_IDX3 != "NULL" && CONFIG_TEST_LIBRARY_IDX14_TASKS_IDX3_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_14, TEST_LUT_INDEX_0, ${CONFIG_TEST_LIBRARY_IDX14_TASKS_IDX3});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX14_TASKS_IDX4 != "NULL" && CONFIG_TEST_LIBRARY_IDX14_TASKS_IDX4_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_14, TEST_LUT_INDEX_0, ${CONFIG_TEST_LIBRARY_IDX14_TASKS_IDX4});
    </#if>
  </#if>
</#if>
<#-- Test index 14 - Library Instance 1 -->
<#if CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX14?has_content>
  <#if CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX14?number gte 2>
    <#if CONFIG_TEST_LIBRARY_IDX14_TASKS_IDX0 != "NULL" && CONFIG_TEST_LIBRARY_IDX14_TASKS_IDX0_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_14, TEST_LUT_INDEX_1, ${CONFIG_TEST_LIBRARY_IDX14_TASKS_IDX0});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX14_TASKS_IDX1 != "NULL" && CONFIG_TEST_LIBRARY_IDX14_TASKS_IDX1_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_14, TEST_LUT_INDEX_1, ${CONFIG_TEST_LIBRARY_IDX14_TASKS_IDX1});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX14_TASKS_IDX2 != "NULL" && CONFIG_TEST_LIBRARY_IDX14_TASKS_IDX2_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_14, TEST_LUT_INDEX_1, ${CONFIG_TEST_LIBRARY_IDX14_TASKS_IDX2});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX14_TASKS_IDX3 != "NULL" && CONFIG_TEST_LIBRARY_IDX14_TASKS_IDX3_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_14, TEST_LUT_INDEX_1, ${CONFIG_TEST_LIBRARY_IDX14_TASKS_IDX3});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX14_TASKS_IDX4 != "NULL" && CONFIG_TEST_LIBRARY_IDX14_TASKS_IDX4_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_14, TEST_LUT_INDEX_1, ${CONFIG_TEST_LIBRARY_IDX14_TASKS_IDX4});
    </#if>
  </#if>
</#if>
<#-- Test index 14 - Library Instance 2 -->
<#if CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX14?has_content>
  <#if CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX14?number gte 3>
    <#if CONFIG_TEST_LIBRARY_IDX14_TASKS_IDX0 != "NULL" && CONFIG_TEST_LIBRARY_IDX14_TASKS_IDX0_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_14, TEST_LUT_INDEX_2, ${CONFIG_TEST_LIBRARY_IDX14_TASKS_IDX0});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX14_TASKS_IDX1 != "NULL" && CONFIG_TEST_LIBRARY_IDX14_TASKS_IDX1_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_14, TEST_LUT_INDEX_2, ${CONFIG_TEST_LIBRARY_IDX14_TASKS_IDX1});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX14_TASKS_IDX2 != "NULL" && CONFIG_TEST_LIBRARY_IDX14_TASKS_IDX2_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_14, TEST_LUT_INDEX_2, ${CONFIG_TEST_LIBRARY_IDX14_TASKS_IDX2});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX14_TASKS_IDX3 != "NULL" && CONFIG_TEST_LIBRARY_IDX14_TASKS_IDX3_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_14, TEST_LUT_INDEX_2, ${CONFIG_TEST_LIBRARY_IDX14_TASKS_IDX3});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX14_TASKS_IDX4 != "NULL" && CONFIG_TEST_LIBRARY_IDX14_TASKS_IDX4_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_14, TEST_LUT_INDEX_2, ${CONFIG_TEST_LIBRARY_IDX14_TASKS_IDX4});
    </#if>
  </#if>
</#if>
<#-- Test index 15 - Library Instance 0 -->
<#if CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX15?has_content>
  <#if CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX15?number gte 1>
    <#if CONFIG_TEST_LIBRARY_IDX15_TASKS_IDX0 != "NULL" && CONFIG_TEST_LIBRARY_IDX15_TASKS_IDX0_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_15, TEST_LUT_INDEX_0, ${CONFIG_TEST_LIBRARY_IDX15_TASKS_IDX0});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX15_TASKS_IDX1 != "NULL" && CONFIG_TEST_LIBRARY_IDX15_TASKS_IDX1_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_15, TEST_LUT_INDEX_0, ${CONFIG_TEST_LIBRARY_IDX15_TASKS_IDX1});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX15_TASKS_IDX2 != "NULL" && CONFIG_TEST_LIBRARY_IDX15_TASKS_IDX2_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_15, TEST_LUT_INDEX_0, ${CONFIG_TEST_LIBRARY_IDX15_TASKS_IDX2});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX15_TASKS_IDX3 != "NULL" && CONFIG_TEST_LIBRARY_IDX15_TASKS_IDX3_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_15, TEST_LUT_INDEX_0, ${CONFIG_TEST_LIBRARY_IDX15_TASKS_IDX3});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX15_TASKS_IDX4 != "NULL" && CONFIG_TEST_LIBRARY_IDX15_TASKS_IDX4_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_15, TEST_LUT_INDEX_0, ${CONFIG_TEST_LIBRARY_IDX15_TASKS_IDX4});
    </#if>
  </#if>
</#if>
<#-- Test index 15 - Library Instance 1 -->
<#if CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX15?has_content>
  <#if CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX15?number gte 2>
    <#if CONFIG_TEST_LIBRARY_IDX15_TASKS_IDX0 != "NULL" && CONFIG_TEST_LIBRARY_IDX15_TASKS_IDX0_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_15, TEST_LUT_INDEX_1, ${CONFIG_TEST_LIBRARY_IDX15_TASKS_IDX0});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX15_TASKS_IDX1 != "NULL" && CONFIG_TEST_LIBRARY_IDX15_TASKS_IDX1_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_15, TEST_LUT_INDEX_1, ${CONFIG_TEST_LIBRARY_IDX15_TASKS_IDX1});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX15_TASKS_IDX2 != "NULL" && CONFIG_TEST_LIBRARY_IDX15_TASKS_IDX2_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_15, TEST_LUT_INDEX_1, ${CONFIG_TEST_LIBRARY_IDX15_TASKS_IDX2});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX15_TASKS_IDX3 != "NULL" && CONFIG_TEST_LIBRARY_IDX15_TASKS_IDX3_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_15, TEST_LUT_INDEX_1, ${CONFIG_TEST_LIBRARY_IDX15_TASKS_IDX3});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX15_TASKS_IDX4 != "NULL" && CONFIG_TEST_LIBRARY_IDX15_TASKS_IDX4_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_15, TEST_LUT_INDEX_1, ${CONFIG_TEST_LIBRARY_IDX15_TASKS_IDX4});
    </#if>
  </#if>
</#if>
<#-- Test index 15 - Library Instance 2 -->
<#if CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX15?has_content>
  <#if CONFIG_TEST_LIBRARY_NUMBER_OF_INSTANCES_IDX15?number gte 3>
    <#if CONFIG_TEST_LIBRARY_IDX15_TASKS_IDX0 != "NULL" && CONFIG_TEST_LIBRARY_IDX15_TASKS_IDX0_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_15, TEST_LUT_INDEX_2, ${CONFIG_TEST_LIBRARY_IDX15_TASKS_IDX0});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX15_TASKS_IDX1 != "NULL" && CONFIG_TEST_LIBRARY_IDX15_TASKS_IDX1_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_15, TEST_LUT_INDEX_2, ${CONFIG_TEST_LIBRARY_IDX15_TASKS_IDX1});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX15_TASKS_IDX2 != "NULL" && CONFIG_TEST_LIBRARY_IDX15_TASKS_IDX2_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_15, TEST_LUT_INDEX_2, ${CONFIG_TEST_LIBRARY_IDX15_TASKS_IDX2});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX15_TASKS_IDX3 != "NULL" && CONFIG_TEST_LIBRARY_IDX15_TASKS_IDX3_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_15, TEST_LUT_INDEX_2, ${CONFIG_TEST_LIBRARY_IDX15_TASKS_IDX3});
    </#if>
    <#if CONFIG_TEST_LIBRARY_IDX15_TASKS_IDX4 != "NULL" && CONFIG_TEST_LIBRARY_IDX15_TASKS_IDX4_INTERRUPT != true>
    TEST_LibraryTasksPolled(TEST_POS_15, TEST_LUT_INDEX_2, ${CONFIG_TEST_LIBRARY_IDX15_TASKS_IDX4});
    </#if>
  </#if>
</#if>
