#
# A Perl script that converts a CSR patch files into C code.
#
# Input: CSR patch file from stdin
# Output: array of canned HCI command
#

use strict;

print <<EOF;
//-------------------------------------------------------------------
// DO NOT MODIFY THIS FILE!
// This file was machine generated by the make_dsp_patch_script.pl script
//-------------------------------------------------------------------

#ifndef __BTX_CSR_DSP_PATCH_SCRIPT_INCLUDED__
#define __BTX_CSR_DSP_PATCH_SCRIPT_INCLUDED__

EOF

my $packetNo = 0;
while (<>) {
	chomp;
	if (/^dcr/) {
		my @tokens = split(' ');
		# skip "dcr ok"
		shift(@tokens); shift(@tokens);
		$packetNo++;
		print "static const bt_byte packet", $packetNo, "[] = {\n";
		print "    DCRH(", $tokens[0], ', ', $#tokens, ", $packetNo), \n";
		shift(@tokens);
		print "    ", map("W($_), ", @tokens), "\n\n";
		print "};\n\n";
	} elsif (/^\/\//) { # a comment line that starts with //
		print $_, "\n";
	}
}
my $numPackets = $packetNo;

print "static const bt_byte* const packets[] = {\n";
for (my $i = 1; $i <= $numPackets; $i++)
{
	if ($i == $numPackets) {
		print "    packet$i\n";
	} else {
		print "    packet$i,\n";
	}
}
print "};\n\n";

print "#define PACKET_COUNT $numPackets\n";


print <<EOF;

#endif // __BTX_CSR_DSP_PATCH_SCRIPT_INCLUDED__

//-------------------------------------------------------------------
// END OF GENERATED FILE
//-------------------------------------------------------------------
EOF
