#include <xc.h>

#include "app1.h"

/*
*********************************************************************************************************
*                                           GLOBALS
*********************************************************************************************************
*/
extern APP1_DATA appData;

/*
*********************************************************************************************************
*                                          ApplicationUSBDeviceHIDEventHandler
*
* Description : This event handler will handle all device layer events. Event callback generated by USB 
*               device layer.
* Arguments   : 
*********************************************************************************************************
*/
USB_DEVICE_HID_EVENT_RESPONSE ApplicationUSBDeviceHIDEventHandler(
    USB_DEVICE_HID_INDEX hidInstance,
    USB_DEVICE_HID_EVENT event,
    void * eventData,
    uintptr_t userData)
{
   APP1_DATA * pUserAppData = (APP1_DATA *)userData;

   switch(event)
   {
      case USB_DEVICE_HID_EVENT_REPORT_SENT:
         /* This means the mouse report was sent.
         We are free to send another report */
         pUserAppData->isReportSentComplete = true;
         break;
      case USB_DEVICE_HID_EVENT_REPORT_RECEIVED:
         /* This means we have received a report */
         pUserAppData->isReportReceived = true;
         break;
      case USB_DEVICE_HID_EVENT_SET_IDLE:
         /* For now just accept this as is */
         USB_DEVICE_ControlStatus(pUserAppData->deviceHandle, USB_DEVICE_CONTROL_STATUS_OK);

         pUserAppData->idleRate = ((USB_DEVICE_HID_EVENT_DATA_SET_IDLE*)eventData)->duration;
         break;
      case USB_DEVICE_HID_EVENT_GET_IDLE:
      
         /* Host is requesting for Idle rate. Now send the Idle rate */
         USB_DEVICE_ControlSend(pUserAppData->deviceHandle, &(pUserAppData->idleRate),1);
         
         /* On successfully reciveing Idle rate, the Host would acknowledge back with a
            Zero Length packet. The HID function drvier returns an event
            USB_DEVICE_HID_EVENT_CONTROL_TRANSFER_DATA_SENT to the application upon
            receiving this Zero Length packet from Host.
            USB_DEVICE_HID_EVENT_CONTROL_TRANSFER_DATA_SENT event indicates this control transfer
            event is complete */ 
         
         break;
      
      case USB_DEVICE_HID_EVENT_SET_PROTOCOL:
         /* Host is trying set protocol. Now receive the protocol and save */
         pUserAppData->activeProtocol = ((USB_DEVICE_HID_EVENT_DATA_SET_PROTOCOL *)eventData)->protocolCode;;
         
           /* Acknowledge the Control Write Transfer */
         USB_DEVICE_ControlStatus(pUserAppData->deviceHandle, USB_DEVICE_CONTROL_STATUS_OK);
         break;
      
      case  USB_DEVICE_HID_EVENT_GET_PROTOCOL:
         
         /* Host is requesting for Current Protocol. Now send the Idle rate */
         USB_DEVICE_ControlSend(pUserAppData->deviceHandle, &(pUserAppData->activeProtocol), 1);
         
         /* On successfully reciveing Idle rate, the Host would acknowledge
           back with a Zero Length packet. The HID function drvier returns
           an event USB_DEVICE_HID_EVENT_CONTROL_TRANSFER_DATA_SENT to the
           application upon receiving this Zero Length packet from Host.
           USB_DEVICE_HID_EVENT_CONTROL_TRANSFER_DATA_SENT event indicates
           this control transfer event is complete */
         break;
      
      case USB_DEVICE_HID_EVENT_CONTROL_TRANSFER_DATA_SENT:
         break;
      
      default:
         break;
   }

   return USB_DEVICE_HID_EVENT_RESPONSE_NONE;
}

/*
*********************************************************************************************************
*                                          ApplicationUSBDeviceEventHandler
*
* Description : This event handler will handle all device layer events. Event callback generated by USB 
*               device layer.
* Arguments   : 
*********************************************************************************************************
*/
void ApplicationUSBDeviceEventHandler(USB_DEVICE_EVENT event, void * eventData, uintptr_t context)
{
   USB_DEVICE_EVENT_DATA_CONFIGURED *configurationValue;
   switch(event)
   {
      case USB_DEVICE_EVENT_SOF:
         /* This event is used for switch debounce. This flag is reset
          * by the switch process routine. */
         appData.sofEventHasOccurred = true;
         break;      
      case USB_DEVICE_EVENT_RESET:
      case USB_DEVICE_EVENT_DECONFIGURED:
   
         /* Device got deconfigured */
         appData.isConfigured = false;
         appData.state = APP_STATE_WAIT_FOR_CONFIGURATION;         
         BSP_LEDOn (  BSP_LED_2);
         BSP_LEDOn(  BSP_LED_3);
         break;
      case USB_DEVICE_EVENT_CONFIGURED:
         /* Device is configured */
         configurationValue = (USB_DEVICE_EVENT_DATA_CONFIGURED *)eventData;
         if(configurationValue->configurationValue == 1)
         {
            appData.isConfigured = true;
   
            BSP_LEDOn (  BSP_LED_2);
            BSP_LEDOn (  BSP_LED_3 );
   
            /* Register the Application HID Event Handler. */
            USB_DEVICE_HID_EventHandlerSet(appData.hidInstance,
               ApplicationUSBDeviceHIDEventHandler, 
               (uintptr_t)&appData);
         }
         break;
      case USB_DEVICE_EVENT_SUSPENDED:
         BSP_LEDOn (  BSP_LED_2 );
         BSP_LEDOn (  BSP_LED_3 );
         break;
      case USB_DEVICE_EVENT_RESUMED:
      case USB_DEVICE_EVENT_POWER_DETECTED:
         /* Attach the device */
         USB_DEVICE_Attach (appData.deviceHandle);
         break;
      case USB_DEVICE_EVENT_POWER_REMOVED:
         /* There is no VBUS. We can detach the device */
         USB_DEVICE_Detach(appData.deviceHandle);
         break;
      case USB_DEVICE_EVENT_ERROR:         
      default:
         break;
   
   }
}

