<#--
/*******************************************************************************
  ADC Driver Interrupt Handler Template File

  File Name:
    drv_adc_int.c

  Summary:
    This file contains source code necessary to initialize the system.

  Description:
    This file contains source code necessary to initialize the system.  It
    implements the "SYS_Initialize" function, configuration bits, and allocates
    any necessary global system resources, such as the systemObjects structure
    that contains the object handles to all the MPLAB Harmony module objects in
    the system.
 *******************************************************************************/

/*******************************************************************************
Copyright (c) 2013-2014 released Microchip Technology Inc.  All rights reserved.

Microchip licenses to you the right to use, modify, copy and distribute
Software only when embedded on a Microchip microcontroller or digital signal
controller that is integrated into your product or third party product
(pursuant to the sublicense terms in the accompanying license agreement).

You should refer to the license agreement accompanying this Software for
additional information regarding your rights and obligations.

SOFTWARE AND DOCUMENTATION ARE PROVIDED AS IS WITHOUT WARRANTY OF ANY KIND,
EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION, ANY WARRANTY OF
MERCHANTABILITY, TITLE, NON-INFRINGEMENT AND FITNESS FOR A PARTICULAR PURPOSE.
IN NO EVENT SHALL MICROCHIP OR ITS LICENSORS BE LIABLE OR OBLIGATED UNDER
CONTRACT, NEGLIGENCE, STRICT LIABILITY, CONTRIBUTION, BREACH OF WARRANTY, OR
OTHER LEGAL EQUITABLE THEORY ANY DIRECT OR INDIRECT DAMAGES OR EXPENSES
INCLUDING BUT NOT LIMITED TO ANY INCIDENTAL, SPECIAL, INDIRECT, PUNITIVE OR
CONSEQUENTIAL DAMAGES, LOST PROFITS OR LOST DATA, COST OF PROCUREMENT OF
SUBSTITUTE GOODS, TECHNOLOGY, SERVICES, OR ANY CLAIMS BY THIRD PARTIES
(INCLUDING BUT NOT LIMITED TO ANY DEFENSE THEREOF), OR OTHER SIMILAR COSTS.
 *******************************************************************************/
 -->
 <#--
	Interrupt configuration for ADC
 -->
<#if CONFIG_DRV_ADC_INTERRUPT_MODE == true>
    <#if CONFIG_USE_3RDPARTY_RTOS>
        <#if CONFIG_3RDPARTY_RTOS_USED == "ThreadX">
            <#lt>void __ISR(${CONFIG_DRV_ADC_ISR_VECTOR}, IPL${CONFIG_DRV_ADC_INT_IPL}SOFT) _IntHandlerDrvAdc(void)
        <#else>
            <#if CONFIG_3RDPARTY_RTOS_USED == "embOS">
                <#lt>void __attribute__( (interrupt(ipl${CONFIG_DRV_ADC_INT_IPL}AUTO), vector(${CONFIG_DRV_ADC_ISR_VECTOR}))) IntHandlerDrvAdc_ISR( void );
            </#if>
            <#lt>void IntHandlerDrvAdc(void)
        </#if>
    <#else>
        <#lt>void __ISR(${CONFIG_DRV_ADC_ISR_VECTOR}, ipl${CONFIG_DRV_ADC_INT_IPL}AUTO) _IntHandlerDrvAdc(void)
    </#if>	
    <#lt>{
    <#if CONFIG_USE_3RDPARTY_RTOS>
        <#if CONFIG_3RDPARTY_RTOS_USED == "embOS">
            <#lt>   OS_EnterNestableInterrupt();
        </#if>
    </#if>
    <#if CONFIG_DRV_ADC_DRIVER_MODE == "DYNAMIC">
        <#lt>   DRV_ADC_Tasks(sysObj.drvAdc);
    <#else>
        <#lt>   /* Clear ADC Interrupt Flag */
        <#lt>   PLIB_INT_SourceFlagClear(INT_ID_0, ${CONFIG_DRV_ADC_INTERRUPT_SOURCE});
    </#if>
    <#if CONFIG_USE_3RDPARTY_RTOS>
        <#if CONFIG_3RDPARTY_RTOS_USED == "embOS">
            <#lt>   OS_LeaveNestableInterrupt();
        </#if>
    </#if>
    <#lt>}
</#if>
 <#--
	Interrupt configuration for ADCHS
 -->
<#if CONFIG_DRV_ADCHS_INTERRUPT_MODE == true>
    <#if CONFIG_DRV_ADCHS_INDIVIDUAL_INTERRUPT_ENABLE == true >
        <#macro ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID ADCHS_ISR_SUFFIX ADCHS_INT_SOURCE ADCHS_ISR_IPL=CONFIG_DRV_ADCHS_INT_IPL>	
            <#if CONFIG_USE_3RDPARTY_RTOS>
                <#if CONFIG_3RDPARTY_RTOS_USED == "ThreadX">
                    <#lt>void __ISR(${CONFIG_DRV_ADCHS_ISR_VECTOR}, IPL${ADCHS_ISR_IPL}SOFT) _IntHandlerDrvAdc${ADCHS_ISR_SUFFIX}(void)
                <#else>
                    <#if CONFIG_3RDPARTY_RTOS_USED == "embOS">
                        <#lt>void __attribute__( (interrupt(ipl${ADCHS_ISR_IPL}AUTO), vector(${CONFIG_DRV_ADCHS_ISR_VECTOR}))) IntHandlerDrvAdc_ISR${ADCHS_ISR_SUFFIX}( void );
                    </#if>
                        <#lt>void IntHandlerDrvAdc${ADCHS_ISR_SUFFIX}(void)
                </#if>
            <#else>
                <#lt>void __ISR(${ADCHS_VECTOR_ID}, ipl${ADCHS_ISR_IPL}AUTO) _IntHandlerDrvAdc${ADCHS_ISR_SUFFIX}(void)
            </#if>
            <#lt>{
            <#if CONFIG_USE_3RDPARTY_RTOS>
                <#if CONFIG_3RDPARTY_RTOS_USED == "embOS">
                    <#lt>   OS_EnterNestableInterrupt();
                </#if>
            </#if>
            <#if CONFIG_DRV_ADCHS_DRIVER_MODE == "DYNAMIC">
                <#lt>   DRV_ADC_Tasks(sysObj.drvAdc);
            <#else>
                <#lt>   /* Clear ADC Interrupt Flag of ${ADCHS_INT_SOURCE}*/
                <#lt>   PLIB_INT_SourceFlagClear(INT_ID_0, ${ADCHS_INT_SOURCE});
            </#if>	
            <#if CONFIG_USE_3RDPARTY_RTOS>
                <#if CONFIG_3RDPARTY_RTOS_USED == "embOS">
                    <#lt>   OS_LeaveNestableInterrupt();
                </#if>
            </#if>
            <#lt>}
        </#macro>
        <#--
        Insert handlers for Class 1 inputs
        -->
        <#-- Insert interrupt handler for Channel 0 -->
        <#if CONFIG_DRV_ADCHS_CHNL_0_ALT_INP_SEL_IDX0?has_content>
			<#if CONFIG_DRV_ADCHS_CHANNEL_DATA_RDY_INTERRUPT_ENABLE_IDX0 == true>
				<@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA0_VECTOR" ADCHS_ISR_SUFFIX="_DATA0" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA0" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_CHANNEL_DATA_RDY_INT_IPL_IDX0/>
			</#if> 
        </#if>
        <#if CONFIG_DRV_ADCHS_CHNL_0_ALT_INP_SEL_IDX1?has_content>
			<#if CONFIG_DRV_ADCHS_CHANNEL_DATA_RDY_INTERRUPT_ENABLE_IDX1 == true>
				<@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA0_VECTOR" ADCHS_ISR_SUFFIX="_DATA0" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA0" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_CHANNEL_DATA_RDY_INT_IPL_IDX1/>
			</#if> 
        </#if>
        <#if CONFIG_DRV_ADCHS_CHNL_0_ALT_INP_SEL_IDX2?has_content>
			<#if CONFIG_DRV_ADCHS_CHANNEL_DATA_RDY_INTERRUPT_ENABLE_IDX2 == true>
				<@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA0_VECTOR" ADCHS_ISR_SUFFIX="_DATA0" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA0" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_CHANNEL_DATA_RDY_INT_IPL_IDX2/>
			</#if>
        </#if>
        <#if CONFIG_DRV_ADCHS_CHNL_0_ALT_INP_SEL_IDX3?has_content>
			<#if CONFIG_DRV_ADCHS_CHANNEL_DATA_RDY_INTERRUPT_ENABLE_IDX3 == true>
				<@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA0_VECTOR" ADCHS_ISR_SUFFIX="_DATA0" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA0" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_CHANNEL_DATA_RDY_INT_IPL_IDX3/>
			</#if>
        </#if>
        <#if CONFIG_DRV_ADCHS_CHNL_0_ALT_INP_SEL_IDX4?has_content>
			<#if CONFIG_DRV_ADCHS_CHANNEL_DATA_RDY_INTERRUPT_ENABLE_IDX4 == true>
				<@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA0_VECTOR" ADCHS_ISR_SUFFIX="_DATA0" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA0" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_CHANNEL_DATA_RDY_INT_IPL_IDX4/>
			</#if>
        </#if>
        <#if CONFIG_DRV_ADCHS_CHNL_0_ALT_INP_SEL_IDX5?has_content>
			<#if CONFIG_DRV_ADCHS_CHANNEL_DATA_RDY_INTERRUPT_ENABLE_IDX5 == true>
				<@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA0_VECTOR" ADCHS_ISR_SUFFIX="_DATA0" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA0" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_CHANNEL_DATA_RDY_INT_IPL_IDX5/>
			</#if> 
        </#if>
        <#-- Insert interrupt handler for Channel 1 -->
        <#if CONFIG_DRV_ADCHS_CHNL_1_ALT_INP_SEL_IDX0?has_content>
            <#if CONFIG_DRV_ADCHS_CHANNEL_DATA_RDY_INTERRUPT_ENABLE_IDX0 == true>
				<@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA1_VECTOR" ADCHS_ISR_SUFFIX="_DATA1" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA1" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_CHANNEL_DATA_RDY_INT_IPL_IDX0/>
			</#if>
        </#if>
        <#if CONFIG_DRV_ADCHS_CHNL_1_ALT_INP_SEL_IDX1?has_content>
           <#if CONFIG_DRV_ADCHS_CHANNEL_DATA_RDY_INTERRUPT_ENABLE_IDX1 == true>
				<@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA1_VECTOR" ADCHS_ISR_SUFFIX="_DATA1" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA1" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_CHANNEL_DATA_RDY_INT_IPL_IDX1/>
			</#if>
        </#if>
        <#if CONFIG_DRV_ADCHS_CHNL_1_ALT_INP_SEL_IDX2?has_content>
            <#if CONFIG_DRV_ADCHS_CHANNEL_DATA_RDY_INTERRUPT_ENABLE_IDX2 == true>
				<@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA1_VECTOR" ADCHS_ISR_SUFFIX="_DATA1" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA1" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_CHANNEL_DATA_RDY_INT_IPL_IDX2/>
			</#if>
        </#if>
        <#if CONFIG_DRV_ADCHS_CHNL_1_ALT_INP_SEL_IDX3?has_content>
            <#if CONFIG_DRV_ADCHS_CHANNEL_DATA_RDY_INTERRUPT_ENABLE_IDX3 == true>
				<@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA1_VECTOR" ADCHS_ISR_SUFFIX="_DATA1" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA1" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_CHANNEL_DATA_RDY_INT_IPL_IDX3/>
			</#if>
        </#if>
        <#if CONFIG_DRV_ADCHS_CHNL_1_ALT_INP_SEL_IDX4?has_content>
           <#if CONFIG_DRV_ADCHS_CHANNEL_DATA_RDY_INTERRUPT_ENABLE_IDX4 == true>
				<@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA1_VECTOR" ADCHS_ISR_SUFFIX="_DATA1" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA1" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_CHANNEL_DATA_RDY_INT_IPL_IDX4/>
		   </#if>
        </#if>
        <#if CONFIG_DRV_ADCHS_CHNL_1_ALT_INP_SEL_IDX5?has_content>
			<#if CONFIG_DRV_ADCHS_CHANNEL_DATA_RDY_INTERRUPT_ENABLE_IDX5 == true>
				<@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA1_VECTOR" ADCHS_ISR_SUFFIX="_DATA1" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA1" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_CHANNEL_DATA_RDY_INT_IPL_IDX5/>
			</#if>
        </#if>
        <#-- Insert interrupt handler for Channel 2 -->
        <#if CONFIG_DRV_ADCHS_CHNL_2_ALT_INP_SEL_IDX0?has_content>
            <#if CONFIG_DRV_ADCHS_CHANNEL_DATA_RDY_INTERRUPT_ENABLE_IDX0 == true>
				<@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA2_VECTOR" ADCHS_ISR_SUFFIX="_DATA2" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA2" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_CHANNEL_DATA_RDY_INT_IPL_IDX0/>
			</#if>
        </#if>
        <#if CONFIG_DRV_ADCHS_CHNL_2_ALT_INP_SEL_IDX1?has_content>
            <#if CONFIG_DRV_ADCHS_CHANNEL_DATA_RDY_INTERRUPT_ENABLE_IDX1 == true>
				<@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA2_VECTOR" ADCHS_ISR_SUFFIX="_DATA2" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA2" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_CHANNEL_DATA_RDY_INT_IPL_IDX1/>
			</#if>
        </#if>
        <#if CONFIG_DRV_ADCHS_CHNL_2_ALT_INP_SEL_IDX2?has_content>
            <#if CONFIG_DRV_ADCHS_CHANNEL_DATA_RDY_INTERRUPT_ENABLE_IDX2 == true>
				<@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA2_VECTOR" ADCHS_ISR_SUFFIX="_DATA2" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA2" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_CHANNEL_DATA_RDY_INT_IPL_IDX2/>
			</#if>
        </#if>
        <#if CONFIG_DRV_ADCHS_CHNL_2_ALT_INP_SEL_IDX3?has_content>
            <#if CONFIG_DRV_ADCHS_CHANNEL_DATA_RDY_INTERRUPT_ENABLE_IDX3 == true>
				<@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA2_VECTOR" ADCHS_ISR_SUFFIX="_DATA2" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA2" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_CHANNEL_DATA_RDY_INT_IPL_IDX3/>
			</#if>
        </#if>
        <#if CONFIG_DRV_ADCHS_CHNL_2_ALT_INP_SEL_IDX4?has_content>
            <#if CONFIG_DRV_ADCHS_CHANNEL_DATA_RDY_INTERRUPT_ENABLE_IDX4 == true>
				<@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA2_VECTOR" ADCHS_ISR_SUFFIX="_DATA2" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA2" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_CHANNEL_DATA_RDY_INT_IPL_IDX4/>
			</#if>
        </#if>
        <#if CONFIG_DRV_ADCHS_CHNL_2_ALT_INP_SEL_IDX5?has_content>
            <#if CONFIG_DRV_ADCHS_CHANNEL_DATA_RDY_INTERRUPT_ENABLE_IDX5 == true>
				<@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA2_VECTOR" ADCHS_ISR_SUFFIX="_DATA2" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA2" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_CHANNEL_DATA_RDY_INT_IPL_IDX5/>
			</#if>
        </#if>
        <#-- Insert interrupt handler for Channel 3 -->
        <#if CONFIG_DRV_ADCHS_CHNL_3_ALT_INP_SEL_IDX0?has_content>
            <#if CONFIG_DRV_ADCHS_CHANNEL_DATA_RDY_INTERRUPT_ENABLE_IDX0 == true>
				<@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA3_VECTOR" ADCHS_ISR_SUFFIX="_DATA3" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA3" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_CHANNEL_DATA_RDY_INT_IPL_IDX0/>
			</#if>
        </#if>
        <#if CONFIG_DRV_ADCHS_CHNL_3_ALT_INP_SEL_IDX1?has_content>
            <#if CONFIG_DRV_ADCHS_CHANNEL_DATA_RDY_INTERRUPT_ENABLE_IDX1 == true>
				<@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA3_VECTOR" ADCHS_ISR_SUFFIX="_DATA3" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA3" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_CHANNEL_DATA_RDY_INT_IPL_IDX1/>
			</#if> ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA3"/>       
        </#if>
        <#if CONFIG_DRV_ADCHS_CHNL_3_ALT_INP_SEL_IDX2?has_content>
             <#if CONFIG_DRV_ADCHS_CHANNEL_DATA_RDY_INTERRUPT_ENABLE_IDX2 == true>
				<@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA3_VECTOR" ADCHS_ISR_SUFFIX="_DATA3" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA3" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_CHANNEL_DATA_RDY_INT_IPL_IDX2/>
			</#if>     
        </#if>
        <#if CONFIG_DRV_ADCHS_CHNL_3_ALT_INP_SEL_IDX3?has_content>
            <#if CONFIG_DRV_ADCHS_CHANNEL_DATA_RDY_INTERRUPT_ENABLE_IDX3 == true>
				<@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA3_VECTOR" ADCHS_ISR_SUFFIX="_DATA3" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA3" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_CHANNEL_DATA_RDY_INT_IPL_IDX3/>
			</#if> 
        </#if>
        <#if CONFIG_DRV_ADCHS_CHNL_3_ALT_INP_SEL_IDX4?has_content>
            <#if CONFIG_DRV_ADCHS_CHANNEL_DATA_RDY_INTERRUPT_ENABLE_IDX4 == true>
				<@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA3_VECTOR" ADCHS_ISR_SUFFIX="_DATA3" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA3" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_CHANNEL_DATA_RDY_INT_IPL_IDX4/>
			</#if> 
        </#if>
        <#if CONFIG_DRV_ADCHS_CHNL_3_ALT_INP_SEL_IDX5?has_content>
            <#if CONFIG_DRV_ADCHS_CHANNEL_DATA_RDY_INTERRUPT_ENABLE_IDX5 == true>
				<@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA3_VECTOR" ADCHS_ISR_SUFFIX="_DATA3" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA3" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_CHANNEL_DATA_RDY_INT_IPL_IDX5/>
			</#if>
        </#if>
        <#-- Insert interrupt handler for Channel 4 -->
        <#if CONFIG_DRV_ADCHS_CHNL_4_ALT_INP_SEL_IDX0?has_content>
            <#if CONFIG_DRV_ADCHS_CHANNEL_DATA_RDY_INTERRUPT_ENABLE_IDX0 == true>
				<@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA4_VECTOR" ADCHS_ISR_SUFFIX="_DATA4" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA4" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_CHANNEL_DATA_RDY_INT_IPL_IDX0/>
			</#if>
        </#if>
        <#if CONFIG_DRV_ADCHS_CHNL_4_ALT_INP_SEL_IDX1?has_content>
            <#if CONFIG_DRV_ADCHS_CHANNEL_DATA_RDY_INTERRUPT_ENABLE_IDX1 == true>
				<@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA4_VECTOR" ADCHS_ISR_SUFFIX="_DATA4" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA4" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_CHANNEL_DATA_RDY_INT_IPL_IDX1/>
			</#if>
        </#if>
        <#if CONFIG_DRV_ADCHS_CHNL_4_ALT_INP_SEL_IDX2?has_content>
            <#if CONFIG_DRV_ADCHS_CHANNEL_DATA_RDY_INTERRUPT_ENABLE_IDX2 == true>
				<@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA4_VECTOR" ADCHS_ISR_SUFFIX="_DATA4" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA4" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_CHANNEL_DATA_RDY_INT_IPL_IDX2/>
			</#if>
        </#if>
        <#if CONFIG_DRV_ADCHS_CHNL_4_ALT_INP_SEL_IDX3?has_content>
            <#if CONFIG_DRV_ADCHS_CHANNEL_DATA_RDY_INTERRUPT_ENABLE_IDX3 == true>
				<@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA4_VECTOR" ADCHS_ISR_SUFFIX="_DATA4" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA4" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_CHANNEL_DATA_RDY_INT_IPL_IDX3/>
			</#if>
        </#if>
        <#if CONFIG_DRV_ADCHS_CHNL_4_ALT_INP_SEL_IDX4?has_content>
            <#if CONFIG_DRV_ADCHS_CHANNEL_DATA_RDY_INTERRUPT_ENABLE_IDX4 == true>
				<@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA4_VECTOR" ADCHS_ISR_SUFFIX="_DATA4" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA4" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_CHANNEL_DATA_RDY_INT_IPL_IDX4/>
			</#if>
        </#if>
        <#if CONFIG_DRV_ADCHS_CHNL_4_ALT_INP_SEL_IDX5?has_content>
            <#if CONFIG_DRV_ADCHS_CHANNEL_DATA_RDY_INTERRUPT_ENABLE_IDX5 == true>
				<@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA4_VECTOR" ADCHS_ISR_SUFFIX="_DATA4" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA4" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_CHANNEL_DATA_RDY_INT_IPL_IDX5/>
			</#if>
        </#if>
        <#--
        Insert handlers for Class 2 inputs
        -->
        <#-- ADCHS_CLASS2_AN5 -->
        <#if CONFIG_DRV_ADCHS_CLASS_2_ANALOG_INPUT_IDX0?has_content && (CONFIG_DRV_ADCHS_CLASS_2_ANALOG_INPUT_IDX0 = "ADCHS_CLASS2_AN5")>
            <#if CONFIG_DRV_ADCHS_CLASS_2_DATA_RDY_INTERRUPT_ENABLE_IDX0 == true>
				<@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA5_VECTOR" ADCHS_ISR_SUFFIX="_DATA5" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA5" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_CLASS_2_DATA_RDY_INT_IPL_IDX0/>
			</#if>
        </#if>
        <#if CONFIG_DRV_ADCHS_CLASS_2_ANALOG_INPUT_IDX1?has_content && (CONFIG_DRV_ADCHS_CLASS_2_ANALOG_INPUT_IDX1 = "ADCHS_CLASS2_AN5")>
            <#if CONFIG_DRV_ADCHS_CLASS_2_DATA_RDY_INTERRUPT_ENABLE_IDX1 == true>
				<@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA5_VECTOR" ADCHS_ISR_SUFFIX="_DATA5" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA5" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_CLASS_2_DATA_RDY_INT_IPL_IDX1/>
			</#if>
        </#if>
        <#if CONFIG_DRV_ADCHS_CLASS_2_ANALOG_INPUT_IDX2?has_content && (CONFIG_DRV_ADCHS_CLASS_2_ANALOG_INPUT_IDX2 = "ADCHS_CLASS2_AN5")>
            <#if CONFIG_DRV_ADCHS_CLASS_2_DATA_RDY_INTERRUPT_ENABLE_IDX2 == true>
				<@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA5_VECTOR" ADCHS_ISR_SUFFIX="_DATA5" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA5" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_CLASS_2_DATA_RDY_INT_IPL_IDX2/>
			</#if>
        </#if>
        <#if CONFIG_DRV_ADCHS_CLASS_2_ANALOG_INPUT_IDX3?has_content && (CONFIG_DRV_ADCHS_CLASS_2_ANALOG_INPUT_IDX3 = "ADCHS_CLASS2_AN5")>
            <#if CONFIG_DRV_ADCHS_CLASS_2_DATA_RDY_INTERRUPT_ENABLE_IDX3 == true>
				<@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA5_VECTOR" ADCHS_ISR_SUFFIX="_DATA5" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA5" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_CLASS_2_DATA_RDY_INT_IPL_IDX3/>
			</#if>
        </#if>
        <#if CONFIG_DRV_ADCHS_CLASS_2_ANALOG_INPUT_IDX4?has_content && (CONFIG_DRV_ADCHS_CLASS_2_ANALOG_INPUT_IDX4 = "ADCHS_CLASS2_AN5")>
            <#if CONFIG_DRV_ADCHS_CLASS_2_DATA_RDY_INTERRUPT_ENABLE_IDX4 == true>
				<@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA5_VECTOR" ADCHS_ISR_SUFFIX="_DATA5" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA5" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_CLASS_2_DATA_RDY_INT_IPL_IDX4/>
			</#if>
        </#if>
        <#if CONFIG_DRV_ADCHS_CLASS_2_ANALOG_INPUT_IDX5?has_content && (CONFIG_DRV_ADCHS_CLASS_2_ANALOG_INPUT_IDX5 = "ADCHS_CLASS2_AN5")>
            <#if CONFIG_DRV_ADCHS_CLASS_2_DATA_RDY_INTERRUPT_ENABLE_IDX5 == true>
				<@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA5_VECTOR" ADCHS_ISR_SUFFIX="_DATA5" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA5" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_CLASS_2_DATA_RDY_INT_IPL_IDX5/>
			</#if>
        </#if>
        <#if CONFIG_DRV_ADCHS_CLASS_2_ANALOG_INPUT_IDX6?has_content && (CONFIG_DRV_ADCHS_CLASS_2_ANALOG_INPUT_IDX6 = "ADCHS_CLASS2_AN5")>
            <#if CONFIG_DRV_ADCHS_CLASS_2_DATA_RDY_INTERRUPT_ENABLE_IDX6 == true>
				<@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA5_VECTOR" ADCHS_ISR_SUFFIX="_DATA5" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA5" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_CLASS_2_DATA_RDY_INT_IPL_IDX6/>
			</#if>
        </#if>
        <#-- ADCHS_CLASS2_AN6 -->
        <#if CONFIG_DRV_ADCHS_CLASS_2_ANALOG_INPUT_IDX0?has_content && (CONFIG_DRV_ADCHS_CLASS_2_ANALOG_INPUT_IDX0 = "ADCHS_CLASS2_AN6")>
            <#if CONFIG_DRV_ADCHS_CLASS_2_DATA_RDY_INTERRUPT_ENABLE_IDX0 == true>
				<@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA6_VECTOR" ADCHS_ISR_SUFFIX="_DATA6" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA6" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_CLASS_2_DATA_RDY_INT_IPL_IDX0/>
			</#if>
        </#if>
        <#if CONFIG_DRV_ADCHS_CLASS_2_ANALOG_INPUT_IDX1?has_content && (CONFIG_DRV_ADCHS_CLASS_2_ANALOG_INPUT_IDX1 = "ADCHS_CLASS2_AN6")>
            <#if CONFIG_DRV_ADCHS_CLASS_2_DATA_RDY_INTERRUPT_ENABLE_IDX1 == true>
				<@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA6_VECTOR" ADCHS_ISR_SUFFIX="_DATA6" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA6" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_CLASS_2_DATA_RDY_INT_IPL_IDX1/>
			</#if>
        </#if>
        <#if CONFIG_DRV_ADCHS_CLASS_2_ANALOG_INPUT_IDX2?has_content && (CONFIG_DRV_ADCHS_CLASS_2_ANALOG_INPUT_IDX2 = "ADCHS_CLASS2_AN6")>
            <#if CONFIG_DRV_ADCHS_CLASS_2_DATA_RDY_INTERRUPT_ENABLE_IDX2 == true>
				<@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA6_VECTOR" ADCHS_ISR_SUFFIX="_DATA6" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA6" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_CLASS_2_DATA_RDY_INT_IPL_IDX2/>
			</#if>
        </#if>
        <#if CONFIG_DRV_ADCHS_CLASS_2_ANALOG_INPUT_IDX3?has_content && (CONFIG_DRV_ADCHS_CLASS_2_ANALOG_INPUT_IDX3 = "ADCHS_CLASS2_AN6")>
            <#if CONFIG_DRV_ADCHS_CLASS_2_DATA_RDY_INTERRUPT_ENABLE_IDX3 == true>
				<@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA6_VECTOR" ADCHS_ISR_SUFFIX="_DATA6" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA6" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_CLASS_2_DATA_RDY_INT_IPL_IDX3/>
			</#if>
        </#if>
        <#if CONFIG_DRV_ADCHS_CLASS_2_ANALOG_INPUT_IDX4?has_content && (CONFIG_DRV_ADCHS_CLASS_2_ANALOG_INPUT_IDX4 = "ADCHS_CLASS2_AN6")>
            <#if CONFIG_DRV_ADCHS_CLASS_2_DATA_RDY_INTERRUPT_ENABLE_IDX4 == true>
				<@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA6_VECTOR" ADCHS_ISR_SUFFIX="_DATA6" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA6" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_CLASS_2_DATA_RDY_INT_IPL_IDX4/>
			</#if>
        </#if>
        <#if CONFIG_DRV_ADCHS_CLASS_2_ANALOG_INPUT_IDX5?has_content && (CONFIG_DRV_ADCHS_CLASS_2_ANALOG_INPUT_IDX5 = "ADCHS_CLASS2_AN6")>
            <#if CONFIG_DRV_ADCHS_CLASS_2_DATA_RDY_INTERRUPT_ENABLE_IDX5 == true>
				<@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA6_VECTOR" ADCHS_ISR_SUFFIX="_DATA6" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA6" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_CLASS_2_DATA_RDY_INT_IPL_IDX5/>
			</#if>
        </#if>
        <#if CONFIG_DRV_ADCHS_CLASS_2_ANALOG_INPUT_IDX6?has_content && (CONFIG_DRV_ADCHS_CLASS_2_ANALOG_INPUT_IDX6 = "ADCHS_CLASS2_AN6")>
            <#if CONFIG_DRV_ADCHS_CLASS_2_DATA_RDY_INTERRUPT_ENABLE_IDX6 == true>
				<@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA6_VECTOR" ADCHS_ISR_SUFFIX="_DATA6" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA6" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_CLASS_2_DATA_RDY_INT_IPL_IDX6/>
			</#if>
        </#if>
        <#-- ADCHS_CLASS2_AN7 -->
        <#if CONFIG_DRV_ADCHS_CLASS_2_ANALOG_INPUT_IDX0?has_content && (CONFIG_DRV_ADCHS_CLASS_2_ANALOG_INPUT_IDX0 = "ADCHS_CLASS2_AN7")>
            <#if CONFIG_DRV_ADCHS_CLASS_2_DATA_RDY_INTERRUPT_ENABLE_IDX0 == true>
				<@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA7_VECTOR" ADCHS_ISR_SUFFIX="_DATA7" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA7" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_CLASS_2_DATA_RDY_INT_IPL_IDX0/>
			</#if>
        </#if>
        <#if CONFIG_DRV_ADCHS_CLASS_2_ANALOG_INPUT_IDX1?has_content && (CONFIG_DRV_ADCHS_CLASS_2_ANALOG_INPUT_IDX1 = "ADCHS_CLASS2_AN7")>
            <#if CONFIG_DRV_ADCHS_CLASS_2_DATA_RDY_INTERRUPT_ENABLE_IDX1 == true>
				<@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA7_VECTOR" ADCHS_ISR_SUFFIX="_DATA7" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA7" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_CLASS_2_DATA_RDY_INT_IPL_IDX1/>
			</#if>
        </#if>
        <#if CONFIG_DRV_ADCHS_CLASS_2_ANALOG_INPUT_IDX2?has_content && (CONFIG_DRV_ADCHS_CLASS_2_ANALOG_INPUT_IDX2 = "ADCHS_CLASS2_AN7")>
            <#if CONFIG_DRV_ADCHS_CLASS_2_DATA_RDY_INTERRUPT_ENABLE_IDX2 == true>
				<@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA7_VECTOR" ADCHS_ISR_SUFFIX="_DATA7" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA7" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_CLASS_2_DATA_RDY_INT_IPL_IDX2/>
			</#if>
        </#if>
        <#if CONFIG_DRV_ADCHS_CLASS_2_ANALOG_INPUT_IDX3?has_content && (CONFIG_DRV_ADCHS_CLASS_2_ANALOG_INPUT_IDX3 = "ADCHS_CLASS2_AN7")>
            <#if CONFIG_DRV_ADCHS_CLASS_2_DATA_RDY_INTERRUPT_ENABLE_IDX3 == true>
				<@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA7_VECTOR" ADCHS_ISR_SUFFIX="_DATA7" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA7" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_CLASS_2_DATA_RDY_INT_IPL_IDX3/>
			</#if>
        </#if>
        <#if CONFIG_DRV_ADCHS_CLASS_2_ANALOG_INPUT_IDX4?has_content && (CONFIG_DRV_ADCHS_CLASS_2_ANALOG_INPUT_IDX4 = "ADCHS_CLASS2_AN7")>
            <#if CONFIG_DRV_ADCHS_CLASS_2_DATA_RDY_INTERRUPT_ENABLE_IDX4 == true>
				<@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA7_VECTOR" ADCHS_ISR_SUFFIX="_DATA7" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA7" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_CLASS_2_DATA_RDY_INT_IPL_IDX4/>
			</#if>
        </#if>
        <#if CONFIG_DRV_ADCHS_CLASS_2_ANALOG_INPUT_IDX5?has_content && (CONFIG_DRV_ADCHS_CLASS_2_ANALOG_INPUT_IDX5 = "ADCHS_CLASS2_AN7")>
            <#if CONFIG_DRV_ADCHS_CLASS_2_DATA_RDY_INTERRUPT_ENABLE_IDX5 == true>
				<@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA7_VECTOR" ADCHS_ISR_SUFFIX="_DATA7" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA7" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_CLASS_2_DATA_RDY_INT_IPL_IDX5/>
			</#if>
        </#if>
        <#if CONFIG_DRV_ADCHS_CLASS_2_ANALOG_INPUT_IDX6?has_content && (CONFIG_DRV_ADCHS_CLASS_2_ANALOG_INPUT_IDX6 = "ADCHS_CLASS2_AN7")>
            <#if CONFIG_DRV_ADCHS_CLASS_2_DATA_RDY_INTERRUPT_ENABLE_IDX6 == true>
				<@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA7_VECTOR" ADCHS_ISR_SUFFIX="_DATA7" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA7" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_CLASS_2_DATA_RDY_INT_IPL_IDX6/>
			</#if>
        </#if>
        <#-- ADCHS_CLASS2_AN8 -->
        <#if CONFIG_DRV_ADCHS_CLASS_2_ANALOG_INPUT_IDX0?has_content && (CONFIG_DRV_ADCHS_CLASS_2_ANALOG_INPUT_IDX0 = "ADCHS_CLASS2_AN8")>
            <#if CONFIG_DRV_ADCHS_CLASS_2_DATA_RDY_INTERRUPT_ENABLE_IDX0 == true>
				<@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA8_VECTOR" ADCHS_ISR_SUFFIX="_DATA8" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA8" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_CLASS_2_DATA_RDY_INT_IPL_IDX0/>
			</#if>
        </#if>
        <#if CONFIG_DRV_ADCHS_CLASS_2_ANALOG_INPUT_IDX1?has_content && (CONFIG_DRV_ADCHS_CLASS_2_ANALOG_INPUT_IDX1 = "ADCHS_CLASS2_AN8")>
            <#if CONFIG_DRV_ADCHS_CLASS_2_DATA_RDY_INTERRUPT_ENABLE_IDX1 == true>
				<@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA8_VECTOR" ADCHS_ISR_SUFFIX="_DATA8" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA8" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_CLASS_2_DATA_RDY_INT_IPL_IDX1/>
			</#if>
        </#if>
        <#if CONFIG_DRV_ADCHS_CLASS_2_ANALOG_INPUT_IDX2?has_content && (CONFIG_DRV_ADCHS_CLASS_2_ANALOG_INPUT_IDX2 = "ADCHS_CLASS2_AN8")>
            <#if CONFIG_DRV_ADCHS_CLASS_2_DATA_RDY_INTERRUPT_ENABLE_IDX2 == true>
				<@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA8_VECTOR" ADCHS_ISR_SUFFIX="_DATA8" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA8" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_CLASS_2_DATA_RDY_INT_IPL_IDX2/>
			</#if>
        </#if>
        <#if CONFIG_DRV_ADCHS_CLASS_2_ANALOG_INPUT_IDX3?has_content && (CONFIG_DRV_ADCHS_CLASS_2_ANALOG_INPUT_IDX3 = "ADCHS_CLASS2_AN8")>
            <#if CONFIG_DRV_ADCHS_CLASS_2_DATA_RDY_INTERRUPT_ENABLE_IDX3 == true>
				<@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA8_VECTOR" ADCHS_ISR_SUFFIX="_DATA8" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA8" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_CLASS_2_DATA_RDY_INT_IPL_IDX3/>
			</#if>
        </#if>
        <#if CONFIG_DRV_ADCHS_CLASS_2_ANALOG_INPUT_IDX4?has_content && (CONFIG_DRV_ADCHS_CLASS_2_ANALOG_INPUT_IDX4 = "ADCHS_CLASS2_AN8")>
            <#if CONFIG_DRV_ADCHS_CLASS_2_DATA_RDY_INTERRUPT_ENABLE_IDX4 == true>
				<@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA8_VECTOR" ADCHS_ISR_SUFFIX="_DATA8" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA8" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_CLASS_2_DATA_RDY_INT_IPL_IDX4/>
			</#if>
        </#if>
        <#if CONFIG_DRV_ADCHS_CLASS_2_ANALOG_INPUT_IDX5?has_content && (CONFIG_DRV_ADCHS_CLASS_2_ANALOG_INPUT_IDX5 = "ADCHS_CLASS2_AN8")>
            <#if CONFIG_DRV_ADCHS_CLASS_2_DATA_RDY_INTERRUPT_ENABLE_IDX5 == true>
				<@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA8_VECTOR" ADCHS_ISR_SUFFIX="_DATA8" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA8" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_CLASS_2_DATA_RDY_INT_IPL_IDX5/>
			</#if>
        </#if>
        <#if CONFIG_DRV_ADCHS_CLASS_2_ANALOG_INPUT_IDX6?has_content && (CONFIG_DRV_ADCHS_CLASS_2_ANALOG_INPUT_IDX6 = "ADCHS_CLASS2_AN8")>
            <#if CONFIG_DRV_ADCHS_CLASS_2_DATA_RDY_INTERRUPT_ENABLE_IDX6 == true>
				<@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA8_VECTOR" ADCHS_ISR_SUFFIX="_DATA8" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA8" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_CLASS_2_DATA_RDY_INT_IPL_IDX6/>
			</#if>
        </#if>
        <#-- ADCHS_CLASS2_AN9 -->
        <#if CONFIG_DRV_ADCHS_CLASS_2_ANALOG_INPUT_IDX0?has_content && (CONFIG_DRV_ADCHS_CLASS_2_ANALOG_INPUT_IDX0 = "ADCHS_CLASS2_AN9")>
            <#if CONFIG_DRV_ADCHS_CLASS_2_DATA_RDY_INTERRUPT_ENABLE_IDX0 == true>
				<@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA9_VECTOR" ADCHS_ISR_SUFFIX="_DATA9" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA9" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_CLASS_2_DATA_RDY_INT_IPL_IDX0/>
			</#if>
        </#if>
        <#if CONFIG_DRV_ADCHS_CLASS_2_ANALOG_INPUT_IDX1?has_content && (CONFIG_DRV_ADCHS_CLASS_2_ANALOG_INPUT_IDX1 = "ADCHS_CLASS2_AN9")>
            <#if CONFIG_DRV_ADCHS_CLASS_2_DATA_RDY_INTERRUPT_ENABLE_IDX1 == true>
				<@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA9_VECTOR" ADCHS_ISR_SUFFIX="_DATA9" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA9" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_CLASS_2_DATA_RDY_INT_IPL_IDX1/>
			</#if>
        </#if>
        <#if CONFIG_DRV_ADCHS_CLASS_2_ANALOG_INPUT_IDX2?has_content && (CONFIG_DRV_ADCHS_CLASS_2_ANALOG_INPUT_IDX2 = "ADCHS_CLASS2_AN9")>
            <#if CONFIG_DRV_ADCHS_CLASS_2_DATA_RDY_INTERRUPT_ENABLE_IDX2 == true>
				<@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA9_VECTOR" ADCHS_ISR_SUFFIX="_DATA9" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA9" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_CLASS_2_DATA_RDY_INT_IPL_IDX2/>
			</#if>
        </#if>
        <#if CONFIG_DRV_ADCHS_CLASS_2_ANALOG_INPUT_IDX3?has_content && (CONFIG_DRV_ADCHS_CLASS_2_ANALOG_INPUT_IDX3 = "ADCHS_CLASS2_AN9")>
            <#if CONFIG_DRV_ADCHS_CLASS_2_DATA_RDY_INTERRUPT_ENABLE_IDX3 == true>
				<@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA9_VECTOR" ADCHS_ISR_SUFFIX="_DATA9" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA9" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_CLASS_2_DATA_RDY_INT_IPL_IDX3/>
			</#if>
        </#if>
        <#if CONFIG_DRV_ADCHS_CLASS_2_ANALOG_INPUT_IDX4?has_content && (CONFIG_DRV_ADCHS_CLASS_2_ANALOG_INPUT_IDX4 = "ADCHS_CLASS2_AN9")>
            <#if CONFIG_DRV_ADCHS_CLASS_2_DATA_RDY_INTERRUPT_ENABLE_IDX4 == true>
				<@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA9_VECTOR" ADCHS_ISR_SUFFIX="_DATA9" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA9" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_CLASS_2_DATA_RDY_INT_IPL_IDX4/>
			</#if>
        </#if>
        <#if CONFIG_DRV_ADCHS_CLASS_2_ANALOG_INPUT_IDX5?has_content && (CONFIG_DRV_ADCHS_CLASS_2_ANALOG_INPUT_IDX5 = "ADCHS_CLASS2_AN9")>
            <#if CONFIG_DRV_ADCHS_CLASS_2_DATA_RDY_INTERRUPT_ENABLE_IDX5 == true>
				<@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA9_VECTOR" ADCHS_ISR_SUFFIX="_DATA9" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA9" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_CLASS_2_DATA_RDY_INT_IPL_IDX5/>
			</#if>
        </#if>
        <#if CONFIG_DRV_ADCHS_CLASS_2_ANALOG_INPUT_IDX6?has_content && (CONFIG_DRV_ADCHS_CLASS_2_ANALOG_INPUT_IDX6 = "ADCHS_CLASS2_AN9")>
            <#if CONFIG_DRV_ADCHS_CLASS_2_DATA_RDY_INTERRUPT_ENABLE_IDX6 == true>
				<@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA9_VECTOR" ADCHS_ISR_SUFFIX="_DATA9" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA9" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_CLASS_2_DATA_RDY_INT_IPL_IDX6/>
			</#if>
        </#if>
        <#-- ADCHS_CLASS2_AN10 -->
        <#if CONFIG_DRV_ADCHS_CLASS_2_ANALOG_INPUT_IDX0?has_content && (CONFIG_DRV_ADCHS_CLASS_2_ANALOG_INPUT_IDX0 = "ADCHS_CLASS2_AN10")>
            <#if CONFIG_DRV_ADCHS_CLASS_2_DATA_RDY_INTERRUPT_ENABLE_IDX0 == true>
				<@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA10_VECTOR" ADCHS_ISR_SUFFIX="_DATA10" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA10" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_CLASS_2_DATA_RDY_INT_IPL_IDX0/>
			</#if>
        </#if>
        <#if CONFIG_DRV_ADCHS_CLASS_2_ANALOG_INPUT_IDX1?has_content && (CONFIG_DRV_ADCHS_CLASS_2_ANALOG_INPUT_IDX1 = "ADCHS_CLASS2_AN10")>
            <#if CONFIG_DRV_ADCHS_CLASS_2_DATA_RDY_INTERRUPT_ENABLE_IDX1 == true>
				<@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA10_VECTOR" ADCHS_ISR_SUFFIX="_DATA10" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA10" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_CLASS_2_DATA_RDY_INT_IPL_IDX1/>
			</#if>
        </#if>
        <#if CONFIG_DRV_ADCHS_CLASS_2_ANALOG_INPUT_IDX2?has_content && (CONFIG_DRV_ADCHS_CLASS_2_ANALOG_INPUT_IDX2 = "ADCHS_CLASS2_AN10")>
            <#if CONFIG_DRV_ADCHS_CLASS_2_DATA_RDY_INTERRUPT_ENABLE_IDX2 == true>
				<@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA10_VECTOR" ADCHS_ISR_SUFFIX="_DATA10" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA10" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_CLASS_2_DATA_RDY_INT_IPL_IDX2/>
			</#if>
        </#if>
        <#if CONFIG_DRV_ADCHS_CLASS_2_ANALOG_INPUT_IDX3?has_content && (CONFIG_DRV_ADCHS_CLASS_2_ANALOG_INPUT_IDX3 = "ADCHS_CLASS2_AN10")>
            <#if CONFIG_DRV_ADCHS_CLASS_2_DATA_RDY_INTERRUPT_ENABLE_IDX3 == true>
				<@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA10_VECTOR" ADCHS_ISR_SUFFIX="_DATA10" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA10" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_CLASS_2_DATA_RDY_INT_IPL_IDX3/>
			</#if>
        </#if>
        <#if CONFIG_DRV_ADCHS_CLASS_2_ANALOG_INPUT_IDX4?has_content && (CONFIG_DRV_ADCHS_CLASS_2_ANALOG_INPUT_IDX4 = "ADCHS_CLASS2_AN10")>
            <#if CONFIG_DRV_ADCHS_CLASS_2_DATA_RDY_INTERRUPT_ENABLE_IDX4 == true>
				<@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA10_VECTOR" ADCHS_ISR_SUFFIX="_DATA10" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA10" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_CLASS_2_DATA_RDY_INT_IPL_IDX4/>
			</#if>
        </#if>
        <#if CONFIG_DRV_ADCHS_CLASS_2_ANALOG_INPUT_IDX5?has_content && (CONFIG_DRV_ADCHS_CLASS_2_ANALOG_INPUT_IDX5 = "ADCHS_CLASS2_AN10")>
            <#if CONFIG_DRV_ADCHS_CLASS_2_DATA_RDY_INTERRUPT_ENABLE_IDX5 == true>
				<@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA10_VECTOR" ADCHS_ISR_SUFFIX="_DATA10" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA10" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_CLASS_2_DATA_RDY_INT_IPL_IDX5/>
			</#if>
        </#if>
        <#if CONFIG_DRV_ADCHS_CLASS_2_ANALOG_INPUT_IDX6?has_content && (CONFIG_DRV_ADCHS_CLASS_2_ANALOG_INPUT_IDX6 = "ADCHS_CLASS2_AN10")>
            <#if CONFIG_DRV_ADCHS_CLASS_2_DATA_RDY_INTERRUPT_ENABLE_IDX6 == true>
				<@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA10_VECTOR" ADCHS_ISR_SUFFIX="_DATA10" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA10" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_CLASS_2_DATA_RDY_INT_IPL_IDX6/>
			</#if>
        </#if>
        <#-- ADCHS_CLASS2_AN11 -->
        <#if CONFIG_DRV_ADCHS_CLASS_2_ANALOG_INPUT_IDX0?has_content && (CONFIG_DRV_ADCHS_CLASS_2_ANALOG_INPUT_IDX0 = "ADCHS_CLASS2_AN11")>
            <#if CONFIG_DRV_ADCHS_CLASS_2_DATA_RDY_INTERRUPT_ENABLE_IDX0 == true>
				<@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA11_VECTOR" ADCHS_ISR_SUFFIX="_DATA11" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA11" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_CLASS_2_DATA_RDY_INT_IPL_IDX0/>
			</#if>
        </#if>
        <#if CONFIG_DRV_ADCHS_CLASS_2_ANALOG_INPUT_IDX1?has_content && (CONFIG_DRV_ADCHS_CLASS_2_ANALOG_INPUT_IDX1 = "ADCHS_CLASS2_AN11")>
            <#if CONFIG_DRV_ADCHS_CLASS_2_DATA_RDY_INTERRUPT_ENABLE_IDX1 == true>
				<@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA11_VECTOR" ADCHS_ISR_SUFFIX="_DATA11" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA11" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_CLASS_2_DATA_RDY_INT_IPL_IDX1/>
			</#if>
        </#if>
        <#if CONFIG_DRV_ADCHS_CLASS_2_ANALOG_INPUT_IDX2?has_content && (CONFIG_DRV_ADCHS_CLASS_2_ANALOG_INPUT_IDX2 = "ADCHS_CLASS2_AN11")>
            <#if CONFIG_DRV_ADCHS_CLASS_2_DATA_RDY_INTERRUPT_ENABLE_IDX2 == true>
				<@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA11_VECTOR" ADCHS_ISR_SUFFIX="_DATA11" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA11" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_CLASS_2_DATA_RDY_INT_IPL_IDX2/>
			</#if>
        </#if>
        <#if CONFIG_DRV_ADCHS_CLASS_2_ANALOG_INPUT_IDX3?has_content && (CONFIG_DRV_ADCHS_CLASS_2_ANALOG_INPUT_IDX3 = "ADCHS_CLASS2_AN11")>
            <#if CONFIG_DRV_ADCHS_CLASS_2_DATA_RDY_INTERRUPT_ENABLE_IDX3 == true>
				<@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA11_VECTOR" ADCHS_ISR_SUFFIX="_DATA11" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA11" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_CLASS_2_DATA_RDY_INT_IPL_IDX3/>
			</#if>
        </#if>
        <#if CONFIG_DRV_ADCHS_CLASS_2_ANALOG_INPUT_IDX4?has_content && (CONFIG_DRV_ADCHS_CLASS_2_ANALOG_INPUT_IDX4 = "ADCHS_CLASS2_AN11")>
            <#if CONFIG_DRV_ADCHS_CLASS_2_DATA_RDY_INTERRUPT_ENABLE_IDX4 == true>
				<@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA11_VECTOR" ADCHS_ISR_SUFFIX="_DATA11" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA11" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_CLASS_2_DATA_RDY_INT_IPL_IDX4/>
			</#if>
        </#if>
        <#if CONFIG_DRV_ADCHS_CLASS_2_ANALOG_INPUT_IDX5?has_content && (CONFIG_DRV_ADCHS_CLASS_2_ANALOG_INPUT_IDX5 = "ADCHS_CLASS2_AN11")>
            <#if CONFIG_DRV_ADCHS_CLASS_2_DATA_RDY_INTERRUPT_ENABLE_IDX5 == true>
				<@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA11_VECTOR" ADCHS_ISR_SUFFIX="_DATA11" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA11" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_CLASS_2_DATA_RDY_INT_IPL_IDX5/>
			</#if>
        </#if>
        <#if CONFIG_DRV_ADCHS_CLASS_2_ANALOG_INPUT_IDX6?has_content && (CONFIG_DRV_ADCHS_CLASS_2_ANALOG_INPUT_IDX6 = "ADCHS_CLASS2_AN11")>
            <#if CONFIG_DRV_ADCHS_CLASS_2_DATA_RDY_INTERRUPT_ENABLE_IDX6 == true>
				<@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA11_VECTOR" ADCHS_ISR_SUFFIX="_DATA11" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA11" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_CLASS_2_DATA_RDY_INT_IPL_IDX6/>
			</#if>
        </#if>
        <#--
        Insert handler for CH12 to CH45
        Here a handler will be inserted only for Class 3 pins.
        For Class 1 and Class 2 pins, it is handled elswhere
        -->
        <#if CONFIG_DRV_ADCHS_ANALOG_INPUT_ID_IDX0?has_content>
            <#assign ch_num = CONFIG_DRV_ADCHS_ANALOG_INPUT_ID_IDX0[8..]?number>
            <#if (ch_num > 11)>
				<#if CONFIG_DRV_ADCHS_SCAN_DATA_RDY_INTERRUPT_ENABLE_IDX0 == true>
					<@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA${ch_num}_VECTOR" ADCHS_ISR_SUFFIX="_DATA${ch_num}" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA${ch_num}" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_SCAN_DATA_RDY_INT_IPL_IDX0/>
				</#if>
             </#if>
        </#if>
      <#if CONFIG_DRV_ADCHS_ANALOG_INPUT_ID_IDX1?has_content>
            <#assign ch_num = CONFIG_DRV_ADCHS_ANALOG_INPUT_ID_IDX1[8..]?number>
            <#if (ch_num > 11)>
               <#if CONFIG_DRV_ADCHS_SCAN_DATA_RDY_INTERRUPT_ENABLE_IDX1 == true>
			   <@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA${ch_num}_VECTOR" ADCHS_ISR_SUFFIX="_DATA${ch_num}" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA${ch_num}" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_SCAN_DATA_RDY_INT_IPL_IDX1/> </#if>
            </#if>
	
        </#if>
        <#if CONFIG_DRV_ADCHS_ANALOG_INPUT_ID_IDX2?has_content>
            <#assign ch_num = CONFIG_DRV_ADCHS_ANALOG_INPUT_ID_IDX2[8..]?number>
            <#if (ch_num > 11)>
               <#if CONFIG_DRV_ADCHS_SCAN_DATA_RDY_INTERRUPT_ENABLE_IDX2 == true>
			   <@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA${ch_num}_VECTOR" ADCHS_ISR_SUFFIX="_DATA${ch_num}" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA${ch_num}" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_SCAN_DATA_RDY_INT_IPL_IDX2/> </#if>
            </#if>
        </#if>
        <#if CONFIG_DRV_ADCHS_ANALOG_INPUT_ID_IDX3?has_content>
            <#assign ch_num = CONFIG_DRV_ADCHS_ANALOG_INPUT_ID_IDX3[8..]?number>
            <#if (ch_num > 11)>
               <#if CONFIG_DRV_ADCHS_SCAN_DATA_RDY_INTERRUPT_ENABLE_IDX3 == true>
			   <@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA${ch_num}_VECTOR" ADCHS_ISR_SUFFIX="_DATA${ch_num}" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA${ch_num}" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_SCAN_DATA_RDY_INT_IPL_IDX3/> </#if>
            </#if>
        </#if>
        <#if CONFIG_DRV_ADCHS_ANALOG_INPUT_ID_IDX4?has_content>
            <#assign ch_num = CONFIG_DRV_ADCHS_ANALOG_INPUT_ID_IDX4[8..]?number>
            <#if (ch_num > 11)>
               <#if CONFIG_DRV_ADCHS_SCAN_DATA_RDY_INTERRUPT_ENABLE_IDX4 == true>
			   <@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA${ch_num}_VECTOR" ADCHS_ISR_SUFFIX="_DATA${ch_num}" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA${ch_num}" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_SCAN_DATA_RDY_INT_IPL_IDX4/> </#if>
            </#if>
        </#if>
        <#if CONFIG_DRV_ADCHS_ANALOG_INPUT_ID_IDX5?has_content>
            <#assign ch_num = CONFIG_DRV_ADCHS_ANALOG_INPUT_ID_IDX5[8..]?number>
            <#if (ch_num > 11)>
               <#if CONFIG_DRV_ADCHS_SCAN_DATA_RDY_INTERRUPT_ENABLE_IDX5== true>
			   <@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA${ch_num}_VECTOR" ADCHS_ISR_SUFFIX="_DATA${ch_num}" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA${ch_num}" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_SCAN_DATA_RDY_INT_IPL_IDX5/> </#if>
            </#if>
        </#if>
        <#if CONFIG_DRV_ADCHS_ANALOG_INPUT_ID_IDX6?has_content>
            <#assign ch_num = CONFIG_DRV_ADCHS_ANALOG_INPUT_ID_IDX6[8..]?number>
            <#if (ch_num > 11)>
               <#if CONFIG_DRV_ADCHS_SCAN_DATA_RDY_INTERRUPT_ENABLE_IDX6 == true>
			   <@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA${ch_num}_VECTOR" ADCHS_ISR_SUFFIX="_DATA${ch_num}" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA${ch_num}" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_SCAN_DATA_RDY_INT_IPL_IDX6/> </#if>
            </#if>
        </#if>
        <#if CONFIG_DRV_ADCHS_ANALOG_INPUT_ID_IDX7?has_content>
            <#assign ch_num = CONFIG_DRV_ADCHS_ANALOG_INPUT_ID_IDX7[8..]?number>
            <#if (ch_num > 11)>
               <#if CONFIG_DRV_ADCHS_SCAN_DATA_RDY_INTERRUPT_ENABLE_IDX7 == true>
			   <@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA${ch_num}_VECTOR" ADCHS_ISR_SUFFIX="_DATA${ch_num}" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA${ch_num}" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_SCAN_DATA_RDY_INT_IPL_IDX7/> </#if>
            </#if>
        </#if>
        <#if CONFIG_DRV_ADCHS_ANALOG_INPUT_ID_IDX8?has_content>
            <#assign ch_num = CONFIG_DRV_ADCHS_ANALOG_INPUT_ID_IDX8[8..]?number>
            <#if (ch_num > 11)>
               <#if CONFIG_DRV_ADCHS_SCAN_DATA_RDY_INTERRUPT_ENABLE_IDX8 == true>
			   <@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA${ch_num}_VECTOR" ADCHS_ISR_SUFFIX="_DATA${ch_num}" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA${ch_num}" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_SCAN_DATA_RDY_INT_IPL_IDX8/> </#if>
            </#if>
        </#if>
        <#if CONFIG_DRV_ADCHS_ANALOG_INPUT_ID_IDX9?has_content>
            <#assign ch_num = CONFIG_DRV_ADCHS_ANALOG_INPUT_ID_IDX9[8..]?number>
            <#if (ch_num > 11)>
               <#if CONFIG_DRV_ADCHS_SCAN_DATA_RDY_INTERRUPT_ENABLE_IDX9 == true>
			   <@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA${ch_num}_VECTOR" ADCHS_ISR_SUFFIX="_DATA${ch_num}" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA${ch_num}" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_SCAN_DATA_RDY_INT_IPL_IDX9/> </#if>
            </#if>
        </#if>
        <#if CONFIG_DRV_ADCHS_ANALOG_INPUT_ID_IDX10?has_content>
            <#assign ch_num = CONFIG_DRV_ADCHS_ANALOG_INPUT_ID_IDX10[8..]?number>
            <#if (ch_num > 11)>
               <#if CONFIG_DRV_ADCHS_SCAN_DATA_RDY_INTERRUPT_ENABLE_IDX10 == true>
			   <@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA${ch_num}_VECTOR" ADCHS_ISR_SUFFIX="_DATA${ch_num}" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA${ch_num}" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_SCAN_DATA_RDY_INT_IPL_IDX10/> </#if>
            </#if>
        </#if>
        <#if CONFIG_DRV_ADCHS_ANALOG_INPUT_ID_IDX11?has_content>
            <#assign ch_num = CONFIG_DRV_ADCHS_ANALOG_INPUT_ID_IDX11[8..]?number>
            <#if (ch_num > 11)>
               <#if CONFIG_DRV_ADCHS_SCAN_DATA_RDY_INTERRUPT_ENABLE_IDX11 == true>
			   <@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA${ch_num}_VECTOR" ADCHS_ISR_SUFFIX="_DATA${ch_num}" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA${ch_num}" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_SCAN_DATA_RDY_INT_IPL_IDX11/> </#if>
            </#if>
        </#if>
        <#if CONFIG_DRV_ADCHS_ANALOG_INPUT_ID_IDX12?has_content>
            <#assign ch_num = CONFIG_DRV_ADCHS_ANALOG_INPUT_ID_IDX12[8..]?number>
            <#if (ch_num > 11)>
               <#if CONFIG_DRV_ADCHS_SCAN_DATA_RDY_INTERRUPT_ENABLE_IDX12 == true>
			   <@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA${ch_num}_VECTOR" ADCHS_ISR_SUFFIX="_DATA${ch_num}" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA${ch_num}" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_SCAN_DATA_RDY_INT_IPL_IDX12/> </#if>
            </#if>
        </#if>
        <#if CONFIG_DRV_ADCHS_ANALOG_INPUT_ID_IDX13?has_content>
            <#assign ch_num = CONFIG_DRV_ADCHS_ANALOG_INPUT_ID_IDX13[8..]?number>
            <#if (ch_num > 11)>
               <#if CONFIG_DRV_ADCHS_SCAN_DATA_RDY_INTERRUPT_ENABLE_IDX13 == true>
			   <@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA${ch_num}_VECTOR" ADCHS_ISR_SUFFIX="_DATA${ch_num}" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA${ch_num}" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_SCAN_DATA_RDY_INT_IPL_IDX13/> </#if>
            </#if>
        </#if>
        <#if CONFIG_DRV_ADCHS_ANALOG_INPUT_ID_IDX14?has_content>
            <#assign ch_num = CONFIG_DRV_ADCHS_ANALOG_INPUT_ID_IDX14[8..]?number>
            <#if (ch_num > 11)>
               <#if CONFIG_DRV_ADCHS_SCAN_DATA_RDY_INTERRUPT_ENABLE_IDX14 == true>
			   <@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA${ch_num}_VECTOR" ADCHS_ISR_SUFFIX="_DATA${ch_num}" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA${ch_num}" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_SCAN_DATA_RDY_INT_IPL_IDX14/> </#if>
            </#if>
        </#if>
        <#if CONFIG_DRV_ADCHS_ANALOG_INPUT_ID_IDX15?has_content>
            <#assign ch_num = CONFIG_DRV_ADCHS_ANALOG_INPUT_ID_IDX15[8..]?number>
            <#if (ch_num > 11)>
               <#if CONFIG_DRV_ADCHS_SCAN_DATA_RDY_INTERRUPT_ENABLE_IDX15 == true>
			   <@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA${ch_num}_VECTOR" ADCHS_ISR_SUFFIX="_DATA${ch_num}" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA${ch_num}" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_SCAN_DATA_RDY_INT_IPL_IDX15/> </#if>
            </#if>
        </#if>
        <#if CONFIG_DRV_ADCHS_ANALOG_INPUT_ID_IDX16?has_content>
            <#assign ch_num = CONFIG_DRV_ADCHS_ANALOG_INPUT_ID_IDX16[8..]?number>
            <#if (ch_num > 11)>
               <#if CONFIG_DRV_ADCHS_SCAN_DATA_RDY_INTERRUPT_ENABLE_IDX16 == true>
			   <@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA${ch_num}_VECTOR" ADCHS_ISR_SUFFIX="_DATA${ch_num}" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA${ch_num}" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_SCAN_DATA_RDY_INT_IPL_IDX16/> </#if>
            </#if>
        </#if>
        <#if CONFIG_DRV_ADCHS_ANALOG_INPUT_ID_IDX17?has_content>
            <#assign ch_num = CONFIG_DRV_ADCHS_ANALOG_INPUT_ID_IDX17[8..]?number>
            <#if (ch_num > 11)>
               <#if CONFIG_DRV_ADCHS_SCAN_DATA_RDY_INTERRUPT_ENABLE_IDX17 == true>
			   <@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA${ch_num}_VECTOR" ADCHS_ISR_SUFFIX="_DATA${ch_num}" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA${ch_num}" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_SCAN_DATA_RDY_INT_IPL_IDX17/> </#if>
            </#if>
        </#if>
        <#if CONFIG_DRV_ADCHS_ANALOG_INPUT_ID_IDX18?has_content>
            <#assign ch_num = CONFIG_DRV_ADCHS_ANALOG_INPUT_ID_IDX18[8..]?number>
            <#if (ch_num > 11)>
               <#if CONFIG_DRV_ADCHS_SCAN_DATA_RDY_INTERRUPT_ENABLE_IDX18 == true>
			   <@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA${ch_num}_VECTOR" ADCHS_ISR_SUFFIX="_DATA${ch_num}" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA${ch_num}" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_SCAN_DATA_RDY_INT_IPL_IDX18/> </#if>
            </#if>
        </#if>
        <#if CONFIG_DRV_ADCHS_ANALOG_INPUT_ID_IDX19?has_content>
            <#assign ch_num = CONFIG_DRV_ADCHS_ANALOG_INPUT_ID_IDX19[8..]?number>
            <#if (ch_num > 11)>
               <#if CONFIG_DRV_ADCHS_SCAN_DATA_RDY_INTERRUPT_ENABLE_IDX19 == true>
			   <@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA${ch_num}_VECTOR" ADCHS_ISR_SUFFIX="_DATA${ch_num}" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA${ch_num}" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_SCAN_DATA_RDY_INT_IPL_IDX19/> </#if>
            </#if>
        </#if>
        <#if CONFIG_DRV_ADCHS_ANALOG_INPUT_ID_IDX20?has_content>
            <#assign ch_num = CONFIG_DRV_ADCHS_ANALOG_INPUT_ID_IDX20[8..]?number>
            <#if (ch_num > 11)>
               <#if CONFIG_DRV_ADCHS_SCAN_DATA_RDY_INTERRUPT_ENABLE_IDX20 == true>
			   <@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA${ch_num}_VECTOR" ADCHS_ISR_SUFFIX="_DATA${ch_num}" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA${ch_num}" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_SCAN_DATA_RDY_INT_IPL_IDX20/> </#if>
            </#if>
        </#if>
        <#if CONFIG_DRV_ADCHS_ANALOG_INPUT_ID_IDX21?has_content>
            <#assign ch_num = CONFIG_DRV_ADCHS_ANALOG_INPUT_ID_IDX21[8..]?number>
            <#if (ch_num > 11)>
               <#if CONFIG_DRV_ADCHS_SCAN_DATA_RDY_INTERRUPT_ENABLE_IDX21 == true>
			   <@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA${ch_num}_VECTOR" ADCHS_ISR_SUFFIX="_DATA${ch_num}" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA${ch_num}" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_SCAN_DATA_RDY_INT_IPL_IDX21/> </#if>
            </#if>
        </#if>
        <#if CONFIG_DRV_ADCHS_ANALOG_INPUT_ID_IDX22?has_content>
            <#assign ch_num = CONFIG_DRV_ADCHS_ANALOG_INPUT_ID_IDX22[8..]?number>
            <#if (ch_num > 11)>
               <#if CONFIG_DRV_ADCHS_SCAN_DATA_RDY_INTERRUPT_ENABLE_IDX22 == true>
			   <@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA${ch_num}_VECTOR" ADCHS_ISR_SUFFIX="_DATA${ch_num}" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA${ch_num}" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_SCAN_DATA_RDY_INT_IPL_IDX22/> </#if>
            </#if>
        </#if>
        <#if CONFIG_DRV_ADCHS_ANALOG_INPUT_ID_IDX23?has_content>
            <#assign ch_num = CONFIG_DRV_ADCHS_ANALOG_INPUT_ID_IDX23[8..]?number>
            <#if (ch_num > 11)>
               <#if CONFIG_DRV_ADCHS_SCAN_DATA_RDY_INTERRUPT_ENABLE_IDX23 == true>
			   <@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA${ch_num}_VECTOR" ADCHS_ISR_SUFFIX="_DATA${ch_num}" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA${ch_num}" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_SCAN_DATA_RDY_INT_IPL_IDX23/> </#if>
            </#if>
        </#if>
        <#if CONFIG_DRV_ADCHS_ANALOG_INPUT_ID_IDX24?has_content>
            <#assign ch_num = CONFIG_DRV_ADCHS_ANALOG_INPUT_ID_IDX24[8..]?number>
            <#if (ch_num > 11)>
               <#if CONFIG_DRV_ADCHS_SCAN_DATA_RDY_INTERRUPT_ENABLE_IDX24 == true>
			   <@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA${ch_num}_VECTOR" ADCHS_ISR_SUFFIX="_DATA${ch_num}" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA${ch_num}" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_SCAN_DATA_RDY_INT_IPL_IDX24/> </#if>
            </#if>
        </#if>
        <#if CONFIG_DRV_ADCHS_ANALOG_INPUT_ID_IDX25?has_content>
            <#assign ch_num = CONFIG_DRV_ADCHS_ANALOG_INPUT_ID_IDX25[8..]?number>
            <#if (ch_num > 11)>
               <#if CONFIG_DRV_ADCHS_SCAN_DATA_RDY_INTERRUPT_ENABLE_IDX25 == true>
			   <@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA${ch_num}_VECTOR" ADCHS_ISR_SUFFIX="_DATA${ch_num}" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA${ch_num}" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_SCAN_DATA_RDY_INT_IPL_IDX25/> </#if>
            </#if>
        </#if>
        <#if CONFIG_DRV_ADCHS_ANALOG_INPUT_ID_IDX26?has_content>
            <#assign ch_num = CONFIG_DRV_ADCHS_ANALOG_INPUT_ID_IDX26[8..]?number>
            <#if (ch_num > 11)>
               <#if CONFIG_DRV_ADCHS_SCAN_DATA_RDY_INTERRUPT_ENABLE_IDX26 == true>
			   <@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA${ch_num}_VECTOR" ADCHS_ISR_SUFFIX="_DATA${ch_num}" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA${ch_num}" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_SCAN_DATA_RDY_INT_IPL_IDX26/> </#if>
            </#if>
        </#if>
        <#if CONFIG_DRV_ADCHS_ANALOG_INPUT_ID_IDX27?has_content>
            <#assign ch_num = CONFIG_DRV_ADCHS_ANALOG_INPUT_ID_IDX27[8..]?number>
            <#if (ch_num > 11)>
               <#if CONFIG_DRV_ADCHS_SCAN_DATA_RDY_INTERRUPT_ENABLE_IDX27 == true>
			   <@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA${ch_num}_VECTOR" ADCHS_ISR_SUFFIX="_DATA${ch_num}" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA${ch_num}" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_SCAN_DATA_RDY_INT_IPL_IDX27/> </#if>
            </#if>
        </#if>
        <#if CONFIG_DRV_ADCHS_ANALOG_INPUT_ID_IDX28?has_content>
            <#assign ch_num = CONFIG_DRV_ADCHS_ANALOG_INPUT_ID_IDX28[8..]?number>
            <#if (ch_num > 11)>
               <#if CONFIG_DRV_ADCHS_SCAN_DATA_RDY_INTERRUPT_ENABLE_IDX28 == true>
			   <@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA${ch_num}_VECTOR" ADCHS_ISR_SUFFIX="_DATA${ch_num}" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA${ch_num}" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_SCAN_DATA_RDY_INT_IPL_IDX28/> </#if>
            </#if>
        </#if>
        <#if CONFIG_DRV_ADCHS_ANALOG_INPUT_ID_IDX29?has_content>
            <#assign ch_num = CONFIG_DRV_ADCHS_ANALOG_INPUT_ID_IDX29[8..]?number>
            <#if (ch_num > 11)>
               <#if CONFIG_DRV_ADCHS_SCAN_DATA_RDY_INTERRUPT_ENABLE_IDX29 == true>
			   <@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA${ch_num}_VECTOR" ADCHS_ISR_SUFFIX="_DATA${ch_num}" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA${ch_num}" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_SCAN_DATA_RDY_INT_IPL_IDX29/> </#if>
            </#if>
        </#if>
        <#if CONFIG_DRV_ADCHS_ANALOG_INPUT_ID_IDX30?has_content>
            <#assign ch_num = CONFIG_DRV_ADCHS_ANALOG_INPUT_ID_IDX30[8..]?number>
            <#if (ch_num > 11)>
               <#if CONFIG_DRV_ADCHS_SCAN_DATA_RDY_INTERRUPT_ENABLE_IDX30 == true>
			   <@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA${ch_num}_VECTOR" ADCHS_ISR_SUFFIX="_DATA${ch_num}" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA${ch_num}" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_SCAN_DATA_RDY_INT_IPL_IDX30/> </#if>
            </#if>
        </#if>
        <#if CONFIG_DRV_ADCHS_ANALOG_INPUT_ID_IDX31?has_content>
            <#assign ch_num = CONFIG_DRV_ADCHS_ANALOG_INPUT_ID_IDX31[8..]?number>
            <#if (ch_num > 11)>
               <#if CONFIG_DRV_ADCHS_SCAN_DATA_RDY_INTERRUPT_ENABLE_IDX31 == true>
			   <@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA${ch_num}_VECTOR" ADCHS_ISR_SUFFIX="_DATA${ch_num}" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA${ch_num}" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_SCAN_DATA_RDY_INT_IPL_IDX31/> </#if>
            </#if>
        </#if>
        <#if CONFIG_DRV_ADCHS_ANALOG_INPUT_ID_IDX32?has_content>
            <#assign ch_num = CONFIG_DRV_ADCHS_ANALOG_INPUT_ID_IDX32[8..]?number>
            <#if (ch_num > 11)>
               <#if CONFIG_DRV_ADCHS_SCAN_DATA_RDY_INTERRUPT_ENABLE_IDX32 == true>
			   <@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA${ch_num}_VECTOR" ADCHS_ISR_SUFFIX="_DATA${ch_num}" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA${ch_num}" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_SCAN_DATA_RDY_INT_IPL_IDX32/> </#if>
            </#if>
        </#if>
        <#if CONFIG_DRV_ADCHS_ANALOG_INPUT_ID_IDX33?has_content>
            <#assign ch_num = CONFIG_DRV_ADCHS_ANALOG_INPUT_ID_IDX33[8..]?number>
            <#if (ch_num > 11)>
               <#if CONFIG_DRV_ADCHS_SCAN_DATA_RDY_INTERRUPT_ENABLE_IDX33 == true>
			   <@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA${ch_num}_VECTOR" ADCHS_ISR_SUFFIX="_DATA${ch_num}" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA${ch_num}" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_SCAN_DATA_RDY_INT_IPL_IDX33/> </#if>
            </#if>
        </#if>
        <#if CONFIG_DRV_ADCHS_ANALOG_INPUT_ID_IDX34?has_content>
            <#assign ch_num = CONFIG_DRV_ADCHS_ANALOG_INPUT_ID_IDX34[8..]?number>
            <#if (ch_num > 11)>
               <#if CONFIG_DRV_ADCHS_SCAN_DATA_RDY_INTERRUPT_ENABLE_IDX34 == true>
			   <@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA${ch_num}_VECTOR" ADCHS_ISR_SUFFIX="_DATA${ch_num}" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA${ch_num}" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_SCAN_DATA_RDY_INT_IPL_IDX34/> </#if>
            </#if>
        </#if>
        <#if CONFIG_DRV_ADCHS_ANALOG_INPUT_ID_IDX35?has_content>
            <#assign ch_num = CONFIG_DRV_ADCHS_ANALOG_INPUT_ID_IDX35[8..]?number>
            <#if (ch_num > 11)>
               <#if CONFIG_DRV_ADCHS_SCAN_DATA_RDY_INTERRUPT_ENABLE_IDX35 == true>
			   <@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA${ch_num}_VECTOR" ADCHS_ISR_SUFFIX="_DATA${ch_num}" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA${ch_num}" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_SCAN_DATA_RDY_INT_IPL_IDX35/> </#if>
            </#if>
        </#if>
        <#if CONFIG_DRV_ADCHS_ANALOG_INPUT_ID_IDX36?has_content>
            <#assign ch_num = CONFIG_DRV_ADCHS_ANALOG_INPUT_ID_IDX36[8..]?number>
            <#if (ch_num > 11)>
               <#if CONFIG_DRV_ADCHS_SCAN_DATA_RDY_INTERRUPT_ENABLE_IDX36 == true>
			   <@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA${ch_num}_VECTOR" ADCHS_ISR_SUFFIX="_DATA${ch_num}" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA${ch_num}" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_SCAN_DATA_RDY_INT_IPL_IDX36/> </#if>
            </#if>
        </#if>
        <#if CONFIG_DRV_ADCHS_ANALOG_INPUT_ID_IDX37?has_content>
            <#assign ch_num = CONFIG_DRV_ADCHS_ANALOG_INPUT_ID_IDX37[8..]?number>
            <#if (ch_num > 11)>
               <#if CONFIG_DRV_ADCHS_SCAN_DATA_RDY_INTERRUPT_ENABLE_IDX37 == true>
			   <@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA${ch_num}_VECTOR" ADCHS_ISR_SUFFIX="_DATA${ch_num}" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA${ch_num}" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_SCAN_DATA_RDY_INT_IPL_IDX37/> </#if>
            </#if>
        </#if>
        <#if CONFIG_DRV_ADCHS_ANALOG_INPUT_ID_IDX38?has_content>
            <#assign ch_num = CONFIG_DRV_ADCHS_ANALOG_INPUT_ID_IDX38[8..]?number>
            <#if (ch_num > 11)>
               <#if CONFIG_DRV_ADCHS_SCAN_DATA_RDY_INTERRUPT_ENABLE_IDX38 == true>
			   <@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA${ch_num}_VECTOR" ADCHS_ISR_SUFFIX="_DATA${ch_num}" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA${ch_num}" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_SCAN_DATA_RDY_INT_IPL_IDX38/> </#if>
            </#if>
        </#if>
        <#if CONFIG_DRV_ADCHS_ANALOG_INPUT_ID_IDX39?has_content>
            <#assign ch_num = CONFIG_DRV_ADCHS_ANALOG_INPUT_ID_IDX39[8..]?number>
            <#if (ch_num > 11)>
               <#if CONFIG_DRV_ADCHS_SCAN_DATA_RDY_INTERRUPT_ENABLE_IDX39 == true>
			   <@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA${ch_num}_VECTOR" ADCHS_ISR_SUFFIX="_DATA${ch_num}" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA${ch_num}" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_SCAN_DATA_RDY_INT_IPL_IDX39/> </#if>
            </#if>
        </#if>
        <#if CONFIG_DRV_ADCHS_ANALOG_INPUT_ID_IDX40?has_content>
            <#assign ch_num = CONFIG_DRV_ADCHS_ANALOG_INPUT_ID_IDX40[8..]?number>
            <#if (ch_num > 11)>
               <#if CONFIG_DRV_ADCHS_SCAN_DATA_RDY_INTERRUPT_ENABLE_IDX40 == true>
			   <@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA${ch_num}_VECTOR" ADCHS_ISR_SUFFIX="_DATA${ch_num}" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA${ch_num}" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_SCAN_DATA_RDY_INT_IPL_IDX40/> </#if>
            </#if>
        </#if>
        <#if CONFIG_DRV_ADCHS_ANALOG_INPUT_ID_IDX41?has_content>
            <#assign ch_num = CONFIG_DRV_ADCHS_ANALOG_INPUT_ID_IDX41[8..]?number>
            <#if (ch_num > 11)>
               <#if CONFIG_DRV_ADCHS_SCAN_DATA_RDY_INTERRUPT_ENABLE_IDX41 == true>
			   <@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA${ch_num}_VECTOR" ADCHS_ISR_SUFFIX="_DATA${ch_num}" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA${ch_num}" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_SCAN_DATA_RDY_INT_IPL_IDX41/> </#if>
            </#if>
        </#if>
        <#if CONFIG_DRV_ADCHS_ANALOG_INPUT_ID_IDX42?has_content>
            <#assign ch_num = CONFIG_DRV_ADCHS_ANALOG_INPUT_ID_IDX42[8..]?number>
            <#if (ch_num > 11)>
               <#if CONFIG_DRV_ADCHS_SCAN_DATA_RDY_INTERRUPT_ENABLE_IDX42 == true>
			   <@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA${ch_num}_VECTOR" ADCHS_ISR_SUFFIX="_DATA${ch_num}" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA${ch_num}" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_SCAN_DATA_RDY_INT_IPL_IDX42/> </#if>
            </#if>
        </#if>
        <#if CONFIG_DRV_ADCHS_ANALOG_INPUT_ID_IDX43?has_content>
            <#assign ch_num = CONFIG_DRV_ADCHS_ANALOG_INPUT_ID_IDX43[8..]?number>
            <#if (ch_num > 11)>
               <#if CONFIG_DRV_ADCHS_SCAN_DATA_RDY_INTERRUPT_ENABLE_IDX43 == true>
			   <@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA${ch_num}_VECTOR" ADCHS_ISR_SUFFIX="_DATA${ch_num}" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA${ch_num}" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_SCAN_DATA_RDY_INT_IPL_IDX43/> </#if>
            </#if>
        </#if>
        <#if CONFIG_DRV_ADCHS_ANALOG_INPUT_ID_IDX44?has_content>
            <#assign ch_num = CONFIG_DRV_ADCHS_ANALOG_INPUT_ID_IDX44[8..]?number>
            <#if (ch_num > 11)>
               <#if CONFIG_DRV_ADCHS_SCAN_DATA_RDY_INTERRUPT_ENABLE_IDX44 == true>
			   <@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID="_ADC_DATA${ch_num}_VECTOR" ADCHS_ISR_SUFFIX="_DATA${ch_num}" ADCHS_INT_SOURCE="INT_SOURCE_ADC_1_DATA${ch_num}" ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_SCAN_DATA_RDY_INT_IPL_IDX44/> </#if>
            </#if>
        </#if>
    <#else> <#-- if CONFIG_DRV_ADCHS_INDIVIDUAL_INTERRUPT_ENABLE == false -->
            <#lt>/* If individual interrupts are not enabled, all data interrupts are handled in this ISR */
            <#assign DRV_ADCHS_GLOBAL_DATA_VECTOR = "_ADC_VECTOR">
            <#assign DRV_ADCHS_GLOBAL_DATA_SOURCE = "INT_SOURCE_ADC_1">
            <@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID=DRV_ADCHS_GLOBAL_DATA_VECTOR ADCHS_ISR_SUFFIX="CommonData" ADCHS_INT_SOURCE=DRV_ADCHS_GLOBAL_DATA_SOURCE ADCHS_ISR_IPL = CONFIG_DRV_ADCHS_INT_IPL/>
    </#if>
    <#-- End of CONFIG_DRV_ADCHS_INDIVIDUAL_INTERRUPT_ENABLE -->
        <#-- Insert vectors for Digital Comparator and Digital Filter -->
        <#if CONFIG_DRV_ADCHS_DIGITAL_FILTER_INTERRUPT == true>
        <#if CONFIG_DRV_ADCHS_DIGITAL_FILTER_INST_IDX0 == true>
            <#assign filter_id = CONFIG_DRV_ADCHS_DIGITAL_FILTER_ID_IDX0[21..]?number>
            <#assign DRV_ADCHS_DIGITAL_FILTER_VECTOR = "_ADC_DF${filter_id}_VECTOR">
            <#assign DRV_ADCHS_DIGITAL_FILTER_SOURCE = "INT_SOURCE_ADC_1_DF${filter_id}">
            <@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID=DRV_ADCHS_DIGITAL_FILTER_VECTOR ADCHS_ISR_SUFFIX="_DF${filter_id}" ADCHS_INT_SOURCE=DRV_ADCHS_DIGITAL_FILTER_SOURCE/>
        </#if>
        <#if CONFIG_DRV_ADCHS_DIGITAL_FILTER_INST_IDX1 == true>
            <#assign filter_id = CONFIG_DRV_ADCHS_DIGITAL_FILTER_ID_IDX1[21..]?number>
            <#assign DRV_ADCHS_DIGITAL_FILTER_VECTOR = "_ADC_DF${filter_id}_VECTOR">
            <#assign DRV_ADCHS_DIGITAL_FILTER_SOURCE = "INT_SOURCE_ADC_1_DF${filter_id}">
            <@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID=DRV_ADCHS_DIGITAL_FILTER_VECTOR ADCHS_ISR_SUFFIX="_DF${filter_id}" ADCHS_INT_SOURCE=DRV_ADCHS_DIGITAL_FILTER_SOURCE/>
        </#if>
        <#if CONFIG_DRV_ADCHS_DIGITAL_FILTER_INST_IDX2 == true>
            <#assign filter_id = CONFIG_DRV_ADCHS_DIGITAL_FILTER_ID_IDX2[21..]?number>
            <#assign DRV_ADCHS_DIGITAL_FILTER_VECTOR = "_ADC_DF${filter_id}_VECTOR">
            <#assign DRV_ADCHS_DIGITAL_FILTER_SOURCE = "INT_SOURCE_ADC_1_DF${filter_id}">
            <@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID=DRV_ADCHS_DIGITAL_FILTER_VECTOR ADCHS_ISR_SUFFIX="_DF${filter_id}" ADCHS_INT_SOURCE=DRV_ADCHS_DIGITAL_FILTER_SOURCE/>
        </#if>
        <#if CONFIG_DRV_ADCHS_DIGITAL_FILTER_INST_IDX3 == true>
            <#assign filter_id = CONFIG_DRV_ADCHS_DIGITAL_FILTER_ID_IDX3[21..]?number>
            <#assign DRV_ADCHS_DIGITAL_FILTER_VECTOR = "_ADC_DF${filter_id}_VECTOR">
            <#assign DRV_ADCHS_DIGITAL_FILTER_SOURCE = "INT_SOURCE_ADC_1_DF${filter_id}">
            <@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID=DRV_ADCHS_DIGITAL_FILTER_VECTOR ADCHS_ISR_SUFFIX="_DF${filter_id}" ADCHS_INT_SOURCE=DRV_ADCHS_DIGITAL_FILTER_SOURCE/>
        </#if>
        <#if CONFIG_DRV_ADCHS_DIGITAL_FILTER_INST_IDX4 == true>
            <#assign filter_id = CONFIG_DRV_ADCHS_DIGITAL_FILTER_ID_IDX4[21..]?number>
            <#assign DRV_ADCHS_DIGITAL_FILTER_VECTOR = "_ADC_DF${filter_id}_VECTOR">
            <#assign DRV_ADCHS_DIGITAL_FILTER_SOURCE = "INT_SOURCE_ADC_1_DF${filter_id}">
            <@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID=DRV_ADCHS_DIGITAL_FILTER_VECTOR ADCHS_ISR_SUFFIX="_DF${filter_id}" ADCHS_INT_SOURCE=DRV_ADCHS_DIGITAL_FILTER_SOURCE/>
        </#if>
        <#if CONFIG_DRV_ADCHS_DIGITAL_FILTER_INST_IDX5 == true>
            <#assign filter_id = CONFIG_DRV_ADCHS_DIGITAL_FILTER_ID_IDX5[21..]?number>
            <#assign DRV_ADCHS_DIGITAL_FILTER_VECTOR = "_ADC_DF${filter_id}_VECTOR">
            <#assign DRV_ADCHS_DIGITAL_FILTER_SOURCE = "INT_SOURCE_ADC_1_DF${filter_id}">
            <@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID=DRV_ADCHS_DIGITAL_FILTER_VECTOR ADCHS_ISR_SUFFIX="_DF${filter_id}" ADCHS_INT_SOURCE=DRV_ADCHS_DIGITAL_FILTER_SOURCE/>
        </#if>
        </#if>
        <#if CONFIG_DRV_ADCHS_DIGITAL_COMPARATOR_INTERRUPT_EN == true>
        <#if CONFIG_DRV_ADCHS_DIGITAL_COMPARATOR_INST_IDX0 == true>
            <#assign comparator_id = CONFIG_DRV_ADCHS_DIGITAL_COMPARATOR_ID_IDX0[25..]?number>
            <#assign DRV_ADCHS_DIGITAL_COMP_VECTOR = "_ADC_DC${comparator_id}_VECTOR">
            <#assign DRV_ADCHS_DIGITAL_COMP_SOURCE = "INT_SOURCE_ADC_1_DC${comparator_id}">
            <@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID=DRV_ADCHS_DIGITAL_COMP_VECTOR ADCHS_ISR_SUFFIX="_DC${comparator_id}" ADCHS_INT_SOURCE=DRV_ADCHS_DIGITAL_COMP_SOURCE/>
        </#if>
        <#if CONFIG_DRV_ADCHS_DIGITAL_COMPARATOR_INST_IDX1 == true>
            <#assign comparator_id = CONFIG_DRV_ADCHS_DIGITAL_COMPARATOR_ID_IDX1[25..]?number>
            <#assign DRV_ADCHS_DIGITAL_COMP_VECTOR = "_ADC_DC${comparator_id}_VECTOR">
            <#assign DRV_ADCHS_DIGITAL_COMP_SOURCE = "INT_SOURCE_ADC_1_DC${comparator_id}">
            <@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID=DRV_ADCHS_DIGITAL_COMP_VECTOR ADCHS_ISR_SUFFIX="_DC${comparator_id}" ADCHS_INT_SOURCE=DRV_ADCHS_DIGITAL_COMP_SOURCE/>
        </#if>
        <#if CONFIG_DRV_ADCHS_DIGITAL_COMPARATOR_INST_IDX2 == true>
            <#assign comparator_id = CONFIG_DRV_ADCHS_DIGITAL_COMPARATOR_ID_IDX2[25..]?number>
            <#assign DRV_ADCHS_DIGITAL_COMP_VECTOR = "_ADC_DC${comparator_id}_VECTOR">
            <#assign DRV_ADCHS_DIGITAL_COMP_SOURCE = "INT_SOURCE_ADC_1_DC${comparator_id}">
            <@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID=DRV_ADCHS_DIGITAL_COMP_VECTOR ADCHS_ISR_SUFFIX="_DC${comparator_id}" ADCHS_INT_SOURCE=DRV_ADCHS_DIGITAL_COMP_SOURCE/>
        </#if>
        <#if CONFIG_DRV_ADCHS_DIGITAL_COMPARATOR_INST_IDX3 == true>
            <#assign comparator_id = CONFIG_DRV_ADCHS_DIGITAL_COMPARATOR_ID_IDX3[25..]?number>
            <#assign DRV_ADCHS_DIGITAL_COMP_VECTOR = "_ADC_DC${comparator_id}_VECTOR">
            <#assign DRV_ADCHS_DIGITAL_COMP_SOURCE = "INT_SOURCE_ADC_1_DC${comparator_id}">
            <@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID=DRV_ADCHS_DIGITAL_COMP_VECTOR ADCHS_ISR_SUFFIX="_DC${comparator_id}" ADCHS_INT_SOURCE=DRV_ADCHS_DIGITAL_COMP_SOURCE/>
        </#if>
        <#if CONFIG_DRV_ADCHS_DIGITAL_COMPARATOR_INST_IDX4 == true>
            <#assign comparator_id = CONFIG_DRV_ADCHS_DIGITAL_COMPARATOR_ID_IDX4[25..]?number>
            <#assign DRV_ADCHS_DIGITAL_COMP_VECTOR = "_ADC_DC${comparator_id}_VECTOR">
            <#assign DRV_ADCHS_DIGITAL_COMP_SOURCE = "INT_SOURCE_ADC_1_DC${comparator_id}">
            <@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID=DRV_ADCHS_DIGITAL_COMP_VECTOR ADCHS_ISR_SUFFIX="_DC${comparator_id}" ADCHS_INT_SOURCE=DRV_ADCHS_DIGITAL_COMP_SOURCE/>
        </#if>
        <#if CONFIG_DRV_ADCHS_DIGITAL_COMPARATOR_INST_IDX5 == true>
            <#assign comparator_id = CONFIG_DRV_ADCHS_DIGITAL_COMPARATOR_ID_IDX5[25..]?number>
            <#assign DRV_ADCHS_DIGITAL_COMP_VECTOR = "_ADC_DC${comparator_id}_VECTOR">
            <#assign DRV_ADCHS_DIGITAL_COMP_SOURCE = "INT_SOURCE_ADC_1_DC${comparator_id}">
            <@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID=DRV_ADCHS_DIGITAL_COMP_VECTOR ADCHS_ISR_SUFFIX="_DC${comparator_id}" ADCHS_INT_SOURCE=DRV_ADCHS_DIGITAL_COMP_SOURCE/>
        </#if>
        </#if>
        <#if CONFIG_USE_DRV_ADCHS_CVD == true>
            <#assign DRV_ADCHS_DIGITAL_COMP_VECTOR = "_ADC_DC1_VECTOR">
            <#assign DRV_ADCHS_DIGITAL_COMP_SOURCE = "INT_SOURCE_ADC_1_DC1">
            <@ADCHS_INDIVIDUAL_INT_HANDLER ADCHS_VECTOR_ID=DRV_ADCHS_DIGITAL_COMP_VECTOR ADCHS_ISR_SUFFIX="_DC1" ADCHS_INT_SOURCE=DRV_ADCHS_DIGITAL_COMP_SOURCE/>
        </#if>
</#if>
<#--
/*******************************************************************************
 End of File
*/
-->