<#--
/*******************************************************************************
  I2S Driver Freemarker Template File

  Company:
    Microchip Technology Inc.

  File Name:
    drv_i2s.ftl

  Summary:
    I2S Driver Freemarker Template File

  Description:

*******************************************************************************/

/*******************************************************************************
Copyright (c) 2014 released Microchip Technology Inc.  All rights reserved.

Microchip licenses to you the right to use, modify, copy and distribute
Software only when embedded on a Microchip microcontroller or digital signal
controller that is integrated into your product or third party product
(pursuant to the sublicense terms in the accompanying license agreement).

You should refer to the license agreement accompanying this Software for
additional information regarding your rights and obligations.

SOFTWARE AND DOCUMENTATION ARE PROVIDED AS IS  WITHOUT  WARRANTY  OF  ANY  KIND,
EITHER EXPRESS  OR  IMPLIED,  INCLUDING  WITHOUT  LIMITATION,  ANY  WARRANTY  OF
MERCHANTABILITY, TITLE, NON-INFRINGEMENT AND FITNESS FOR A  PARTICULAR  PURPOSE.
IN NO EVENT SHALL MICROCHIP OR  ITS  LICENSORS  BE  LIABLE  OR  OBLIGATED  UNDER
CONTRACT, NEGLIGENCE, STRICT LIABILITY, CONTRIBUTION,  BREACH  OF  WARRANTY,  OR
OTHER LEGAL  EQUITABLE  THEORY  ANY  DIRECT  OR  INDIRECT  DAMAGES  OR  EXPENSES
INCLUDING BUT NOT LIMITED TO ANY  INCIDENTAL,  SPECIAL,  INDIRECT,  PUNITIVE  OR
CONSEQUENTIAL DAMAGES, LOST  PROFITS  OR  LOST  DATA,  COST  OF  PROCUREMENT  OF
SUBSTITUTE  GOODS,  TECHNOLOGY,  SERVICES,  OR  ANY  CLAIMS  BY  THIRD   PARTIES
(INCLUDING BUT NOT LIMITED TO ANY DEFENSE  THEREOF),  OR  OTHER  SIMILAR  COSTS.
*******************************************************************************/
-->

/*** I2S Driver Configuration ***/


<#if CONFIG_USE_DRV_I2S ==  true>
<#if CONFIG_DRV_I2S_INTERRUPT_MODE == true || CONFIG_DRV_I2S_DMA_INTERRUPTS_ENABLE ==true>
#define DRV_I2S_INTERRUPT_MODE					true
<#else>
#define DRV_I2S_INTERRUPT_MODE					false
</#if>
#define DRV_I2S_CLIENTS_NUMBER					${CONFIG_DRV_I2S_CLIENTS_NUMBER}
#define DRV_I2S_INSTANCES_NUMBER				${CONFIG_DRV_I2S_INSTANCES_NUMBER}
<#if CONFIG_DRV_I2S_STOP_IN_IDLE == true>
#define DRV_I2S_STOP_IN_IDLE					true
<#else>
#define DRV_I2S_STOP_IN_IDLE					false
</#if>
<#assign i2sCombinedQueueSizeOfAllInstances = 0>
<#-- Instance 0 -->
<#if CONFIG_DRV_I2S_INST_IDX0 == true>
#define DRV_I2S_PERIPHERAL_ID_IDX0				${CONFIG_DRV_I2S_PERIPHERAL_ID_IDX0}
#define DRV_I2S_USAGE_MODE_IDX0					${CONFIG_DRV_I2S_USAGE_MODE_IDX0}
<#if CONFIG_DRV_I2S_STOP_IN_IDLE_IDX0 == true>
#define DRV_I2S_STOP_IN_IDLE_IDX0				true
<#else>
#define DRV_I2S_STOP_IN_IDLE_IDX0				false
</#if>
#define SPI_BAUD_RATE_CLK_IDX0					${CONFIG_SPI_BAUD_RATE_CLK_IDX0}
#define DRV_I2S_BAUD_RATE                       ${CONFIG_DRV_I2S_BAUD_RATE}
#define DRV_I2S_CLK_MODE_IDX0					${CONFIG_DRV_I2S_CLK_MODE_IDX0}
#define SPI_AUDIO_COMM_WIDTH_IDX0				${CONFIG_SPI_AUDIO_COMM_WIDTH_IDX0}
#define SPI_AUDIO_TRANSMIT_MODE_IDX0			${CONFIG_SPI_AUDIO_TRANSMIT_MODE_IDX0}
#define SPI_INPUT_SAMPLING_PHASE_IDX0			${CONFIG_SPI_INPUT_SAMPLING_PHASE_IDX0}
#define DRV_I2S_AUDIO_PROTOCOL_MODE_IDX0		${CONFIG_DRV_I2S_AUDIO_PROTOCOL_MODE_IDX0}
<#if CONFIG_DRV_I2S_DMA_INTERRUPTS_ENABLE == true>
#define DRV_I2S_TX_INT_SRC_IDX0					${CONFIG_DRV_I2S_TX_INT_SRC_IDX0}
#define DRV_I2S_RX_INT_SRC_IDX0					${CONFIG_DRV_I2S_RX_INT_SRC_IDX0}
</#if>
<#if CONFIG_DRV_I2S_INTERRUPT_MODE == true>
#define DRV_I2S_TX_INT_SRC_IDX0					${CONFIG_DRV_I2S_TX_INT_SRC_IDX0}
#define DRV_I2S_RX_INT_SRC_IDX0					${CONFIG_DRV_I2S_RX_INT_SRC_IDX0}
#define DRV_I2S_ERR_INT_SRC_IDX0				${CONFIG_DRV_I2S_ERR_INT_SRC_IDX0}
<#if CONFIG_PIC32MX == true>
#define DRV_I2S_ISR_VECTOR_IDX0					${CONFIG_DRV_I2S_ISR_VECTOR_IDX0}
#define DRV_I2S_INT_VECTOR_IDX0					${CONFIG_DRV_I2S_INT_VECTOR_IDX0}
#define DRV_I2S_INT_PRIORITY_IDX0				${CONFIG_DRV_I2S_INT_PRIORITY_IDX0}
#define DRV_I2S_INT_SUB_PRIORITY_IDX0			${CONFIG_DRV_I2S_INT_SUB_PRIORITY_IDX0}
<#else>
#define DRV_I2S_TX_INT_VECTOR_IDX0				${CONFIG_DRV_I2S_TX_INT_VECTOR_IDX0}
#define DRV_I2S_TX_INT_PRIORITY_IDX0			${CONFIG_DRV_I2S_TX_INT_PRIORITY_IDX0}
#define DRV_I2S_TX_INT_SUB_PRIORITY_IDX0		${CONFIG_DRV_I2S_TX_INT_SUB_PRIORITY_IDX0}
#define DRV_I2S_TX_ISR_VECTOR_IDX0				${CONFIG_DRV_I2S_TX_ISR_VECTOR_IDX0}
#define DRV_I2S_RX_INT_VECTOR_IDX0				${CONFIG_DRV_I2S_RX_INT_VECTOR_IDX0}
#define DRV_I2S_RX_INT_PRIORITY_IDX0			${CONFIG_DRV_I2S_RX_INT_PRIORITY_IDX0}
#define DRV_I2S_RX_INT_SUB_PRIORITY_IDX0		${CONFIG_DRV_I2S_RX_INT_SUB_PRIORITY_IDX0}
#define DRV_I2S_RX_ISR_VECTOR_IDX0				${CONFIG_DRV_I2S_RX_ISR_VECTOR_IDX0}
#define DRV_I2S_ERR_INT_VECTOR_IDX0				${CONFIG_DRV_I2S_ERR_INT_VECTOR_IDX0}
#define DRV_I2S_ERR_INT_PRIORITY_IDX0			${CONFIG_DRV_I2S_ERR_INT_PRIORITY_IDX0}
#define DRV_I2S_ERR_INT_SUB_PRIORITY_IDX0		${CONFIG_DRV_I2S_ERR_INT_SUB_PRIORITY_IDX0}
#define DRV_I2S_ERR_ISR_VECTOR_IDX0				${CONFIG_DRV_I2S_ERR_ISR_VECTOR_IDX0}
</#if>
</#if> 
#define QUEUE_SIZE_TX_IDX0                      ${CONFIG_QUEUE_SIZE_TX_IDX0}
#define QUEUE_SIZE_RX_IDX0                      ${CONFIG_QUEUE_SIZE_RX_IDX0}
<#assign i2sCombinedQueueSizeOfAllInstances = i2sCombinedQueueSizeOfAllInstances + CONFIG_QUEUE_SIZE_TX_IDX0?number >
<#assign i2sCombinedQueueSizeOfAllInstances = i2sCombinedQueueSizeOfAllInstances + CONFIG_QUEUE_SIZE_RX_IDX0?number>
<#if CONFIG_DRV_I2S_SUPPORT_TRANSMIT_DMA == true>
<#if CONFIG_DRV_I2S_TX_DMA_CHANNEL_IDX0 == "0">
#define DRV_I2S_TX_DMA_CHANNEL_IDX0				${CONFIG_SYS_DMA_CHANNEL_ID_IDX0}
<#assign DRV_I2S_TX_DMA_CHANNEL_INT_SRC_IDX0 = CONFIG_SYS_DMA_CHANNEL_ID_IDX0> 
</#if>
<#if CONFIG_DRV_I2S_TX_DMA_CHANNEL_IDX0 == "1">
#define DRV_I2S_TX_DMA_CHANNEL_IDX0				${CONFIG_SYS_DMA_CHANNEL_ID_IDX1}
<#assign DRV_I2S_TX_DMA_CHANNEL_INT_SRC_IDX0 = CONFIG_SYS_DMA_CHANNEL_ID_IDX1> 
</#if>
<#if CONFIG_DRV_I2S_TX_DMA_CHANNEL_IDX0 == "2">
#define DRV_I2S_TX_DMA_CHANNEL_IDX0				${CONFIG_SYS_DMA_CHANNEL_ID_IDX2}
<#assign DRV_I2S_TX_DMA_CHANNEL_INT_SRC_IDX0 = CONFIG_SYS_DMA_CHANNEL_ID_IDX2> 
</#if>
<#if CONFIG_DRV_I2S_TX_DMA_CHANNEL_IDX0 == "3">
#define DRV_I2S_TX_DMA_CHANNEL_IDX0				${CONFIG_SYS_DMA_CHANNEL_ID_IDX3}
<#assign DRV_I2S_TX_DMA_CHANNEL_INT_SRC_IDX0 = CONFIG_SYS_DMA_CHANNEL_ID_IDX3> 
</#if>
<#if CONFIG_DRV_I2S_TX_DMA_CHANNEL_IDX0 == "4">
#define DRV_I2S_TX_DMA_CHANNEL_IDX0				${CONFIG_SYS_DMA_CHANNEL_ID_IDX4}
<#assign DRV_I2S_TX_DMA_CHANNEL_INT_SRC_IDX0 = CONFIG_SYS_DMA_CHANNEL_ID_IDX4> 
</#if>
<#if CONFIG_DRV_I2S_TX_DMA_CHANNEL_IDX0 == "5">
#define DRV_I2S_TX_DMA_CHANNEL_IDX0				${CONFIG_SYS_DMA_CHANNEL_ID_IDX5}
<#assign DRV_I2S_TX_DMA_CHANNEL_INT_SRC_IDX0 = CONFIG_SYS_DMA_CHANNEL_ID_IDX5> 
</#if>
<#if CONFIG_DRV_I2S_TX_DMA_CHANNEL_IDX0 == "6">
#define DRV_I2S_TX_DMA_CHANNEL_IDX0				${CONFIG_SYS_DMA_CHANNEL_ID_IDX6}
<#assign DRV_I2S_TX_DMA_CHANNEL_INT_SRC_IDX0 = CONFIG_SYS_DMA_CHANNEL_ID_IDX6> 
</#if>
<#if CONFIG_DRV_I2S_TX_DMA_CHANNEL_IDX0 == "7">
#define DRV_I2S_TX_DMA_CHANNEL_IDX0				${CONFIG_SYS_DMA_CHANNEL_ID_IDX7}
<#assign DRV_I2S_TX_DMA_CHANNEL_INT_SRC_IDX0 = CONFIG_SYS_DMA_CHANNEL_ID_IDX7> 
</#if>
<#if CONFIG_DRV_I2S_DMA_USE_CHANNEL_CHAINING == true>
<#if CONFIG_DRV_I2S_TX_DMA_CHAINING_CHANNEL_IDX0 == "0">
#define DRV_I2S_TX_DMA_CHAINING_CHANNEL_IDX0    ${CONFIG_SYS_DMA_CHANNEL_ID_IDX0}
<#assign DRV_I2S_TX_DMA_CHAINING_CHANNEL_INT_SRC_IDX0 = CONFIG_SYS_DMA_CHANNEL_ID_IDX0> 
</#if>
<#if CONFIG_DRV_I2S_TX_DMA_CHAINING_CHANNEL_IDX0 == "1">
#define DRV_I2S_TX_DMA_CHAINING_CHANNEL_IDX0    ${CONFIG_SYS_DMA_CHANNEL_ID_IDX1}
<#assign DRV_I2S_TX_DMA_CHAINING_CHANNEL_INT_SRC_IDX0 = CONFIG_SYS_DMA_CHANNEL_ID_IDX1> 
</#if>
<#if CONFIG_DRV_I2S_TX_DMA_CHAINING_CHANNEL_IDX0 == "2">
#define DRV_I2S_TX_DMA_CHAINING_CHANNEL_IDX0    ${CONFIG_SYS_DMA_CHANNEL_ID_IDX2}
<#assign DRV_I2S_TX_DMA_CHAINING_CHANNEL_INT_SRC_IDX0 = CONFIG_SYS_DMA_CHANNEL_ID_IDX2> 
</#if>
<#if CONFIG_DRV_I2S_TX_DMA_CHAINING_CHANNEL_IDX0 == "3">
#define DRV_I2S_TX_DMA_CHAINING_CHANNEL_IDX0    ${CONFIG_SYS_DMA_CHANNEL_ID_IDX3}
<#assign DRV_I2S_TX_DMA_CHAINING_CHANNEL_INT_SRC_IDX0 = CONFIG_SYS_DMA_CHANNEL_ID_IDX3> 
</#if>
<#if CONFIG_DRV_I2S_TX_DMA_CHAINING_CHANNEL_IDX0 == "4">
#define DRV_I2S_TX_DMA_CHAINING_CHANNEL_IDX0	${CONFIG_SYS_DMA_CHANNEL_ID_IDX4}
<#assign DRV_I2S_TX_DMA_CHAINING_CHANNEL_INT_SRC_IDX0 = CONFIG_SYS_DMA_CHANNEL_ID_IDX4> 
</#if>
<#if CONFIG_DRV_I2S_TX_DMA_CHAINING_CHANNEL_IDX0 == "5">
#define DRV_I2S_TX_DMA_CHAINING_CHANNEL_IDX0	${CONFIG_SYS_DMA_CHANNEL_ID_IDX5}
<#assign DRV_I2S_TX_DMA_CHAINING_CHANNEL_INT_SRC_IDX0 = CONFIG_SYS_DMA_CHANNEL_ID_IDX5> 
</#if>
<#if CONFIG_DRV_I2S_TX_DMA_CHAINING_CHANNEL_IDX0 == "6">
#define DRV_I2S_TX_DMA_CHAINING_CHANNEL_IDX0	${CONFIG_SYS_DMA_CHANNEL_ID_IDX6}
<#assign DRV_I2S_TX_DMA_CHAINING_CHANNEL_INT_SRC_IDX0 = CONFIG_SYS_DMA_CHANNEL_ID_IDX6> 
</#if>
<#if CONFIG_DRV_I2S_TX_DMA_CHAINING_CHANNEL_IDX0 == "7">
#define DRV_I2S_TX_DMA_CHAINING_CHANNEL_IDX0	${CONFIG_SYS_DMA_CHANNEL_ID_IDX7}
<#assign DRV_I2S_TX_DMA_CHAINING_CHANNEL_INT_SRC_IDX0 = CONFIG_SYS_DMA_CHANNEL_ID_IDX7> 
</#if>
</#if>
<#if CONFIG_DRV_I2S_DMA_INTERRUPTS_ENABLE == true>
<#if DRV_I2S_TX_DMA_CHANNEL_INT_SRC_IDX0 == "DMA_CHANNEL_0">
#define DRV_I2S_TX_DMA_SOURCE_IDX0				INT_SOURCE_DMA_0
</#if>
<#if DRV_I2S_TX_DMA_CHANNEL_INT_SRC_IDX0 == "DMA_CHANNEL_1">
#define DRV_I2S_TX_DMA_SOURCE_IDX0				INT_SOURCE_DMA_1
</#if>
<#if DRV_I2S_TX_DMA_CHANNEL_INT_SRC_IDX0 == "DMA_CHANNEL_2">
#define DRV_I2S_TX_DMA_SOURCE_IDX0				INT_SOURCE_DMA_2
</#if>
<#if DRV_I2S_TX_DMA_CHANNEL_INT_SRC_IDX0 == "DMA_CHANNEL_3">
#define DRV_I2S_TX_DMA_SOURCE_IDX0				INT_SOURCE_DMA_3
</#if>
<#if DRV_I2S_TX_DMA_CHANNEL_INT_SRC_IDX0 == "DMA_CHANNEL_4">
#define DRV_I2S_TX_DMA_SOURCE_IDX0				INT_SOURCE_DMA_4
</#if>
<#if DRV_I2S_TX_DMA_CHANNEL_INT_SRC_IDX0 == "DMA_CHANNEL_5">
#define DRV_I2S_TX_DMA_SOURCE_IDX0				INT_SOURCE_DMA_5
</#if>
<#if DRV_I2S_TX_DMA_CHANNEL_INT_SRC_IDX0 == "DMA_CHANNEL_6">
#define DRV_I2S_TX_DMA_SOURCE_IDX0				INT_SOURCE_DMA_6
</#if>
<#if DRV_I2S_TX_DMA_CHANNEL_INT_SRC_IDX0 == "DMA_CHANNEL_7">
#define DRV_I2S_TX_DMA_SOURCE_IDX0				INT_SOURCE_DMA_7
</#if>
<#if CONFIG_DRV_I2S_DMA_USE_CHANNEL_CHAINING == true>
<#if DRV_I2S_TX_DMA_CHAINING_CHANNEL_INT_SRC_IDX0 == "DMA_CHANNEL_0">
#define DRV_I2S_TX_DMA_CHAINING_SOURCE_IDX0     INT_SOURCE_DMA_0
</#if>
<#if DRV_I2S_TX_DMA_CHAINING_CHANNEL_INT_SRC_IDX0 == "DMA_CHANNEL_1">
#define DRV_I2S_TX_DMA_CHAINING_SOURCE_IDX0		INT_SOURCE_DMA_1
</#if>
<#if DRV_I2S_TX_DMA_CHAINING_CHANNEL_INT_SRC_IDX0 == "DMA_CHANNEL_2">
#define DRV_I2S_TX_DMA_CHAINING_SOURCE_IDX0		INT_SOURCE_DMA_2
</#if>
<#if DRV_I2S_TX_DMA_CHAINING_CHANNEL_INT_SRC_IDX0 == "DMA_CHANNEL_3">
#define DRV_I2S_TX_DMA_CHAINING_SOURCE_IDX0		INT_SOURCE_DMA_3
</#if>
<#if DRV_I2S_TX_DMA_CHAINING_CHANNEL_INT_SRC_IDX0 == "DMA_CHANNEL_4">
#define DRV_I2S_TX_DMA_CHAINING_SOURCE_IDX0		INT_SOURCE_DMA_4
</#if>
<#if DRV_I2S_TX_DMA_CHAINING_CHANNEL_INT_SRC_IDX0 == "DMA_CHANNEL_5">
#define DRV_I2S_TX_DMA_CHAINING_SOURCE_IDX0		INT_SOURCE_DMA_5
</#if>
<#if DRV_I2S_TX_DMA_CHAINING_CHANNEL_INT_SRC_IDX0 == "DMA_CHANNEL_6">
#define DRV_I2S_TX_DMA_CHAINING_SOURCE_IDX0		INT_SOURCE_DMA_6
</#if>
<#if DRV_I2S_TX_DMA_CHAINING_CHANNEL_INT_SRC_IDX0 == "DMA_CHANNEL_7">
#define DRV_I2S_TX_DMA_CHAINING_SOURCE_IDX0		INT_SOURCE_DMA_7
</#if>
</#if>
</#if>
</#if>
<#if CONFIG_DRV_I2S_SUPPORT_RECEIVE_DMA == true>
<#if CONFIG_DRV_I2S_RX_DMA_CHANNEL_IDX0 == "0">
#define DRV_I2S_RX_DMA_CHANNEL_IDX0				${CONFIG_SYS_DMA_CHANNEL_ID_IDX0}
<#assign DRV_I2S_RX_DMA_CHANNEL_INT_SRC_IDX0 = CONFIG_SYS_DMA_CHANNEL_ID_IDX0> 
</#if>
<#if CONFIG_DRV_I2S_RX_DMA_CHANNEL_IDX0 == "1">
#define DRV_I2S_RX_DMA_CHANNEL_IDX0				${CONFIG_SYS_DMA_CHANNEL_ID_IDX1}
<#assign DRV_I2S_RX_DMA_CHANNEL_INT_SRC_IDX0 = CONFIG_SYS_DMA_CHANNEL_ID_IDX1> 
</#if>
<#if CONFIG_DRV_I2S_RX_DMA_CHANNEL_IDX0 == "2">
#define DRV_I2S_RX_DMA_CHANNEL_IDX0				${CONFIG_SYS_DMA_CHANNEL_ID_IDX2}
<#assign DRV_I2S_RX_DMA_CHANNEL_INT_SRC_IDX0 = CONFIG_SYS_DMA_CHANNEL_ID_IDX2> 
</#if>
<#if CONFIG_DRV_I2S_RX_DMA_CHANNEL_IDX0 == "3">
#define DRV_I2S_RX_DMA_CHANNEL_IDX0				${CONFIG_SYS_DMA_CHANNEL_ID_IDX3}
<#assign DRV_I2S_RX_DMA_CHANNEL_INT_SRC_IDX0 = CONFIG_SYS_DMA_CHANNEL_ID_IDX3> 
</#if>
<#if CONFIG_DRV_I2S_RX_DMA_CHANNEL_IDX0 == "4">
#define DRV_I2S_RX_DMA_CHANNEL_IDX0				${CONFIG_SYS_DMA_CHANNEL_ID_IDX4}
<#assign DRV_I2S_RX_DMA_CHANNEL_INT_SRC_IDX0 = CONFIG_SYS_DMA_CHANNEL_ID_IDX4> 
</#if>
<#if CONFIG_DRV_I2S_RX_DMA_CHANNEL_IDX0 == "5">
#define DRV_I2S_RX_DMA_CHANNEL_IDX0				${CONFIG_SYS_DMA_CHANNEL_ID_IDX5}
<#assign DRV_I2S_RX_DMA_CHANNEL_INT_SRC_IDX0 = CONFIG_SYS_DMA_CHANNEL_ID_IDX5> 
</#if>
<#if CONFIG_DRV_I2S_RX_DMA_CHANNEL_IDX0 == "6">
#define DRV_I2S_RX_DMA_CHANNEL_IDX0				${CONFIG_SYS_DMA_CHANNEL_ID_IDX6}
<#assign DRV_I2S_RX_DMA_CHANNEL_INT_SRC_IDX0 = CONFIG_SYS_DMA_CHANNEL_ID_IDX6> 
</#if>
<#if CONFIG_DRV_I2S_RX_DMA_CHANNEL_IDX0 == "7">
#define DRV_I2S_RX_DMA_CHANNEL_IDX0				${CONFIG_SYS_DMA_CHANNEL_ID_IDX7}
<#assign DRV_I2S_RX_DMA_CHANNEL_INT_SRC_IDX0 = CONFIG_SYS_DMA_CHANNEL_ID_IDX7> 
</#if>
<#if CONFIG_DRV_I2S_DMA_USE_CHANNEL_CHAINING == true>
<#if CONFIG_DRV_I2S_RX_DMA_CHAINING_CHANNEL_IDX0 == "0">
#define DRV_I2S_RX_DMA_CHAINING_CHANNEL_IDX0	${CONFIG_SYS_DMA_CHANNEL_ID_IDX0}
<#assign DRV_I2S_RX_DMA_CHAINING_CHANNEL_INT_SRC_IDX0 = CONFIG_SYS_DMA_CHANNEL_ID_IDX0> 
</#if>
<#if CONFIG_DRV_I2S_RX_DMA_CHAINING_CHANNEL_IDX0 == "1">
#define DRV_I2S_RX_DMA_CHAINING_CHANNEL_IDX0	${CONFIG_SYS_DMA_CHANNEL_ID_IDX1}
<#assign DRV_I2S_RX_DMA_CHAINING_CHANNEL_INT_SRC_IDX0 = CONFIG_SYS_DMA_CHANNEL_ID_IDX1> 
</#if>
<#if CONFIG_DRV_I2S_RX_DMA_CHAINING_CHANNEL_IDX0 == "2">
#define DRV_I2S_RX_DMA_CHAINING_CHANNEL_IDX0	${CONFIG_SYS_DMA_CHANNEL_ID_IDX2}
<#assign DRV_I2S_RX_DMA_CHAINING_CHANNEL_INT_SRC_IDX0 = CONFIG_SYS_DMA_CHANNEL_ID_IDX2> 
</#if>
<#if CONFIG_DRV_I2S_RX_DMA_CHAINING_CHANNEL_IDX0 == "3">
#define DRV_I2S_RX_DMA_CHAINING_CHANNEL_IDX0	${CONFIG_SYS_DMA_CHANNEL_ID_IDX3}
<#assign DRV_I2S_RX_DMA_CHAINING_CHANNEL_INT_SRC_IDX0 = CONFIG_SYS_DMA_CHANNEL_ID_IDX3> 
</#if>
<#if CONFIG_DRV_I2S_RX_DMA_CHAINING_CHANNEL_IDX0 == "4">
#define DRV_I2S_RX_DMA_CHAINING_CHANNEL_IDX0	${CONFIG_SYS_DMA_CHANNEL_ID_IDX4}
<#assign DRV_I2S_RX_DMA_CHAINING_CHANNEL_INT_SRC_IDX0 = CONFIG_SYS_DMA_CHANNEL_ID_IDX4> 
</#if>
<#if CONFIG_DRV_I2S_RX_DMA_CHAINING_CHANNEL_IDX0 == "5">
#define DRV_I2S_RX_DMA_CHAINING_CHANNEL_IDX0	${CONFIG_SYS_DMA_CHANNEL_ID_IDX5}
<#assign DRV_I2S_RX_DMA_CHAINING_CHANNEL_INT_SRC_IDX0 = CONFIG_SYS_DMA_CHANNEL_ID_IDX5> 
</#if>
<#if CONFIG_DRV_I2S_RX_DMA_CHAINING_CHANNEL_IDX0 == "6">
#define DRV_I2S_RX_DMA_CHAINING_CHANNEL_IDX0	${CONFIG_SYS_DMA_CHANNEL_ID_IDX6}
<#assign DRV_I2S_RX_DMA_CHAINING_CHANNEL_INT_SRC_IDX0 = CONFIG_SYS_DMA_CHANNEL_ID_IDX6> 
</#if>
<#if CONFIG_DRV_I2S_RX_DMA_CHAINING_CHANNEL_IDX0 == "7">
#define DRV_I2S_RX_DMA_CHAINING_CHANNEL_IDX0	${CONFIG_SYS_DMA_CHANNEL_ID_IDX7}
<#assign DRV_I2S_RX_DMA_CHAINING_CHANNEL_INT_SRC_IDX0 = CONFIG_SYS_DMA_CHANNEL_ID_IDX7> 
</#if>
</#if>
<#if CONFIG_DRV_I2S_DMA_INTERRUPTS_ENABLE == true>
<#if DRV_I2S_RX_DMA_CHANNEL_INT_SRC_IDX0 == "DMA_CHANNEL_0">
#define DRV_I2S_RX_DMA_SOURCE_IDX0				INT_SOURCE_DMA_0
</#if>
<#if DRV_I2S_RX_DMA_CHANNEL_INT_SRC_IDX0 == "DMA_CHANNEL_1">
#define DRV_I2S_RX_DMA_SOURCE_IDX0				INT_SOURCE_DMA_1
</#if>
<#if DRV_I2S_RX_DMA_CHANNEL_INT_SRC_IDX0 == "DMA_CHANNEL_2">
#define DRV_I2S_RX_DMA_SOURCE_IDX0				INT_SOURCE_DMA_2
</#if>
<#if DRV_I2S_RX_DMA_CHANNEL_INT_SRC_IDX0 == "DMA_CHANNEL_3">
#define DRV_I2S_RX_DMA_SOURCE_IDX0				INT_SOURCE_DMA_3
</#if>
<#if DRV_I2S_RX_DMA_CHANNEL_INT_SRC_IDX0 == "DMA_CHANNEL_4">
#define DRV_I2S_RX_DMA_SOURCE_IDX0				INT_SOURCE_DMA_4
</#if>
<#if DRV_I2S_RX_DMA_CHANNEL_INT_SRC_IDX0 == "DMA_CHANNEL_5">
#define DRV_I2S_RX_DMA_SOURCE_IDX0				INT_SOURCE_DMA_5
</#if>
<#if DRV_I2S_RX_DMA_CHANNEL_INT_SRC_IDX0 == "DMA_CHANNEL_6">
#define DRV_I2S_RX_DMA_SOURCE_IDX0				INT_SOURCE_DMA_6
</#if>
<#if DRV_I2S_RX_DMA_CHANNEL_INT_SRC_IDX0 == "DMA_CHANNEL_7">
#define DRV_I2S_RX_DMA_SOURCE_IDX0				INT_SOURCE_DMA_7
</#if>
<#if CONFIG_DRV_I2S_DMA_USE_CHANNEL_CHAINING == true>
<#if DRV_I2S_RX_DMA_CHAINING_CHANNEL_INT_SRC_IDX0 == "DMA_CHANNEL_0">
#define DRV_I2S_RX_DMA_CHAINING_SOURCE_IDX0		INT_SOURCE_DMA_0
</#if>
<#if DRV_I2S_RX_DMA_CHAINING_CHANNEL_INT_SRC_IDX0 == "DMA_CHANNEL_1">
#define DRV_I2S_RX_DMA_CHAINING_SOURCE_IDX0		INT_SOURCE_DMA_1
</#if>
<#if DRV_I2S_RX_DMA_CHAINING_CHANNEL_INT_SRC_IDX0 == "DMA_CHANNEL_2">
#define DRV_I2S_RX_DMA_CHAINING_SOURCE_IDX0		INT_SOURCE_DMA_2
</#if>
<#if DRV_I2S_RX_DMA_CHAINING_CHANNEL_INT_SRC_IDX0 == "DMA_CHANNEL_3">
#define DRV_I2S_RX_DMA_CHAINING_SOURCE_IDX0		INT_SOURCE_DMA_3
</#if>
<#if DRV_I2S_RX_DMA_CHAINING_CHANNEL_INT_SRC_IDX0 == "DMA_CHANNEL_4">
#define DRV_I2S_RX_DMA_CHAINING_SOURCE_IDX0		INT_SOURCE_DMA_4
</#if>
<#if DRV_I2S_RX_DMA_CHAINING_CHANNEL_INT_SRC_IDX0 == "DMA_CHANNEL_5">
#define DRV_I2S_RX_DMA_CHAINING_SOURCE_IDX0		INT_SOURCE_DMA_5
</#if>
<#if DRV_I2S_RX_DMA_CHAINING_CHANNEL_INT_SRC_IDX0 == "DMA_CHANNEL_6">
#define DRV_I2S_RX_DMA_CHAINING_SOURCE_IDX0		INT_SOURCE_DMA_6
</#if>
<#if DRV_I2S_RX_DMA_CHAINING_CHANNEL_INT_SRC_IDX0 == "DMA_CHANNEL_7">
#define DRV_I2S_RX_DMA_CHAINING_SOURCE_IDX0		INT_SOURCE_DMA_7
</#if>
</#if>
</#if>
</#if>
#define DRV_I2S_POWER_STATE_IDX0				${CONFIG_DRV_I2S_POWER_STATE_IDX0}
</#if>
<#-- Instance 1 -->
<#if CONFIG_DRV_I2S_INST_IDX1 == true>
#define DRV_I2S_PERIPHERAL_ID_IDX1		  		${CONFIG_DRV_I2S_PERIPHERAL_ID_IDX1}
#define DRV_I2S_USAGE_MODE_IDX1			  		${CONFIG_DRV_I2S_USAGE_MODE_IDX1}
<#if CONFIG_DRV_I2S_STOP_IN_IDLE_IDX1 == true>
#define DRV_I2S_STOP_IN_IDLE_IDX1		  		true
#else
#define DRV_I2S_STOP_IN_IDLE_IDX1		  		false
</#if>
#define SPI_BAUD_RATE_CLK_IDX1			  		${CONFIG_SPI_BAUD_RATE_CLK_IDX1}
#define BAUD_RATE_IDX1                          ${CONFIG_DRV_I2S_BAUD_RATE}
#define DRV_I2S_CLK_MODE_IDX1			  		${CONFIG_DRV_I2S_CLK_MODE_IDX1}
#define SPI_AUDIO_COMM_WIDTH_IDX1		  		${CONFIG_SPI_AUDIO_COMM_WIDTH_IDX1}
#define SPI_AUDIO_TRANSMIT_MODE_IDX1		  	${CONFIG_SPI_AUDIO_TRANSMIT_MODE_IDX1}
#define SPI_INPUT_SAMPLING_PHASE_IDX1		  	${CONFIG_SPI_INPUT_SAMPLING_PHASE_IDX1}
#define DRV_I2S_AUDIO_PROTOCOL_MODE_IDX1        ${CONFIG_DRV_I2S_AUDIO_PROTOCOL_MODE_IDX1}
<#if CONFIG_DRV_I2S_DMA_INTERRUPTS_ENABLE == true>
#define DRV_I2S_TX_INT_SRC_IDX1					${CONFIG_DRV_I2S_TX_INT_SRC_IDX1}
#define DRV_I2S_RX_INT_SRC_IDX1					${CONFIG_DRV_I2S_RX_INT_SRC_IDX1}
</#if>
<#if CONFIG_DRV_I2S_INTERRUPT_MODE == true>
#define DRV_I2S_TX_INT_SRC_IDX1					${CONFIG_DRV_I2S_TX_INT_SRC_IDX1}
#define DRV_I2S_RX_INT_SRC_IDX1					${CONFIG_DRV_I2S_RX_INT_SRC_IDX1}
#define DRV_I2S_ERR_INT_SRC_IDX1				${CONFIG_DRV_I2S_ERR_INT_SRC_IDX1}
<#if CONFIG_PIC32MX == true>
#define DRV_I2S_ISR_VECTOR_IDX1					${CONFIG_DRV_I2S_ISR_VECTOR_IDX1}
#define DRV_I2S_INT_VECTOR_IDX1					${CONFIG_DRV_I2S_INT_VECTOR_IDX1}
#define DRV_I2S_INT_PRIORITY_IDX1				${CONFIG_DRV_I2S_INT_PRIORITY_IDX1}
#define DRV_I2S_INT_SUB_PRIORITY_IDX1			${CONFIG_DRV_I2S_INT_SUB_PRIORITY_IDX1}
<#else>
#define DRV_I2S_TX_INT_VECTOR_IDX1				${CONFIG_DRV_I2S_TX_INT_VECTOR_IDX1}
#define DRV_I2S_TX_INT_PRIORITY_IDX1			${CONFIG_DRV_I2S_TX_INT_PRIORITY_IDX1}
#define DRV_I2S_TX_INT_SUB_PRIORITY_IDX1		${CONFIG_DRV_I2S_TX_INT_SUB_PRIORITY_IDX1}
#define DRV_I2S_TX_ISR_VECTOR_IDX1				${CONFIG_DRV_I2S_TX_ISR_VECTOR_IDX1}
#define DRV_I2S_RX_INT_VECTOR_IDX1				${CONFIG_DRV_I2S_RX_INT_VECTOR_IDX1}
#define DRV_I2S_RX_INT_PRIORITY_IDX1			${CONFIG_DRV_I2S_RX_INT_PRIORITY_IDX1}
#define DRV_I2S_RX_INT_SUB_PRIORITY_IDX1		${CONFIG_DRV_I2S_RX_INT_SUB_PRIORITY_IDX1}
#define DRV_I2S_RX_ISR_VECTOR_IDX1				${CONFIG_DRV_I2S_RX_ISR_VECTOR_IDX1}
#define DRV_I2S_ERR_INT_VECTOR_IDX1				${CONFIG_DRV_I2S_ERR_INT_VECTOR_IDX1}
#define DRV_I2S_ERR_INT_PRIORITY_IDX1			${CONFIG_DRV_I2S_ERR_INT_PRIORITY_IDX1}
#define DRV_I2S_ERR_INT_SUB_PRIORITY_IDX1		${CONFIG_DRV_I2S_ERR_INT_SUB_PRIORITY_IDX1}
#define DRV_I2S_ERR_ISR_VECTOR_IDX1				${CONFIG_DRV_I2S_ERR_ISR_VECTOR_IDX1}
</#if>
</#if> 
#define QUEUE_SIZE_TX_IDX1                      ${CONFIG_QUEUE_SIZE_TX_IDX1}
#define QUEUE_SIZE_RX_IDX1                      ${CONFIG_QUEUE_SIZE_RX_IDX1}
<#assign i2sCombinedQueueSizeOfAllInstances = i2sCombinedQueueSizeOfAllInstances + CONFIG_QUEUE_SIZE_TX_IDX1?number >
<#assign i2sCombinedQueueSizeOfAllInstances = i2sCombinedQueueSizeOfAllInstances + CONFIG_QUEUE_SIZE_RX_IDX1?number>
<#if CONFIG_DRV_I2S_SUPPORT_TRANSMIT_DMA == true>
<#if CONFIG_DRV_I2S_TX_DMA_CHANNEL_IDX1 == "0">
#define DRV_I2S_TX_DMA_CHANNEL_IDX1				${CONFIG_SYS_DMA_CHANNEL_ID_IDX0}
<#assign DRV_I2S_TX_DMA_CHANNEL_INT_SRC_IDX1 = CONFIG_SYS_DMA_CHANNEL_ID_IDX0> 
</#if>
<#if CONFIG_DRV_I2S_TX_DMA_CHANNEL_IDX1 == "1">
#define DRV_I2S_TX_DMA_CHANNEL_IDX1				${CONFIG_SYS_DMA_CHANNEL_ID_IDX1}
<#assign DRV_I2S_TX_DMA_CHANNEL_INT_SRC_IDX1 = CONFIG_SYS_DMA_CHANNEL_ID_IDX1> 
</#if>
<#if CONFIG_DRV_I2S_TX_DMA_CHANNEL_IDX1 == "2">
#define DRV_I2S_TX_DMA_CHANNEL_IDX1				${CONFIG_SYS_DMA_CHANNEL_ID_IDX2}
<#assign DRV_I2S_TX_DMA_CHANNEL_INT_SRC_IDX1 = CONFIG_SYS_DMA_CHANNEL_ID_IDX2> 
</#if>
<#if CONFIG_DRV_I2S_TX_DMA_CHANNEL_IDX1 == "3">
#define DRV_I2S_TX_DMA_CHANNEL_IDX1				${CONFIG_SYS_DMA_CHANNEL_ID_IDX3}
<#assign DRV_I2S_TX_DMA_CHANNEL_INT_SRC_IDX1 = CONFIG_SYS_DMA_CHANNEL_ID_IDX3> 
</#if>
<#if CONFIG_DRV_I2S_TX_DMA_CHANNEL_IDX1 == "4">
#define DRV_I2S_TX_DMA_CHANNEL_IDX1				${CONFIG_SYS_DMA_CHANNEL_ID_IDX4}
<#assign DRV_I2S_TX_DMA_CHANNEL_INT_SRC_IDX1 = CONFIG_SYS_DMA_CHANNEL_ID_IDX4> 
</#if>
<#if CONFIG_DRV_I2S_TX_DMA_CHANNEL_IDX1 == "5">
#define DRV_I2S_TX_DMA_CHANNEL_IDX1				${CONFIG_SYS_DMA_CHANNEL_ID_IDX5}
<#assign DRV_I2S_TX_DMA_CHANNEL_INT_SRC_IDX1 = CONFIG_SYS_DMA_CHANNEL_ID_IDX5> 
</#if>
<#if CONFIG_DRV_I2S_TX_DMA_CHANNEL_IDX1 == "6">
#define DRV_I2S_TX_DMA_CHANNEL_IDX1				${CONFIG_SYS_DMA_CHANNEL_ID_IDX6}
<#assign DRV_I2S_TX_DMA_CHANNEL_INT_SRC_IDX1 = CONFIG_SYS_DMA_CHANNEL_ID_IDX6> 
</#if>
<#if CONFIG_DRV_I2S_TX_DMA_CHANNEL_IDX1 == "7">
#define DRV_I2S_TX_DMA_CHANNEL_IDX1				${CONFIG_SYS_DMA_CHANNEL_ID_IDX7}
<#assign DRV_I2S_TX_DMA_CHANNEL_INT_SRC_IDX1 = CONFIG_SYS_DMA_CHANNEL_ID_IDX7> 
</#if>
<#if CONFIG_DRV_I2S_DMA_USE_CHANNEL_CHAINING == true>
<#if CONFIG_DRV_I2S_TX_DMA_CHAINING_CHANNEL_IDX1 == "0">
#define DRV_I2S_TX_DMA_CHAINING_CHANNEL_IDX1	${CONFIG_SYS_DMA_CHANNEL_ID_IDX0}
<#assign DRV_I2S_TX_DMA_CHAINING_CHANNEL_INT_SRC_IDX1 = CONFIG_SYS_DMA_CHANNEL_ID_IDX0> 
</#if>
<#if CONFIG_DRV_I2S_TX_DMA_CHAINING_CHANNEL_IDX1 == "1">
#define DRV_I2S_TX_DMA_CHAINING_CHANNEL_IDX1	${CONFIG_SYS_DMA_CHANNEL_ID_IDX1}
<#assign DRV_I2S_TX_DMA_CHAINING_CHANNEL_INT_SRC_IDX1 = CONFIG_SYS_DMA_CHANNEL_ID_IDX1> 
</#if>
<#if CONFIG_DRV_I2S_TX_DMA_CHAINING_CHANNEL_IDX1 == "2">
#define DRV_I2S_TX_DMA_CHAINING_CHANNEL_IDX1	${CONFIG_SYS_DMA_CHANNEL_ID_IDX2}
<#assign DRV_I2S_TX_DMA_CHAINING_CHANNEL_INT_SRC_IDX1 = CONFIG_SYS_DMA_CHANNEL_ID_IDX2> 
</#if>
<#if CONFIG_DRV_I2S_TX_DMA_CHAINING_CHANNEL_IDX1 == "3">
#define DRV_I2S_TX_DMA_CHAINING_CHANNEL_IDX1	${CONFIG_SYS_DMA_CHANNEL_ID_IDX3}
<#assign DRV_I2S_TX_DMA_CHAINING_CHANNEL_INT_SRC_IDX1 = CONFIG_SYS_DMA_CHANNEL_ID_IDX3> 
</#if>
<#if CONFIG_DRV_I2S_TX_DMA_CHAINING_CHANNEL_IDX1 == "4">
#define DRV_I2S_TX_DMA_CHAINING_CHANNEL_IDX1	${CONFIG_SYS_DMA_CHANNEL_ID_IDX4}
<#assign DRV_I2S_TX_DMA_CHAINING_CHANNEL_INT_SRC_IDX1 = CONFIG_SYS_DMA_CHANNEL_ID_IDX4> 
</#if>
<#if CONFIG_DRV_I2S_TX_DMA_CHAINING_CHANNEL_IDX1 == "5">
#define DRV_I2S_TX_DMA_CHAINING_CHANNEL_IDX1	${CONFIG_SYS_DMA_CHANNEL_ID_IDX5}
<#assign DRV_I2S_TX_DMA_CHAINING_CHANNEL_INT_SRC_IDX1 = CONFIG_SYS_DMA_CHANNEL_ID_IDX5> 
</#if>
<#if CONFIG_DRV_I2S_TX_DMA_CHAINING_CHANNEL_IDX1 == "6">
#define DRV_I2S_TX_DMA_CHAINING_CHANNEL_IDX1	${CONFIG_SYS_DMA_CHANNEL_ID_IDX6}
<#assign DRV_I2S_TX_DMA_CHAINING_CHANNEL_INT_SRC_IDX1 = CONFIG_SYS_DMA_CHANNEL_ID_IDX6> 
</#if>
<#if CONFIG_DRV_I2S_TX_DMA_CHAINING_CHANNEL_IDX1 == "7">
#define DRV_I2S_TX_DMA_CHAINING_CHANNEL_IDX1	${CONFIG_SYS_DMA_CHANNEL_ID_IDX7}
<#assign DRV_I2S_TX_DMA_CHAINING_CHANNEL_INT_SRC_IDX1 = CONFIG_SYS_DMA_CHANNEL_ID_IDX7> 
</#if>
</#if>
<#if CONFIG_DRV_I2S_DMA_INTERRUPTS_ENABLE == true>
<#if DRV_I2S_TX_DMA_CHANNEL_INT_SRC_IDX1 == "DMA_CHANNEL_0">
#define DRV_I2S_TX_DMA_SOURCE_IDX1				INT_SOURCE_DMA_0
</#if>
<#if DRV_I2S_TX_DMA_CHANNEL_INT_SRC_IDX1 == "DMA_CHANNEL_1">
#define DRV_I2S_TX_DMA_SOURCE_IDX1				INT_SOURCE_DMA_1
</#if>
<#if DRV_I2S_TX_DMA_CHANNEL_INT_SRC_IDX1 == "DMA_CHANNEL_2">
#define DRV_I2S_TX_DMA_SOURCE_IDX1				INT_SOURCE_DMA_2
</#if>
<#if DRV_I2S_TX_DMA_CHANNEL_INT_SRC_IDX1 == "DMA_CHANNEL_3">
#define DRV_I2S_TX_DMA_SOURCE_IDX1				INT_SOURCE_DMA_3
</#if>
<#if DRV_I2S_TX_DMA_CHANNEL_INT_SRC_IDX1 == "DMA_CHANNEL_4">
#define DRV_I2S_TX_DMA_SOURCE_IDX1				INT_SOURCE_DMA_4
</#if>
<#if DRV_I2S_TX_DMA_CHANNEL_INT_SRC_IDX1 == "DMA_CHANNEL_5">
#define DRV_I2S_TX_DMA_SOURCE_IDX1				INT_SOURCE_DMA_5
</#if>
<#if DRV_I2S_TX_DMA_CHANNEL_INT_SRC_IDX1 == "DMA_CHANNEL_6">
#define DRV_I2S_TX_DMA_SOURCE_IDX1				INT_SOURCE_DMA_6
</#if>
<#if DRV_I2S_TX_DMA_CHANNEL_INT_SRC_IDX1 == "DMA_CHANNEL_7">
#define DRV_I2S_TX_DMA_SOURCE_IDX1				INT_SOURCE_DMA_7
</#if>
<#if CONFIG_DRV_I2S_DMA_USE_CHANNEL_CHAINING == true>
<#if DRV_I2S_TX_DMA_CHAINING_CHANNEL_INT_SRC_IDX1 == "DMA_CHANNEL_0">
#define DRV_I2S_TX_DMA_CHAINING_SOURCE_IDX1		INT_SOURCE_DMA_0
</#if>
<#if DRV_I2S_TX_DMA_CHAINING_CHANNEL_INT_SRC_IDX1 == "DMA_CHANNEL_1">
#define DRV_I2S_TX_DMA_CHAINING_SOURCE_IDX1		INT_SOURCE_DMA_1
</#if>
<#if DRV_I2S_TX_DMA_CHAINING_CHANNEL_INT_SRC_IDX1 == "DMA_CHANNEL_2">
#define DRV_I2S_TX_DMA_CHAINING_SOURCE_IDX1		INT_SOURCE_DMA_2
</#if>
<#if DRV_I2S_TX_DMA_CHAINING_CHANNEL_INT_SRC_IDX1 == "DMA_CHANNEL_3">
#define DRV_I2S_TX_DMA_CHAINING_SOURCE_IDX1		INT_SOURCE_DMA_3
</#if>
<#if DRV_I2S_TX_DMA_CHAINING_CHANNEL_INT_SRC_IDX1 == "DMA_CHANNEL_4">
#define DRV_I2S_TX_DMA_CHAINING_SOURCE_IDX1		INT_SOURCE_DMA_4
</#if>
<#if DRV_I2S_TX_DMA_CHAINING_CHANNEL_INT_SRC_IDX1 == "DMA_CHANNEL_5">
#define DRV_I2S_TX_DMA_CHAINING_SOURCE_IDX1		INT_SOURCE_DMA_5
</#if>
<#if DRV_I2S_TX_DMA_CHAINING_CHANNEL_INT_SRC_IDX1 == "DMA_CHANNEL_6">
#define DRV_I2S_TX_DMA_CHAINING_SOURCE_IDX1		INT_SOURCE_DMA_6
</#if>
<#if DRV_I2S_TX_DMA_CHAINING_CHANNEL_INT_SRC_IDX1 == "DMA_CHANNEL_7">
#define DRV_I2S_TX_DMA_CHAINING_SOURCE_IDX1		INT_SOURCE_DMA_7
</#if>
</#if>
</#if>
</#if>
<#if CONFIG_DRV_I2S_SUPPORT_RECEIVE_DMA == true>
<#if CONFIG_DRV_I2S_RX_DMA_CHANNEL_IDX1 == "0">
#define DRV_I2S_RX_DMA_CHANNEL_IDX1				${CONFIG_SYS_DMA_CHANNEL_ID_IDX0}
<#assign DRV_I2S_RX_DMA_CHANNEL_INT_SRC_IDX1 = CONFIG_SYS_DMA_CHANNEL_ID_IDX0> 
</#if>
<#if CONFIG_DRV_I2S_RX_DMA_CHANNEL_IDX1 == "1">
#define DRV_I2S_RX_DMA_CHANNEL_IDX1				${CONFIG_SYS_DMA_CHANNEL_ID_IDX1}
<#assign DRV_I2S_RX_DMA_CHANNEL_INT_SRC_IDX1 = CONFIG_SYS_DMA_CHANNEL_ID_IDX1> 
</#if>
<#if CONFIG_DRV_I2S_RX_DMA_CHANNEL_IDX1 == "2">
#define DRV_I2S_RX_DMA_CHANNEL_IDX1				${CONFIG_SYS_DMA_CHANNEL_ID_IDX2}
<#assign DRV_I2S_RX_DMA_CHANNEL_INT_SRC_IDX1 = CONFIG_SYS_DMA_CHANNEL_ID_IDX2> 
</#if>
<#if CONFIG_DRV_I2S_RX_DMA_CHANNEL_IDX1 == "3">
#define DRV_I2S_RX_DMA_CHANNEL_IDX1				${CONFIG_SYS_DMA_CHANNEL_ID_IDX3}
<#assign DRV_I2S_RX_DMA_CHANNEL_INT_SRC_IDX1 = CONFIG_SYS_DMA_CHANNEL_ID_IDX3> 
</#if>
<#if CONFIG_DRV_I2S_RX_DMA_CHANNEL_IDX1 == "4">
#define DRV_I2S_RX_DMA_CHANNEL_IDX1				${CONFIG_SYS_DMA_CHANNEL_ID_IDX4}
<#assign DRV_I2S_RX_DMA_CHANNEL_INT_SRC_IDX1 = CONFIG_SYS_DMA_CHANNEL_ID_IDX4> 
</#if>
<#if CONFIG_DRV_I2S_RX_DMA_CHANNEL_IDX1 == "5">
#define DRV_I2S_RX_DMA_CHANNEL_IDX1				${CONFIG_SYS_DMA_CHANNEL_ID_IDX5}
<#assign DRV_I2S_RX_DMA_CHANNEL_INT_SRC_IDX1 = CONFIG_SYS_DMA_CHANNEL_ID_IDX5> 
</#if>
<#if CONFIG_DRV_I2S_RX_DMA_CHANNEL_IDX1 == "6">
#define DRV_I2S_RX_DMA_CHANNEL_IDX1				${CONFIG_SYS_DMA_CHANNEL_ID_IDX6}
<#assign DRV_I2S_RX_DMA_CHANNEL_INT_SRC_IDX1 = CONFIG_SYS_DMA_CHANNEL_ID_IDX6> 
</#if>
<#if CONFIG_DRV_I2S_RX_DMA_CHANNEL_IDX1 == "7">
#define DRV_I2S_RX_DMA_CHANNEL_IDX1				${CONFIG_SYS_DMA_CHANNEL_ID_IDX7}
<#assign DRV_I2S_RX_DMA_CHANNEL_INT_SRC_IDX1 = CONFIG_SYS_DMA_CHANNEL_ID_IDX7> 
</#if>
<#if CONFIG_DRV_I2S_DMA_USE_CHANNEL_CHAINING == true>
<#if CONFIG_DRV_I2S_RX_DMA_CHAINING_CHANNEL_IDX1 == "0">
#define DRV_I2S_RX_DMA_CHAINING_CHANNEL_IDX1	${CONFIG_SYS_DMA_CHANNEL_ID_IDX0}
<#assign DRV_I2S_RX_DMA_CHAINING_CHANNEL_INT_SRC_IDX1 = CONFIG_SYS_DMA_CHANNEL_ID_IDX0> 
</#if>
<#if CONFIG_DRV_I2S_RX_DMA_CHAINING_CHANNEL_IDX1 == "1">
#define DRV_I2S_RX_DMA_CHAINING_CHANNEL_IDX1	${CONFIG_SYS_DMA_CHANNEL_ID_IDX1}
<#assign DRV_I2S_RX_DMA_CHAINING_CHANNEL_INT_SRC_IDX1 = CONFIG_SYS_DMA_CHANNEL_ID_IDX1> 
</#if>
<#if CONFIG_DRV_I2S_RX_DMA_CHAINING_CHANNEL_IDX1 == "2">
#define DRV_I2S_RX_DMA_CHAINING_CHANNEL_IDX1	${CONFIG_SYS_DMA_CHANNEL_ID_IDX2}
<#assign DRV_I2S_RX_DMA_CHAINING_CHANNEL_INT_SRC_IDX1 = CONFIG_SYS_DMA_CHANNEL_ID_IDX2> 
</#if>
<#if CONFIG_DRV_I2S_RX_DMA_CHAINING_CHANNEL_IDX1 == "3">
#define DRV_I2S_RX_DMA_CHAINING_CHANNEL_IDX1	${CONFIG_SYS_DMA_CHANNEL_ID_IDX3}
<#assign DRV_I2S_RX_DMA_CHAINING_CHANNEL_INT_SRC_IDX1 = CONFIG_SYS_DMA_CHANNEL_ID_IDX3> 
</#if>
<#if CONFIG_DRV_I2S_RX_DMA_CHAINING_CHANNEL_IDX1 == "4">
#define DRV_I2S_RX_DMA_CHAINING_CHANNEL_IDX1	${CONFIG_SYS_DMA_CHANNEL_ID_IDX4}
<#assign DRV_I2S_RX_DMA_CHAINING_CHANNEL_INT_SRC_IDX1 = CONFIG_SYS_DMA_CHANNEL_ID_IDX4> 
</#if>
<#if CONFIG_DRV_I2S_RX_DMA_CHAINING_CHANNEL_IDX1 == "5">
#define DRV_I2S_RX_DMA_CHAINING_CHANNEL_IDX1	${CONFIG_SYS_DMA_CHANNEL_ID_IDX5}
<#assign DRV_I2S_RX_DMA_CHAINING_CHANNEL_INT_SRC_IDX1 = CONFIG_SYS_DMA_CHANNEL_ID_IDX5> 
</#if>
<#if CONFIG_DRV_I2S_RX_DMA_CHAINING_CHANNEL_IDX1 == "6">
#define DRV_I2S_RX_DMA_CHAINING_CHANNEL_IDX1	${CONFIG_SYS_DMA_CHANNEL_ID_IDX6}
<#assign DRV_I2S_RX_DMA_CHAINING_CHANNEL_INT_SRC_IDX1 = CONFIG_SYS_DMA_CHANNEL_ID_IDX6> 
</#if>
<#if CONFIG_DRV_I2S_RX_DMA_CHAINING_CHANNEL_IDX1 == "7">
#define DRV_I2S_RX_DMA_CHAINING_CHANNEL_IDX1	${CONFIG_SYS_DMA_CHANNEL_ID_IDX7}
<#assign DRV_I2S_RX_DMA_CHAINING_CHANNEL_INT_SRC_IDX1 = CONFIG_SYS_DMA_CHANNEL_ID_IDX7> 
</#if>
</#if>
<#if CONFIG_DRV_I2S_DMA_INTERRUPTS_ENABLE == true>
<#if DRV_I2S_RX_DMA_CHANNEL_INT_SRC_IDX1 == "DMA_CHANNEL_0">
#define DRV_I2S_RX_DMA_SOURCE_IDX1				INT_SOURCE_DMA_0
</#if>
<#if DRV_I2S_RX_DMA_CHANNEL_INT_SRC_IDX1 == "DMA_CHANNEL_1">
#define DRV_I2S_RX_DMA_SOURCE_IDX1				INT_SOURCE_DMA_1
</#if>
<#if DRV_I2S_RX_DMA_CHANNEL_INT_SRC_IDX1 == "DMA_CHANNEL_2">
#define DRV_I2S_RX_DMA_SOURCE_IDX1				INT_SOURCE_DMA_2
</#if>
<#if DRV_I2S_RX_DMA_CHANNEL_INT_SRC_IDX1 == "DMA_CHANNEL_3">
#define DRV_I2S_RX_DMA_SOURCE_IDX1				INT_SOURCE_DMA_3
</#if>
<#if DRV_I2S_RX_DMA_CHANNEL_INT_SRC_IDX1 == "DMA_CHANNEL_4">
#define DRV_I2S_RX_DMA_SOURCE_IDX1				INT_SOURCE_DMA_4
</#if>
<#if DRV_I2S_RX_DMA_CHANNEL_INT_SRC_IDX1 == "DMA_CHANNEL_5">
#define DRV_I2S_RX_DMA_SOURCE_IDX1				INT_SOURCE_DMA_5
</#if>
<#if DRV_I2S_RX_DMA_CHANNEL_INT_SRC_IDX1 == "DMA_CHANNEL_6">
#define DRV_I2S_RX_DMA_SOURCE_IDX1				INT_SOURCE_DMA_6
</#if>
<#if DRV_I2S_RX_DMA_CHANNEL_INT_SRC_IDX1 == "DMA_CHANNEL_7">
#define DRV_I2S_RX_DMA_SOURCE_IDX1				INT_SOURCE_DMA_7
</#if>
<#if CONFIG_DRV_I2S_DMA_USE_CHANNEL_CHAINING == true>
<#if DRV_I2S_RX_DMA_CHAINING_CHANNEL_INT_SRC_IDX1 == "DMA_CHANNEL_0">
#define DRV_I2S_RX_DMA_CHAINING_SOURCE_IDX1		INT_SOURCE_DMA_0
</#if>
<#if DRV_I2S_RX_DMA_CHAINING_CHANNEL_INT_SRC_IDX1 == "DMA_CHANNEL_1">
#define DRV_I2S_RX_DMA_CHAINING_SOURCE_IDX1		INT_SOURCE_DMA_1
</#if>
<#if DRV_I2S_RX_DMA_CHAINING_CHANNEL_INT_SRC_IDX1 == "DMA_CHANNEL_2">
#define DRV_I2S_RX_DMA_CHAINING_SOURCE_IDX1		INT_SOURCE_DMA_2
</#if>
<#if DRV_I2S_RX_DMA_CHAINING_CHANNEL_INT_SRC_IDX1 == "DMA_CHANNEL_3">
#define DRV_I2S_RX_DMA_CHAINING_SOURCE_IDX1		INT_SOURCE_DMA_3
</#if>
<#if DRV_I2S_RX_DMA_CHAINING_CHANNEL_INT_SRC_IDX1 == "DMA_CHANNEL_4">
#define DRV_I2S_RX_DMA_CHAINING_SOURCE_IDX1		INT_SOURCE_DMA_4
</#if>
<#if DRV_I2S_RX_DMA_CHAINING_CHANNEL_INT_SRC_IDX1 == "DMA_CHANNEL_5">
#define DRV_I2S_RX_DMA_CHAINING_SOURCE_IDX1		INT_SOURCE_DMA_5
</#if>
<#if DRV_I2S_RX_DMA_CHAINING_CHANNEL_INT_SRC_IDX1 == "DMA_CHANNEL_6">
#define DRV_I2S_RX_DMA_CHAINING_SOURCE_IDX1		INT_SOURCE_DMA_6
</#if>
<#if DRV_I2S_RX_DMA_CHAINING_CHANNEL_INT_SRC_IDX1 == "DMA_CHANNEL_7">
#define DRV_I2S_RX_DMA_CHAINING_SOURCE_IDX1		INT_SOURCE_DMA_7
</#if>
</#if>
</#if>
</#if>
#define DRV_I2S_POWER_STATE_IDX1				${CONFIG_DRV_I2S_POWER_STATE_IDX1}
</#if>
<#-- Instance 2 -->
<#if CONFIG_DRV_I2S_INST_IDX2 == true>
#define DRV_I2S_PERIPHERAL_ID_IDX2				${CONFIG_DRV_I2S_PERIPHERAL_ID_IDX2}
#define DRV_I2S_USAGE_MODE_IDX2					${CONFIG_DRV_I2S_USAGE_MODE_IDX2}
<#if CONFIG_DRV_I2S_STOP_IN_IDLE_IDX2 == true>
#define DRV_I2S_STOP_IN_IDLE_IDX2				true
#else
#define DRV_I2S_STOP_IN_IDLE_IDX2				false
</#if>
#define SPI_BAUD_RATE_CLK_IDX2					${CONFIG_SPI_BAUD_RATE_CLK_IDX2}
#define BAUD_RATE_IDX2                          ${CONFIG_DRV_I2S_BAUD_RATE}
#define DRV_I2S_CLK_MODE_IDX2					${CONFIG_DRV_I2S_CLK_MODE_IDX2}
#define SPI_AUDIO_COMM_WIDTH_IDX2				${CONFIG_SPI_AUDIO_COMM_WIDTH_IDX2}
#define SPI_AUDIO_TRANSMIT_MODE_IDX2			${CONFIG_SPI_AUDIO_TRANSMIT_MODE_IDX2}
#define SPI_INPUT_SAMPLING_PHASE_IDX2			${CONFIG_SPI_INPUT_SAMPLING_PHASE_IDX2}
#define DRV_I2S_AUDIO_PROTOCOL_MODE_IDX2        ${CONFIG_DRV_I2S_AUDIO_PROTOCOL_MODE_IDX2}
<#if CONFIG_DRV_I2S_DMA_INTERRUPTS_ENABLE == true>
#define DRV_I2S_TX_INT_SRC_IDX2					${CONFIG_DRV_I2S_TX_INT_SRC_IDX2}
#define DRV_I2S_RX_INT_SRC_IDX2					${CONFIG_DRV_I2S_RX_INT_SRC_IDX2}
</#if>
<#if CONFIG_DRV_I2S_INTERRUPT_MODE == true>
#define DRV_I2S_TX_INT_SRC_IDX2					${CONFIG_DRV_I2S_TX_INT_SRC_IDX2}
#define DRV_I2S_RX_INT_SRC_IDX2					${CONFIG_DRV_I2S_RX_INT_SRC_IDX2}
#define DRV_I2S_ERR_INT_SRC_IDX2				${CONFIG_DRV_I2S_ERR_INT_SRC_IDX2}
<#if CONFIG_PIC32MX == true>
#define DRV_I2S_ISR_VECTOR_IDX2					${CONFIG_DRV_I2S_ISR_VECTOR_IDX2}
#define DRV_I2S_INT_VECTOR_IDX2					${CONFIG_DRV_I2S_INT_VECTOR_IDX2}
#define DRV_I2S_INT_PRIORITY_IDX2				${CONFIG_DRV_I2S_INT_PRIORITY_IDX2}
#define DRV_I2S_INT_SUB_PRIORITY_IDX2			${CONFIG_DRV_I2S_INT_SUB_PRIORITY_IDX2}
<#else>
#define DRV_I2S_TX_INT_VECTOR_IDX2				${CONFIG_DRV_I2S_TX_INT_VECTOR_IDX2}
#define DRV_I2S_TX_INT_PRIORITY_IDX2			${CONFIG_DRV_I2S_TX_INT_PRIORITY_IDX2}
#define DRV_I2S_TX_INT_SUB_PRIORITY_IDX2		${CONFIG_DRV_I2S_TX_INT_SUB_PRIORITY_IDX2}
#define DRV_I2S_TX_ISR_VECTOR_IDX2				${CONFIG_DRV_I2S_TX_ISR_VECTOR_IDX2}
#define DRV_I2S_RX_INT_VECTOR_IDX2				${CONFIG_DRV_I2S_RX_INT_VECTOR_IDX2}
#define DRV_I2S_RX_INT_PRIORITY_IDX2			${CONFIG_DRV_I2S_RX_INT_PRIORITY_IDX2}
#define DRV_I2S_RX_INT_SUB_PRIORITY_IDX2		${CONFIG_DRV_I2S_RX_INT_SUB_PRIORITY_IDX2}
#define DRV_I2S_RX_ISR_VECTOR_IDX2				${CONFIG_DRV_I2S_RX_ISR_VECTOR_IDX2}
#define DRV_I2S_ERR_INT_VECTOR_IDX2				${CONFIG_DRV_I2S_ERR_INT_VECTOR_IDX2}
#define DRV_I2S_ERR_INT_PRIORITY_IDX2			${CONFIG_DRV_I2S_ERR_INT_PRIORITY_IDX2}
#define DRV_I2S_ERR_INT_SUB_PRIORITY_IDX2		${CONFIG_DRV_I2S_ERR_INT_SUB_PRIORITY_IDX2}
#define DRV_I2S_ERR_ISR_VECTOR_IDX2				${CONFIG_DRV_I2S_ERR_ISR_VECTOR_IDX2}
</#if>
</#if> 
#define QUEUE_SIZE_TX_IDX2                      ${CONFIG_QUEUE_SIZE_TX_IDX2}
#define QUEUE_SIZE_RX_IDX2                      ${CONFIG_QUEUE_SIZE_RX_IDX2}
<#assign i2sCombinedQueueSizeOfAllInstances = i2sCombinedQueueSizeOfAllInstances + CONFIG_QUEUE_SIZE_TX_IDX2?number >
<#assign i2sCombinedQueueSizeOfAllInstances = i2sCombinedQueueSizeOfAllInstances + CONFIG_QUEUE_SIZE_TX_IDX2?number>
<#if CONFIG_DRV_I2S_SUPPORT_TRANSMIT_DMA == true>
<#if CONFIG_DRV_I2S_TX_DMA_CHANNEL_IDX2 == "0">
#define DRV_I2S_TX_DMA_CHANNEL_IDX2				${CONFIG_SYS_DMA_CHANNEL_ID_IDX0}
<#assign DRV_I2S_TX_DMA_CHANNEL_INT_SRC_IDX2 = CONFIG_SYS_DMA_CHANNEL_ID_IDX0> 
</#if>
<#if CONFIG_DRV_I2S_TX_DMA_CHANNEL_IDX2 == "1">
#define DRV_I2S_TX_DMA_CHANNEL_IDX2				${CONFIG_SYS_DMA_CHANNEL_ID_IDX1}
<#assign DRV_I2S_TX_DMA_CHANNEL_INT_SRC_IDX2 = CONFIG_SYS_DMA_CHANNEL_ID_IDX1> 
</#if>
<#if CONFIG_DRV_I2S_TX_DMA_CHANNEL_IDX2 == "2">
#define DRV_I2S_TX_DMA_CHANNEL_IDX2				${CONFIG_SYS_DMA_CHANNEL_ID_IDX2}
<#assign DRV_I2S_TX_DMA_CHANNEL_INT_SRC_IDX2 = CONFIG_SYS_DMA_CHANNEL_ID_IDX2> 
</#if>
<#if CONFIG_DRV_I2S_TX_DMA_CHANNEL_IDX2 == "3">
#define DRV_I2S_TX_DMA_CHANNEL_IDX2				${CONFIG_SYS_DMA_CHANNEL_ID_IDX3}
<#assign DRV_I2S_TX_DMA_CHANNEL_INT_SRC_IDX2 = CONFIG_SYS_DMA_CHANNEL_ID_IDX3> 
</#if>
<#if CONFIG_DRV_I2S_TX_DMA_CHANNEL_IDX2 == "4">
#define DRV_I2S_TX_DMA_CHANNEL_IDX2				${CONFIG_SYS_DMA_CHANNEL_ID_IDX4}
<#assign DRV_I2S_TX_DMA_CHANNEL_INT_SRC_IDX2 = CONFIG_SYS_DMA_CHANNEL_ID_IDX4> 
</#if>
<#if CONFIG_DRV_I2S_TX_DMA_CHANNEL_IDX2 == "5">
#define DRV_I2S_TX_DMA_CHANNEL_IDX2				${CONFIG_SYS_DMA_CHANNEL_ID_IDX5}
<#assign DRV_I2S_TX_DMA_CHANNEL_INT_SRC_IDX2 = CONFIG_SYS_DMA_CHANNEL_ID_IDX5> 
</#if>
<#if CONFIG_DRV_I2S_TX_DMA_CHANNEL_IDX2 == "6">
#define DRV_I2S_TX_DMA_CHANNEL_IDX2				${CONFIG_SYS_DMA_CHANNEL_ID_IDX6}
<#assign DRV_I2S_TX_DMA_CHANNEL_INT_SRC_IDX2 = CONFIG_SYS_DMA_CHANNEL_ID_IDX6> 
</#if>
<#if CONFIG_DRV_I2S_TX_DMA_CHANNEL_IDX2 == "7">
#define DRV_I2S_TX_DMA_CHANNEL_IDX2				${CONFIG_SYS_DMA_CHANNEL_ID_IDX7}
<#assign DRV_I2S_TX_DMA_CHANNEL_INT_SRC_IDX2 = CONFIG_SYS_DMA_CHANNEL_ID_IDX7> 
</#if>
<#if CONFIG_DRV_I2S_DMA_USE_CHANNEL_CHAINING == true>
<#if CONFIG_DRV_I2S_TX_DMA_CHAINING_CHANNEL_IDX2 == "0">
#define DRV_I2S_TX_DMA_CHAINING_CHANNEL_IDX2	${CONFIG_SYS_DMA_CHANNEL_ID_IDX0}
<#assign DRV_I2S_TX_DMA_CHAINING_CHANNEL_INT_SRC_IDX2 = CONFIG_SYS_DMA_CHANNEL_ID_IDX0> 
</#if>
<#if CONFIG_DRV_I2S_TX_DMA_CHAINING_CHANNEL_IDX2 == "1">
#define DRV_I2S_TX_DMA_CHAINING_CHANNEL_IDX2	${CONFIG_SYS_DMA_CHANNEL_ID_IDX1}
<#assign DRV_I2S_TX_DMA_CHAINING_CHANNEL_INT_SRC_IDX2 = CONFIG_SYS_DMA_CHANNEL_ID_IDX1> 
</#if>
<#if CONFIG_DRV_I2S_TX_DMA_CHAINING_CHANNEL_IDX2 == "2">
#define DRV_I2S_TX_DMA_CHAINING_CHANNEL_IDX2	${CONFIG_SYS_DMA_CHANNEL_ID_IDX2}
<#assign DRV_I2S_TX_DMA_CHAINING_CHANNEL_INT_SRC_IDX2 = CONFIG_SYS_DMA_CHANNEL_ID_IDX2> 
</#if>
<#if CONFIG_DRV_I2S_TX_DMA_CHAINING_CHANNEL_IDX2 == "3">
#define DRV_I2S_TX_DMA_CHAINING_CHANNEL_IDX2	${CONFIG_SYS_DMA_CHANNEL_ID_IDX3}
<#assign DRV_I2S_TX_DMA_CHAINING_CHANNEL_INT_SRC_IDX2 = CONFIG_SYS_DMA_CHANNEL_ID_IDX3> 
</#if>
<#if CONFIG_DRV_I2S_TX_DMA_CHAINING_CHANNEL_IDX2 == "4">
#define DRV_I2S_TX_DMA_CHAINING_CHANNEL_IDX2	${CONFIG_SYS_DMA_CHANNEL_ID_IDX4}
<#assign DRV_I2S_TX_DMA_CHAINING_CHANNEL_INT_SRC_IDX2 = CONFIG_SYS_DMA_CHANNEL_ID_IDX4> 
</#if>
<#if CONFIG_DRV_I2S_TX_DMA_CHAINING_CHANNEL_IDX2 == "5">
#define DRV_I2S_TX_DMA_CHAINING_CHANNEL_IDX2	${CONFIG_SYS_DMA_CHANNEL_ID_IDX5}
<#assign DRV_I2S_TX_DMA_CHAINING_CHANNEL_INT_SRC_IDX2 = CONFIG_SYS_DMA_CHANNEL_ID_IDX5> 
</#if>
<#if CONFIG_DRV_I2S_TX_DMA_CHAINING_CHANNEL_IDX2 == "6">
#define DRV_I2S_TX_DMA_CHAINING_CHANNEL_IDX2	${CONFIG_SYS_DMA_CHANNEL_ID_IDX6}
<#assign DRV_I2S_TX_DMA_CHAINING_CHANNEL_INT_SRC_IDX2 = CONFIG_SYS_DMA_CHANNEL_ID_IDX6> 
</#if>
<#if CONFIG_DRV_I2S_TX_DMA_CHAINING_CHANNEL_IDX2 == "7">
#define DRV_I2S_TX_DMA_CHAINING_CHANNEL_IDX2	${CONFIG_SYS_DMA_CHANNEL_ID_IDX7}
<#assign DRV_I2S_TX_DMA_CHAINING_CHANNEL_INT_SRC_IDX2 = CONFIG_SYS_DMA_CHANNEL_ID_IDX7> 
</#if>
</#if>
<#if CONFIG_DRV_I2S_DMA_INTERRUPTS_ENABLE == true>
<#if DRV_I2S_TX_DMA_CHANNEL_INT_SRC_IDX2 == "DMA_CHANNEL_0">
#define DRV_I2S_TX_DMA_SOURCE_IDX2				INT_SOURCE_DMA_0
</#if>
<#if DRV_I2S_TX_DMA_CHANNEL_INT_SRC_IDX2 == "DMA_CHANNEL_1">
#define DRV_I2S_TX_DMA_SOURCE_IDX2				INT_SOURCE_DMA_1
</#if>
<#if DRV_I2S_TX_DMA_CHANNEL_INT_SRC_IDX2 == "DMA_CHANNEL_2">
#define DRV_I2S_TX_DMA_SOURCE_IDX2				INT_SOURCE_DMA_2
</#if>
<#if DRV_I2S_TX_DMA_CHANNEL_INT_SRC_IDX2 == "DMA_CHANNEL_3">
#define DRV_I2S_TX_DMA_SOURCE_IDX2				INT_SOURCE_DMA_3
</#if>
<#if DRV_I2S_TX_DMA_CHANNEL_INT_SRC_IDX2 == "DMA_CHANNEL_4">
#define DRV_I2S_TX_DMA_SOURCE_IDX2				INT_SOURCE_DMA_4
</#if>
<#if DRV_I2S_TX_DMA_CHANNEL_INT_SRC_IDX2 == "DMA_CHANNEL_5">
#define DRV_I2S_TX_DMA_SOURCE_IDX2				INT_SOURCE_DMA_5
</#if>
<#if DRV_I2S_TX_DMA_CHANNEL_INT_SRC_IDX2 == "DMA_CHANNEL_6">
#define DRV_I2S_TX_DMA_SOURCE_IDX2				INT_SOURCE_DMA_6
</#if>
<#if DRV_I2S_TX_DMA_CHANNEL_INT_SRC_IDX2 == "DMA_CHANNEL_7">
#define DRV_I2S_TX_DMA_SOURCE_IDX2				INT_SOURCE_DMA_7
</#if>
<#if CONFIG_DRV_I2S_DMA_USE_CHANNEL_CHAINING == true>
<#if DRV_I2S_TX_DMA_CHAINING_CHANNEL_INT_SRC_IDX2 == "DMA_CHANNEL_0">
#define DRV_I2S_TX_DMA_CHAINING_SOURCE_IDX2		INT_SOURCE_DMA_0
</#if>
<#if DRV_I2S_TX_DMA_CHAINING_CHANNEL_INT_SRC_IDX2 == "DMA_CHANNEL_1">
#define DRV_I2S_TX_DMA_CHAINING_SOURCE_IDX2		INT_SOURCE_DMA_1
</#if>
<#if DRV_I2S_TX_DMA_CHAINING_CHANNEL_INT_SRC_IDX2 == "DMA_CHANNEL_2">
#define DRV_I2S_TX_DMA_CHAINING_SOURCE_IDX2		INT_SOURCE_DMA_2
</#if>
<#if DRV_I2S_TX_DMA_CHAINING_CHANNEL_INT_SRC_IDX2 == "DMA_CHANNEL_3">
#define DRV_I2S_TX_DMA_CHAINING_SOURCE_IDX2		INT_SOURCE_DMA_3
</#if>
<#if DRV_I2S_TX_DMA_CHAINING_CHANNEL_INT_SRC_IDX2 == "DMA_CHANNEL_4">
#define DRV_I2S_TX_DMA_CHAINING_SOURCE_IDX2		INT_SOURCE_DMA_4
</#if>
<#if DRV_I2S_TX_DMA_CHAINING_CHANNEL_INT_SRC_IDX2 == "DMA_CHANNEL_5">
#define DRV_I2S_TX_DMA_CHAINING_SOURCE_IDX2		INT_SOURCE_DMA_5
</#if>
<#if DRV_I2S_TX_DMA_CHAINING_CHANNEL_INT_SRC_IDX2 == "DMA_CHANNEL_6">
#define DRV_I2S_TX_DMA_CHAINING_SOURCE_IDX2		INT_SOURCE_DMA_6
</#if>
<#if DRV_I2S_TX_DMA_CHAINING_CHANNEL_INT_SRC_IDX2 == "DMA_CHANNEL_7">
#define DRV_I2S_TX_DMA_CHAINING_SOURCE_IDX2		INT_SOURCE_DMA_7
</#if>
</#if>
</#if>
</#if>
<#if CONFIG_DRV_I2S_SUPPORT_RECEIVE_DMA == true>
<#if CONFIG_DRV_I2S_RX_DMA_CHANNEL_IDX2 == "0">
#define DRV_I2S_RX_DMA_CHANNEL_IDX2				${CONFIG_SYS_DMA_CHANNEL_ID_IDX0}
<#assign DRV_I2S_RX_DMA_CHANNEL_INT_SRC_IDX2 = CONFIG_SYS_DMA_CHANNEL_ID_IDX0> 
</#if>
<#if CONFIG_DRV_I2S_RX_DMA_CHANNEL_IDX2 == "1">
#define DRV_I2S_RX_DMA_CHANNEL_IDX2				${CONFIG_SYS_DMA_CHANNEL_ID_IDX1}
<#assign DRV_I2S_RX_DMA_CHANNEL_INT_SRC_IDX2 = CONFIG_SYS_DMA_CHANNEL_ID_IDX1> 
</#if>
<#if CONFIG_DRV_I2S_RX_DMA_CHANNEL_IDX2 == "2">
#define DRV_I2S_RX_DMA_CHANNEL_IDX2				${CONFIG_SYS_DMA_CHANNEL_ID_IDX2}
<#assign DRV_I2S_RX_DMA_CHANNEL_INT_SRC_IDX2 = CONFIG_SYS_DMA_CHANNEL_ID_IDX2> 
</#if>
<#if CONFIG_DRV_I2S_RX_DMA_CHANNEL_IDX2 == "3">
#define DRV_I2S_RX_DMA_CHANNEL_IDX2				${CONFIG_SYS_DMA_CHANNEL_ID_IDX3}
<#assign DRV_I2S_RX_DMA_CHANNEL_INT_SRC_IDX2 = CONFIG_SYS_DMA_CHANNEL_ID_IDX3> 
</#if>
<#if CONFIG_DRV_I2S_RX_DMA_CHANNEL_IDX2 == "4">
#define DRV_I2S_RX_DMA_CHANNEL_IDX2				${CONFIG_SYS_DMA_CHANNEL_ID_IDX4}
<#assign DRV_I2S_RX_DMA_CHANNEL_INT_SRC_IDX2 = CONFIG_SYS_DMA_CHANNEL_ID_IDX4> 
</#if>
<#if CONFIG_DRV_I2S_RX_DMA_CHANNEL_IDX2 == "5">
#define DRV_I2S_RX_DMA_CHANNEL_IDX2				${CONFIG_SYS_DMA_CHANNEL_ID_IDX5}
<#assign DRV_I2S_RX_DMA_CHANNEL_INT_SRC_IDX2 = CONFIG_SYS_DMA_CHANNEL_ID_IDX5> 
</#if>
<#if CONFIG_DRV_I2S_RX_DMA_CHANNEL_IDX2 == "6">
#define DRV_I2S_RX_DMA_CHANNEL_IDX2				${CONFIG_SYS_DMA_CHANNEL_ID_IDX6}
<#assign DRV_I2S_RX_DMA_CHANNEL_INT_SRC_IDX2 = CONFIG_SYS_DMA_CHANNEL_ID_IDX6> 
</#if>
<#if CONFIG_DRV_I2S_RX_DMA_CHANNEL_IDX2 == "7">
#define DRV_I2S_RX_DMA_CHANNEL_IDX2				${CONFIG_SYS_DMA_CHANNEL_ID_IDX7}
<#assign DRV_I2S_RX_DMA_CHANNEL_INT_SRC_IDX2 = CONFIG_SYS_DMA_CHANNEL_ID_IDX7> 
</#if>
<#if CONFIG_DRV_I2S_DMA_USE_CHANNEL_CHAINING == true>
<#if CONFIG_DRV_I2S_RX_DMA_CHAINING_CHANNEL_IDX2 == "0">
#define DRV_I2S_RX_DMA_CHAINING_CHANNEL_IDX2	${CONFIG_SYS_DMA_CHANNEL_ID_IDX0}
<#assign DRV_I2S_RX_DMA_CHAINING_CHANNEL_INT_SRC_IDX2 = CONFIG_SYS_DMA_CHANNEL_ID_IDX0> 
</#if>
<#if CONFIG_DRV_I2S_RX_DMA_CHAINING_CHANNEL_IDX2 == "1">
#define DRV_I2S_RX_DMA_CHAINING_CHANNEL_IDX2	${CONFIG_SYS_DMA_CHANNEL_ID_IDX1}
<#assign DRV_I2S_RX_DMA_CHAINING_CHANNEL_INT_SRC_IDX2 = CONFIG_SYS_DMA_CHANNEL_ID_IDX1> 
</#if>
<#if CONFIG_DRV_I2S_RX_DMA_CHAINING_CHANNEL_IDX2 == "2">
#define DRV_I2S_RX_DMA_CHAINING_CHANNEL_IDX0	${CONFIG_SYS_DMA_CHANNEL_ID_IDX2}
<#assign DRV_I2S_RX_DMA_CHAINING_CHANNEL_INT_SRC_IDX2 = CONFIG_SYS_DMA_CHANNEL_ID_IDX2> 
</#if>
<#if CONFIG_DRV_I2S_RX_DMA_CHAINING_CHANNEL_IDX2 == "3">
#define DRV_I2S_RX_DMA_CHAINING_CHANNEL_IDX2	${CONFIG_SYS_DMA_CHANNEL_ID_IDX3}
<#assign DRV_I2S_RX_DMA_CHAINING_CHANNEL_INT_SRC_IDX2 = CONFIG_SYS_DMA_CHANNEL_ID_IDX3> 
</#if>
<#if CONFIG_DRV_I2S_RX_DMA_CHAINING_CHANNEL_IDX2 == "4">
#define DRV_I2S_RX_DMA_CHAINING_CHANNEL_IDX2	${CONFIG_SYS_DMA_CHANNEL_ID_IDX4}
<#assign DRV_I2S_RX_DMA_CHAINING_CHANNEL_INT_SRC_IDX2 = CONFIG_SYS_DMA_CHANNEL_ID_IDX4> 
</#if>
<#if CONFIG_DRV_I2S_RX_DMA_CHAINING_CHANNEL_IDX2 == "5">
#define DRV_I2S_RX_DMA_CHAINING_CHANNEL_IDX2	${CONFIG_SYS_DMA_CHANNEL_ID_IDX5}
<#assign DRV_I2S_RX_DMA_CHAINING_CHANNEL_INT_SRC_IDX2 = CONFIG_SYS_DMA_CHANNEL_ID_IDX5> 
</#if>
<#if CONFIG_DRV_I2S_RX_DMA_CHAINING_CHANNEL_IDX2 == "6">
#define DRV_I2S_RX_DMA_CHAINING_CHANNEL_IDX2	${CONFIG_SYS_DMA_CHANNEL_ID_IDX6}
<#assign DRV_I2S_RX_DMA_CHAINING_CHANNEL_INT_SRC_IDX2 = CONFIG_SYS_DMA_CHANNEL_ID_IDX6> 
</#if>
<#if CONFIG_DRV_I2S_RX_DMA_CHAINING_CHANNEL_IDX2 == "7">
#define DRV_I2S_RX_DMA_CHAINING_CHANNEL_IDX2	${CONFIG_SYS_DMA_CHANNEL_ID_IDX7}
<#assign DRV_I2S_RX_DMA_CHAINING_CHANNEL_INT_SRC_IDX2 = CONFIG_SYS_DMA_CHANNEL_ID_IDX7> 
</#if>
</#if>
<#if CONFIG_DRV_I2S_DMA_INTERRUPTS_ENABLE == true>
<#if DRV_I2S_RX_DMA_CHANNEL_INT_SRC_IDX2 == "DMA_CHANNEL_0">
#define DRV_I2S_RX_DMA_SOURCE_IDX2				INT_SOURCE_DMA_0
</#if>
<#if DRV_I2S_RX_DMA_CHANNEL_INT_SRC_IDX2 == "DMA_CHANNEL_1">
#define DRV_I2S_RX_DMA_SOURCE_IDX2				INT_SOURCE_DMA_1
</#if>
<#if DRV_I2S_RX_DMA_CHANNEL_INT_SRC_IDX2 == "DMA_CHANNEL_2">
#define DRV_I2S_RX_DMA_SOURCE_IDX2				INT_SOURCE_DMA_2
</#if>
<#if DRV_I2S_RX_DMA_CHANNEL_INT_SRC_IDX2 == "DMA_CHANNEL_3">
#define DRV_I2S_RX_DMA_SOURCE_IDX2				INT_SOURCE_DMA_3
</#if>
<#if DRV_I2S_RX_DMA_CHANNEL_INT_SRC_IDX2 == "DMA_CHANNEL_4">
#define DRV_I2S_RX_DMA_SOURCE_IDX2				INT_SOURCE_DMA_4
</#if>
<#if DRV_I2S_RX_DMA_CHANNEL_INT_SRC_IDX2 == "DMA_CHANNEL_5">
#define DRV_I2S_RX_DMA_SOURCE_IDX2				INT_SOURCE_DMA_5
</#if>
<#if DRV_I2S_RX_DMA_CHANNEL_INT_SRC_IDX2 == "DMA_CHANNEL_6">
#define DRV_I2S_RX_DMA_SOURCE_IDX2				INT_SOURCE_DMA_6
</#if>
<#if DRV_I2S_RX_DMA_CHANNEL_INT_SRC_IDX2 == "DMA_CHANNEL_7">
#define DRV_I2S_RX_DMA_SOURCE_IDX2				INT_SOURCE_DMA_7
</#if>
<#if CONFIG_DRV_I2S_DMA_USE_CHANNEL_CHAINING == true>
<#if DRV_I2S_RX_DMA_CHAINING_CHANNEL_INT_SRC_IDX2 == "DMA_CHANNEL_0">
#define DRV_I2S_RX_DMA_CHAINING_SOURCE_IDX2		INT_SOURCE_DMA_0
</#if>
<#if DRV_I2S_RX_DMA_CHAINING_CHANNEL_INT_SRC_IDX2 == "DMA_CHANNEL_1">
#define DRV_I2S_RX_DMA_CHAINING_SOURCE_IDX2		INT_SOURCE_DMA_1
</#if>
<#if DRV_I2S_RX_DMA_CHAINING_CHANNEL_INT_SRC_IDX2 == "DMA_CHANNEL_2">
#define DRV_I2S_RX_DMA_CHAINING_SOURCE_IDX2		INT_SOURCE_DMA_2
</#if>
<#if DRV_I2S_RX_DMA_CHAINING_CHANNEL_INT_SRC_IDX2 == "DMA_CHANNEL_3">
#define DRV_I2S_RX_DMA_CHAINING_SOURCE_IDX2		INT_SOURCE_DMA_3
</#if>
<#if DRV_I2S_RX_DMA_CHAINING_CHANNEL_INT_SRC_IDX2 == "DMA_CHANNEL_4">
#define DRV_I2S_RX_DMA_CHAINING_SOURCE_IDX2		INT_SOURCE_DMA_4
</#if>
<#if DRV_I2S_RX_DMA_CHAINING_CHANNEL_INT_SRC_IDX2 == "DMA_CHANNEL_5">
#define DRV_I2S_RX_DMA_CHAINING_SOURCE_IDX2		INT_SOURCE_DMA_5
</#if>
<#if DRV_I2S_RX_DMA_CHAINING_CHANNEL_INT_SRC_IDX2 == "DMA_CHANNEL_6">
#define DRV_I2S_RX_DMA_CHAINING_SOURCE_IDX2		INT_SOURCE_DMA_6
</#if>
<#if DRV_I2S_RX_DMA_CHAINING_CHANNEL_INT_SRC_IDX2 == "DMA_CHANNEL_7">
#define DRV_I2S_RX_DMA_CHAINING_SOURCE_IDX2		INT_SOURCE_DMA_7
</#if>
</#if>
</#if>
</#if>
#define DRV_I2S_POWER_STATE_IDX2				${CONFIG_DRV_I2S_POWER_STATE_IDX2}
</#if>
<#-- Instance 3 -->
<#if CONFIG_DRV_I2S_INST_IDX3 == true>
#define DRV_I2S_PERIPHERAL_ID_IDX3				${CONFIG_DRV_I2S_PERIPHERAL_ID_IDX3}
#define DRV_I2S_USAGE_MODE_IDX3					${CONFIG_DRV_I2S_USAGE_MODE_IDX3}
<#if CONFIG_DRV_I2S_STOP_IN_IDLE_IDX3 == true>
#define DRV_I2S_STOP_IN_IDLE_IDX3				true
#else
#define DRV_I2S_STOP_IN_IDLE_IDX3				false
</#if>
#define SPI_BAUD_RATE_CLK_IDX3					${CONFIG_SPI_BAUD_RATE_CLK_IDX3}
#define BAUD_RATE_IDX3                          ${CONFIG_DRV_I2S_BAUD_RATE}
#define DRV_I2S_CLK_MODE_IDX3					${CONFIG_DRV_I2S_CLK_MODE_IDX3}
#define SPI_AUDIO_COMM_WIDTH_IDX3				${CONFIG_SPI_AUDIO_COMM_WIDTH_IDX3}
#define SPI_AUDIO_TRANSMIT_MODE_IDX3			${CONFIG_SPI_AUDIO_TRANSMIT_MODE_IDX3}
#define SPI_INPUT_SAMPLING_PHASE_IDX3			${CONFIG_SPI_INPUT_SAMPLING_PHASE_IDX3}
#define DRV_I2S_AUDIO_PROTOCOL_MODE_IDX3        ${CONFIG_DRV_I2S_AUDIO_PROTOCOL_MODE_IDX3}
<#if CONFIG_DRV_I2S_DMA_INTERRUPTS_ENABLE == true>
#define DRV_I2S_TX_INT_SRC_IDX3					${CONFIG_DRV_I2S_TX_INT_SRC_IDX3}
#define DRV_I2S_RX_INT_SRC_IDX3					${CONFIG_DRV_I2S_RX_INT_SRC_IDX3}
</#if>
<#if CONFIG_DRV_I2S_INTERRUPT_MODE == true>
#define DRV_I2S_TX_INT_SRC_IDX3					${CONFIG_DRV_I2S_TX_INT_SRC_IDX3}
#define DRV_I2S_RX_INT_SRC_IDX3					${CONFIG_DRV_I2S_RX_INT_SRC_IDX3}
#define DRV_I2S_ERR_INT_SRC_IDX3				${CONFIG_DRV_I2S_ERR_INT_SRC_IDX3}
<#if CONFIG_PIC32MX == true>
#define DRV_I2S_ISR_VECTOR_IDX3					${CONFIG_DRV_I2S_ISR_VECTOR_IDX3}
#define DRV_I2S_INT_VECTOR_IDX3					${CONFIG_DRV_I2S_INT_VECTOR_IDX3}
#define DRV_I2S_INT_PRIORITY_IDX3				${CONFIG_DRV_I2S_INT_PRIORITY_IDX3}
#define DRV_I2S_INT_SUB_PRIORITY_IDX3			${CONFIG_DRV_I2S_INT_SUB_PRIORITY_IDX3}
<#else>
#define DRV_I2S_TX_INT_VECTOR_IDX3				${CONFIG_DRV_I2S_TX_INT_VECTOR_IDX3}
#define DRV_I2S_TX_INT_PRIORITY_IDX3			${CONFIG_DRV_I2S_TX_INT_PRIORITY_IDX3}
#define DRV_I2S_TX_INT_SUB_PRIORITY_IDX3		${CONFIG_DRV_I2S_TX_INT_SUB_PRIORITY_IDX3}
#define DRV_I2S_TX_ISR_VECTOR_IDX3				${CONFIG_DRV_I2S_TX_ISR_VECTOR_IDX3}
#define DRV_I2S_RX_INT_VECTOR_IDX3				${CONFIG_DRV_I2S_RX_INT_VECTOR_IDX3}
#define DRV_I2S_RX_INT_PRIORITY_IDX3			${CONFIG_DRV_I2S_RX_INT_PRIORITY_IDX3}
#define DRV_I2S_RX_INT_SUB_PRIORITY_IDX3		${CONFIG_DRV_I2S_RX_INT_SUB_PRIORITY_IDX3}
#define DRV_I2S_RX_ISR_VECTOR_IDX3				${CONFIG_DRV_I2S_RX_ISR_VECTOR_IDX3}
#define DRV_I2S_ERR_INT_VECTOR_IDX3				${CONFIG_DRV_I2S_ERR_INT_VECTOR_IDX3}
#define DRV_I2S_ERR_INT_PRIORITY_IDX3			${CONFIG_DRV_I2S_ERR_INT_PRIORITY_IDX3}
#define DRV_I2S_ERR_INT_SUB_PRIORITY_IDX3		${CONFIG_DRV_I2S_ERR_INT_SUB_PRIORITY_IDX3}
#define DRV_I2S_ERR_ISR_VECTOR_IDX3				${CONFIG_DRV_I2S_ERR_ISR_VECTOR_IDX3}
</#if>
</#if> 
#define QUEUE_SIZE_TX_IDX3                      ${CONFIG_QUEUE_SIZE_TX_IDX3}
#define QUEUE_SIZE_RX_IDX3                      ${CONFIG_QUEUE_SIZE_RX_IDX3}
<#assign i2sCombinedQueueSizeOfAllInstances = i2sCombinedQueueSizeOfAllInstances + CONFIG_QUEUE_SIZE_TX_IDX3?number >
<#assign i2sCombinedQueueSizeOfAllInstances = i2sCombinedQueueSizeOfAllInstances + CONFIG_QUEUE_SIZE_TX_IDX3?number>
<#if CONFIG_DRV_I2S_SUPPORT_TRANSMIT_DMA == true>
<#if CONFIG_DRV_I2S_TX_DMA_CHANNEL_IDX3 == "0">
#define DRV_I2S_TX_DMA_CHANNEL_IDX3				${CONFIG_SYS_DMA_CHANNEL_ID_IDX0}
<#assign DRV_I2S_TX_DMA_CHANNEL_INT_SRC_IDX3 = CONFIG_SYS_DMA_CHANNEL_ID_IDX0> 
</#if>
<#if CONFIG_DRV_I2S_TX_DMA_CHANNEL_IDX3 == "1">
#define DRV_I2S_TX_DMA_CHANNEL_IDX3				${CONFIG_SYS_DMA_CHANNEL_ID_IDX1}
<#assign DRV_I2S_TX_DMA_CHANNEL_INT_SRC_IDX3 = CONFIG_SYS_DMA_CHANNEL_ID_IDX1> 
</#if>
<#if CONFIG_DRV_I2S_TX_DMA_CHANNEL_IDX3 == "2">
#define DRV_I2S_TX_DMA_CHANNEL_IDX3				${CONFIG_SYS_DMA_CHANNEL_ID_IDX2}
<#assign DRV_I2S_TX_DMA_CHANNEL_INT_SRC_IDX3 = CONFIG_SYS_DMA_CHANNEL_ID_IDX2> 
</#if>
<#if CONFIG_DRV_I2S_TX_DMA_CHANNEL_IDX3 == "3">
#define DRV_I2S_TX_DMA_CHANNEL_IDX3				${CONFIG_SYS_DMA_CHANNEL_ID_IDX3}
<#assign DRV_I2S_TX_DMA_CHANNEL_INT_SRC_IDX3 = CONFIG_SYS_DMA_CHANNEL_ID_IDX3> 
</#if>
<#if CONFIG_DRV_I2S_TX_DMA_CHANNEL_IDX3 == "4">
#define DRV_I2S_TX_DMA_CHANNEL_IDX3				${CONFIG_SYS_DMA_CHANNEL_ID_IDX4}
<#assign DRV_I2S_TX_DMA_CHANNEL_INT_SRC_IDX3 = CONFIG_SYS_DMA_CHANNEL_ID_IDX4> 
</#if>
<#if CONFIG_DRV_I2S_TX_DMA_CHANNEL_IDX3 == "5">
#define DRV_I2S_TX_DMA_CHANNEL_IDX3				${CONFIG_SYS_DMA_CHANNEL_ID_IDX5}
<#assign DRV_I2S_TX_DMA_CHANNEL_INT_SRC_IDX3 = CONFIG_SYS_DMA_CHANNEL_ID_IDX5> 
</#if>
<#if CONFIG_DRV_I2S_TX_DMA_CHANNEL_IDX3 == "6">
#define DRV_I2S_TX_DMA_CHANNEL_IDX3				${CONFIG_SYS_DMA_CHANNEL_ID_IDX6}
<#assign DRV_I2S_TX_DMA_CHANNEL_INT_SRC_IDX3 = CONFIG_SYS_DMA_CHANNEL_ID_IDX6> 
</#if>
<#if CONFIG_DRV_I2S_TX_DMA_CHANNEL_IDX3 == "7">
#define DRV_I2S_TX_DMA_CHANNEL_IDX3				${CONFIG_SYS_DMA_CHANNEL_ID_IDX7}
<#assign DRV_I2S_TX_DMA_CHANNEL_INT_SRC_IDX3 = CONFIG_SYS_DMA_CHANNEL_ID_IDX7> 
</#if>
<#if CONFIG_DRV_I2S_DMA_USE_CHANNEL_CHAINING == true>
<#if CONFIG_DRV_I2S_TX_DMA_CHAINING_CHANNEL_IDX3 == "0">
#define DRV_I2S_TX_DMA_CHAINING_CHANNEL_IDX3	${CONFIG_SYS_DMA_CHANNEL_ID_IDX0}
<#assign DRV_I2S_TX_DMA_CHAINING_CHANNEL_INT_SRC_IDX3 = CONFIG_SYS_DMA_CHANNEL_ID_IDX0> 
</#if>
<#if CONFIG_DRV_I2S_TX_DMA_CHAINING_CHANNEL_IDX3 == "1">
#define DRV_I2S_TX_DMA_CHAINING_CHANNEL_IDX3	${CONFIG_SYS_DMA_CHANNEL_ID_IDX1}
<#assign DRV_I2S_TX_DMA_CHAINING_CHANNEL_INT_SRC_IDX3 = CONFIG_SYS_DMA_CHANNEL_ID_IDX1> 
</#if>
<#if CONFIG_DRV_I2S_TX_DMA_CHAINING_CHANNEL_IDX3 == "2">
#define DRV_I2S_TX_DMA_CHAINING_CHANNEL_IDX3	${CONFIG_SYS_DMA_CHANNEL_ID_IDX2}
<#assign DRV_I2S_TX_DMA_CHAINING_CHANNEL_INT_SRC_IDX3 = CONFIG_SYS_DMA_CHANNEL_ID_IDX2> 
</#if>
<#if CONFIG_DRV_I2S_TX_DMA_CHAINING_CHANNEL_IDX3 == "3">
#define DRV_I2S_TX_DMA_CHAINING_CHANNEL_IDX3	${CONFIG_SYS_DMA_CHANNEL_ID_IDX3}
<#assign DRV_I2S_TX_DMA_CHAINING_CHANNEL_INT_SRC_IDX3 = CONFIG_SYS_DMA_CHANNEL_ID_IDX3> 
</#if>
<#if CONFIG_DRV_I2S_TX_DMA_CHAINING_CHANNEL_IDX3 == "4">
#define DRV_I2S_TX_DMA_CHAINING_CHANNEL_IDX3	${CONFIG_SYS_DMA_CHANNEL_ID_IDX4}
<#assign DRV_I2S_TX_DMA_CHAINING_CHANNEL_INT_SRC_IDX3 = CONFIG_SYS_DMA_CHANNEL_ID_IDX4> 
</#if>
<#if CONFIG_DRV_I2S_TX_DMA_CHAINING_CHANNEL_IDX3 == "5">
#define DRV_I2S_TX_DMA_CHAINING_CHANNEL_IDX3	${CONFIG_SYS_DMA_CHANNEL_ID_IDX5}
<#assign DRV_I2S_TX_DMA_CHAINING_CHANNEL_INT_SRC_IDX3 = CONFIG_SYS_DMA_CHANNEL_ID_IDX5> 
</#if>
<#if CONFIG_DRV_I2S_TX_DMA_CHAINING_CHANNEL_IDX3 == "6">
#define DRV_I2S_TX_DMA_CHAINING_CHANNEL_IDX3	${CONFIG_SYS_DMA_CHANNEL_ID_IDX6}
<#assign DRV_I2S_TX_DMA_CHAINING_CHANNEL_INT_SRC_IDX3 = CONFIG_SYS_DMA_CHANNEL_ID_IDX6> 
</#if>
<#if CONFIG_DRV_I2S_TX_DMA_CHAINING_CHANNEL_IDX3 == "7">
#define DRV_I2S_TX_DMA_CHAINING_CHANNEL_IDX3	${CONFIG_SYS_DMA_CHANNEL_ID_IDX7}
<#assign DRV_I2S_TX_DMA_CHAINING_CHANNEL_INT_SRC_IDX3 = CONFIG_SYS_DMA_CHANNEL_ID_IDX7> 
</#if>
</#if>
<#if CONFIG_DRV_I2S_DMA_INTERRUPTS_ENABLE == true>
<#if DRV_I2S_TX_DMA_CHANNEL_INT_SRC_IDX3 == "DMA_CHANNEL_0">
#define DRV_I2S_TX_DMA_SOURCE_IDX3				INT_SOURCE_DMA_0
</#if>
<#if DRV_I2S_TX_DMA_CHANNEL_INT_SRC_IDX3 == "DMA_CHANNEL_1">
#define DRV_I2S_TX_DMA_SOURCE_IDX3				INT_SOURCE_DMA_1
</#if>
<#if DRV_I2S_TX_DMA_CHANNEL_INT_SRC_IDX3 == "DMA_CHANNEL_2">
#define DRV_I2S_TX_DMA_SOURCE_IDX3				INT_SOURCE_DMA_2
</#if>
<#if DRV_I2S_TX_DMA_CHANNEL_INT_SRC_IDX3 == "DMA_CHANNEL_3">
#define DRV_I2S_TX_DMA_SOURCE_IDX3				INT_SOURCE_DMA_3
</#if>
<#if DRV_I2S_TX_DMA_CHANNEL_INT_SRC_IDX3 == "DMA_CHANNEL_4">
#define DRV_I2S_TX_DMA_SOURCE_IDX3				INT_SOURCE_DMA_4
</#if>
<#if DRV_I2S_TX_DMA_CHANNEL_INT_SRC_IDX3 == "DMA_CHANNEL_5">
#define DRV_I2S_TX_DMA_SOURCE_IDX3				INT_SOURCE_DMA_5
</#if>
<#if DRV_I2S_TX_DMA_CHANNEL_INT_SRC_IDX3 == "DMA_CHANNEL_6">
#define DRV_I2S_TX_DMA_SOURCE_IDX3				INT_SOURCE_DMA_6
</#if>
<#if DRV_I2S_TX_DMA_CHANNEL_INT_SRC_IDX3 == "DMA_CHANNEL_7">
#define DRV_I2S_TX_DMA_SOURCE_IDX3				INT_SOURCE_DMA_7
</#if>
<#if CONFIG_DRV_I2S_DMA_USE_CHANNEL_CHAINING == true>
<#if DRV_I2S_TX_DMA_CHAINING_CHANNEL_INT_SRC_IDX3 == "DMA_CHANNEL_0">
#define DRV_I2S_TX_DMA_CHAINING_SOURCE_IDX3		INT_SOURCE_DMA_0
</#if>
<#if DRV_I2S_TX_DMA_CHAINING_CHANNEL_INT_SRC_IDX3 == "DMA_CHANNEL_1">
#define DRV_I2S_TX_DMA_CHAINING_SOURCE_IDX3		INT_SOURCE_DMA_1
</#if>
<#if DRV_I2S_TX_DMA_CHAINING_CHANNEL_INT_SRC_IDX3 == "DMA_CHANNEL_2">
#define DRV_I2S_TX_DMA_CHAINING_SOURCE_IDX3		INT_SOURCE_DMA_2
</#if>
<#if DRV_I2S_TX_DMA_CHAINING_CHANNEL_INT_SRC_IDX3 == "DMA_CHANNEL_3">
#define DRV_I2S_TX_DMA_CHAINING_SOURCE_IDX3		INT_SOURCE_DMA_3
</#if>
<#if DRV_I2S_TX_DMA_CHAINING_CHANNEL_INT_SRC_IDX3 == "DMA_CHANNEL_4">
#define DRV_I2S_TX_DMA_CHAINING_SOURCE_IDX3		INT_SOURCE_DMA_4
</#if>
<#if DRV_I2S_TX_DMA_CHAINING_CHANNEL_INT_SRC_IDX3 == "DMA_CHANNEL_5">
#define DRV_I2S_TX_DMA_CHAINING_SOURCE_IDX3		INT_SOURCE_DMA_5
</#if>
<#if DRV_I2S_TX_DMA_CHAINING_CHANNEL_INT_SRC_IDX3 == "DMA_CHANNEL_6">
#define DRV_I2S_TX_DMA_CHAINING_SOURCE_IDX3		INT_SOURCE_DMA_6
</#if>
<#if DRV_I2S_TX_DMA_CHAINING_CHANNEL_INT_SRC_IDX3 == "DMA_CHANNEL_7">
#define DRV_I2S_TX_DMA_CHAINING_SOURCE_IDX3		INT_SOURCE_DMA_7
</#if>
</#if>
</#if>
</#if>
<#if CONFIG_DRV_I2S_SUPPORT_RECEIVE_DMA == true>
<#if CONFIG_DRV_I2S_RX_DMA_CHANNEL_IDX3 == "0">
#define DRV_I2S_RX_DMA_CHANNEL_IDX3				${CONFIG_SYS_DMA_CHANNEL_ID_IDX0}
<#assign DRV_I2S_RX_DMA_CHANNEL_INT_SRC_IDX3 = CONFIG_SYS_DMA_CHANNEL_ID_IDX0> 
</#if>
<#if CONFIG_DRV_I2S_RX_DMA_CHANNEL_IDX3 == "1">
#define DRV_I2S_RX_DMA_CHANNEL_IDX3				${CONFIG_SYS_DMA_CHANNEL_ID_IDX1}
<#assign DRV_I2S_RX_DMA_CHANNEL_INT_SRC_IDX3 = CONFIG_SYS_DMA_CHANNEL_ID_IDX1> 
</#if>
<#if CONFIG_DRV_I2S_RX_DMA_CHANNEL_IDX3 == "2">
#define DRV_I2S_RX_DMA_CHANNEL_IDX3				${CONFIG_SYS_DMA_CHANNEL_ID_IDX2}
<#assign DRV_I2S_RX_DMA_CHANNEL_INT_SRC_IDX3 = CONFIG_SYS_DMA_CHANNEL_ID_IDX2> 
</#if>
<#if CONFIG_DRV_I2S_RX_DMA_CHANNEL_IDX3 == "3">
#define DRV_I2S_RX_DMA_CHANNEL_IDX3				${CONFIG_SYS_DMA_CHANNEL_ID_IDX3}
<#assign DRV_I2S_RX_DMA_CHANNEL_INT_SRC_IDX3 = CONFIG_SYS_DMA_CHANNEL_ID_IDX3> 
</#if>
<#if CONFIG_DRV_I2S_RX_DMA_CHANNEL_IDX3 == "4">
#define DRV_I2S_RX_DMA_CHANNEL_IDX3				${CONFIG_SYS_DMA_CHANNEL_ID_IDX4}
<#assign DRV_I2S_RX_DMA_CHANNEL_INT_SRC_IDX3 = CONFIG_SYS_DMA_CHANNEL_ID_IDX4> 
</#if>
<#if CONFIG_DRV_I2S_RX_DMA_CHANNEL_IDX3 == "5">
#define DRV_I2S_RX_DMA_CHANNEL_IDX3				${CONFIG_SYS_DMA_CHANNEL_ID_IDX5}
<#assign DRV_I2S_RX_DMA_CHANNEL_INT_SRC_IDX3 = CONFIG_SYS_DMA_CHANNEL_ID_IDX5> 
</#if>
<#if CONFIG_DRV_I2S_RX_DMA_CHANNEL_IDX3 == "6">
#define DRV_I2S_RX_DMA_CHANNEL_IDX3				${CONFIG_SYS_DMA_CHANNEL_ID_IDX6}
<#assign DRV_I2S_RX_DMA_CHANNEL_INT_SRC_IDX3 = CONFIG_SYS_DMA_CHANNEL_ID_IDX6> 
</#if>
<#if CONFIG_DRV_I2S_RX_DMA_CHANNEL_IDX3 == "7">
#define DRV_I2S_RX_DMA_CHANNEL_IDX3				${CONFIG_SYS_DMA_CHANNEL_ID_IDX7}
<#assign DRV_I2S_RX_DMA_CHANNEL_INT_SRC_IDX3 = CONFIG_SYS_DMA_CHANNEL_ID_IDX7> 
</#if>
<#if CONFIG_DRV_I2S_DMA_USE_CHANNEL_CHAINING == true>
<#if CONFIG_DRV_I2S_RX_DMA_CHAINING_CHANNEL_IDX3 == "0">
#define DRV_I2S_RX_DMA_CHAINING_CHANNEL_IDX3	${CONFIG_SYS_DMA_CHANNEL_ID_IDX0}
<#assign DRV_I2S_RX_DMA_CHAINING_CHANNEL_INT_SRC_IDX3 = CONFIG_SYS_DMA_CHANNEL_ID_IDX0> 
</#if>
<#if CONFIG_DRV_I2S_RX_DMA_CHAINING_CHANNEL_IDX3 == "1">
#define DRV_I2S_RX_DMA_CHAINING_CHANNEL_IDX3	${CONFIG_SYS_DMA_CHANNEL_ID_IDX1}
<#assign DRV_I2S_RX_DMA_CHAINING_CHANNEL_INT_SRC_IDX3 = CONFIG_SYS_DMA_CHANNEL_ID_IDX1> 
</#if>
<#if CONFIG_DRV_I2S_RX_DMA_CHAINING_CHANNEL_IDX3 == "2">
#define DRV_I2S_RX_DMA_CHAINING_CHANNEL_IDX3	${CONFIG_SYS_DMA_CHANNEL_ID_IDX2}
<#assign DRV_I2S_RX_DMA_CHAINING_CHANNEL_INT_SRC_IDX3 = CONFIG_SYS_DMA_CHANNEL_ID_IDX2> 
</#if>
<#if CONFIG_DRV_I2S_RX_DMA_CHAINING_CHANNEL_IDX3 == "3">
#define DRV_I2S_RX_DMA_CHAINING_CHANNEL_IDX3	${CONFIG_SYS_DMA_CHANNEL_ID_IDX3}
<#assign DRV_I2S_RX_DMA_CHAINING_CHANNEL_INT_SRC_IDX3 = CONFIG_SYS_DMA_CHANNEL_ID_IDX3> 
</#if>
<#if CONFIG_DRV_I2S_RX_DMA_CHAINING_CHANNEL_IDX3 == "4">
#define DRV_I2S_RX_DMA_CHAINING_CHANNEL_IDX3	${CONFIG_SYS_DMA_CHANNEL_ID_IDX4}
<#assign DRV_I2S_RX_DMA_CHAINING_CHANNEL_INT_SRC_IDX3 = CONFIG_SYS_DMA_CHANNEL_ID_IDX4> 
</#if>
<#if CONFIG_DRV_I2S_RX_DMA_CHAINING_CHANNEL_IDX3 == "5">
#define DRV_I2S_RX_DMA_CHAINING_CHANNEL_IDX3	${CONFIG_SYS_DMA_CHANNEL_ID_IDX5}
<#assign DRV_I2S_RX_DMA_CHAINING_CHANNEL_INT_SRC_IDX3 = CONFIG_SYS_DMA_CHANNEL_ID_IDX5> 
</#if>
<#if CONFIG_DRV_I2S_RX_DMA_CHAINING_CHANNEL_IDX3 == "6">
#define DRV_I2S_RX_DMA_CHAINING_CHANNEL_IDX3	${CONFIG_SYS_DMA_CHANNEL_ID_IDX6}
<#assign DRV_I2S_RX_DMA_CHAINING_CHANNEL_INT_SRC_IDX3 = CONFIG_SYS_DMA_CHANNEL_ID_IDX6> 
</#if>
<#if CONFIG_DRV_I2S_RX_DMA_CHAINING_CHANNEL_IDX3 == "7">
#define DRV_I2S_RX_DMA_CHAINING_CHANNEL_IDX3	${CONFIG_SYS_DMA_CHANNEL_ID_IDX7}
<#assign DRV_I2S_RX_DMA_CHAINING_CHANNEL_INT_SRC_IDX3 = CONFIG_SYS_DMA_CHANNEL_ID_IDX7> 
</#if>
</#if>
<#if CONFIG_DRV_I2S_DMA_INTERRUPTS_ENABLE == true>
<#if DRV_I2S_RX_DMA_CHANNEL_INT_SRC_IDX3 == "DMA_CHANNEL_0">
#define DRV_I2S_RX_DMA_SOURCE_IDX3				INT_SOURCE_DMA_0
</#if>
<#if DRV_I2S_RX_DMA_CHANNEL_INT_SRC_IDX3 == "DMA_CHANNEL_1">
#define DRV_I2S_RX_DMA_SOURCE_IDX3				INT_SOURCE_DMA_1
</#if>
<#if DRV_I2S_RX_DMA_CHANNEL_INT_SRC_IDX3 == "DMA_CHANNEL_2">
#define DRV_I2S_RX_DMA_SOURCE_IDX3				INT_SOURCE_DMA_2
</#if>
<#if DRV_I2S_RX_DMA_CHANNEL_INT_SRC_IDX3 == "DMA_CHANNEL_3">
#define DRV_I2S_RX_DMA_SOURCE_IDX3				INT_SOURCE_DMA_3
</#if>
<#if DRV_I2S_RX_DMA_CHANNEL_INT_SRC_IDX3 == "DMA_CHANNEL_4">
#define DRV_I2S_RX_DMA_SOURCE_IDX3				INT_SOURCE_DMA_4
</#if>
<#if DRV_I2S_RX_DMA_CHANNEL_INT_SRC_IDX3 == "DMA_CHANNEL_5">
#define DRV_I2S_RX_DMA_SOURCE_IDX3				INT_SOURCE_DMA_5
</#if>
<#if DRV_I2S_RX_DMA_CHANNEL_INT_SRC_IDX3 == "DMA_CHANNEL_6">
#define DRV_I2S_RX_DMA_SOURCE_IDX3				INT_SOURCE_DMA_6
</#if>
<#if DRV_I2S_RX_DMA_CHANNEL_INT_SRC_IDX3 == "DMA_CHANNEL_7">
#define DRV_I2S_RX_DMA_SOURCE_IDX3				INT_SOURCE_DMA_7
</#if>
<#if CONFIG_DRV_I2S_DMA_USE_CHANNEL_CHAINING == true>
<#if DRV_I2S_RX_DMA_CHAINING_CHANNEL_INT_SRC_IDX3 == "DMA_CHANNEL_0">
#define DRV_I2S_RX_DMA_CHAINING_SOURCE_IDX3		INT_SOURCE_DMA_0
</#if>
<#if DRV_I2S_RX_DMA_CHAINING_CHANNEL_INT_SRC_IDX3 == "DMA_CHANNEL_1">
#define DRV_I2S_RX_DMA_CHAINING_SOURCE_IDX3		INT_SOURCE_DMA_1
</#if>
<#if DRV_I2S_RX_DMA_CHAINING_CHANNEL_INT_SRC_IDX3 == "DMA_CHANNEL_2">
#define DRV_I2S_RX_DMA_CHAINING_SOURCE_IDX3		INT_SOURCE_DMA_2
</#if>
<#if DRV_I2S_RX_DMA_CHAINING_CHANNEL_INT_SRC_IDX3 == "DMA_CHANNEL_3">
#define DRV_I2S_RX_DMA_CHAINING_SOURCE_IDX3		INT_SOURCE_DMA_3
</#if>
<#if DRV_I2S_RX_DMA_CHAINING_CHANNEL_INT_SRC_IDX3 == "DMA_CHANNEL_4">
#define DRV_I2S_RX_DMA_CHAINING_SOURCE_IDX3		INT_SOURCE_DMA_4
</#if>
<#if DRV_I2S_RX_DMA_CHAINING_CHANNEL_INT_SRC_IDX3 == "DMA_CHANNEL_5">
#define DRV_I2S_RX_DMA_CHAINING_SOURCE_IDX3		INT_SOURCE_DMA_5
</#if>
<#if DRV_I2S_RX_DMA_CHAINING_CHANNEL_INT_SRC_IDX3 == "DMA_CHANNEL_6">
#define DRV_I2S_RX_DMA_CHAINING_SOURCE_IDX3		INT_SOURCE_DMA_6
</#if>
<#if DRV_I2S_RX_DMA_CHAINING_CHANNEL_INT_SRC_IDX3 == "DMA_CHANNEL_7">
#define DRV_I2S_RX_DMA_CHAINING_SOURCE_IDX3		INT_SOURCE_DMA_7
</#if>
</#if>
</#if>
</#if>
#define DRV_I2S_POWER_STATE_IDX3				${CONFIG_DRV_I2S_POWER_STATE_IDX3}
</#if>
<#-- Instance 4 -->
<#if CONFIG_DRV_I2S_INST_IDX4 == true>
#define DRV_I2S_PERIPHERAL_ID_IDX4				${CONFIG_DRV_I2S_PERIPHERAL_ID_IDX4}
#define DRV_I2S_USAGE_MODE_IDX4					${CONFIG_DRV_I2S_USAGE_MODE_IDX4}
<#if CONFIG_DRV_I2S_STOP_IN_IDLE_IDX4 == true>
#define DRV_I2S_STOP_IN_IDLE_IDX4				true
#else
#define DRV_I2S_STOP_IN_IDLE_IDX4				false
</#if>
#define SPI_BAUD_RATE_CLK_IDX4					${CONFIG_SPI_BAUD_RATE_CLK_IDX4}
#define BAUD_RATE_IDX4                          ${CONFIG_DRV_I2S_BAUD_RATE}
#define DRV_I2S_CLK_MODE_IDX4					${CONFIG_DRV_I2S_CLK_MODE_IDX4}
#define SPI_AUDIO_COMM_WIDTH_IDX4				${CONFIG_SPI_AUDIO_COMM_WIDTH_IDX4}
#define SPI_AUDIO_TRANSMIT_MODE_IDX4			${CONFIG_SPI_AUDIO_TRANSMIT_MODE_IDX4}
#define SPI_INPUT_SAMPLING_PHASE_IDX4			${CONFIG_SPI_INPUT_SAMPLING_PHASE_IDX4}
#define DRV_I2S_AUDIO_PROTOCOL_MODE_IDX4        ${CONFIG_DRV_I2S_AUDIO_PROTOCOL_MODE_IDX4}
<#if CONFIG_DRV_I2S_DMA_INTERRUPTS_ENABLE == true>
#define DRV_I2S_TX_INT_SRC_IDX4					${CONFIG_DRV_I2S_TX_INT_SRC_IDX4}
#define DRV_I2S_RX_INT_SRC_IDX4					${CONFIG_DRV_I2S_RX_INT_SRC_IDX4}
</#if>
<#if CONFIG_DRV_I2S_INTERRUPT_MODE == true>
#define DRV_I2S_TX_INT_SRC_IDX4					${CONFIG_DRV_I2S_TX_INT_SRC_IDX4}
#define DRV_I2S_RX_INT_SRC_IDX4					${CONFIG_DRV_I2S_RX_INT_SRC_IDX4}
#define DRV_I2S_ERR_INT_SRC_IDX4				${CONFIG_DRV_I2S_ERR_INT_SRC_IDX4}
<#if CONFIG_PIC32MX == true>
#define DRV_I2S_ISR_VECTOR_IDX4					${CONFIG_DRV_I2S_ISR_VECTOR_IDX4}
#define DRV_I2S_INT_VECTOR_IDX4					${CONFIG_DRV_I2S_INT_VECTOR_IDX4}
#define DRV_I2S_INT_PRIORITY_IDX4				${CONFIG_DRV_I2S_INT_PRIORITY_IDX4}
#define DRV_I2S_INT_SUB_PRIORITY_IDX4			${CONFIG_DRV_I2S_INT_SUB_PRIORITY_IDX4}
<#else>
#define DRV_I2S_TX_INT_VECTOR_IDX4				${CONFIG_DRV_I2S_TX_INT_VECTOR_IDX4}
#define DRV_I2S_TX_INT_PRIORITY_IDX4			${CONFIG_DRV_I2S_TX_INT_PRIORITY_IDX4}
#define DRV_I2S_TX_INT_SUB_PRIORITY_IDX4		${CONFIG_DRV_I2S_TX_INT_SUB_PRIORITY_IDX4}
#define DRV_I2S_TX_ISR_VECTOR_IDX4				${CONFIG_DRV_I2S_TX_ISR_VECTOR_IDX4}
#define DRV_I2S_RX_INT_VECTOR_IDX4				${CONFIG_DRV_I2S_RX_INT_VECTOR_IDX4}
#define DRV_I2S_RX_INT_PRIORITY_IDX4			${CONFIG_DRV_I2S_RX_INT_PRIORITY_IDX4}
#define DRV_I2S_RX_INT_SUB_PRIORITY_IDX4		${CONFIG_DRV_I2S_RX_INT_SUB_PRIORITY_IDX4}
#define DRV_I2S_RX_ISR_VECTOR_IDX4				${CONFIG_DRV_I2S_RX_ISR_VECTOR_IDX4}
#define DRV_I2S_ERR_INT_VECTOR_IDX4				${CONFIG_DRV_I2S_ERR_INT_VECTOR_IDX4}
#define DRV_I2S_ERR_INT_PRIORITY_IDX4			${CONFIG_DRV_I2S_ERR_INT_PRIORITY_IDX4}
#define DRV_I2S_ERR_INT_SUB_PRIORITY_IDX4		${CONFIG_DRV_I2S_ERR_INT_SUB_PRIORITY_IDX4}
#define DRV_I2S_ERR_ISR_VECTOR_IDX4				${CONFIG_DRV_I2S_ERR_ISR_VECTOR_IDX4}
</#if>
</#if> 
#define QUEUE_SIZE_TX_IDX4                      ${CONFIG_QUEUE_SIZE_TX_IDX4}
#define QUEUE_SIZE_RX_IDX4                      ${CONFIG_QUEUE_SIZE_RX_IDX4}
<#assign i2sCombinedQueueSizeOfAllInstances = i2sCombinedQueueSizeOfAllInstances + CONFIG_QUEUE_SIZE_TX_IDX4?number >
<#assign i2sCombinedQueueSizeOfAllInstances = i2sCombinedQueueSizeOfAllInstances + CONFIG_QUEUE_SIZE_TX_IDX4?number>
<#if CONFIG_DRV_I2S_SUPPORT_TRANSMIT_DMA == true>
<#if CONFIG_DRV_I2S_TX_DMA_CHANNEL_IDX4 == "0">
#define DRV_I2S_TX_DMA_CHANNEL_IDX4				${CONFIG_SYS_DMA_CHANNEL_ID_IDX0}
<#assign DRV_I2S_TX_DMA_CHANNEL_INT_SRC_IDX4 = CONFIG_SYS_DMA_CHANNEL_ID_IDX0> 
</#if>
<#if CONFIG_DRV_I2S_TX_DMA_CHANNEL_IDX4 == "1">
#define DRV_I2S_TX_DMA_CHANNEL_IDX4				${CONFIG_SYS_DMA_CHANNEL_ID_IDX1}
<#assign DRV_I2S_TX_DMA_CHANNEL_INT_SRC_IDX4 = CONFIG_SYS_DMA_CHANNEL_ID_IDX1> 
</#if>
<#if CONFIG_DRV_I2S_TX_DMA_CHANNEL_IDX4 == "2">
#define DRV_I2S_TX_DMA_CHANNEL_IDX4				${CONFIG_SYS_DMA_CHANNEL_ID_IDX2}
<#assign DRV_I2S_TX_DMA_CHANNEL_INT_SRC_IDX4 = CONFIG_SYS_DMA_CHANNEL_ID_IDX2> 
</#if>
<#if CONFIG_DRV_I2S_TX_DMA_CHANNEL_IDX4 == "3">
#define DRV_I2S_TX_DMA_CHANNEL_IDX4				${CONFIG_SYS_DMA_CHANNEL_ID_IDX3}
<#assign DRV_I2S_TX_DMA_CHANNEL_INT_SRC_IDX4 = CONFIG_SYS_DMA_CHANNEL_ID_IDX3> 
</#if>
<#if CONFIG_DRV_I2S_TX_DMA_CHANNEL_IDX4 == "4">
#define DRV_I2S_TX_DMA_CHANNEL_IDX4				${CONFIG_SYS_DMA_CHANNEL_ID_IDX4}
<#assign DRV_I2S_TX_DMA_CHANNEL_INT_SRC_IDX4 = CONFIG_SYS_DMA_CHANNEL_ID_IDX4> 
</#if>
<#if CONFIG_DRV_I2S_TX_DMA_CHANNEL_IDX4 == "5">
#define DRV_I2S_TX_DMA_CHANNEL_IDX4				${CONFIG_SYS_DMA_CHANNEL_ID_IDX5}
<#assign DRV_I2S_TX_DMA_CHANNEL_INT_SRC_IDX4 = CONFIG_SYS_DMA_CHANNEL_ID_IDX5> 
</#if>
<#if CONFIG_DRV_I2S_TX_DMA_CHANNEL_IDX4 == "6">
#define DRV_I2S_TX_DMA_CHANNEL_IDX4				${CONFIG_SYS_DMA_CHANNEL_ID_IDX6}
<#assign DRV_I2S_TX_DMA_CHANNEL_INT_SRC_IDX4 = CONFIG_SYS_DMA_CHANNEL_ID_IDX6> 
</#if>
<#if CONFIG_DRV_I2S_TX_DMA_CHANNEL_IDX4 == "7">
#define DRV_I2S_TX_DMA_CHANNEL_IDX4				${CONFIG_SYS_DMA_CHANNEL_ID_IDX7}
<#assign DRV_I2S_TX_DMA_CHANNEL_INT_SRC_IDX4 = CONFIG_SYS_DMA_CHANNEL_ID_IDX7> 
</#if>
<#if CONFIG_DRV_I2S_DMA_USE_CHANNEL_CHAINING == true>
<#if CONFIG_DRV_I2S_TX_DMA_CHAINING_CHANNEL_IDX4 == "0">
#define DRV_I2S_TX_DMA_CHAINING_CHANNEL_IDX4	${CONFIG_SYS_DMA_CHANNEL_ID_IDX0}
<#assign DRV_I2S_TX_DMA_CHAINING_CHANNEL_INT_SRC_IDX4 = CONFIG_SYS_DMA_CHANNEL_ID_IDX0> 
</#if>
<#if CONFIG_DRV_I2S_TX_DMA_CHAINING_CHANNEL_IDX4 == "1">
#define DRV_I2S_TX_DMA_CHAINING_CHANNEL_IDX4	${CONFIG_SYS_DMA_CHANNEL_ID_IDX1}
<#assign DRV_I2S_TX_DMA_CHAINING_CHANNEL_INT_SRC_IDX4 = CONFIG_SYS_DMA_CHANNEL_ID_IDX1> 
</#if>
<#if CONFIG_DRV_I2S_TX_DMA_CHAINING_CHANNEL_IDX4 == "2">
#define DRV_I2S_TX_DMA_CHAINING_CHANNEL_IDX4	${CONFIG_SYS_DMA_CHANNEL_ID_IDX2}
<#assign DRV_I2S_TX_DMA_CHAINING_CHANNEL_INT_SRC_IDX4 = CONFIG_SYS_DMA_CHANNEL_ID_IDX2> 
</#if>
<#if CONFIG_DRV_I2S_TX_DMA_CHAINING_CHANNEL_IDX4 == "3">
#define DRV_I2S_TX_DMA_CHAINING_CHANNEL_IDX4	${CONFIG_SYS_DMA_CHANNEL_ID_IDX3}
<#assign DRV_I2S_TX_DMA_CHAINING_CHANNEL_INT_SRC_IDX4 = CONFIG_SYS_DMA_CHANNEL_ID_IDX3> 
</#if>
<#if CONFIG_DRV_I2S_TX_DMA_CHAINING_CHANNEL_IDX4 == "4">
#define DRV_I2S_TX_DMA_CHAINING_CHANNEL_IDX4	${CONFIG_SYS_DMA_CHANNEL_ID_IDX4}
<#assign DRV_I2S_TX_DMA_CHAINING_CHANNEL_INT_SRC_IDX4 = CONFIG_SYS_DMA_CHANNEL_ID_IDX4> 
</#if>
<#if CONFIG_DRV_I2S_TX_DMA_CHAINING_CHANNEL_IDX4 == "5">
#define DRV_I2S_TX_DMA_CHAINING_CHANNEL_IDX4	${CONFIG_SYS_DMA_CHANNEL_ID_IDX5}
<#assign DRV_I2S_TX_DMA_CHAINING_CHANNEL_INT_SRC_IDX4 = CONFIG_SYS_DMA_CHANNEL_ID_IDX5> 
</#if>
<#if CONFIG_DRV_I2S_TX_DMA_CHAINING_CHANNEL_IDX4 == "6">
#define DRV_I2S_TX_DMA_CHAINING_CHANNEL_IDX4	${CONFIG_SYS_DMA_CHANNEL_ID_IDX6}
<#assign DRV_I2S_TX_DMA_CHAINING_CHANNEL_INT_SRC_IDX4 = CONFIG_SYS_DMA_CHANNEL_ID_IDX6> 
</#if>
<#if CONFIG_DRV_I2S_TX_DMA_CHAINING_CHANNEL_IDX4 == "7">
#define DRV_I2S_TX_DMA_CHAINING_CHANNEL_IDX4	${CONFIG_SYS_DMA_CHANNEL_ID_IDX7}
<#assign DRV_I2S_TX_DMA_CHAINING_CHANNEL_INT_SRC_IDX4 = CONFIG_SYS_DMA_CHANNEL_ID_IDX7> 
</#if>
</#if>
<#if CONFIG_DRV_I2S_DMA_INTERRUPTS_ENABLE == true>
<#if DRV_I2S_TX_DMA_CHANNEL_INT_SRC_IDX4 == "DMA_CHANNEL_0">
#define DRV_I2S_TX_DMA_SOURCE_IDX4				INT_SOURCE_DMA_0
</#if>
<#if DRV_I2S_TX_DMA_CHANNEL_INT_SRC_IDX4 == "DMA_CHANNEL_1">
#define DRV_I2S_TX_DMA_SOURCE_IDX4				INT_SOURCE_DMA_1
</#if>
<#if DRV_I2S_TX_DMA_CHANNEL_INT_SRC_IDX4 == "DMA_CHANNEL_2">
#define DRV_I2S_TX_DMA_SOURCE_IDX4				INT_SOURCE_DMA_2
</#if>
<#if DRV_I2S_TX_DMA_CHANNEL_INT_SRC_IDX4 == "DMA_CHANNEL_3">
#define DRV_I2S_TX_DMA_SOURCE_IDX4				INT_SOURCE_DMA_3
</#if>
<#if DRV_I2S_TX_DMA_CHANNEL_INT_SRC_IDX4 == "DMA_CHANNEL_4">
#define DRV_I2S_TX_DMA_SOURCE_IDX4				INT_SOURCE_DMA_4
</#if>
<#if DRV_I2S_TX_DMA_CHANNEL_INT_SRC_IDX4 == "DMA_CHANNEL_5">
#define DRV_I2S_TX_DMA_SOURCE_IDX4				INT_SOURCE_DMA_5
</#if>
<#if DRV_I2S_TX_DMA_CHANNEL_INT_SRC_IDX4 == "DMA_CHANNEL_6">
#define DRV_I2S_TX_DMA_SOURCE_IDX4				INT_SOURCE_DMA_6
</#if>
<#if DRV_I2S_TX_DMA_CHANNEL_INT_SRC_IDX4 == "DMA_CHANNEL_7">
#define DRV_I2S_TX_DMA_SOURCE_IDX4				INT_SOURCE_DMA_7
</#if>
<#if CONFIG_DRV_I2S_DMA_USE_CHANNEL_CHAINING == true>
<#if DRV_I2S_TX_DMA_CHAINING_CHANNEL_INT_SRC_IDX4 == "DMA_CHANNEL_0">
#define DRV_I2S_TX_DMA_CHAINING_SOURCE_IDX4		INT_SOURCE_DMA_0
</#if>
<#if DRV_I2S_TX_DMA_CHAINING_CHANNEL_INT_SRC_IDX4 == "DMA_CHANNEL_1">
#define DRV_I2S_TX_DMA_CHAINING_SOURCE_IDX4		INT_SOURCE_DMA_1
</#if>
<#if DRV_I2S_TX_DMA_CHAINING_CHANNEL_INT_SRC_IDX4 == "DMA_CHANNEL_2">
#define DRV_I2S_TX_DMA_CHAINING_SOURCE_IDX4		INT_SOURCE_DMA_2
</#if>
<#if DRV_I2S_TX_DMA_CHAINING_CHANNEL_INT_SRC_IDX4 == "DMA_CHANNEL_3">
#define DRV_I2S_TX_DMA_CHAINING_SOURCE_IDX4		INT_SOURCE_DMA_3
</#if>
<#if DRV_I2S_TX_DMA_CHAINING_CHANNEL_INT_SRC_IDX4 == "DMA_CHANNEL_4">
#define DRV_I2S_TX_DMA_CHAINING_SOURCE_IDX4		INT_SOURCE_DMA_4
</#if>
<#if DRV_I2S_TX_DMA_CHAINING_CHANNEL_INT_SRC_IDX4 == "DMA_CHANNEL_5">
#define DRV_I2S_TX_DMA_CHAINING_SOURCE_IDX4		INT_SOURCE_DMA_5
</#if>
<#if DRV_I2S_TX_DMA_CHAINING_CHANNEL_INT_SRC_IDX4 == "DMA_CHANNEL_6">
#define DRV_I2S_TX_DMA_CHAINING_SOURCE_IDX4		INT_SOURCE_DMA_6
</#if>
<#if DRV_I2S_TX_DMA_CHAINING_CHANNEL_INT_SRC_IDX4 == "DMA_CHANNEL_7">
#define DRV_I2S_TX_DMA_CHAINING_SOURCE_IDX4		INT_SOURCE_DMA_7
</#if>
</#if>
</#if>
</#if>
<#if CONFIG_DRV_I2S_SUPPORT_RECEIVE_DMA == true>
<#if CONFIG_DRV_I2S_RX_DMA_CHANNEL_IDX4 == "0">
#define DRV_I2S_RX_DMA_CHANNEL_IDX4				${CONFIG_SYS_DMA_CHANNEL_ID_IDX0}
<#assign DRV_I2S_RX_DMA_CHANNEL_INT_SRC_IDX4 = CONFIG_SYS_DMA_CHANNEL_ID_IDX0> 
</#if>
<#if CONFIG_DRV_I2S_RX_DMA_CHANNEL_IDX4 == "1">
#define DRV_I2S_RX_DMA_CHANNEL_IDX4				${CONFIG_SYS_DMA_CHANNEL_ID_IDX1}
<#assign DRV_I2S_RX_DMA_CHANNEL_INT_SRC_IDX4 = CONFIG_SYS_DMA_CHANNEL_ID_IDX1> 
</#if>
<#if CONFIG_DRV_I2S_RX_DMA_CHANNEL_IDX4 == "2">
#define DRV_I2S_RX_DMA_CHANNEL_IDX4				${CONFIG_SYS_DMA_CHANNEL_ID_IDX2}
<#assign DRV_I2S_RX_DMA_CHANNEL_INT_SRC_IDX4 = CONFIG_SYS_DMA_CHANNEL_ID_IDX2> 
</#if>
<#if CONFIG_DRV_I2S_RX_DMA_CHANNEL_IDX4 == "3">
#define DRV_I2S_RX_DMA_CHANNEL_IDX4				${CONFIG_SYS_DMA_CHANNEL_ID_IDX3}
<#assign DRV_I2S_RX_DMA_CHANNEL_INT_SRC_IDX4 = CONFIG_SYS_DMA_CHANNEL_ID_IDX3> 
</#if>
<#if CONFIG_DRV_I2S_RX_DMA_CHANNEL_IDX4 == "4">
#define DRV_I2S_RX_DMA_CHANNEL_IDX4				${CONFIG_SYS_DMA_CHANNEL_ID_IDX4}
<#assign DRV_I2S_RX_DMA_CHANNEL_INT_SRC_IDX4 = CONFIG_SYS_DMA_CHANNEL_ID_IDX4> 
</#if>
<#if CONFIG_DRV_I2S_RX_DMA_CHANNEL_IDX4 == "5">
#define DRV_I2S_RX_DMA_CHANNEL_IDX4				${CONFIG_SYS_DMA_CHANNEL_ID_IDX5}
<#assign DRV_I2S_RX_DMA_CHANNEL_INT_SRC_IDX4 = CONFIG_SYS_DMA_CHANNEL_ID_IDX5> 
</#if>
<#if CONFIG_DRV_I2S_RX_DMA_CHANNEL_IDX4 == "6">
#define DRV_I2S_RX_DMA_CHANNEL_IDX4				${CONFIG_SYS_DMA_CHANNEL_ID_IDX6}
<#assign DRV_I2S_RX_DMA_CHANNEL_INT_SRC_IDX4 = CONFIG_SYS_DMA_CHANNEL_ID_IDX6> 
</#if>
<#if CONFIG_DRV_I2S_RX_DMA_CHANNEL_IDX4 == "7">
#define DRV_I2S_RX_DMA_CHANNEL_IDX4				${CONFIG_SYS_DMA_CHANNEL_ID_IDX7}
<#assign DRV_I2S_RX_DMA_CHANNEL_INT_SRC_IDX4 = CONFIG_SYS_DMA_CHANNEL_ID_IDX7> 
</#if>
<#if CONFIG_DRV_I2S_DMA_USE_CHANNEL_CHAINING == true>
<#if CONFIG_DRV_I2S_RX_DMA_CHAINING_CHANNEL_IDX4 == "0">
#define DRV_I2S_RX_DMA_CHAINING_CHANNEL_IDX4	${CONFIG_SYS_DMA_CHANNEL_ID_IDX0}
<#assign DRV_I2S_RX_DMA_CHAINING_CHANNEL_INT_SRC_IDX4 = CONFIG_SYS_DMA_CHANNEL_ID_IDX0> 
</#if>
<#if CONFIG_DRV_I2S_RX_DMA_CHAINING_CHANNEL_IDX4 == "1">
#define DRV_I2S_RX_DMA_CHAINING_CHANNEL_IDX4	${CONFIG_SYS_DMA_CHANNEL_ID_IDX1}
<#assign DRV_I2S_RX_DMA_CHAINING_CHANNEL_INT_SRC_IDX4 = CONFIG_SYS_DMA_CHANNEL_ID_IDX1> 
</#if>
<#if CONFIG_DRV_I2S_RX_DMA_CHAINING_CHANNEL_IDX4 == "2">
#define DRV_I2S_RX_DMA_CHAINING_CHANNEL_IDX4	${CONFIG_SYS_DMA_CHANNEL_ID_IDX2}
<#assign DRV_I2S_RX_DMA_CHAINING_CHANNEL_INT_SRC_IDX4 = CONFIG_SYS_DMA_CHANNEL_ID_IDX2> 
</#if>
<#if CONFIG_DRV_I2S_RX_DMA_CHAINING_CHANNEL_IDX4 == "3">
#define DRV_I2S_RX_DMA_CHAINING_CHANNEL_IDX4	${CONFIG_SYS_DMA_CHANNEL_ID_IDX3}
<#assign DRV_I2S_RX_DMA_CHAINING_CHANNEL_INT_SRC_IDX4 = CONFIG_SYS_DMA_CHANNEL_ID_IDX3> 
</#if>
<#if CONFIG_DRV_I2S_RX_DMA_CHAINING_CHANNEL_IDX4 == "4">
#define DRV_I2S_RX_DMA_CHAINING_CHANNEL_IDX4	${CONFIG_SYS_DMA_CHANNEL_ID_IDX4}
<#assign DRV_I2S_RX_DMA_CHAINING_CHANNEL_INT_SRC_IDX4 = CONFIG_SYS_DMA_CHANNEL_ID_IDX4> 
</#if>
<#if CONFIG_DRV_I2S_RX_DMA_CHAINING_CHANNEL_IDX4 == "5">
#define DRV_I2S_RX_DMA_CHAINING_CHANNEL_IDX4	${CONFIG_SYS_DMA_CHANNEL_ID_IDX5}
<#assign DRV_I2S_RX_DMA_CHAINING_CHANNEL_INT_SRC_IDX4 = CONFIG_SYS_DMA_CHANNEL_ID_IDX5> 
</#if>
<#if CONFIG_DRV_I2S_RX_DMA_CHAINING_CHANNEL_IDX4 == "6">
#define DRV_I2S_RX_DMA_CHAINING_CHANNEL_IDX4	${CONFIG_SYS_DMA_CHANNEL_ID_IDX6}
<#assign DRV_I2S_RX_DMA_CHAINING_CHANNEL_INT_SRC_IDX4 = CONFIG_SYS_DMA_CHANNEL_ID_IDX6> 
</#if>
<#if CONFIG_DRV_I2S_RX_DMA_CHAINING_CHANNEL_IDX4 == "7">
#define DRV_I2S_RX_DMA_CHAINING_CHANNEL_IDX4	${CONFIG_SYS_DMA_CHANNEL_ID_IDX7}
<#assign DRV_I2S_RX_DMA_CHAINING_CHANNEL_INT_SRC_IDX4 = CONFIG_SYS_DMA_CHANNEL_ID_IDX7> 
</#if>
</#if>
<#if CONFIG_DRV_I2S_DMA_INTERRUPTS_ENABLE == true>
<#if DRV_I2S_RX_DMA_CHANNEL_INT_SRC_IDX4 == "DMA_CHANNEL_0">
#define DRV_I2S_RX_DMA_SOURCE_IDX4				INT_SOURCE_DMA_0
</#if>
<#if DRV_I2S_RX_DMA_CHANNEL_INT_SRC_IDX4 == "DMA_CHANNEL_1">
#define DRV_I2S_RX_DMA_SOURCE_IDX4				INT_SOURCE_DMA_1
</#if>
<#if DRV_I2S_RX_DMA_CHANNEL_INT_SRC_IDX4 == "DMA_CHANNEL_2">
#define DRV_I2S_RX_DMA_SOURCE_IDX4				INT_SOURCE_DMA_2
</#if>
<#if DRV_I2S_RX_DMA_CHANNEL_INT_SRC_IDX4 == "DMA_CHANNEL_3">
#define DRV_I2S_RX_DMA_SOURCE_IDX4				INT_SOURCE_DMA_3
</#if>
<#if DRV_I2S_RX_DMA_CHANNEL_INT_SRC_IDX4 == "DMA_CHANNEL_4">
#define DRV_I2S_RX_DMA_SOURCE_IDX4				INT_SOURCE_DMA_4
</#if>
<#if DRV_I2S_RX_DMA_CHANNEL_INT_SRC_IDX4 == "DMA_CHANNEL_5">
#define DRV_I2S_RX_DMA_SOURCE_IDX4				INT_SOURCE_DMA_5
</#if>
<#if DRV_I2S_RX_DMA_CHANNEL_INT_SRC_IDX4 == "DMA_CHANNEL_6">
#define DRV_I2S_RX_DMA_SOURCE_IDX4				INT_SOURCE_DMA_6
</#if>
<#if DRV_I2S_RX_DMA_CHANNEL_INT_SRC_IDX4 == "DMA_CHANNEL_7">
#define DRV_I2S_RX_DMA_SOURCE_IDX4				INT_SOURCE_DMA_7
</#if>
<#if CONFIG_DRV_I2S_DMA_USE_CHANNEL_CHAINING == true>
<#if DRV_I2S_RX_DMA_CHAINING_CHANNEL_INT_SRC_IDX0 == "DMA_CHANNEL_0">
#define DRV_I2S_RX_DMA_CHAINING_SOURCE_IDX4		INT_SOURCE_DMA_0
</#if>
<#if DRV_I2S_RX_DMA_CHAINING_CHANNEL_INT_SRC_IDX4 == "DMA_CHANNEL_1">
#define DRV_I2S_RX_DMA_CHAINING_SOURCE_IDX4		INT_SOURCE_DMA_1
</#if>
<#if DRV_I2S_RX_DMA_CHAINING_CHANNEL_INT_SRC_IDX4 == "DMA_CHANNEL_2">
#define DRV_I2S_RX_DMA_CHAINING_SOURCE_IDX4		INT_SOURCE_DMA_2
</#if>
<#if DRV_I2S_RX_DMA_CHAINING_CHANNEL_INT_SRC_IDX4 == "DMA_CHANNEL_3">
#define DRV_I2S_RX_DMA_CHAINING_SOURCE_IDX4		INT_SOURCE_DMA_3
</#if>
<#if DRV_I2S_RX_DMA_CHAINING_CHANNEL_INT_SRC_IDX4 == "DMA_CHANNEL_4">
#define DRV_I2S_RX_DMA_CHAINING_SOURCE_IDX4		INT_SOURCE_DMA_4
</#if>
<#if DRV_I2S_RX_DMA_CHAINING_CHANNEL_INT_SRC_IDX4 == "DMA_CHANNEL_5">
#define DRV_I2S_RX_DMA_CHAINING_SOURCE_IDX4		INT_SOURCE_DMA_5
</#if>
<#if DRV_I2S_RX_DMA_CHAINING_CHANNEL_INT_SRC_IDX4 == "DMA_CHANNEL_6">
#define DRV_I2S_RX_DMA_CHAINING_SOURCE_IDX4		INT_SOURCE_DMA_6
</#if>
<#if DRV_I2S_RX_DMA_CHAINING_CHANNEL_INT_SRC_IDX4 == "DMA_CHANNEL_7">
#define DRV_I2S_RX_DMA_CHAINING_SOURCE_IDX4		INT_SOURCE_DMA_7
</#if>
</#if>
</#if>
</#if>
#define DRV_I2S_POWER_STATE_IDX4				${CONFIG_DRV_I2S_POWER_STATE_IDX4}
</#if>
<#-- Instance 5 -->
<#if CONFIG_DRV_I2S_INST_IDX5 == true>
#define DRV_I2S_PERIPHERAL_ID_IDX5				${CONFIG_DRV_I2S_PERIPHERAL_ID_IDX5}
#define DRV_I2S_USAGE_MODE_IDX5					${CONFIG_DRV_I2S_USAGE_MODE_IDX5}
<#if CONFIG_DRV_I2S_STOP_IN_IDLE_IDX5 == true>
#define DRV_I2S_STOP_IN_IDLE_IDX5				true
#else
#define DRV_I2S_STOP_IN_IDLE_IDX5				false
</#if>
#define SPI_BAUD_RATE_CLK_IDX5					${CONFIG_SPI_BAUD_RATE_CLK_IDX5}
#define BAUD_RATE_IDX5                          ${CONFIG_DRV_I2S_BAUD_RATE}
#define DRV_I2S_CLK_MODE_IDX5					${CONFIG_DRV_I2S_CLK_MODE_IDX5}
#define SPI_AUDIO_COMM_WIDTH_IDX5				${CONFIG_SPI_AUDIO_COMM_WIDTH_IDX5}
#define SPI_AUDIO_TRANSMIT_MODE_IDX5			${CONFIG_SPI_AUDIO_TRANSMIT_MODE_IDX5}
#define SPI_INPUT_SAMPLING_PHASE_IDX5			${CONFIG_SPI_INPUT_SAMPLING_PHASE_IDX5}
#define DRV_I2S_AUDIO_PROTOCOL_MODE_IDX5        ${CONFIG_DRV_I2S_AUDIO_PROTOCOL_MODE_IDX5}
<#if CONFIG_DRV_I2S_DMA_INTERRUPTS_ENABLE == true>
#define DRV_I2S_TX_INT_SRC_IDX5					${CONFIG_DRV_I2S_TX_INT_SRC_IDX5}
#define DRV_I2S_RX_INT_SRC_IDX5					${CONFIG_DRV_I2S_RX_INT_SRC_IDX5}
</#if>
<#if CONFIG_DRV_I2S_INTERRUPT_MODE == true>
#define DRV_I2S_TX_INT_SRC_IDX5					${CONFIG_DRV_I2S_TX_INT_SRC_IDX5}
#define DRV_I2S_RX_INT_SRC_IDX5					${CONFIG_DRV_I2S_RX_INT_SRC_IDX5}
#define DRV_I2S_ERR_INT_SRC_IDX5				${CONFIG_DRV_I2S_ERR_INT_SRC_IDX5}
<#if CONFIG_PIC32MX == true>
#define DRV_I2S_ISR_VECTOR_IDX5					${CONFIG_DRV_I2S_ISR_VECTOR_IDX5}
#define DRV_I2S_INT_VECTOR_IDX5					${CONFIG_DRV_I2S_INT_VECTOR_IDX5}
#define DRV_I2S_INT_PRIORITY_IDX5				${CONFIG_DRV_I2S_INT_PRIORITY_IDX5}
#define DRV_I2S_INT_SUB_PRIORITY_IDX5			${CONFIG_DRV_I2S_INT_SUB_PRIORITY_IDX5}
<#else>
#define DRV_I2S_TX_INT_VECTOR_IDX5				${CONFIG_DRV_I2S_TX_INT_VECTOR_IDX5}
#define DRV_I2S_TX_INT_PRIORITY_IDX5			${CONFIG_DRV_I2S_TX_INT_PRIORITY_IDX5}
#define DRV_I2S_TX_INT_SUB_PRIORITY_IDX5		${CONFIG_DRV_I2S_TX_INT_SUB_PRIORITY_IDX5}
#define DRV_I2S_TX_ISR_VECTOR_IDX5				${CONFIG_DRV_I2S_TX_ISR_VECTOR_IDX5}
#define DRV_I2S_RX_INT_VECTOR_IDX5				${CONFIG_DRV_I2S_RX_INT_VECTOR_IDX5}
#define DRV_I2S_RX_INT_PRIORITY_IDX5			${CONFIG_DRV_I2S_RX_INT_PRIORITY_IDX5}
#define DRV_I2S_RX_INT_SUB_PRIORITY_IDX5		${CONFIG_DRV_I2S_RX_INT_SUB_PRIORITY_IDX5}
#define DRV_I2S_RX_ISR_VECTOR_IDX5				${CONFIG_DRV_I2S_RX_ISR_VECTOR_IDX5}
#define DRV_I2S_ERR_INT_VECTOR_IDX5				${CONFIG_DRV_I2S_ERR_INT_VECTOR_IDX5}
#define DRV_I2S_ERR_INT_PRIORITY_IDX5			${CONFIG_DRV_I2S_ERR_INT_PRIORITY_IDX5}
#define DRV_I2S_ERR_INT_SUB_PRIORITY_IDX5		${CONFIG_DRV_I2S_ERR_INT_SUB_PRIORITY_IDX5}
#define DRV_I2S_ERR_ISR_VECTOR_IDX5				${CONFIG_DRV_I2S_ERR_ISR_VECTOR_IDX5}
</#if>
</#if> 
#define QUEUE_SIZE_TX_IDX5                      ${CONFIG_QUEUE_SIZE_TX_IDX5}
#define QUEUE_SIZE_RX_IDX5                      ${CONFIG_QUEUE_SIZE_RX_IDX5}
<#assign i2sCombinedQueueSizeOfAllInstances = i2sCombinedQueueSizeOfAllInstances + CONFIG_QUEUE_SIZE_TX_IDX5?number >
<#assign i2sCombinedQueueSizeOfAllInstances = i2sCombinedQueueSizeOfAllInstances + CONFIG_QUEUE_SIZE_TX_IDX5?number>
<#if CONFIG_DRV_I2S_SUPPORT_TRANSMIT_DMA == true>
<#if CONFIG_DRV_I2S_TX_DMA_CHANNEL_IDX5 == "0">
#define DRV_I2S_TX_DMA_CHANNEL_IDX5				${CONFIG_SYS_DMA_CHANNEL_ID_IDX0}
<#assign DRV_I2S_TX_DMA_CHANNEL_INT_SRC_IDX5 = CONFIG_SYS_DMA_CHANNEL_ID_IDX0> 
</#if>
<#if CONFIG_DRV_I2S_TX_DMA_CHANNEL_IDX5 == "1">
#define DRV_I2S_TX_DMA_CHANNEL_IDX5				${CONFIG_SYS_DMA_CHANNEL_ID_IDX1}
<#assign DRV_I2S_TX_DMA_CHANNEL_INT_SRC_IDX5 = CONFIG_SYS_DMA_CHANNEL_ID_IDX1> 
</#if>
<#if CONFIG_DRV_I2S_TX_DMA_CHANNEL_IDX5 == "2">
#define DRV_I2S_TX_DMA_CHANNEL_IDX5				${CONFIG_SYS_DMA_CHANNEL_ID_IDX2}
<#assign DRV_I2S_TX_DMA_CHANNEL_INT_SRC_IDX5 = CONFIG_SYS_DMA_CHANNEL_ID_IDX2> 
</#if>
<#if CONFIG_DRV_I2S_TX_DMA_CHANNEL_IDX5 == "3">
#define DRV_I2S_TX_DMA_CHANNEL_IDX5				${CONFIG_SYS_DMA_CHANNEL_ID_IDX3}
<#assign DRV_I2S_TX_DMA_CHANNEL_INT_SRC_IDX5 = CONFIG_SYS_DMA_CHANNEL_ID_IDX3> 
</#if>
<#if CONFIG_DRV_I2S_TX_DMA_CHANNEL_IDX5 == "4">
#define DRV_I2S_TX_DMA_CHANNEL_IDX5				${CONFIG_SYS_DMA_CHANNEL_ID_IDX4}
<#assign DRV_I2S_TX_DMA_CHANNEL_INT_SRC_IDX5 = CONFIG_SYS_DMA_CHANNEL_ID_IDX4> 
</#if>
<#if CONFIG_DRV_I2S_TX_DMA_CHANNEL_IDX5 == "5">
#define DRV_I2S_TX_DMA_CHANNEL_IDX5				${CONFIG_SYS_DMA_CHANNEL_ID_IDX5}
<#assign DRV_I2S_TX_DMA_CHANNEL_INT_SRC_IDX5 = CONFIG_SYS_DMA_CHANNEL_ID_IDX5> 
</#if>
<#if CONFIG_DRV_I2S_TX_DMA_CHANNEL_IDX5 == "6">
#define DRV_I2S_TX_DMA_CHANNEL_IDX5				${CONFIG_SYS_DMA_CHANNEL_ID_IDX6}
<#assign DRV_I2S_TX_DMA_CHANNEL_INT_SRC_IDX5 = CONFIG_SYS_DMA_CHANNEL_ID_IDX6> 
</#if>
<#if CONFIG_DRV_I2S_TX_DMA_CHANNEL_IDX5 == "7">
#define DRV_I2S_TX_DMA_CHANNEL_IDX5				${CONFIG_SYS_DMA_CHANNEL_ID_IDX7}
<#assign DRV_I2S_TX_DMA_CHANNEL_INT_SRC_IDX5 = CONFIG_SYS_DMA_CHANNEL_ID_IDX7> 
</#if>
<#if CONFIG_DRV_I2S_DMA_USE_CHANNEL_CHAINING == true>
<#if CONFIG_DRV_I2S_TX_DMA_CHAINING_CHANNEL_IDX5 == "0">
#define DRV_I2S_TX_DMA_CHAINING_CHANNEL_IDX5	${CONFIG_SYS_DMA_CHANNEL_ID_IDX0}
<#assign DRV_I2S_TX_DMA_CHAINING_CHANNEL_INT_SRC_IDX5 = CONFIG_SYS_DMA_CHANNEL_ID_IDX0> 
</#if>
<#if CONFIG_DRV_I2S_TX_DMA_CHAINING_CHANNEL_IDX5 == "1">
#define DRV_I2S_TX_DMA_CHAINING_CHANNEL_IDX5	${CONFIG_SYS_DMA_CHANNEL_ID_IDX1}
<#assign DRV_I2S_TX_DMA_CHAINING_CHANNEL_INT_SRC_IDX5 = CONFIG_SYS_DMA_CHANNEL_ID_IDX1> 
</#if>
<#if CONFIG_DRV_I2S_TX_DMA_CHAINING_CHANNEL_IDX5 == "2">
#define DRV_I2S_TX_DMA_CHAINING_CHANNEL_IDX5	${CONFIG_SYS_DMA_CHANNEL_ID_IDX2}
<#assign DRV_I2S_TX_DMA_CHAINING_CHANNEL_INT_SRC_IDX5 = CONFIG_SYS_DMA_CHANNEL_ID_IDX2> 
</#if>
<#if CONFIG_DRV_I2S_TX_DMA_CHAINING_CHANNEL_IDX5 == "3">
#define DRV_I2S_TX_DMA_CHAINING_CHANNEL_IDX5	${CONFIG_SYS_DMA_CHANNEL_ID_IDX3}
<#assign DRV_I2S_TX_DMA_CHAINING_CHANNEL_INT_SRC_IDX5 = CONFIG_SYS_DMA_CHANNEL_ID_IDX3> 
</#if>
<#if CONFIG_DRV_I2S_TX_DMA_CHAINING_CHANNEL_IDX5 == "4">
#define DRV_I2S_TX_DMA_CHAINING_CHANNEL_IDX5	${CONFIG_SYS_DMA_CHANNEL_ID_IDX4}
<#assign DRV_I2S_TX_DMA_CHAINING_CHANNEL_INT_SRC_IDX5 = CONFIG_SYS_DMA_CHANNEL_ID_IDX4> 
</#if>
<#if CONFIG_DRV_I2S_TX_DMA_CHAINING_CHANNEL_IDX5 == "5">
#define DRV_I2S_TX_DMA_CHAINING_CHANNEL_IDX5	${CONFIG_SYS_DMA_CHANNEL_ID_IDX5}
<#assign DRV_I2S_TX_DMA_CHAINING_CHANNEL_INT_SRC_IDX5 = CONFIG_SYS_DMA_CHANNEL_ID_IDX5> 
</#if>
<#if CONFIG_DRV_I2S_TX_DMA_CHAINING_CHANNEL_IDX5 == "6">
#define DRV_I2S_TX_DMA_CHAINING_CHANNEL_IDX5	${CONFIG_SYS_DMA_CHANNEL_ID_IDX6}
<#assign DRV_I2S_TX_DMA_CHAINING_CHANNEL_INT_SRC_IDX5 = CONFIG_SYS_DMA_CHANNEL_ID_IDX6> 
</#if>
<#if CONFIG_DRV_I2S_TX_DMA_CHAINING_CHANNEL_IDX5 == "7">
#define DRV_I2S_TX_DMA_CHAINING_CHANNEL_IDX5	${CONFIG_SYS_DMA_CHANNEL_ID_IDX7}
<#assign DRV_I2S_TX_DMA_CHAINING_CHANNEL_INT_SRC_IDX5 = CONFIG_SYS_DMA_CHANNEL_ID_IDX7> 
</#if>
</#if>
<#if CONFIG_DRV_I2S_DMA_INTERRUPTS_ENABLE == true>
<#if DRV_I2S_TX_DMA_CHANNEL_INT_SRC_IDX5 == "DMA_CHANNEL_0">
#define DRV_I2S_TX_DMA_SOURCE_IDX5				INT_SOURCE_DMA_0
</#if>
<#if DRV_I2S_TX_DMA_CHANNEL_INT_SRC_IDX5 == "DMA_CHANNEL_1">
#define DRV_I2S_TX_DMA_SOURCE_IDX5				INT_SOURCE_DMA_1
</#if>
<#if DRV_I2S_TX_DMA_CHANNEL_INT_SRC_IDX5 == "DMA_CHANNEL_2">
#define DRV_I2S_TX_DMA_SOURCE_IDX5				INT_SOURCE_DMA_2
</#if>
<#if DRV_I2S_TX_DMA_CHANNEL_INT_SRC_IDX5 == "DMA_CHANNEL_3">
#define DRV_I2S_TX_DMA_SOURCE_IDX5				INT_SOURCE_DMA_3
</#if>
<#if DRV_I2S_TX_DMA_CHANNEL_INT_SRC_IDX5 == "DMA_CHANNEL_4">
#define DRV_I2S_TX_DMA_SOURCE_IDX5				INT_SOURCE_DMA_4
</#if>
<#if DRV_I2S_TX_DMA_CHANNEL_INT_SRC_IDX5 == "DMA_CHANNEL_5">
#define DRV_I2S_TX_DMA_SOURCE_IDX5				INT_SOURCE_DMA_5
</#if>
<#if DRV_I2S_TX_DMA_CHANNEL_INT_SRC_IDX5 == "DMA_CHANNEL_6">
#define DRV_I2S_TX_DMA_SOURCE_IDX5				INT_SOURCE_DMA_6
</#if>
<#if DRV_I2S_TX_DMA_CHANNEL_INT_SRC_IDX5 == "DMA_CHANNEL_7">
#define DRV_I2S_TX_DMA_SOURCE_IDX5				INT_SOURCE_DMA_7
</#if>
<#if CONFIG_DRV_I2S_DMA_USE_CHANNEL_CHAINING == true>
<#if DRV_I2S_TX_DMA_CHAINING_CHANNEL_INT_SRC_IDX5 == "DMA_CHANNEL_0">
#define DRV_I2S_TX_DMA_CHAINING_SOURCE_IDX5		INT_SOURCE_DMA_0
</#if>
<#if DRV_I2S_TX_DMA_CHAINING_CHANNEL_INT_SRC_IDX5 == "DMA_CHANNEL_1">
#define DRV_I2S_TX_DMA_CHAINING_SOURCE_IDX5		INT_SOURCE_DMA_1
</#if>
<#if DRV_I2S_TX_DMA_CHAINING_CHANNEL_INT_SRC_IDX5 == "DMA_CHANNEL_2">
#define DRV_I2S_TX_DMA_CHAINING_SOURCE_IDX5		INT_SOURCE_DMA_2
</#if>
<#if DRV_I2S_TX_DMA_CHAINING_CHANNEL_INT_SRC_IDX5 == "DMA_CHANNEL_3">
#define DRV_I2S_TX_DMA_CHAINING_SOURCE_IDX5		INT_SOURCE_DMA_3
</#if>
<#if DRV_I2S_TX_DMA_CHAINING_CHANNEL_INT_SRC_IDX5 == "DMA_CHANNEL_4">
#define DRV_I2S_TX_DMA_CHAINING_SOURCE_IDX5		INT_SOURCE_DMA_4
</#if>
<#if DRV_I2S_TX_DMA_CHAINING_CHANNEL_INT_SRC_IDX5 == "DMA_CHANNEL_5">
#define DRV_I2S_TX_DMA_CHAINING_SOURCE_IDX5		INT_SOURCE_DMA_5
</#if>
<#if DRV_I2S_TX_DMA_CHAINING_CHANNEL_INT_SRC_IDX5 == "DMA_CHANNEL_6">
#define DRV_I2S_TX_DMA_CHAINING_SOURCE_IDX5		INT_SOURCE_DMA_6
</#if>
<#if DRV_I2S_TX_DMA_CHAINING_CHANNEL_INT_SRC_IDX5 == "DMA_CHANNEL_7">
#define DRV_I2S_TX_DMA_CHAINING_SOURCE_IDX5		INT_SOURCE_DMA_7
</#if>
</#if>
</#if>
</#if>
<#if CONFIG_DRV_I2S_SUPPORT_RECEIVE_DMA == true>
<#if CONFIG_DRV_I2S_RX_DMA_CHANNEL_IDX5 == "0">
#define DRV_I2S_RX_DMA_CHANNEL_IDX5				${CONFIG_SYS_DMA_CHANNEL_ID_IDX0}
<#assign DRV_I2S_RX_DMA_CHANNEL_INT_SRC_IDX5 = CONFIG_SYS_DMA_CHANNEL_ID_IDX0> 
</#if>
<#if CONFIG_DRV_I2S_RX_DMA_CHANNEL_IDX5 == "1">
#define DRV_I2S_RX_DMA_CHANNEL_IDX5				${CONFIG_SYS_DMA_CHANNEL_ID_IDX1}
<#assign DRV_I2S_RX_DMA_CHANNEL_INT_SRC_IDX5 = CONFIG_SYS_DMA_CHANNEL_ID_IDX1> 
</#if>
<#if CONFIG_DRV_I2S_RX_DMA_CHANNEL_IDX5 == "2">
#define DRV_I2S_RX_DMA_CHANNEL_IDX5				${CONFIG_SYS_DMA_CHANNEL_ID_IDX2}
<#assign DRV_I2S_RX_DMA_CHANNEL_INT_SRC_IDX5 = CONFIG_SYS_DMA_CHANNEL_ID_IDX2> 
</#if>
<#if CONFIG_DRV_I2S_RX_DMA_CHANNEL_IDX5 == "3">
#define DRV_I2S_RX_DMA_CHANNEL_IDX5				${CONFIG_SYS_DMA_CHANNEL_ID_IDX3}
<#assign DRV_I2S_RX_DMA_CHANNEL_INT_SRC_IDX5 = CONFIG_SYS_DMA_CHANNEL_ID_IDX3> 
</#if>
<#if CONFIG_DRV_I2S_RX_DMA_CHANNEL_IDX5 == "4">
#define DRV_I2S_RX_DMA_CHANNEL_IDX5				${CONFIG_SYS_DMA_CHANNEL_ID_IDX4}
<#assign DRV_I2S_RX_DMA_CHANNEL_INT_SRC_IDX5 = CONFIG_SYS_DMA_CHANNEL_ID_IDX4> 
</#if>
<#if CONFIG_DRV_I2S_RX_DMA_CHANNEL_IDX5 == "5">
#define DRV_I2S_RX_DMA_CHANNEL_IDX5				${CONFIG_SYS_DMA_CHANNEL_ID_IDX5}
<#assign DRV_I2S_RX_DMA_CHANNEL_INT_SRC_IDX5 = CONFIG_SYS_DMA_CHANNEL_ID_IDX5> 
</#if>
<#if CONFIG_DRV_I2S_RX_DMA_CHANNEL_IDX5 == "6">
#define DRV_I2S_RX_DMA_CHANNEL_IDX5				${CONFIG_SYS_DMA_CHANNEL_ID_IDX6}
<#assign DRV_I2S_RX_DMA_CHANNEL_INT_SRC_IDX5 = CONFIG_SYS_DMA_CHANNEL_ID_IDX6> 
</#if>
<#if CONFIG_DRV_I2S_RX_DMA_CHANNEL_IDX5 == "7">
#define DRV_I2S_RX_DMA_CHANNEL_IDX5				${CONFIG_SYS_DMA_CHANNEL_ID_IDX7}
<#assign DRV_I2S_RX_DMA_CHANNEL_INT_SRC_IDX5 = CONFIG_SYS_DMA_CHANNEL_ID_IDX7> 
</#if>
<#if CONFIG_DRV_I2S_DMA_USE_CHANNEL_CHAINING == true>
<#if CONFIG_DRV_I2S_RX_DMA_CHAINING_CHANNEL_IDX5 == "0">
#define DRV_I2S_RX_DMA_CHAINING_CHANNEL_IDX5	${CONFIG_SYS_DMA_CHANNEL_ID_IDX0}
<#assign DRV_I2S_RX_DMA_CHAINING_CHANNEL_INT_SRC_IDX5 = CONFIG_SYS_DMA_CHANNEL_ID_IDX0> 
</#if>
<#if CONFIG_DRV_I2S_RX_DMA_CHAINING_CHANNEL_IDX5 == "1">
#define DRV_I2S_RX_DMA_CHAINING_CHANNEL_IDX5	${CONFIG_SYS_DMA_CHANNEL_ID_IDX1}
<#assign DRV_I2S_RX_DMA_CHAINING_CHANNEL_INT_SRC_IDX5 = CONFIG_SYS_DMA_CHANNEL_ID_IDX1> 
</#if>
<#if CONFIG_DRV_I2S_RX_DMA_CHAINING_CHANNEL_IDX5 == "2">
#define DRV_I2S_RX_DMA_CHAINING_CHANNEL_IDX5	${CONFIG_SYS_DMA_CHANNEL_ID_IDX2}
<#assign DRV_I2S_RX_DMA_CHAINING_CHANNEL_INT_SRC_IDX5 = CONFIG_SYS_DMA_CHANNEL_ID_IDX2> 
</#if>
<#if CONFIG_DRV_I2S_RX_DMA_CHAINING_CHANNEL_IDX5 == "3">
#define DRV_I2S_RX_DMA_CHAINING_CHANNEL_IDX5	${CONFIG_SYS_DMA_CHANNEL_ID_IDX3}
<#assign DRV_I2S_RX_DMA_CHAINING_CHANNEL_INT_SRC_IDX5 = CONFIG_SYS_DMA_CHANNEL_ID_IDX3> 
</#if>
<#if CONFIG_DRV_I2S_RX_DMA_CHAINING_CHANNEL_IDX5 == "4">
#define DRV_I2S_RX_DMA_CHAINING_CHANNEL_IDX5	${CONFIG_SYS_DMA_CHANNEL_ID_IDX4}
<#assign DRV_I2S_RX_DMA_CHAINING_CHANNEL_INT_SRC_IDX5 = CONFIG_SYS_DMA_CHANNEL_ID_IDX4> 
</#if>
<#if CONFIG_DRV_I2S_RX_DMA_CHAINING_CHANNEL_IDX5 == "5">
#define DRV_I2S_RX_DMA_CHAINING_CHANNEL_IDX5	${CONFIG_SYS_DMA_CHANNEL_ID_IDX5}
<#assign DRV_I2S_RX_DMA_CHAINING_CHANNEL_INT_SRC_IDX5 = CONFIG_SYS_DMA_CHANNEL_ID_IDX5> 
</#if>
<#if CONFIG_DRV_I2S_RX_DMA_CHAINING_CHANNEL_IDX5 == "6">
#define DRV_I2S_RX_DMA_CHAINING_CHANNEL_IDX5	${CONFIG_SYS_DMA_CHANNEL_ID_IDX6}
<#assign DRV_I2S_RX_DMA_CHAINING_CHANNEL_INT_SRC_IDX5 = CONFIG_SYS_DMA_CHANNEL_ID_IDX6> 
</#if>
<#if CONFIG_DRV_I2S_RX_DMA_CHAINING_CHANNEL_IDX5 == "7">
#define DRV_I2S_RX_DMA_CHAINING_CHANNEL_IDX5	${CONFIG_SYS_DMA_CHANNEL_ID_IDX7}
<#assign DRV_I2S_RX_DMA_CHAINING_CHANNEL_INT_SRC_IDX5 = CONFIG_SYS_DMA_CHANNEL_ID_IDX7> 
</#if>
</#if>
<#if CONFIG_DRV_I2S_DMA_INTERRUPTS_ENABLE == true>
<#if DRV_I2S_RX_DMA_CHANNEL_INT_SRC_IDX5 == "DMA_CHANNEL_0">
#define DRV_I2S_RX_DMA_SOURCE_IDX5				INT_SOURCE_DMA_0
</#if>
<#if DRV_I2S_RX_DMA_CHANNEL_INT_SRC_IDX5 == "DMA_CHANNEL_1">
#define DRV_I2S_RX_DMA_SOURCE_IDX5				INT_SOURCE_DMA_1
</#if>
<#if DRV_I2S_RX_DMA_CHANNEL_INT_SRC_IDX5 == "DMA_CHANNEL_2">
#define DRV_I2S_RX_DMA_SOURCE_IDX5				INT_SOURCE_DMA_2
</#if>
<#if DRV_I2S_RX_DMA_CHANNEL_INT_SRC_IDX5 == "DMA_CHANNEL_3">
#define DRV_I2S_RX_DMA_SOURCE_IDX5				INT_SOURCE_DMA_3
</#if>
<#if DRV_I2S_RX_DMA_CHANNEL_INT_SRC_IDX5 == "DMA_CHANNEL_4">
#define DRV_I2S_RX_DMA_SOURCE_IDX5				INT_SOURCE_DMA_4
</#if>
<#if DRV_I2S_RX_DMA_CHANNEL_INT_SRC_IDX5 == "DMA_CHANNEL_5">
#define DRV_I2S_RX_DMA_SOURCE_IDX5				INT_SOURCE_DMA_5
</#if>
<#if DRV_I2S_RX_DMA_CHANNEL_INT_SRC_IDX5 == "DMA_CHANNEL_6">
#define DRV_I2S_RX_DMA_SOURCE_IDX5				INT_SOURCE_DMA_6
</#if>
<#if DRV_I2S_RX_DMA_CHANNEL_INT_SRC_IDX5 == "DMA_CHANNEL_7">
#define DRV_I2S_RX_DMA_SOURCE_IDX5				INT_SOURCE_DMA_7
</#if>
<#if CONFIG_DRV_I2S_DMA_USE_CHANNEL_CHAINING == true>
<#if DRV_I2S_RX_DMA_CHAINING_CHANNEL_INT_SRC_IDX5 == "DMA_CHANNEL_0">
#define DRV_I2S_RX_DMA_CHAINING_SOURCE_IDX5		INT_SOURCE_DMA_0
</#if>
<#if DRV_I2S_RX_DMA_CHAINING_CHANNEL_INT_SRC_IDX5 == "DMA_CHANNEL_1">
#define DRV_I2S_RX_DMA_CHAINING_SOURCE_IDX5		INT_SOURCE_DMA_1
</#if>
<#if DRV_I2S_RX_DMA_CHAINING_CHANNEL_INT_SRC_IDX5 == "DMA_CHANNEL_2">
#define DRV_I2S_RX_DMA_CHAINING_SOURCE_IDX5		INT_SOURCE_DMA_2
</#if>
<#if DRV_I2S_RX_DMA_CHAINING_CHANNEL_INT_SRC_IDX5 == "DMA_CHANNEL_3">
#define DRV_I2S_RX_DMA_CHAINING_SOURCE_IDX5		INT_SOURCE_DMA_3
</#if>
<#if DRV_I2S_RX_DMA_CHAINING_CHANNEL_INT_SRC_IDX5 == "DMA_CHANNEL_4">
#define DRV_I2S_RX_DMA_CHAINING_SOURCE_IDX5		INT_SOURCE_DMA_4
</#if>
<#if DRV_I2S_RX_DMA_CHAINING_CHANNEL_INT_SRC_IDX5 == "DMA_CHANNEL_5">
#define DRV_I2S_RX_DMA_CHAINING_SOURCE_IDX5		INT_SOURCE_DMA_5
</#if>
<#if DRV_I2S_RX_DMA_CHAINING_CHANNEL_INT_SRC_IDX5 == "DMA_CHANNEL_6">
#define DRV_I2S_RX_DMA_CHAINING_SOURCE_IDX5		INT_SOURCE_DMA_6
</#if>
<#if DRV_I2S_RX_DMA_CHAINING_CHANNEL_INT_SRC_IDX5 == "DMA_CHANNEL_7">
#define DRV_I2S_RX_DMA_CHAINING_SOURCE_IDX5		INT_SOURCE_DMA_7
</#if>
</#if>
</#if>
</#if>
#define DRV_I2S_POWER_STATE_IDX5				${CONFIG_DRV_I2S_POWER_STATE_IDX5}
</#if>
</#if>
#define DRV_I2S_QUEUE_DEPTH_COMBINED     		${i2sCombinedQueueSizeOfAllInstances}

<#--
/*******************************************************************************
 End of File
*/
-->
