<#--
/*******************************************************************************
  USART interrupt Template File

  File Name:
    drv_i2s_int.s

  Summary:
    This file contains source code necessary to initialize the system.

  Description:
    This file contains source code necessary to run the system.  It
	generates code that is added to system_interrupt.c in order to handle
	all interrupts.
 *******************************************************************************/

/*******************************************************************************
Copyright (c) 2013-2014 released Microchip Technology Inc.  All rights reserved.

Microchip licenses to you the right to use, modify, copy and distribute
Software only when embedded on a Microchip microcontroller or digital signal
controller that is integrated into your product or third party product
(pursuant to the sublicense terms in the accompanying license agreement).

You should refer to the license agreement accompanying this Software for
additional information regarding your rights and obligations.

SOFTWARE AND DOCUMENTATION ARE PROVIDED AS IS WITHOUT WARRANTY OF ANY KIND,
EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION, ANY WARRANTY OF
MERCHANTABILITY, TITLE, NON-INFRINGEMENT AND FITNESS FOR A PARTICULAR PURPOSE.
IN NO EVENT SHALL MICROCHIP OR ITS LICENSORS BE LIABLE OR OBLIGATED UNDER
CONTRACT, NEGLIGENCE, STRICT LIABILITY, CONTRIBUTION, BREACH OF WARRANTY, OR
OTHER LEGAL EQUITABLE THEORY ANY DIRECT OR INDIRECT DAMAGES OR EXPENSES
INCLUDING BUT NOT LIMITED TO ANY INCIDENTAL, SPECIAL, INDIRECT, PUNITIVE OR
CONSEQUENTIAL DAMAGES, LOST PROFITS OR LOST DATA, COST OF PROCUREMENT OF
SUBSTITUTE GOODS, TECHNOLOGY, SERVICES, OR ANY CLAIMS BY THIRD PARTIES
(INCLUDING BUT NOT LIMITED TO ANY DEFENSE THEREOF), OR OTHER SIMILAR COSTS.
 *******************************************************************************/
 -->
<#macro DRV_I2S_ASM_MX_INT DRV_I2S_INSTANCE DRV_I2S_ID>
<#if DRV_I2S_ID == "SPI_ID_1">
<#assign I2S_ISR_VECTOR = CONFIG_INT_VECT_SPI_1>
</#if>
<#if DRV_I2S_ID == "SPI_ID_2">
<#assign I2S_ISR_VECTOR = CONFIG_INT_VECT_SPI_2>
</#if>
<#if DRV_I2S_ID == "SPI_ID_3">
<#assign I2S_ISR_VECTOR = CONFIG_INT_VECT_SPI_3>
</#if>
<#if DRV_I2S_ID == "SPI_ID_4">
<#assign I2S_ISR_VECTOR = CONFIG_INT_VECT_SPI_4>
</#if>
<#if DRV_I2S_ID == "SPI_ID_5">
<#assign I2S_ISR_VECTOR = CONFIG_INT_VECT_SPI_5>
</#if>
<#if DRV_I2S_ID == "SPI_ID_6">
<#assign I2S_ISR_VECTOR = CONFIG_INT_VECT_SPI_6>
</#if>
<#if DRV_I2S_INSTANCE == "0">
<#assign I2S_ISR_NAME = "DrvI2SInstance0">
<#assign I2S_INTPRIO = CONFIG_DRV_I2S_INT_PRIORITY_IDX0>
</#if>
<#if DRV_I2S_INSTANCE == "1">
<#assign I2S_ISR_NAME = "DrvI2SInstance1">
<#assign I2S_INTPRIO = CONFIG_DRV_I2S_INT_PRIORITY_IDX1>
</#if>
<#if DRV_I2S_INSTANCE == "2">
<#assign I2S_ISR_NAME = "DrvI2SInstance2">
<#assign I2S_INTPRIO = CONFIG_DRV_I2S_INT_PRIORITY_IDX2>
</#if>
<#if DRV_I2S_INSTANCE == "3">
<#assign I2S_ISR_NAME = "DrvI2SInstance3">
<#assign I2S_INTPRIO = CONFIG_DRV_I2S_INT_PRIORITY_IDX3>
</#if>
<#if DRV_I2S_INSTANCE == "4">
<#assign I2S_ISR_NAME = "DrvI2SInstance4">
<#assign I2S_INTPRIO = CONFIG_DRV_I2S_INT_PRIORITY_IDX4>
</#if>
<#if DRV_I2S_INSTANCE == "5">
<#assign I2S_ISR_NAME = "DrvI2SInstance5">
<#assign I2S_INTPRIO = CONFIG_DRV_I2S_INT_PRIORITY_IDX5>
</#if>
/* I2S Instance ${DRV_I2S_INSTANCE} Interrupt */
<@RTOS_ISR VECTOR = I2S_ISR_VECTOR NAME = I2S_ISR_NAME PRIORITY = I2S_INTPRIO/>
</#macro>
<#macro DRV_I2S_ASM_MZ_INT DRV_I2S_INSTANCE DRV_I2S_ID>
<#if DRV_I2S_ID == "SPI_ID_1">
<#assign I2S_RX_ISR_VECTOR = CONFIG_INT_VECT_SPI1_RX>
<#assign I2S_TX_ISR_VECTOR = CONFIG_INT_VECT_SPI1_TX>
<#assign I2S_FAULT_ISR_VECTOR = CONFIG_INT_VECT_SPI1_FAULT>
</#if>
<#if DRV_I2S_ID == "SPI_ID_2">
<#assign I2S_RX_ISR_VECTOR = CONFIG_INT_VECT_SPI2_RX>
<#assign I2S_TX_ISR_VECTOR = CONFIG_INT_VECT_SPI2_TX>
<#assign I2S_FAULT_ISR_VECTOR = CONFIG_INT_VECT_SPI2_FAULT>
</#if>
<#if DRV_I2S_ID == "SPI_ID_3">
<#assign I2S_RX_ISR_VECTOR = CONFIG_INT_VECT_SPI3_RX>
<#assign I2S_TX_ISR_VECTOR = CONFIG_INT_VECT_SPI3_TX>
<#assign I2S_FAULT_ISR_VECTOR = CONFIG_INT_VECT_SPI3_FAULT>
</#if>
<#if DRV_I2S_ID == "SPI_ID_4">
<#assign I2S_RX_ISR_VECTOR = CONFIG_INT_VECT_SPI4_RX>
<#assign I2S_TX_ISR_VECTOR = CONFIG_INT_VECT_SPI4_TX>
<#assign I2S_FAULT_ISR_VECTOR = CONFIG_INT_VECT_SPI4_FAULT>
</#if>
<#if DRV_I2S_ID == "SPI_ID_5">
<#assign I2S_RX_ISR_VECTOR = CONFIG_INT_VECT_SPI5_RX>
<#assign I2S_TX_ISR_VECTOR = CONFIG_INT_VECT_SPI5_TX>
<#assign I2S_FAULT_ISR_VECTOR = CONFIG_INT_VECT_SPI5_FAULT>
</#if>
<#if DRV_I2S_ID == "SPI_ID_6">
<#assign I2S_RX_ISR_VECTOR = CONFIG_INT_VECT_SPI6_RX>
<#assign I2S_TX_ISR_VECTOR = CONFIG_INT_VECT_SPI6_TX>
<#assign I2S_FAULT_ISR_VECTOR = CONFIG_INT_VECT_SPI6_FAULT>
</#if>
<#if DRV_I2S_INSTANCE == "0">
<#assign I2S_RX_ISR_NAME = "DrvI2SRxInstance0">
<#assign I2S_TX_ISR_NAME = "DrvI2STxInstance0">
<#assign I2S_FAULT_ISR_NAME = "DrvI2SFaultInstance0">
<#assign I2S_RX_INTPRIO = CONFIG_DRV_I2S_RX_INT_PRIORITY_IDX0>
<#assign I2S_TX_INTPRIO = CONFIG_DRV_I2S_TX_INT_PRIORITY_IDX0>
<#assign I2S_FAULT_INTPRIO = CONFIG_DRV_I2S_ERR_INT_PRIORITY_IDX0>
</#if>
<#if DRV_I2S_INSTANCE == "1">
<#assign I2S_RX_ISR_NAME = "DrvI2SRxInstance1">
<#assign I2S_TX_ISR_NAME = "DrvI2STxInstance1">
<#assign I2S_FAULT_ISR_NAME = "DrvI2SFaultInstance1">
<#assign I2S_RX_INTPRIO = CONFIG_DRV_I2S_RX_INT_PRIORITY_IDX1>
<#assign I2S_TX_INTPRIO = CONFIG_DRV_I2S_TX_INT_PRIORITY_IDX1>
<#assign I2S_FAULT_INTPRIO = CONFIG_DRV_I2S_ERR_INT_PRIORITY_IDX1>
</#if>
<#if DRV_I2S_INSTANCE == "2">
<#assign I2S_RX_ISR_NAME = "DrvI2SRxInstance2">
<#assign I2S_TX_ISR_NAME = "DrvI2STxInstance2">
<#assign I2S_FAULT_ISR_NAME = "DrvI2SFaultInstance2">
<#assign I2S_RX_INTPRIO = CONFIG_DRV_I2S_RX_INT_PRIORITY_IDX2>
<#assign I2S_TX_INTPRIO = CONFIG_DRV_I2S_TX_INT_PRIORITY_IDX2>
<#assign I2S_FAULT_INTPRIO = CONFIG_DRV_I2S_ERR_INT_PRIORITY_IDX2>
</#if>
<#if DRV_I2S_INSTANCE == "3">
<#assign I2S_RX_ISR_NAME = "DrvI2SRxInstance3">
<#assign I2S_TX_ISR_NAME = "DrvI2STxInstance3">
<#assign I2S_FAULT_ISR_NAME = "DrvI2SFaultInstance3">
<#assign I2S_RX_INTPRIO = CONFIG_DRV_I2S_RX_INT_PRIORITY_IDX3>
<#assign I2S_TX_INTPRIO = CONFIG_DRV_I2S_TX_INT_PRIORITY_IDX3>
<#assign I2S_FAULT_INTPRIO = CONFIG_DRV_I2S_ERR_INT_PRIORITY_IDX3>
</#if>
<#if DRV_I2S_INSTANCE == "4">
<#assign I2S_RX_ISR_NAME = "DrvI2SRxInstance4">
<#assign I2S_TX_ISR_NAME = "DrvI2STxInstance4">
<#assign I2S_FAULT_ISR_NAME = "DrvI2SFaultInstance4">
<#assign I2S_RX_INTPRIO = CONFIG_DRV_I2S_RX_INT_PRIORITY_IDX4>
<#assign I2S_TX_INTPRIO = CONFIG_DRV_I2S_TX_INT_PRIORITY_IDX4>
<#assign I2S_FAULT_INTPRIO = CONFIG_DRV_I2S_ERR_INT_PRIORITY_IDX4>
</#if>
<#if DRV_I2S_INSTANCE == "5">
<#assign I2S_RX_ISR_NAME = "DrvI2SRxInstance5">
<#assign I2S_TX_ISR_NAME = "DrvI2STxInstance5">
<#assign I2S_FAULT_ISR_NAME = "DrvI2SFaultInstance5">
<#assign I2S_RX_INTPRIO = CONFIG_DRV_I2S_RX_INT_PRIORITY_IDX5>
<#assign I2S_TX_INTPRIO = CONFIG_DRV_I2S_TX_INT_PRIORITY_IDX5>
<#assign I2S_FAULT_INTPRIO = CONFIG_DRV_I2S_ERR_INT_PRIORITY_IDX5>
</#if>
/* I2S Instance ${DRV_I2S_INSTANCE} Interrupt */
<@RTOS_ISR VECTOR = I2S_RX_ISR_VECTOR NAME = I2S_RX_ISR_NAME PRIORITY = I2S_RX_INTPRIO/>
<@RTOS_ISR VECTOR = I2S_TX_ISR_VECTOR NAME = I2S_TX_ISR_NAME PRIORITY = I2S_TX_INTPRIO/>
<@RTOS_ISR VECTOR = I2S_FAULT_ISR_VECTOR NAME = I2S_FAULT_ISR_NAME PRIORITY = I2S_FAULT_INTPRIO/>
</#macro>
<#if CONFIG_DRV_I2S_INTERRUPT_MODE == true>
<#if CONFIG_PIC32MX == true>
<#if CONFIG_DRV_I2S_INST_IDX0 == true>
<@DRV_I2S_ASM_MX_INT DRV_I2S_INSTANCE="0" DRV_I2S_ID=CONFIG_DRV_I2S_PERIPHERAL_ID_IDX0/>
</#if>
<#if CONFIG_DRV_I2S_INST_IDX1 == true>
<@DRV_I2S_ASM_MX_INT DRV_I2S_INSTANCE="1" DRV_I2S_ID=CONFIG_DRV_I2S_PERIPHERAL_ID_IDX1/>
</#if>
<#if CONFIG_DRV_I2S_INST_IDX2 == true>
<@DRV_I2S_ASM_MX_INT DRV_I2S_INSTANCE="2" DRV_I2S_ID=CONFIG_DRV_I2S_PERIPHERAL_ID_IDX2/>
</#if>
<#if CONFIG_DRV_I2S_INST_IDX3 == true>
<@DRV_I2S_ASM_MX_INT DRV_I2S_INSTANCE="3" DRV_I2S_ID=CONFIG_DRV_I2S_PERIPHERAL_ID_IDX3/>
</#if>
<#if CONFIG_DRV_I2S_INST_IDX4 == true>
<@DRV_I2S_ASM_MX_INT DRV_I2S_INSTANCE="4" DRV_I2S_ID=CONFIG_DRV_I2S_PERIPHERAL_ID_IDX4/>
</#if>
<#if CONFIG_DRV_I2S_INST_IDX5 == true>
<@DRV_I2S_ASM_MX_INT DRV_I2S_INSTANCE="5" DRV_I2S_ID=CONFIG_DRV_I2S_PERIPHERAL_ID_IDX5/>
</#if>
<#else>
<#if CONFIG_DRV_I2S_INST_IDX0 == true>
<@DRV_I2S_ASM_MZ_INT DRV_I2S_INSTANCE="0" DRV_I2S_ID=CONFIG_DRV_I2S_PERIPHERAL_ID_IDX0/>
</#if>
<#if CONFIG_DRV_I2S_INST_IDX1 == true>
<@DRV_I2S_ASM_MZ_INT DRV_I2S_INSTANCE="1" DRV_I2S_ID=CONFIG_DRV_I2S_PERIPHERAL_ID_IDX1/>
</#if>
<#if CONFIG_DRV_I2S_INST_IDX2 == true>
<@DRV_I2S_ASM_MZ_INT DRV_I2S_INSTANCE="2" DRV_I2S_ID=CONFIG_DRV_I2S_PERIPHERAL_ID_IDX2/>
</#if>
<#if CONFIG_DRV_I2S_INST_IDX3 == true>
<@DRV_I2S_ASM_MZ_INT DRV_I2S_INSTANCE="3" DRV_I2S_ID=CONFIG_DRV_I2S_PERIPHERAL_ID_IDX3/>
</#if>
<#if CONFIG_DRV_I2S_INST_IDX4 == true>
<@DRV_I2S_ASM_MZ_INT DRV_I2S_INSTANCE="4" DRV_I2S_ID=CONFIG_DRV_I2S_PERIPHERAL_ID_IDX4/>
</#if>
<#if CONFIG_DRV_I2S_INST_IDX5 == true>
<@DRV_I2S_ASM_MZ_INT DRV_I2S_INSTANCE="5" DRV_I2S_ID=CONFIG_DRV_I2S_PERIPHERAL_ID_IDX5/>
</#if>
</#if>
</#if>
