/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.36                          *
*        Compiled Aug 31 2016, 10:53:09                              *
*        (c) 2016 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
#include "system_config.h"
#include "system_definitions.h"
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_FRAMEWIN_0 (GUI_ID_USER + 0x00)
#define ID_BUTTON_0 (GUI_ID_USER + 0x01)
#define ID_PROGBAR_0 (GUI_ID_USER + 0x02)
#define ID_SLIDER_0 (GUI_ID_USER + 0x03)
#define ID_SCROLLBAR_0 (GUI_ID_USER + 0x04)
#define ID_TEXT_0 (GUI_ID_USER + 0x05)
#define ID_TEXT_1 (GUI_ID_USER + 0x06)
#define ID_TEXT_2 (GUI_ID_USER + 0x07)
#define ID_BUTTON_1 (GUI_ID_USER + 0x08)
#define ID_BUTTON_2 (GUI_ID_USER + 0x09)
#define ID_BUTTON_3 (GUI_ID_USER + 0x0A)
#define ID_BUTTON_4 (GUI_ID_USER + 0x0B)
#define ID_BUTTON_5 (GUI_ID_USER + 0x0C)
#define ID_BUTTON_6 (GUI_ID_USER + 0x0D)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { FRAMEWIN_CreateIndirect, "", ID_FRAMEWIN_0, 0, 0, 480, 272, 0, 0x64, 0 },
  { BUTTON_CreateIndirect, "Back", ID_BUTTON_0, 15, 171, 60, 60, 0, 0x0, 0 },
  { PROGBAR_CreateIndirect, "Progbar", ID_PROGBAR_0, 175, 20, 220, 40, 0, 0x0, 0 },
  { SLIDER_CreateIndirect, "Slider", ID_SLIDER_0, 175, 80, 220, 40, 0, 0x0, 0 },
  { SCROLLBAR_CreateIndirect, "Scrollbar", ID_SCROLLBAR_0, 176, 140, 220, 40, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "PeogBarText", ID_TEXT_0, 10, 20, 95, 23, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "SliderText", ID_TEXT_1, 10, 80, 81, 27, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "ScrollBarText", ID_TEXT_2, 10, 140, 92, 27, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "AddButton", ID_BUTTON_1, 410, 20, 50, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "SubButton", ID_BUTTON_2, 115, 20, 50, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "AddButton2", ID_BUTTON_3, 410, 80, 50, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "SubButton2", ID_BUTTON_4, 115, 80, 50, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "AddButton3", ID_BUTTON_5, 410, 140, 50, 40, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "SubButton3", ID_BUTTON_6, 115, 140, 50, 40, 0, 0x0, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  static unsigned char ProgBarIncNum = 0;
  static unsigned char SliderIncNum = 0; 
  static unsigned char ScrollBarIncNum = 0;
  
  static unsigned short pBackButtonString[2] = {0x8fd4,0x56de};
  static char pBackButtonDisplayBuf[6] = "";
  
  static unsigned short pTextString1[3] = {0x8fdb,0x5ea6,0x6761};
  static char pTextString1DisplayBuf[9] = "";
  
  static unsigned short pTextString2[2] = {0x6ed1,0x6761};
  static char pTextString2DisplayBuf[6] = "";
  
  static unsigned short pTextString3[3] = {0x6eda,0x52a8,0x6761};
  static char pTextString3DisplayBuf[9] = "";  
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'ChineseMenu'
    //
    hItem = pMsg->hWin;
    FRAMEWIN_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    FRAMEWIN_SetText(hItem, "");
    FRAMEWIN_SetFont(hItem, GUI_FONT_13B_1);
    // USER START (Optionally insert additional code for further widget initialization)
    
    // Initialization of 'Back'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
//    BUTTON_SetText(hItem, "");
    GUI_UC_SetEncodeUTF8();
    GUI_UC_ConvertUC2UTF8(pBackButtonString,2,pBackButtonDisplayBuf,2*3);    
//    BUTTON_SetFont(hItem, GUI_FONT_13B_1);
    BUTTON_SetText(hItem, pBackButtonDisplayBuf);  
    BUTTON_SetFont(hItem, GUI_FONT_KAITI20);
    // USER START (Optionally insert additional code for further widget initialization)
     //
    // Initialization of 'ProgBarText'
    //    
     hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    GUI_UC_SetEncodeUTF8();
    GUI_UC_ConvertUC2UTF8(pTextString1,3,pTextString1DisplayBuf,3*3);
    TEXT_SetText(hItem, pTextString1DisplayBuf);  
    TEXT_SetFont(hItem, GUI_FONT_KAITI20);    
    //
    // Initialization of 'SliderText'
    //      
     hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
    GUI_UC_SetEncodeUTF8();
    GUI_UC_ConvertUC2UTF8(pTextString2,2,pTextString2DisplayBuf,2*3);
    TEXT_SetText(hItem, pTextString2DisplayBuf);  
    TEXT_SetFont(hItem, GUI_FONT_KAITI20);   
    //
    // Initialization of 'ScrollBarText'
    // 
     hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
    GUI_UC_SetEncodeUTF8();
    GUI_UC_ConvertUC2UTF8(pTextString3,3,pTextString3DisplayBuf,3*3);
    TEXT_SetText(hItem, pTextString3DisplayBuf);  
    TEXT_SetFont(hItem, GUI_FONT_KAITI20);       

      
    hItem = pMsg->hWin;
    FRAMEWIN_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'AddButton'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
    BUTTON_SetText(hItem, "+");
    BUTTON_SetFont(hItem, GUI_FONT_20_1);
    //
    // Initialization of 'SubButton'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
    BUTTON_SetFont(hItem, GUI_FONT_20_1);
    BUTTON_SetText(hItem, "-");
    //
    // Initialization of 'AddButton2'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3);
    BUTTON_SetText(hItem, "+");
    BUTTON_SetFont(hItem, GUI_FONT_20_1);
    //
    // Initialization of 'SubButton2'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_4);
    BUTTON_SetFont(hItem, GUI_FONT_20_1);
    BUTTON_SetText(hItem, "-");    
    //
    // Initialization of 'AddButton3'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_5);
    BUTTON_SetText(hItem, "+");
    BUTTON_SetFont(hItem, GUI_FONT_20_1);
    //
    // Initialization of 'SubButton3'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_6);
    BUTTON_SetFont(hItem, GUI_FONT_20_1);
    BUTTON_SetText(hItem, "-");     
    // USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_BUTTON_0: // Notifications sent by 'Back'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        emWin_GuiScreenChange(EMWIN_APP_SCREEN_ENGLISH_MENU);
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_SLIDER_0: // Notifications sent by 'Slider'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_SCROLLBAR_0: // Notifications sent by 'Scrollbar'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'AddButton'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        if(ProgBarIncNum < 100)
        {
            ProgBarIncNum ++;
        }  
        PROGBAR_SetValue(WM_GetDialogItem(pMsg->hWin, ID_PROGBAR_0), ProgBarIncNum);
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_2: // Notifications sent by 'SubButton'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        if(ProgBarIncNum > 0)
        {
            ProgBarIncNum --;
        }  
        PROGBAR_SetValue(WM_GetDialogItem(pMsg->hWin, ID_PROGBAR_0), ProgBarIncNum);  
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_3: // Notifications sent by 'AddButton2'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        if(SliderIncNum < 100)
        {
            SliderIncNum ++;
        }
        SLIDER_SetValue(WM_GetDialogItem(pMsg->hWin, ID_SLIDER_0), SliderIncNum);
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_4: // Notifications sent by 'SubButton2'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        if(SliderIncNum > 0)
        {
            SliderIncNum --;
        }
        SLIDER_SetValue(WM_GetDialogItem(pMsg->hWin, ID_SLIDER_0), SliderIncNum);      
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_5: // Notifications sent by 'AddButton3'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        if(ScrollBarIncNum < 100)
        {
            ScrollBarIncNum ++;
        }
        SCROLLBAR_SetValue(WM_GetDialogItem(pMsg->hWin, ID_SCROLLBAR_0), ScrollBarIncNum);
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_6: // Notifications sent by 'SubButton3'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        if(ScrollBarIncNum > 0)
        {
            ScrollBarIncNum --;
        }
        SCROLLBAR_SetValue(WM_GetDialogItem(pMsg->hWin, ID_SCROLLBAR_0), ScrollBarIncNum);
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateChineseMenu
*/
WM_HWIN CreateChineseMenu(void);
WM_HWIN CreateChineseMenu(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
