config DRV_ADCHS_ANALOG_INPUT_SCAN_INSTANCES_NUMBER_GT_${INSTANCE+1}
    depends on USE_DRV_ADC
    bool
<#if INSTANCE != 0>
	default n if DRV_ADCHS_ANALOG_INPUT_SCAN_INSTANCES_NUMBER_GT_${INSTANCE} = n     
</#if>	
	default n if DRV_ADCHS_ANALOG_INPUT_SCAN_INSTANCES_NUMBER = ${INSTANCE+1}
	default y
	
config DRV_ADCHS_ANALOG_INPUT_SCAN_INST_IDX${INSTANCE}
    depends on USE_DRV_ADC 
<#if INSTANCE != 0>
	             && DRV_ADCHS_ANALOG_INPUT_SCAN_INSTANCES_NUMBER_GT_${INSTANCE}
</#if>
    bool "Analog Input Scan Instance ${INSTANCE}"
    default n
    ---help---
    IDH_HTML_DRV_ADCHS_ANALOG_INPUT_SCAN_INSTANCES_NUMBER
    ---endhelp---

ifblock DRV_ADCHS_ANALOG_INPUT_SCAN_INST_IDX${INSTANCE}

comment "**** For Class-1 or Class-2 analog inputs, additionally, select respective trigger as ADCHS_TRIGGER_SOURCE_SCAN ****"
	depends on DRV_ADC_TYPE_ADCHS
	
config DRV_ADCHS_ANALOG_INPUT_ID_IDX${INSTANCE}
    string "Analog Input Selection"
    depends on USE_DRV_ADC
	depends on DRV_ADC_TYPE_ADCHS
	range ADCHS_AN_INPUT_ID
    default "ADCHS_AN12"
	---help---
	IDH_HTML_ADCHS_AN_INPUT_ID
	---endhelp---

config DRV_ADCHS_SCAN_ANALOG_INPUT_MODE_IDX${INSTANCE}
    string "Analog Input Mode"
    depends on USE_DRV_ADC
	depends on DRV_ADC_TYPE_ADCHS
	range ADCHS_INPUT_MODE
    default "ADCHS_INPUT_MODE_SINGLE_ENDED_UNIPOLAR"
	---help---
	IDH_HTML_ADCHS_INPUT_MODE
	---endhelp---
config DRV_ADCHS_SCAN_DATA_RDY_INTERRUPT_ENABLE_IDX${INSTANCE}
	bool "Data Ready Interrupt Enable"
	depends on USE_DRV_ADC && DRV_ADCHS_INDIVIDUAL_INTERRUPT_ENABLE
	default n
	---help---
	IDH_HTML_ADCHS_CHANNEL_DATA_RDY_INTERRUPT_ENABLE
	---endhelp---
	
config DRV_ADCHS_SCAN_DATA_RDY_INTERRUPT_PRIORITY_IDX${INSTANCE}
    string "Interrupt Priority"
    depends on USE_DRV_ADC && DRV_ADCHS_SCAN_DATA_RDY_INTERRUPT_ENABLE_IDX${INSTANCE}
    range INT_PRIORITY_LEVEL
    default "INT_PRIORITY_LEVEL3"
    ---help---
      IDH_HTML_INT_PRIORITY_LEVEL
    ---endhelp---
    
config DRV_ADCHS_SCAN_DATA_RDY_INTERRUPT_SUB_PRIORITY_IDX${INSTANCE}
    string "Interrupt Sub-priority"
    depends on USE_DRV_ADC && DRV_ADCHS_SCAN_DATA_RDY_INTERRUPT_ENABLE_IDX${INSTANCE}
    range INT_SUBPRIORITY_LEVEL
    default "INT_SUBPRIORITY_LEVEL0"
    ---help---
      IDH_HTML_INT_SUBPRIORITY_LEVEL
    ---endhelp---
	
config DRV_ADCHS_SCAN_DATA_RDY_INT_IPL_IDX${INSTANCE}
    string
    depends on USE_DRV_ADC && DRV_ADCHS_SCAN_DATA_RDY_INTERRUPT_ENABLE_IDX${INSTANCE}
    default "0" if DRV_ADCHS_SCAN_DATA_RDY_INTERRUPT_PRIORITY_IDX${INSTANCE} = "INT_DISABLE_INTERRUPT"
    default "1" if DRV_ADCHS_SCAN_DATA_RDY_INTERRUPT_PRIORITY_IDX${INSTANCE} = "INT_PRIORITY_LEVEL1"
    default "2" if DRV_ADCHS_SCAN_DATA_RDY_INTERRUPT_PRIORITY_IDX${INSTANCE} = "INT_PRIORITY_LEVEL2"
    default "3" if DRV_ADCHS_SCAN_DATA_RDY_INTERRUPT_PRIORITY_IDX${INSTANCE} = "INT_PRIORITY_LEVEL3"
    default "4" if DRV_ADCHS_SCAN_DATA_RDY_INTERRUPT_PRIORITY_IDX${INSTANCE} = "INT_PRIORITY_LEVEL4"
    default "5" if DRV_ADCHS_SCAN_DATA_RDY_INTERRUPT_PRIORITY_IDX${INSTANCE} = "INT_PRIORITY_LEVEL5"
    default "6" if DRV_ADCHS_SCAN_DATA_RDY_INTERRUPT_PRIORITY_IDX${INSTANCE} = "INT_PRIORITY_LEVEL6"
    default "7" if DRV_ADCHS_SCAN_DATA_RDY_INTERRUPT_PRIORITY_IDX${INSTANCE} = "INT_PRIORITY_LEVEL7"	
endif

	
