/*******************************************************************************
  MCPWM Driver Functions for Static Single Instance Driver

  Company:
    Microchip Technology Inc.

  File Name:
    drv_mcpwm_static.c

  Summary:
   MCPWM driver implementation for the static single instance driver.

  Description:
    The MCPWM device driver provides a simple interface to manage the MCPWM
    modules on Microchip microcontrollers.
    
  Remarks:
    Static interfaces incorporate the driver instance number within the names
    of the routines, eliminating the need for an object ID or object handle.
    Static single-open interfaces also eliminate the need for the open handle.
*******************************************************************************/

//DOM-IGNORE-BEGIN
/*******************************************************************************
Copyright (c) 2017 released Microchip Technology Inc.  All rights reserved.

Microchip licenses to you the right to use, modify, copy and distribute
Software only when embedded on a Microchip microcontroller or digital signal
controller that is integrated into your product or third party product
(pursuant to the sublicense terms in the accompanying license agreement).

You should refer to the license agreement accompanying this Software for
additional information regarding your rights and obligations.

SOFTWARE AND DOCUMENTATION ARE PROVIDED AS IS WITHOUT WARRANTY OF ANY KIND,
EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION, ANY WARRANTY OF
MERCHANTABILITY, TITLE, NON-INFRINGEMENT AND FITNESS FOR A PARTICULAR PURPOSE.
IN NO EVENT SHALL MICROCHIP OR ITS LICENSORS BE LIABLE OR OBLIGATED UNDER
CONTRACT, NEGLIGENCE, STRICT LIABILITY, CONTRIBUTION, BREACH OF WARRANTY, OR
OTHER LEGAL EQUITABLE THEORY ANY DIRECT OR INDIRECT DAMAGES OR EXPENSES
INCLUDING BUT NOT LIMITED TO ANY INCIDENTAL, SPECIAL, INDIRECT, PUNITIVE OR
CONSEQUENTIAL DAMAGES, LOST PROFITS OR LOST DATA, COST OF PROCUREMENT OF
SUBSTITUTE GOODS, TECHNOLOGY, SERVICES, OR ANY CLAIMS BY THIRD PARTIES
(INCLUDING BUT NOT LIMITED TO ANY DEFENSE THEREOF), OR OTHER SIMILAR COSTS.
*******************************************************************************/
//DOM-IGNORE-END

// *****************************************************************************
// *****************************************************************************
// Header Includes
// *****************************************************************************
// *****************************************************************************
#include "framework/driver/mcpwm/drv_mcpwm_static.h"

<#macro DRV_MCPWM_STATIC_FUNCTIONS MCPWM_CHANNEL_INSTANCE MCPWM_TIME_BASE_SOURCE MCPWM_TIME_BASE_MODE MCPWM_ALIGNMENT_MODE
MCPWM_OUTPUT_MODE MCPWM_PWMxH_OUTPUT_POLARITY MCPWM_PWMxL_OUTPUT_POLARITY MCPWM_DEADTIME_MODE MCPWM_DEADTIME_POLARITY MCPWM_TRIGGER_POSTSCALER MCPWM_PRIMARY_TRIGGER_CYCLE_SELECT
MCPWM_SECONDARY_TRIGGER_CYCLE_SELECT MCPWM_ADC_TRIGGER_SOURCE MCPWM_TRIGGER_INTERRUPT_SOURCE MCPWM_PRIMARY_TRIGGER_COMPARE_VALUE
MCPWM_SECONDARY_TRIGGER_COMPARE_VALUE MCPWM_TRIGGER_INTERRUPT_ENABLE MCPWM_LEB_TRIGGER_PWMxHRISINGEDGE_ENABLE MCPWM_LEB_TRIGGER_PWMxHFALLINGEDGE_ENABLE 
MCPWM_LEB_TRIGGER_PWMxLRISINGEDGE_ENABLE MCPWM_LEB_TRIGGER_PWMxLFALLINGEDGE_ENABLE MCPWM_FAULT_INPUT_LEB_CONTROL MCPWM_CURRENTLIMIT_INPUT_LEB_CONTROL 
MCPWM_LEB_PERIOD_VALUE MCPWM_CHOP_CLOCK_SOURCE MCPWM_PWMxH_CHOP_CONTROL MCPWM_PWMxL_CHOP_CONTROL MCPWM_FAULT_SOURCE MCPWM_FAULT_INPUT_POLARITY 
MCPWM_FAULT_OVERRIDE_PWMxH_VALUE MCPWM_FAULT_OVERRIDE_PWMxL_VALUE MCPWM_FAULT_MODE MCPWM_FAULT_INTERRUPT_ENABLE MCPWM_CURRENTLIMIT_SOURCE
MCPWM_CURRENTLIMIT_INPUT_POLARITY MCPWM_CURRENTLIMIT_OVERRIDE_PWMxH_VALUE MCPWM_CURRENTLIMIT_OVERRIDE_PWMxL_VALUE MCPWM_CURRENTLIMIT_MODE MCPWM_CURRENTLIMIT_INTERRUPT_ENABLE 
MCPWM_OVERRIDE_PWMxH_VALUE MCPWM_OVERRIDE_PWMxL_VALUE MCPWM_OVERRIDE_PWMxH_ENABLE MCPWM_OVERRIDE_PWMxL_ENABLE MCPWM_SYNC_OVERRIDE_SELECT MCPWM_PWMH_ENABLE MCPWM_PERIOD_MATCH_INTERRUPT_ENABLE MCPWM_PWML_ENABLE MCPWM_PERIOD_RESET_INTERRUPT_ENABLE MCPWM_SWAP_PWMH_PWML_ENABLE MCPWM_PDC_VALUE MCPWM_SDC_VALUE MCPWM_PHASE_VALUE MCPWM_DTR_VALUE MCPWM_ALTDTR_VALUE
MCPWM_DTCOMP_VALUE MCPWM_CHANNEL_INTERRUPT_ENABLE MCPWM_CHANNEL_INTERRUPT_PRIORITY MCPWM_CHANNEL_INTERRUPT_SUBPRIORITY MCPWM_CHANNEL_INTERRUPT_VECTOR MCPWM_CHANNEL_INTERRUPT_SOURCE>
// *****************************************************************************
/* MCPWM Channel instance ${MCPWM_CHANNEL_INSTANCE} */
	PLIB_MCPWM_ChannelSetup (MCPWM_ID_0 , ${MCPWM_CHANNEL_INSTANCE}, ${MCPWM_TIME_BASE_SOURCE} , ${MCPWM_TIME_BASE_MODE} , ${MCPWM_ALIGNMENT_MODE},
	${MCPWM_OUTPUT_MODE}, ${MCPWM_PWMxH_OUTPUT_POLARITY} ,${MCPWM_PWMxL_OUTPUT_POLARITY} , ${MCPWM_DEADTIME_MODE}, ${MCPWM_DEADTIME_POLARITY} );
	
	PLIB_MCPWM_ChannelPrimaryDutyCycleSet (MCPWM_ID_0 , ${MCPWM_CHANNEL_INSTANCE} , ${MCPWM_PDC_VALUE});
	PLIB_MCPWM_ChannelSecondaryDutyCycleSet (MCPWM_ID_0 , ${MCPWM_CHANNEL_INSTANCE} , ${MCPWM_SDC_VALUE});
	PLIB_MCPWM_ChannelPWMxHDeadtimeSet (MCPWM_ID_0 , ${MCPWM_CHANNEL_INSTANCE} , ${MCPWM_DTR_VALUE});
	PLIB_MCPWM_ChannelPWMxLDeadtimeSet (MCPWM_ID_0 , ${MCPWM_CHANNEL_INSTANCE} , ${MCPWM_ALTDTR_VALUE});
	PLIB_MCPWM_ChannelDeadtimeCompSet (MCPWM_ID_0 , ${MCPWM_CHANNEL_INSTANCE} , ${MCPWM_DTCOMP_VALUE});
	PLIB_MCPWM_ChannelPhaseSet (MCPWM_ID_0 , ${MCPWM_CHANNEL_INSTANCE} , ${MCPWM_PHASE_VALUE});
	
	
	PLIB_MCPWM_ChannelTriggerSetup (MCPWM_ID_0 , ${MCPWM_CHANNEL_INSTANCE} , ${MCPWM_TRIGGER_POSTSCALER}, 
	${MCPWM_PRIMARY_TRIGGER_CYCLE_SELECT} , ${MCPWM_SECONDARY_TRIGGER_CYCLE_SELECT} , ${MCPWM_ADC_TRIGGER_SOURCE},
	${MCPWM_TRIGGER_INTERRUPT_SOURCE}, ${MCPWM_PRIMARY_TRIGGER_COMPARE_VALUE} , ${MCPWM_SECONDARY_TRIGGER_COMPARE_VALUE});
	

	<#if MCPWM_FAULT_INPUT_LEB_CONTROL == true & MCPWM_CURRENTLIMIT_INPUT_LEB_CONTROL == true>
	PLIB_MCPWM_ChannelLEBSetup (MCPWM_ID_0 , ${MCPWM_CHANNEL_INSTANCE} , MCPWM_FAULT_INPUT_LEB_ENABLE, MCPWM_CURRENTLIMIT_INPUT_LEB_ENABLE, 
	${MCPWM_LEB_PERIOD_VALUE});
	<#elseif MCPWM_FAULT_INPUT_LEB_CONTROL == true & MCPWM_CURRENTLIMIT_INPUT_LEB_CONTROL == false>
	PLIB_MCPWM_ChannelLEBSetup (MCPWM_ID_0 , ${MCPWM_CHANNEL_INSTANCE} , MCPWM_FAULT_INPUT_LEB_ENABLE, MCPWM_CURRENTLIMIT_INPUT_LEB_DISABLE, 
	${MCPWM_LEB_PERIOD_VALUE});	
	<#elseif MCPWM_FAULT_INPUT_LEB_CONTROL == false & MCPWM_CURRENTLIMIT_INPUT_LEB_CONTROL == true>
	PLIB_MCPWM_ChannelLEBSetup (MCPWM_ID_0 , ${MCPWM_CHANNEL_INSTANCE} , MCPWM_FAULT_INPUT_LEB_DISABLE, MCPWM_CURRENTLIMIT_INPUT_LEB_ENABLE, 
	${MCPWM_LEB_PERIOD_VALUE});	
	<#else>
	PLIB_MCPWM_ChannelLEBSetup (MCPWM_ID_0 , ${MCPWM_CHANNEL_INSTANCE} , MCPWM_FAULT_INPUT_LEB_DISABLE, MCPWM_CURRENTLIMIT_INPUT_LEB_DISABLE, 
	${MCPWM_LEB_PERIOD_VALUE});	
	</#if>
	
	<#if MCPWM_LEB_TRIGGER_PWMxHRISINGEDGE_ENABLE == true >
	PLIB_MCPWM_ChannelLEBTriggerPWMxHRisingEdgeEnable (MCPWM_ID_0 , ${MCPWM_CHANNEL_INSTANCE});
	</#if>

	<#if MCPWM_LEB_TRIGGER_PWMxHFALLINGEDGE_ENABLE == true >
	PLIB_MCPWM_ChannelLEBTriggerPWMxHFallingEdgeEnable (MCPWM_ID_0 , ${MCPWM_CHANNEL_INSTANCE});
	</#if>

	<#if MCPWM_LEB_TRIGGER_PWMxLRISINGEDGE_ENABLE == true >
	PLIB_MCPWM_ChannelLEBTriggerPWMxLRisingEdgeEnable (MCPWM_ID_0 , ${MCPWM_CHANNEL_INSTANCE});
	</#if>

	<#if MCPWM_LEB_TRIGGER_PWMxLFALLINGEDGE_ENABLE == true >
	PLIB_MCPWM_ChannelLEBTriggerPWMxLFallingEdgeEnable (MCPWM_ID_0 , ${MCPWM_CHANNEL_INSTANCE});
	</#if>	
	
	PLIB_MCPWM_ChannelChopSetup (MCPWM_ID_0 , ${MCPWM_CHANNEL_INSTANCE} , ${MCPWM_CHOP_CLOCK_SOURCE}, ${MCPWM_PWMxH_CHOP_CONTROL}, ${MCPWM_PWMxL_CHOP_CONTROL});
	
	
	PLIB_MCPWM_ChannelFaultSetup (MCPWM_ID_0 , ${MCPWM_CHANNEL_INSTANCE}, ${MCPWM_FAULT_SOURCE} , ${MCPWM_FAULT_INPUT_POLARITY},
	${MCPWM_FAULT_OVERRIDE_PWMxH_VALUE}, ${MCPWM_FAULT_OVERRIDE_PWMxL_VALUE}, ${MCPWM_FAULT_MODE});
	
	
	PLIB_MCPWM_ChannelCurrentLimitSetup (MCPWM_ID_0 , ${MCPWM_CHANNEL_INSTANCE}, ${MCPWM_CURRENTLIMIT_SOURCE} , ${MCPWM_CURRENTLIMIT_INPUT_POLARITY},
	${MCPWM_CURRENTLIMIT_OVERRIDE_PWMxH_VALUE},${MCPWM_CURRENTLIMIT_OVERRIDE_PWMxL_VALUE}, ${MCPWM_CURRENTLIMIT_MODE} );
	
	
	PLIB_MCPWM_ChannelOverrideOutputSet (MCPWM_ID_0 , ${MCPWM_CHANNEL_INSTANCE}, ${MCPWM_OVERRIDE_PWMxH_VALUE}, ${MCPWM_OVERRIDE_PWMxL_VALUE});
	
	<#if MCPWM_OVERRIDE_PWMxH_ENABLE == true >
	PLIB_MCPWM_ChannelPWMxHOverrideEnable (MCPWM_ID_0 ,${MCPWM_CHANNEL_INSTANCE});
	</#if>
	
	<#if MCPWM_OVERRIDE_PWMxL_ENABLE == true >
	PLIB_MCPWM_ChannelPWMxLOverrideEnable (MCPWM_ID_0 ,${MCPWM_CHANNEL_INSTANCE});
	</#if>
	
	<#if MCPWM_PWMH_ENABLE == true >
	PLIB_MCPWM_ChannelPWMxHEnable (MCPWM_ID_0 ,${MCPWM_CHANNEL_INSTANCE});
	</#if>

	<#if MCPWM_PWML_ENABLE == true >
	PLIB_MCPWM_ChannelPWMxLEnable (MCPWM_ID_0 ,${MCPWM_CHANNEL_INSTANCE});
	</#if>

	<#if MCPWM_SWAP_PWMH_PWML_ENABLE == true >
	PLIB_MCPWM_ChannelSwapHighLowEnable (MCPWM_ID_0 ,${ MCPWM_CHANNEL_INSTANCE} );
	</#if>
	
	<#if MCPWM_FAULT_INTERRUPT_ENABLE == true >
	PLIB_MCPWM_ChannelFaultInterruptEnable (MCPWM_ID_0 , ${MCPWM_CHANNEL_INSTANCE});
	</#if>
	
	<#if MCPWM_CURRENTLIMIT_INTERRUPT_ENABLE == true >
	PLIB_MCPWM_ChannelCurrentLimitInterruptEnable (MCPWM_ID_0 , ${MCPWM_CHANNEL_INSTANCE});
	</#if>	

	<#if MCPWM_TRIGGER_INTERRUPT_ENABLE == true >
	PLIB_MCPWM_ChannelTriggerInterruptEnable (MCPWM_ID_0 , ${MCPWM_CHANNEL_INSTANCE});
	</#if>

	<#if MCPWM_PERIOD_MATCH_INTERRUPT_ENABLE == true >
	PLIB_MCPWM_ChannelPeriodMatchInterruptEnable (MCPWM_ID_0 ,${ MCPWM_CHANNEL_INSTANCE} );
	</#if>
	
	
	<#if MCPWM_PERIOD_RESET_INTERRUPT_ENABLE == true >
	PLIB_MCPWM_ChannelPeriodResetInterruptEnable (MCPWM_ID_0 ,${ MCPWM_CHANNEL_INSTANCE} );
	</#if>
	<#if MCPWM_CHANNEL_INTERRUPT_ENABLE == true>
	PLIB_INT_SourceFlagClear(INT_ID_0, ${MCPWM_CHANNEL_INTERRUPT_SOURCE});
	PLIB_INT_SourceEnable(INT_ID_0, ${MCPWM_CHANNEL_INTERRUPT_SOURCE});
	PLIB_INT_VectorPrioritySet(INT_ID_0, ${MCPWM_CHANNEL_INTERRUPT_SOURCE}, ${MCPWM_CHANNEL_INTERRUPT_PRIORITY});
	PLIB_INT_VectorSubPrioritySet(INT_ID_0, ${MCPWM_CHANNEL_INTERRUPT_SOURCE}, ${MCPWM_CHANNEL_INTERRUPT_SUBPRIORITY});      
	</#if>

</#macro>

// *****************************************************************************
// *****************************************************************************
// Section: MCPWM static driver functions
// *****************************************************************************
// *****************************************************************************

void DRV_MCPWM_Enable (void)
{
/*Enable MCPWM*/

PLIB_MCPWM_Enable (MCPWM_ID_0);

}

void DRV_MCPWM_Disable (void)
{
/*Disable MCPWM*/

PLIB_MCPWM_Disable (MCPWM_ID_0);

}

void DRV_MCPWM_Initialize(void)
{

PLIB_MCPWM_Disable (MCPWM_ID_0);

<#if CONFIG_DRV_MCPWM_STOP_IN_IDLE_MODE>
PLIB_MCPWM_StopInIdleEnable (MCPWM_ID_0);
</#if>

/* Configure Primary MCPWM Master Timer */
PLIB_MCPWM_PrimaryTimerSetup (MCPWM_ID_0 , ${CONFIG_DRV_MCPWM_PRIMARY_CLOCK_PRESCALER} , ${CONFIG_DRV_MCPWM_PRIMARY_TIMER_PERIOD});

/* Configure Secondary MCPWM Master Timer */
PLIB_MCPWM_SecondaryTimerSetup (MCPWM_ID_0 , ${CONFIG_DRV_MCPWM_SECONDARY_CLOCK_PRESCALER} , ${CONFIG_DRV_MCPWM_SECONDARY_TIMER_PERIOD});

/* Configure Primary Special Event Trigger */
PLIB_MCPWM_PrimarySpecialEventTriggerSetup (MCPWM_ID_0 , ${CONFIG_DRV_MCPWM_PRIMARY_SEVT_COMPARE_VALUE} , ${CONFIG_DRV_MCPWM_PRIMARY_SEVT_POSTSCALER});

<#if CONFIG_DRV_MCPWM_PRIMARY_SEVT_INTERRUPT_ENABLE == true>
PLIB_MCPWM_PrimarySpecialEventTriggerInterruptEnable (MCPWM_ID_0);
PLIB_INT_SourceFlagClear(INT_ID_0, INT_SOURCE_PWM_PRIMARY);
PLIB_INT_SourceEnable(INT_ID_0, INT_SOURCE_PWM_PRIMARY);
PLIB_INT_VectorPrioritySet(INT_ID_0, INT_SOURCE_PWM_PRIMARY, ${CONFIG_DRV_MCPWM_PRIMARY_SEVT_INTERRUPT_PRIORITY});
PLIB_INT_VectorSubPrioritySet(INT_ID_0, INT_SOURCE_PWM_PRIMARY, ${CONFIG_DRV_MCPWM_PRIMARY_SEVT_INTERRUPT_SUBPRIORITY});      
</#if>

/* Configure Secondary Special Event Trigger */
PLIB_MCPWM_SecondarySpecialEventTriggerSetup (MCPWM_ID_0 , ${CONFIG_DRV_MCPWM_SECONDARY_SEVT_COMPARE_VALUE} , ${CONFIG_DRV_MCPWM_SECONDARY_SEVT_POSTSCALER});

<#if CONFIG_DRV_MCPWM_SECONDARY_SEVT_INTERRUPT_ENABLE == true>
PLIB_MCPWM_SecondarySpecialEventTriggerInterruptEnable (MCPWM_ID_0);
PLIB_INT_SourceFlagClear(INT_ID_0, INT_SOURCE_PWM_SECONDARY);
PLIB_INT_SourceEnable(INT_ID_0, INT_SOURCE_PWM_SECONDARY);
PLIB_INT_VectorPrioritySet(INT_ID_0, INT_SOURCE_PWM_SECONDARY, ${CONFIG_DRV_MCPWM_SECONDARY_SEVT_INTERRUPT_PRIORITY});
PLIB_INT_VectorSubPrioritySet(INT_ID_0, INT_SOURCE_PWM_SECONDARY, ${CONFIG_DRV_MCPWM_SECONDARY_SEVT_INTERRUPT_SUBPRIORITY});      
</#if>

/* Configure Chop Clock */
<#if CONFIG_DRV_MCPWM_CHOP_CLOCK_ENABLE == true >
PLIB_MCPWM_ChopClockSetup (MCPWM_ID_0 , ${CONFIG_DRV_MCPWM_CHOP_CLOCK_PRESCALER} ,MCPWM_CHOP_CLOCK_ENABLE);
<#else>
PLIB_MCPWM_ChopClockSetup (MCPWM_ID_0 , ${CONFIG_DRV_MCPWM_CHOP_CLOCK_PRESCALER} ,MCPWM_CHOP_CLOCK_DISABLE);
</#if>
/*Configure PWM Channel */

<#if CONFIG_DRV_MCPWM_INST_IDX0 == true>
<@DRV_MCPWM_STATIC_FUNCTIONS MCPWM_CHANNEL_INSTANCE=CONFIG_DRV_MCPWM_CHANNEL_ID_IDX0 
MCPWM_TIME_BASE_SOURCE = CONFIG_DRV_MCPWM_CHANNEL_TIME_BASE_SOURCE_IDX0 
MCPWM_TIME_BASE_MODE = CONFIG_DRV_MCPWM_CHANNEL_TIME_BASE_MODE_IDX0
MCPWM_ALIGNMENT_MODE = CONFIG_DRV_MCPWM_CHANNEL_ALIGNMENT_MODE_IDX0
MCPWM_OUTPUT_MODE = CONFIG_DRV_MCPWM_CHANNEL_OUTPUT_MODE_IDX0
MCPWM_PWMxH_OUTPUT_POLARITY = CONFIG_DRV_MCPWM_CHANNEL_PWMxH_OUTPUT_POLARITY_IDX0
MCPWM_PWMxL_OUTPUT_POLARITY = CONFIG_DRV_MCPWM_CHANNEL_PWMxL_OUTPUT_POLARITY_IDX0
MCPWM_DEADTIME_MODE = CONFIG_DRV_MCPWM_CHANNEL_DEADTIME_MODE_IDX0
MCPWM_DEADTIME_POLARITY = CONFIG_DRV_MCPWM_CHANNEL_DEADTIME_COMPENSATION_POLARITY_IDX0
MCPWM_TRIGGER_POSTSCALER = CONFIG_DRV_MCPWM_CHANNEL_TRIGGER_POSTSCALER_IDX0
MCPWM_PRIMARY_TRIGGER_CYCLE_SELECT = CONFIG_DRV_MCPWM_CHANNEL_PRIMARY_TRIGGER_CYCLE_SELECT_IDX0
MCPWM_SECONDARY_TRIGGER_CYCLE_SELECT = CONFIG_DRV_MCPWM_CHANNEL_SECONDARY_TRIGGER_CYCLE_SELECT_IDX0
MCPWM_ADC_TRIGGER_SOURCE = CONFIG_DRV_MCPWM_CHANNEL_ADC_TRIGGER_SOURCE_IDX0
MCPWM_TRIGGER_INTERRUPT_SOURCE = CONFIG_DRV_MCPWM_CHANNEL_TRIGGER_INTERRUPT_SOURCE_IDX0
MCPWM_PRIMARY_TRIGGER_COMPARE_VALUE = CONFIG_DRV_MCPWM_CHANNEL_PRIMARY_TRIGGER_COMPARE_VALUE_IDX0
MCPWM_SECONDARY_TRIGGER_COMPARE_VALUE = CONFIG_DRV_MCPWM_CHANNEL_SECONDARY_TRIGGER_COMPARE_VALUE_IDX0
MCPWM_TRIGGER_INTERRUPT_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_TRIGGER_INTERRUPT_ENABLE_IDX0
MCPWM_LEB_TRIGGER_PWMxHRISINGEDGE_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_LEB_TRIGGER_PWMxHRISINGEDGE_ENABLE_IDX0
MCPWM_LEB_TRIGGER_PWMxHFALLINGEDGE_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_LEB_TRIGGER_PWMxHFALLINGEDGE_ENABLE_IDX0
MCPWM_LEB_TRIGGER_PWMxLRISINGEDGE_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_LEB_TRIGGER_PWMxLRISINGEDGE_ENABLE_IDX0
MCPWM_LEB_TRIGGER_PWMxLFALLINGEDGE_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_LEB_TRIGGER_PWMxLFALLINGEDGE_ENABLE_IDX0
MCPWM_FAULT_INPUT_LEB_CONTROL = CONFIG_DRV_MCPWM_CHANNEL_FAULT_INPUT_LEB_CONTROL_IDX0
MCPWM_CURRENTLIMIT_INPUT_LEB_CONTROL = CONFIG_DRV_MCPWM_CHANNEL_CURRENTLIMIT_INPUT_LEB_CONTROL_IDX0
MCPWM_LEB_PERIOD_VALUE = CONFIG_DRV_MCPWM_CHANNEL_LEB_PERIOD_VALUE_IDX0
MCPWM_CHOP_CLOCK_SOURCE = CONFIG_DRV_MCPWM_CHANNEL_CHOP_CLOCK_SOURCE_IDX0
MCPWM_PWMxH_CHOP_CONTROL = CONFIG_DRV_MCPWM_CHANNEL_PWMxH_CHOP_CONTROL_IDX0
MCPWM_PWMxL_CHOP_CONTROL = CONFIG_DRV_MCPWM_CHANNEL_PWMxL_CHOP_CONTROL_IDX0
MCPWM_FAULT_SOURCE = CONFIG_DRV_MCPWM_CHANNEL_FAULT_SOURCE_IDX0
MCPWM_FAULT_INPUT_POLARITY = CONFIG_DRV_MCPWM_CHANNEL_FAULT_INPUT_POLARITY_IDX0
MCPWM_FAULT_OVERRIDE_PWMxH_VALUE = CONFIG_DRV_MCPWM_CHANNEL_FAULT_OVERRIDE_PWMxH_VALUE_IDX0
MCPWM_FAULT_OVERRIDE_PWMxL_VALUE = CONFIG_DRV_MCPWM_CHANNEL_FAULT_OVERRIDE_PWMxL_VALUE_IDX0
MCPWM_FAULT_MODE = CONFIG_DRV_MCPWM_CHANNEL_FAULT_MODE_IDX0
MCPWM_FAULT_INTERRUPT_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_FAULT_INTERRUPT_ENABLE_IDX0
MCPWM_CURRENTLIMIT_SOURCE = CONFIG_DRV_MCPWM_CHANNEL_CURRENTLIMIT_SOURCE_IDX0
MCPWM_CURRENTLIMIT_INPUT_POLARITY = CONFIG_DRV_MCPWM_CHANNEL_CURRENTLIMIT_INPUT_POLARITY_IDX0
MCPWM_CURRENTLIMIT_OVERRIDE_PWMxH_VALUE = CONFIG_DRV_MCPWM_CHANNEL_CURRENTLIMIT_OVERRIDE_PWMxH_VALUE_IDX0
MCPWM_CURRENTLIMIT_OVERRIDE_PWMxL_VALUE = CONFIG_DRV_MCPWM_CHANNEL_CURRENTLIMIT_OVERRIDE_PWMxL_VALUE_IDX0
MCPWM_CURRENTLIMIT_MODE = CONFIG_DRV_MCPWM_CHANNEL_CURRENTLIMIT_MODE_IDX0
MCPWM_CURRENTLIMIT_INTERRUPT_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_CURRENTLIMIT_INTERRUPT_ENABLE_IDX0
MCPWM_OVERRIDE_PWMxH_VALUE =CONFIG_DRV_MCPWM_CHANNEL_OVERRIDE_PWMxH_VALUE_IDX0
MCPWM_OVERRIDE_PWMxL_VALUE =CONFIG_DRV_MCPWM_CHANNEL_OVERRIDE_PWMxL_VALUE_IDX0
MCPWM_OVERRIDE_PWMxH_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_OVERRIDE_PWMxH_ENABLE_IDX0
MCPWM_OVERRIDE_PWMxL_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_OVERRIDE_PWMxL_ENABLE_IDX0
MCPWM_SYNC_OVERRIDE_SELECT = CONFIG_DRV_MCPWM_CHANNEL_SYNC_OVERRIDE_SELECT_IDX0
MCPWM_PWMH_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_PWMH_ENABLE_IDX0
MCPWM_PERIOD_MATCH_INTERRUPT_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_PERIOD_MATCH_INTERRUPT_ENABLE_IDX0
MCPWM_PWML_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_PWML_ENABLE_IDX0
MCPWM_PERIOD_RESET_INTERRUPT_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_PERIOD_RESET_INTERRUPT_ENABLE_IDX0
MCPWM_SWAP_PWMH_PWML_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_SWAP_PWMH_PWML_IDX0
MCPWM_PDC_VALUE = CONFIG_DRV_MCPWM_PDC_VALUE_IDX0
MCPWM_SDC_VALUE = CONFIG_DRV_MCPWM_SDC_VALUE_IDX0
MCPWM_PHASE_VALUE = CONFIG_DRV_MCPWM_PHASE_VALUE_IDX0
MCPWM_DTR_VALUE = CONFIG_DRV_MCPWM_DTR_VALUE_IDX0
MCPWM_ALTDTR_VALUE = CONFIG_DRV_MCPWM_ALTDTR_VALUE_IDX0
MCPWM_DTCOMP_VALUE = CONFIG_DRV_MCPWM_DTCOMP_VALUE_IDX0
MCPWM_CHANNEL_INTERRUPT_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_INTERRUPT_ENABLE_IDX0
MCPWM_CHANNEL_INTERRUPT_PRIORITY = CONFIG_DRV_MCPWM_CHANNEL_INTERRUPT_PRIORITY_IDX0
MCPWM_CHANNEL_INTERRUPT_SUBPRIORITY = CONFIG_DRV_MCPWM_CHANNEL_INTERRUPT_SUBPRIORITY_IDX0
MCPWM_CHANNEL_INTERRUPT_VECTOR = CONFIG_DRV_MCPWM_CHANNEL_INTERRUPT_VECTOR_IDX0
MCPWM_CHANNEL_INTERRUPT_SOURCE = CONFIG_DRV_MCPWM_CHANNEL_INTERRUPT_SOURCE_IDX0/>
										
</#if>

<#if CONFIG_DRV_MCPWM_INST_IDX1 == true>
<@DRV_MCPWM_STATIC_FUNCTIONS MCPWM_CHANNEL_INSTANCE=CONFIG_DRV_MCPWM_CHANNEL_ID_IDX1 
MCPWM_TIME_BASE_SOURCE = CONFIG_DRV_MCPWM_CHANNEL_TIME_BASE_SOURCE_IDX1 
MCPWM_TIME_BASE_MODE = CONFIG_DRV_MCPWM_CHANNEL_TIME_BASE_MODE_IDX1
MCPWM_ALIGNMENT_MODE = CONFIG_DRV_MCPWM_CHANNEL_ALIGNMENT_MODE_IDX1
MCPWM_OUTPUT_MODE = CONFIG_DRV_MCPWM_CHANNEL_OUTPUT_MODE_IDX1
MCPWM_PWMxH_OUTPUT_POLARITY = CONFIG_DRV_MCPWM_CHANNEL_PWMxH_OUTPUT_POLARITY_IDX1
MCPWM_PWMxL_OUTPUT_POLARITY = CONFIG_DRV_MCPWM_CHANNEL_PWMxL_OUTPUT_POLARITY_IDX1
MCPWM_DEADTIME_MODE = CONFIG_DRV_MCPWM_CHANNEL_DEADTIME_MODE_IDX1
MCPWM_DEADTIME_POLARITY = CONFIG_DRV_MCPWM_CHANNEL_DEADTIME_COMPENSATION_POLARITY_IDX1
MCPWM_TRIGGER_POSTSCALER = CONFIG_DRV_MCPWM_CHANNEL_TRIGGER_POSTSCALER_IDX1
MCPWM_PRIMARY_TRIGGER_CYCLE_SELECT = CONFIG_DRV_MCPWM_CHANNEL_PRIMARY_TRIGGER_CYCLE_SELECT_IDX1
MCPWM_SECONDARY_TRIGGER_CYCLE_SELECT = CONFIG_DRV_MCPWM_CHANNEL_SECONDARY_TRIGGER_CYCLE_SELECT_IDX1
MCPWM_ADC_TRIGGER_SOURCE = CONFIG_DRV_MCPWM_CHANNEL_ADC_TRIGGER_SOURCE_IDX1
MCPWM_TRIGGER_INTERRUPT_SOURCE = CONFIG_DRV_MCPWM_CHANNEL_TRIGGER_INTERRUPT_SOURCE_IDX1
MCPWM_PRIMARY_TRIGGER_COMPARE_VALUE = CONFIG_DRV_MCPWM_CHANNEL_PRIMARY_TRIGGER_COMPARE_VALUE_IDX1
MCPWM_SECONDARY_TRIGGER_COMPARE_VALUE = CONFIG_DRV_MCPWM_CHANNEL_SECONDARY_TRIGGER_COMPARE_VALUE_IDX1
MCPWM_TRIGGER_INTERRUPT_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_TRIGGER_INTERRUPT_ENABLE_IDX1
MCPWM_LEB_TRIGGER_PWMxHRISINGEDGE_ENABLE =CONFIG_DRV_MCPWM_CHANNEL_LEB_TRIGGER_PWMxHRISINGEDGE_ENABLE_IDX1
MCPWM_LEB_TRIGGER_PWMxHFALLINGEDGE_ENABLE =CONFIG_DRV_MCPWM_CHANNEL_LEB_TRIGGER_PWMxHFALLINGEDGE_ENABLE_IDX1
MCPWM_LEB_TRIGGER_PWMxLRISINGEDGE_ENABLE =CONFIG_DRV_MCPWM_CHANNEL_LEB_TRIGGER_PWMxLRISINGEDGE_ENABLE_IDX1
MCPWM_LEB_TRIGGER_PWMxLFALLINGEDGE_ENABLE =CONFIG_DRV_MCPWM_CHANNEL_LEB_TRIGGER_PWMxLFALLINGEDGE_ENABLE_IDX1
MCPWM_FAULT_INPUT_LEB_CONTROL = CONFIG_DRV_MCPWM_CHANNEL_FAULT_INPUT_LEB_CONTROL_IDX1
MCPWM_CURRENTLIMIT_INPUT_LEB_CONTROL = CONFIG_DRV_MCPWM_CHANNEL_CURRENTLIMIT_INPUT_LEB_CONTROL_IDX1
MCPWM_LEB_PERIOD_VALUE = CONFIG_DRV_MCPWM_CHANNEL_LEB_PERIOD_VALUE_IDX1
MCPWM_CHOP_CLOCK_SOURCE = CONFIG_DRV_MCPWM_CHANNEL_CHOP_CLOCK_SOURCE_IDX1
MCPWM_PWMxH_CHOP_CONTROL = CONFIG_DRV_MCPWM_CHANNEL_PWMxH_CHOP_CONTROL_IDX1
MCPWM_PWMxL_CHOP_CONTROL = CONFIG_DRV_MCPWM_CHANNEL_PWMxL_CHOP_CONTROL_IDX1
MCPWM_FAULT_SOURCE = CONFIG_DRV_MCPWM_CHANNEL_FAULT_SOURCE_IDX1
MCPWM_FAULT_INPUT_POLARITY = CONFIG_DRV_MCPWM_CHANNEL_FAULT_INPUT_POLARITY_IDX1
MCPWM_FAULT_OVERRIDE_PWMxH_VALUE = CONFIG_DRV_MCPWM_CHANNEL_FAULT_OVERRIDE_PWMxH_VALUE_IDX1
MCPWM_FAULT_OVERRIDE_PWMxL_VALUE = CONFIG_DRV_MCPWM_CHANNEL_FAULT_OVERRIDE_PWMxL_VALUE_IDX1
MCPWM_FAULT_MODE = CONFIG_DRV_MCPWM_CHANNEL_FAULT_MODE_IDX1
MCPWM_FAULT_INTERRUPT_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_FAULT_INTERRUPT_ENABLE_IDX1
MCPWM_CURRENTLIMIT_SOURCE = CONFIG_DRV_MCPWM_CHANNEL_CURRENTLIMIT_SOURCE_IDX1
MCPWM_CURRENTLIMIT_INPUT_POLARITY = CONFIG_DRV_MCPWM_CHANNEL_CURRENTLIMIT_INPUT_POLARITY_IDX1
MCPWM_CURRENTLIMIT_OVERRIDE_PWMxH_VALUE =CONFIG_DRV_MCPWM_CHANNEL_CURRENTLIMIT_OVERRIDE_PWMxH_VALUE_IDX1
MCPWM_CURRENTLIMIT_OVERRIDE_PWMxL_VALUE =CONFIG_DRV_MCPWM_CHANNEL_CURRENTLIMIT_OVERRIDE_PWMxL_VALUE_IDX1
MCPWM_CURRENTLIMIT_MODE = CONFIG_DRV_MCPWM_CHANNEL_CURRENTLIMIT_MODE_IDX1
MCPWM_CURRENTLIMIT_INTERRUPT_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_CURRENTLIMIT_INTERRUPT_ENABLE_IDX1
MCPWM_OVERRIDE_PWMxH_VALUE =CONFIG_DRV_MCPWM_CHANNEL_OVERRIDE_PWMxH_VALUE_IDX1
MCPWM_OVERRIDE_PWMxL_VALUE =CONFIG_DRV_MCPWM_CHANNEL_OVERRIDE_PWMxL_VALUE_IDX1
MCPWM_OVERRIDE_PWMxH_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_OVERRIDE_PWMxH_ENABLE_IDX1
MCPWM_OVERRIDE_PWMxL_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_OVERRIDE_PWMxL_ENABLE_IDX1
MCPWM_SYNC_OVERRIDE_SELECT = CONFIG_DRV_MCPWM_CHANNEL_SYNC_OVERRIDE_SELECT_IDX1
MCPWM_PWMH_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_PWMH_ENABLE_IDX1
MCPWM_PERIOD_MATCH_INTERRUPT_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_PERIOD_MATCH_INTERRUPT_ENABLE_IDX1
MCPWM_PWML_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_PWML_ENABLE_IDX1
MCPWM_PERIOD_RESET_INTERRUPT_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_PERIOD_RESET_INTERRUPT_ENABLE_IDX1
MCPWM_SWAP_PWMH_PWML_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_SWAP_PWMH_PWML_IDX1
MCPWM_PDC_VALUE = CONFIG_DRV_MCPWM_PDC_VALUE_IDX1
MCPWM_SDC_VALUE = CONFIG_DRV_MCPWM_SDC_VALUE_IDX1
MCPWM_PHASE_VALUE = CONFIG_DRV_MCPWM_PHASE_VALUE_IDX1
MCPWM_DTR_VALUE = CONFIG_DRV_MCPWM_DTR_VALUE_IDX1
MCPWM_ALTDTR_VALUE = CONFIG_DRV_MCPWM_ALTDTR_VALUE_IDX1
MCPWM_DTCOMP_VALUE = CONFIG_DRV_MCPWM_DTCOMP_VALUE_IDX1
MCPWM_CHANNEL_INTERRUPT_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_INTERRUPT_ENABLE_IDX1
MCPWM_CHANNEL_INTERRUPT_PRIORITY = CONFIG_DRV_MCPWM_CHANNEL_INTERRUPT_PRIORITY_IDX1
MCPWM_CHANNEL_INTERRUPT_SUBPRIORITY = CONFIG_DRV_MCPWM_CHANNEL_INTERRUPT_SUBPRIORITY_IDX1
MCPWM_CHANNEL_INTERRUPT_VECTOR = CONFIG_DRV_MCPWM_CHANNEL_INTERRUPT_VECTOR_IDX1
MCPWM_CHANNEL_INTERRUPT_SOURCE = CONFIG_DRV_MCPWM_CHANNEL_INTERRUPT_SOURCE_IDX1/>
</#if>

<#if CONFIG_DRV_MCPWM_INST_IDX2 == true>
<@DRV_MCPWM_STATIC_FUNCTIONS MCPWM_CHANNEL_INSTANCE=CONFIG_DRV_MCPWM_CHANNEL_ID_IDX2 
MCPWM_TIME_BASE_SOURCE = CONFIG_DRV_MCPWM_CHANNEL_TIME_BASE_SOURCE_IDX2 
MCPWM_TIME_BASE_MODE = CONFIG_DRV_MCPWM_CHANNEL_TIME_BASE_MODE_IDX2
MCPWM_ALIGNMENT_MODE = CONFIG_DRV_MCPWM_CHANNEL_ALIGNMENT_MODE_IDX2
MCPWM_OUTPUT_MODE = CONFIG_DRV_MCPWM_CHANNEL_OUTPUT_MODE_IDX2
MCPWM_PWMxH_OUTPUT_POLARITY = CONFIG_DRV_MCPWM_CHANNEL_PWMxH_OUTPUT_POLARITY_IDX2
MCPWM_PWMxL_OUTPUT_POLARITY = CONFIG_DRV_MCPWM_CHANNEL_PWMxL_OUTPUT_POLARITY_IDX2
MCPWM_DEADTIME_MODE = CONFIG_DRV_MCPWM_CHANNEL_DEADTIME_MODE_IDX2
MCPWM_DEADTIME_POLARITY = CONFIG_DRV_MCPWM_CHANNEL_DEADTIME_COMPENSATION_POLARITY_IDX2
MCPWM_TRIGGER_POSTSCALER = CONFIG_DRV_MCPWM_CHANNEL_TRIGGER_POSTSCALER_IDX2
MCPWM_PRIMARY_TRIGGER_CYCLE_SELECT = CONFIG_DRV_MCPWM_CHANNEL_PRIMARY_TRIGGER_CYCLE_SELECT_IDX2
MCPWM_SECONDARY_TRIGGER_CYCLE_SELECT = CONFIG_DRV_MCPWM_CHANNEL_SECONDARY_TRIGGER_CYCLE_SELECT_IDX2
MCPWM_ADC_TRIGGER_SOURCE = CONFIG_DRV_MCPWM_CHANNEL_ADC_TRIGGER_SOURCE_IDX2
MCPWM_TRIGGER_INTERRUPT_SOURCE = CONFIG_DRV_MCPWM_CHANNEL_TRIGGER_INTERRUPT_SOURCE_IDX2
MCPWM_PRIMARY_TRIGGER_COMPARE_VALUE = CONFIG_DRV_MCPWM_CHANNEL_PRIMARY_TRIGGER_COMPARE_VALUE_IDX2
MCPWM_SECONDARY_TRIGGER_COMPARE_VALUE = CONFIG_DRV_MCPWM_CHANNEL_SECONDARY_TRIGGER_COMPARE_VALUE_IDX2
MCPWM_TRIGGER_INTERRUPT_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_TRIGGER_INTERRUPT_ENABLE_IDX2
MCPWM_LEB_TRIGGER_PWMxHRISINGEDGE_ENABLE =CONFIG_DRV_MCPWM_CHANNEL_LEB_TRIGGER_PWMxHRISINGEDGE_ENABLE_IDX2
MCPWM_LEB_TRIGGER_PWMxHFALLINGEDGE_ENABLE =CONFIG_DRV_MCPWM_CHANNEL_LEB_TRIGGER_PWMxHFALLINGEDGE_ENABLE_IDX2
MCPWM_LEB_TRIGGER_PWMxLRISINGEDGE_ENABLE =CONFIG_DRV_MCPWM_CHANNEL_LEB_TRIGGER_PWMxLRISINGEDGE_ENABLE_IDX2
MCPWM_LEB_TRIGGER_PWMxLFALLINGEDGE_ENABLE =CONFIG_DRV_MCPWM_CHANNEL_LEB_TRIGGER_PWMxLFALLINGEDGE_ENABLE_IDX2
MCPWM_FAULT_INPUT_LEB_CONTROL = CONFIG_DRV_MCPWM_CHANNEL_FAULT_INPUT_LEB_CONTROL_IDX2
MCPWM_CURRENTLIMIT_INPUT_LEB_CONTROL = CONFIG_DRV_MCPWM_CHANNEL_CURRENTLIMIT_INPUT_LEB_CONTROL_IDX2
MCPWM_LEB_PERIOD_VALUE = CONFIG_DRV_MCPWM_CHANNEL_LEB_PERIOD_VALUE_IDX2
MCPWM_CHOP_CLOCK_SOURCE = CONFIG_DRV_MCPWM_CHANNEL_CHOP_CLOCK_SOURCE_IDX2
MCPWM_PWMxH_CHOP_CONTROL = CONFIG_DRV_MCPWM_CHANNEL_PWMxH_CHOP_CONTROL_IDX2
MCPWM_PWMxL_CHOP_CONTROL = CONFIG_DRV_MCPWM_CHANNEL_PWMxL_CHOP_CONTROL_IDX2
MCPWM_FAULT_SOURCE = CONFIG_DRV_MCPWM_CHANNEL_FAULT_SOURCE_IDX2
MCPWM_FAULT_INPUT_POLARITY = CONFIG_DRV_MCPWM_CHANNEL_FAULT_INPUT_POLARITY_IDX2
MCPWM_FAULT_OVERRIDE_PWMxH_VALUE = CONFIG_DRV_MCPWM_CHANNEL_FAULT_OVERRIDE_PWMxH_VALUE_IDX2
MCPWM_FAULT_OVERRIDE_PWMxL_VALUE = CONFIG_DRV_MCPWM_CHANNEL_FAULT_OVERRIDE_PWMxL_VALUE_IDX2
MCPWM_FAULT_MODE = CONFIG_DRV_MCPWM_CHANNEL_FAULT_MODE_IDX2
MCPWM_FAULT_INTERRUPT_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_FAULT_INTERRUPT_ENABLE_IDX2
MCPWM_CURRENTLIMIT_SOURCE = CONFIG_DRV_MCPWM_CHANNEL_CURRENTLIMIT_SOURCE_IDX2
MCPWM_CURRENTLIMIT_INPUT_POLARITY = CONFIG_DRV_MCPWM_CHANNEL_CURRENTLIMIT_INPUT_POLARITY_IDX2
MCPWM_CURRENTLIMIT_OVERRIDE_PWMxH_VALUE =CONFIG_DRV_MCPWM_CHANNEL_CURRENTLIMIT_OVERRIDE_PWMxH_VALUE_IDX2
MCPWM_CURRENTLIMIT_OVERRIDE_PWMxL_VALUE =CONFIG_DRV_MCPWM_CHANNEL_CURRENTLIMIT_OVERRIDE_PWMxL_VALUE_IDX2
MCPWM_CURRENTLIMIT_MODE = CONFIG_DRV_MCPWM_CHANNEL_CURRENTLIMIT_MODE_IDX2
MCPWM_CURRENTLIMIT_INTERRUPT_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_CURRENTLIMIT_INTERRUPT_ENABLE_IDX2
MCPWM_OVERRIDE_PWMxH_VALUE =CONFIG_DRV_MCPWM_CHANNEL_OVERRIDE_PWMxH_VALUE_IDX2
MCPWM_OVERRIDE_PWMxL_VALUE =CONFIG_DRV_MCPWM_CHANNEL_OVERRIDE_PWMxL_VALUE_IDX2
MCPWM_OVERRIDE_PWMxH_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_OVERRIDE_PWMxH_ENABLE_IDX2
MCPWM_OVERRIDE_PWMxL_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_OVERRIDE_PWMxL_ENABLE_IDX2
MCPWM_SYNC_OVERRIDE_SELECT = CONFIG_DRV_MCPWM_CHANNEL_SYNC_OVERRIDE_SELECT_IDX2
MCPWM_PWMH_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_PWMH_ENABLE_IDX2
MCPWM_PERIOD_MATCH_INTERRUPT_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_PERIOD_MATCH_INTERRUPT_ENABLE_IDX2
MCPWM_PWML_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_PWML_ENABLE_IDX2
MCPWM_PERIOD_RESET_INTERRUPT_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_PERIOD_RESET_INTERRUPT_ENABLE_IDX2
MCPWM_SWAP_PWMH_PWML_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_SWAP_PWMH_PWML_IDX2
MCPWM_PDC_VALUE = CONFIG_DRV_MCPWM_PDC_VALUE_IDX2
MCPWM_SDC_VALUE = CONFIG_DRV_MCPWM_SDC_VALUE_IDX2
MCPWM_PHASE_VALUE = CONFIG_DRV_MCPWM_PHASE_VALUE_IDX2
MCPWM_DTR_VALUE = CONFIG_DRV_MCPWM_DTR_VALUE_IDX2
MCPWM_ALTDTR_VALUE = CONFIG_DRV_MCPWM_ALTDTR_VALUE_IDX2
MCPWM_DTCOMP_VALUE = CONFIG_DRV_MCPWM_DTCOMP_VALUE_IDX2
MCPWM_CHANNEL_INTERRUPT_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_INTERRUPT_ENABLE_IDX2
MCPWM_CHANNEL_INTERRUPT_PRIORITY = CONFIG_DRV_MCPWM_CHANNEL_INTERRUPT_PRIORITY_IDX2
MCPWM_CHANNEL_INTERRUPT_SUBPRIORITY = CONFIG_DRV_MCPWM_CHANNEL_INTERRUPT_SUBPRIORITY_IDX2
MCPWM_CHANNEL_INTERRUPT_VECTOR = CONFIG_DRV_MCPWM_CHANNEL_INTERRUPT_VECTOR_IDX2
MCPWM_CHANNEL_INTERRUPT_SOURCE = CONFIG_DRV_MCPWM_CHANNEL_INTERRUPT_SOURCE_IDX2/>
</#if>

<#if CONFIG_DRV_MCPWM_INST_IDX3 == true>
<@DRV_MCPWM_STATIC_FUNCTIONS MCPWM_CHANNEL_INSTANCE=CONFIG_DRV_MCPWM_CHANNEL_ID_IDX3 
MCPWM_TIME_BASE_SOURCE = CONFIG_DRV_MCPWM_CHANNEL_TIME_BASE_SOURCE_IDX3 
MCPWM_TIME_BASE_MODE = CONFIG_DRV_MCPWM_CHANNEL_TIME_BASE_MODE_IDX3
MCPWM_ALIGNMENT_MODE = CONFIG_DRV_MCPWM_CHANNEL_ALIGNMENT_MODE_IDX3
MCPWM_OUTPUT_MODE = CONFIG_DRV_MCPWM_CHANNEL_OUTPUT_MODE_IDX3
MCPWM_PWMxH_OUTPUT_POLARITY = CONFIG_DRV_MCPWM_CHANNEL_PWMxH_OUTPUT_POLARITY_IDX3
MCPWM_PWMxL_OUTPUT_POLARITY = CONFIG_DRV_MCPWM_CHANNEL_PWMxL_OUTPUT_POLARITY_IDX3
MCPWM_DEADTIME_MODE = CONFIG_DRV_MCPWM_CHANNEL_DEADTIME_MODE_IDX3
MCPWM_DEADTIME_POLARITY = CONFIG_DRV_MCPWM_CHANNEL_DEADTIME_COMPENSATION_POLARITY_IDX3
MCPWM_TRIGGER_POSTSCALER = CONFIG_DRV_MCPWM_CHANNEL_TRIGGER_POSTSCALER_IDX3
MCPWM_PRIMARY_TRIGGER_CYCLE_SELECT = CONFIG_DRV_MCPWM_CHANNEL_PRIMARY_TRIGGER_CYCLE_SELECT_IDX3
MCPWM_SECONDARY_TRIGGER_CYCLE_SELECT = CONFIG_DRV_MCPWM_CHANNEL_SECONDARY_TRIGGER_CYCLE_SELECT_IDX3
MCPWM_ADC_TRIGGER_SOURCE = CONFIG_DRV_MCPWM_CHANNEL_ADC_TRIGGER_SOURCE_IDX3
MCPWM_TRIGGER_INTERRUPT_SOURCE = CONFIG_DRV_MCPWM_CHANNEL_TRIGGER_INTERRUPT_SOURCE_IDX3
MCPWM_PRIMARY_TRIGGER_COMPARE_VALUE = CONFIG_DRV_MCPWM_CHANNEL_PRIMARY_TRIGGER_COMPARE_VALUE_IDX3
MCPWM_SECONDARY_TRIGGER_COMPARE_VALUE = CONFIG_DRV_MCPWM_CHANNEL_SECONDARY_TRIGGER_COMPARE_VALUE_IDX3
MCPWM_TRIGGER_INTERRUPT_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_TRIGGER_INTERRUPT_ENABLE_IDX3
MCPWM_LEB_TRIGGER_PWMxHRISINGEDGE_ENABLE =CONFIG_DRV_MCPWM_CHANNEL_LEB_TRIGGER_PWMxHRISINGEDGE_ENABLE_IDX3
MCPWM_LEB_TRIGGER_PWMxHFALLINGEDGE_ENABLE =CONFIG_DRV_MCPWM_CHANNEL_LEB_TRIGGER_PWMxHFALLINGEDGE_ENABLE_IDX3
MCPWM_LEB_TRIGGER_PWMxLRISINGEDGE_ENABLE =CONFIG_DRV_MCPWM_CHANNEL_LEB_TRIGGER_PWMxLRISINGEDGE_ENABLE_IDX3
MCPWM_LEB_TRIGGER_PWMxLFALLINGEDGE_ENABLE =CONFIG_DRV_MCPWM_CHANNEL_LEB_TRIGGER_PWMxLFALLINGEDGE_ENABLE_IDX3
MCPWM_FAULT_INPUT_LEB_CONTROL = CONFIG_DRV_MCPWM_CHANNEL_FAULT_INPUT_LEB_CONTROL_IDX3
MCPWM_CURRENTLIMIT_INPUT_LEB_CONTROL = CONFIG_DRV_MCPWM_CHANNEL_CURRENTLIMIT_INPUT_LEB_CONTROL_IDX3
MCPWM_LEB_PERIOD_VALUE = CONFIG_DRV_MCPWM_CHANNEL_LEB_PERIOD_VALUE_IDX3
MCPWM_CHOP_CLOCK_SOURCE = CONFIG_DRV_MCPWM_CHANNEL_CHOP_CLOCK_SOURCE_IDX3
MCPWM_PWMxH_CHOP_CONTROL = CONFIG_DRV_MCPWM_CHANNEL_PWMxH_CHOP_CONTROL_IDX3
MCPWM_PWMxL_CHOP_CONTROL = CONFIG_DRV_MCPWM_CHANNEL_PWMxL_CHOP_CONTROL_IDX3
MCPWM_FAULT_SOURCE = CONFIG_DRV_MCPWM_CHANNEL_FAULT_SOURCE_IDX3
MCPWM_FAULT_INPUT_POLARITY = CONFIG_DRV_MCPWM_CHANNEL_FAULT_INPUT_POLARITY_IDX3
MCPWM_FAULT_OVERRIDE_PWMxH_VALUE = CONFIG_DRV_MCPWM_CHANNEL_FAULT_OVERRIDE_PWMxH_VALUE_IDX3
MCPWM_FAULT_OVERRIDE_PWMxL_VALUE = CONFIG_DRV_MCPWM_CHANNEL_FAULT_OVERRIDE_PWMxL_VALUE_IDX3
MCPWM_FAULT_MODE = CONFIG_DRV_MCPWM_CHANNEL_FAULT_MODE_IDX3
MCPWM_FAULT_INTERRUPT_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_FAULT_INTERRUPT_ENABLE_IDX3
MCPWM_CURRENTLIMIT_SOURCE = CONFIG_DRV_MCPWM_CHANNEL_CURRENTLIMIT_SOURCE_IDX3
MCPWM_CURRENTLIMIT_INPUT_POLARITY = CONFIG_DRV_MCPWM_CHANNEL_CURRENTLIMIT_INPUT_POLARITY_IDX3
MCPWM_CURRENTLIMIT_OVERRIDE_PWMxH_VALUE =CONFIG_DRV_MCPWM_CHANNEL_CURRENTLIMIT_OVERRIDE_PWMxH_VALUE_IDX3
MCPWM_CURRENTLIMIT_OVERRIDE_PWMxL_VALUE =CONFIG_DRV_MCPWM_CHANNEL_CURRENTLIMIT_OVERRIDE_PWMxL_VALUE_IDX3
MCPWM_CURRENTLIMIT_MODE = CONFIG_DRV_MCPWM_CHANNEL_CURRENTLIMIT_MODE_IDX3
MCPWM_CURRENTLIMIT_INTERRUPT_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_CURRENTLIMIT_INTERRUPT_ENABLE_IDX3
MCPWM_OVERRIDE_PWMxH_VALUE =CONFIG_DRV_MCPWM_CHANNEL_OVERRIDE_PWMxH_VALUE_IDX3
MCPWM_OVERRIDE_PWMxL_VALUE =CONFIG_DRV_MCPWM_CHANNEL_OVERRIDE_PWMxL_VALUE_IDX3
MCPWM_OVERRIDE_PWMxH_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_OVERRIDE_PWMxH_ENABLE_IDX3
MCPWM_OVERRIDE_PWMxL_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_OVERRIDE_PWMxL_ENABLE_IDX3
MCPWM_SYNC_OVERRIDE_SELECT = CONFIG_DRV_MCPWM_CHANNEL_SYNC_OVERRIDE_SELECT_IDX3
MCPWM_PWMH_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_PWMH_ENABLE_IDX3
MCPWM_PERIOD_MATCH_INTERRUPT_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_PERIOD_MATCH_INTERRUPT_ENABLE_IDX3
MCPWM_PWML_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_PWML_ENABLE_IDX3
MCPWM_PERIOD_RESET_INTERRUPT_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_PERIOD_RESET_INTERRUPT_ENABLE_IDX3
MCPWM_SWAP_PWMH_PWML_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_SWAP_PWMH_PWML_IDX3
MCPWM_PDC_VALUE = CONFIG_DRV_MCPWM_PDC_VALUE_IDX3
MCPWM_SDC_VALUE = CONFIG_DRV_MCPWM_SDC_VALUE_IDX3
MCPWM_PHASE_VALUE = CONFIG_DRV_MCPWM_PHASE_VALUE_IDX3
MCPWM_DTR_VALUE = CONFIG_DRV_MCPWM_DTR_VALUE_IDX3
MCPWM_ALTDTR_VALUE = CONFIG_DRV_MCPWM_ALTDTR_VALUE_IDX3
MCPWM_DTCOMP_VALUE = CONFIG_DRV_MCPWM_DTCOMP_VALUE_IDX3
MCPWM_CHANNEL_INTERRUPT_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_INTERRUPT_ENABLE_IDX3
MCPWM_CHANNEL_INTERRUPT_PRIORITY = CONFIG_DRV_MCPWM_CHANNEL_INTERRUPT_PRIORITY_IDX3
MCPWM_CHANNEL_INTERRUPT_SUBPRIORITY = CONFIG_DRV_MCPWM_CHANNEL_INTERRUPT_SUBPRIORITY_IDX3
MCPWM_CHANNEL_INTERRUPT_VECTOR = CONFIG_DRV_MCPWM_CHANNEL_INTERRUPT_VECTOR_IDX3
MCPWM_CHANNEL_INTERRUPT_SOURCE = CONFIG_DRV_MCPWM_CHANNEL_INTERRUPT_SOURCE_IDX3/>
</#if>

<#if CONFIG_DRV_MCPWM_INST_IDX4 == true>
<@DRV_MCPWM_STATIC_FUNCTIONS MCPWM_CHANNEL_INSTANCE=CONFIG_DRV_MCPWM_CHANNEL_ID_IDX4 
MCPWM_TIME_BASE_SOURCE = CONFIG_DRV_MCPWM_CHANNEL_TIME_BASE_SOURCE_IDX4 
MCPWM_TIME_BASE_MODE = CONFIG_DRV_MCPWM_CHANNEL_TIME_BASE_MODE_IDX4
MCPWM_ALIGNMENT_MODE = CONFIG_DRV_MCPWM_CHANNEL_ALIGNMENT_MODE_IDX4
MCPWM_OUTPUT_MODE = CONFIG_DRV_MCPWM_CHANNEL_OUTPUT_MODE_IDX4
MCPWM_PWMxH_OUTPUT_POLARITY = CONFIG_DRV_MCPWM_CHANNEL_PWMxH_OUTPUT_POLARITY_IDX4
MCPWM_PWMxL_OUTPUT_POLARITY = CONFIG_DRV_MCPWM_CHANNEL_PWMxL_OUTPUT_POLARITY_IDX4
MCPWM_DEADTIME_MODE = CONFIG_DRV_MCPWM_CHANNEL_DEADTIME_MODE_IDX4
MCPWM_DEADTIME_POLARITY = CONFIG_DRV_MCPWM_CHANNEL_DEADTIME_COMPENSATION_POLARITY_IDX4
MCPWM_TRIGGER_POSTSCALER = CONFIG_DRV_MCPWM_CHANNEL_TRIGGER_POSTSCALER_IDX4
MCPWM_PRIMARY_TRIGGER_CYCLE_SELECT = CONFIG_DRV_MCPWM_CHANNEL_PRIMARY_TRIGGER_CYCLE_SELECT_IDX4
MCPWM_SECONDARY_TRIGGER_CYCLE_SELECT = CONFIG_DRV_MCPWM_CHANNEL_SECONDARY_TRIGGER_CYCLE_SELECT_IDX4
MCPWM_ADC_TRIGGER_SOURCE = CONFIG_DRV_MCPWM_CHANNEL_ADC_TRIGGER_SOURCE_IDX4
MCPWM_TRIGGER_INTERRUPT_SOURCE = CONFIG_DRV_MCPWM_CHANNEL_TRIGGER_INTERRUPT_SOURCE_IDX4
MCPWM_PRIMARY_TRIGGER_COMPARE_VALUE = CONFIG_DRV_MCPWM_CHANNEL_PRIMARY_TRIGGER_COMPARE_VALUE_IDX4
MCPWM_SECONDARY_TRIGGER_COMPARE_VALUE = CONFIG_DRV_MCPWM_CHANNEL_SECONDARY_TRIGGER_COMPARE_VALUE_IDX4
MCPWM_TRIGGER_INTERRUPT_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_TRIGGER_INTERRUPT_ENABLE_IDX4
MCPWM_LEB_TRIGGER_PWMxHRISINGEDGE_ENABLE =CONFIG_DRV_MCPWM_CHANNEL_LEB_TRIGGER_PWMxHRISINGEDGE_ENABLE_IDX4
MCPWM_LEB_TRIGGER_PWMxHFALLINGEDGE_ENABLE =CONFIG_DRV_MCPWM_CHANNEL_LEB_TRIGGER_PWMxHFALLINGEDGE_ENABLE_IDX4
MCPWM_LEB_TRIGGER_PWMxLRISINGEDGE_ENABLE =CONFIG_DRV_MCPWM_CHANNEL_LEB_TRIGGER_PWMxLRISINGEDGE_ENABLE_IDX4
MCPWM_LEB_TRIGGER_PWMxLFALLINGEDGE_ENABLE =CONFIG_DRV_MCPWM_CHANNEL_LEB_TRIGGER_PWMxLFALLINGEDGE_ENABLE_IDX4
MCPWM_FAULT_INPUT_LEB_CONTROL = CONFIG_DRV_MCPWM_CHANNEL_FAULT_INPUT_LEB_CONTROL_IDX4
MCPWM_CURRENTLIMIT_INPUT_LEB_CONTROL = CONFIG_DRV_MCPWM_CHANNEL_CURRENTLIMIT_INPUT_LEB_CONTROL_IDX4
MCPWM_LEB_PERIOD_VALUE = CONFIG_DRV_MCPWM_CHANNEL_LEB_PERIOD_VALUE_IDX4
MCPWM_CHOP_CLOCK_SOURCE = CONFIG_DRV_MCPWM_CHANNEL_CHOP_CLOCK_SOURCE_IDX4
MCPWM_PWMxH_CHOP_CONTROL = CONFIG_DRV_MCPWM_CHANNEL_PWMxH_CHOP_CONTROL_IDX4
MCPWM_PWMxL_CHOP_CONTROL = CONFIG_DRV_MCPWM_CHANNEL_PWMxL_CHOP_CONTROL_IDX4
MCPWM_FAULT_SOURCE = CONFIG_DRV_MCPWM_CHANNEL_FAULT_SOURCE_IDX4
MCPWM_FAULT_INPUT_POLARITY = CONFIG_DRV_MCPWM_CHANNEL_FAULT_INPUT_POLARITY_IDX4
MCPWM_FAULT_OVERRIDE_PWMxH_VALUE = CONFIG_DRV_MCPWM_CHANNEL_FAULT_OVERRIDE_PWMxH_VALUE_IDX4
MCPWM_FAULT_OVERRIDE_PWMxL_VALUE = CONFIG_DRV_MCPWM_CHANNEL_FAULT_OVERRIDE_PWMxL_VALUE_IDX4
MCPWM_FAULT_MODE = CONFIG_DRV_MCPWM_CHANNEL_FAULT_MODE_IDX4
MCPWM_FAULT_INTERRUPT_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_FAULT_INTERRUPT_ENABLE_IDX4
MCPWM_CURRENTLIMIT_SOURCE = CONFIG_DRV_MCPWM_CHANNEL_CURRENTLIMIT_SOURCE_IDX4
MCPWM_CURRENTLIMIT_INPUT_POLARITY = CONFIG_DRV_MCPWM_CHANNEL_CURRENTLIMIT_INPUT_POLARITY_IDX4
MCPWM_CURRENTLIMIT_OVERRIDE_PWMxH_VALUE =CONFIG_DRV_MCPWM_CHANNEL_CURRENTLIMIT_OVERRIDE_PWMxH_VALUE_IDX4
MCPWM_CURRENTLIMIT_OVERRIDE_PWMxL_VALUE =CONFIG_DRV_MCPWM_CHANNEL_CURRENTLIMIT_OVERRIDE_PWMxL_VALUE_IDX4
MCPWM_CURRENTLIMIT_MODE = CONFIG_DRV_MCPWM_CHANNEL_CURRENTLIMIT_MODE_IDX4
MCPWM_CURRENTLIMIT_INTERRUPT_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_CURRENTLIMIT_INTERRUPT_ENABLE_IDX4
MCPWM_OVERRIDE_PWMxH_VALUE =CONFIG_DRV_MCPWM_CHANNEL_OVERRIDE_PWMxH_VALUE_IDX4
MCPWM_OVERRIDE_PWMxL_VALUE =CONFIG_DRV_MCPWM_CHANNEL_OVERRIDE_PWMxL_VALUE_IDX4
MCPWM_OVERRIDE_PWMxH_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_OVERRIDE_PWMxH_ENABLE_IDX4
MCPWM_OVERRIDE_PWMxL_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_OVERRIDE_PWMxL_ENABLE_IDX4
MCPWM_SYNC_OVERRIDE_SELECT = CONFIG_DRV_MCPWM_CHANNEL_SYNC_OVERRIDE_SELECT_IDX4
MCPWM_PWMH_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_PWMH_ENABLE_IDX4
MCPWM_PERIOD_MATCH_INTERRUPT_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_PERIOD_MATCH_INTERRUPT_ENABLE_IDX4
MCPWM_PWML_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_PWML_ENABLE_IDX4
MCPWM_PERIOD_RESET_INTERRUPT_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_PERIOD_RESET_INTERRUPT_ENABLE_IDX4
MCPWM_SWAP_PWMH_PWML_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_SWAP_PWMH_PWML_IDX4
MCPWM_PDC_VALUE = CONFIG_DRV_MCPWM_PDC_VALUE_IDX4
MCPWM_SDC_VALUE = CONFIG_DRV_MCPWM_SDC_VALUE_IDX4
MCPWM_PHASE_VALUE = CONFIG_DRV_MCPWM_PHASE_VALUE_IDX4
MCPWM_DTR_VALUE = CONFIG_DRV_MCPWM_DTR_VALUE_IDX4
MCPWM_ALTDTR_VALUE = CONFIG_DRV_MCPWM_ALTDTR_VALUE_IDX4
MCPWM_DTCOMP_VALUE = CONFIG_DRV_MCPWM_DTCOMP_VALUE_IDX4
MCPWM_CHANNEL_INTERRUPT_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_INTERRUPT_ENABLE_IDX4
MCPWM_CHANNEL_INTERRUPT_PRIORITY = CONFIG_DRV_MCPWM_CHANNEL_INTERRUPT_PRIORITY_IDX4
MCPWM_CHANNEL_INTERRUPT_SUBPRIORITY = CONFIG_DRV_MCPWM_CHANNEL_INTERRUPT_SUBPRIORITY_IDX4
MCPWM_CHANNEL_INTERRUPT_VECTOR = CONFIG_DRV_MCPWM_CHANNEL_INTERRUPT_VECTOR_IDX4
MCPWM_CHANNEL_INTERRUPT_SOURCE = CONFIG_DRV_MCPWM_CHANNEL_INTERRUPT_SOURCE_IDX4/>
</#if>

<#if CONFIG_DRV_MCPWM_INST_IDX5 == true>
<@DRV_MCPWM_STATIC_FUNCTIONS MCPWM_CHANNEL_INSTANCE=CONFIG_DRV_MCPWM_CHANNEL_ID_IDX5 
MCPWM_TIME_BASE_SOURCE = CONFIG_DRV_MCPWM_CHANNEL_TIME_BASE_SOURCE_IDX5 
MCPWM_TIME_BASE_MODE = CONFIG_DRV_MCPWM_CHANNEL_TIME_BASE_MODE_IDX5
MCPWM_ALIGNMENT_MODE = CONFIG_DRV_MCPWM_CHANNEL_ALIGNMENT_MODE_IDX5
MCPWM_OUTPUT_MODE = CONFIG_DRV_MCPWM_CHANNEL_OUTPUT_MODE_IDX5
MCPWM_PWMxH_OUTPUT_POLARITY = CONFIG_DRV_MCPWM_CHANNEL_PWMxH_OUTPUT_POLARITY_IDX5
MCPWM_PWMxL_OUTPUT_POLARITY = CONFIG_DRV_MCPWM_CHANNEL_PWMxL_OUTPUT_POLARITY_IDX5
MCPWM_DEADTIME_MODE = CONFIG_DRV_MCPWM_CHANNEL_DEADTIME_MODE_IDX5
MCPWM_DEADTIME_POLARITY = CONFIG_DRV_MCPWM_CHANNEL_DEADTIME_COMPENSATION_POLARITY_IDX5
MCPWM_TRIGGER_POSTSCALER = CONFIG_DRV_MCPWM_CHANNEL_TRIGGER_POSTSCALER_IDX5
MCPWM_PRIMARY_TRIGGER_CYCLE_SELECT = CONFIG_DRV_MCPWM_CHANNEL_PRIMARY_TRIGGER_CYCLE_SELECT_IDX5
MCPWM_SECONDARY_TRIGGER_CYCLE_SELECT = CONFIG_DRV_MCPWM_CHANNEL_SECONDARY_TRIGGER_CYCLE_SELECT_IDX5
MCPWM_ADC_TRIGGER_SOURCE = CONFIG_DRV_MCPWM_CHANNEL_ADC_TRIGGER_SOURCE_IDX5
MCPWM_TRIGGER_INTERRUPT_SOURCE = CONFIG_DRV_MCPWM_CHANNEL_TRIGGER_INTERRUPT_SOURCE_IDX5
MCPWM_PRIMARY_TRIGGER_COMPARE_VALUE = CONFIG_DRV_MCPWM_CHANNEL_PRIMARY_TRIGGER_COMPARE_VALUE_IDX5
MCPWM_SECONDARY_TRIGGER_COMPARE_VALUE = CONFIG_DRV_MCPWM_CHANNEL_SECONDARY_TRIGGER_COMPARE_VALUE_IDX5
MCPWM_TRIGGER_INTERRUPT_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_TRIGGER_INTERRUPT_ENABLE_IDX5
MCPWM_LEB_TRIGGER_PWMxHRISINGEDGE_ENABLE =CONFIG_DRV_MCPWM_CHANNEL_LEB_TRIGGER_PWMxHRISINGEDGE_ENABLE_IDX5
MCPWM_LEB_TRIGGER_PWMxHFALLINGEDGE_ENABLE =CONFIG_DRV_MCPWM_CHANNEL_LEB_TRIGGER_PWMxHFALLINGEDGE_ENABLE_IDX5
MCPWM_LEB_TRIGGER_PWMxLRISINGEDGE_ENABLE =CONFIG_DRV_MCPWM_CHANNEL_LEB_TRIGGER_PWMxLRISINGEDGE_ENABLE_IDX5
MCPWM_LEB_TRIGGER_PWMxLFALLINGEDGE_ENABLE =CONFIG_DRV_MCPWM_CHANNEL_LEB_TRIGGER_PWMxLFALLINGEDGE_ENABLE_IDX5
MCPWM_FAULT_INPUT_LEB_CONTROL = CONFIG_DRV_MCPWM_CHANNEL_FAULT_INPUT_LEB_CONTROL_IDX5
MCPWM_CURRENTLIMIT_INPUT_LEB_CONTROL = CONFIG_DRV_MCPWM_CHANNEL_CURRENTLIMIT_INPUT_LEB_CONTROL_IDX5
MCPWM_LEB_PERIOD_VALUE = CONFIG_DRV_MCPWM_CHANNEL_LEB_PERIOD_VALUE_IDX5
MCPWM_CHOP_CLOCK_SOURCE = CONFIG_DRV_MCPWM_CHANNEL_CHOP_CLOCK_SOURCE_IDX5
MCPWM_PWMxH_CHOP_CONTROL = CONFIG_DRV_MCPWM_CHANNEL_PWMxH_CHOP_CONTROL_IDX5
MCPWM_PWMxL_CHOP_CONTROL = CONFIG_DRV_MCPWM_CHANNEL_PWMxL_CHOP_CONTROL_IDX5
MCPWM_FAULT_SOURCE = CONFIG_DRV_MCPWM_CHANNEL_FAULT_SOURCE_IDX5
MCPWM_FAULT_INPUT_POLARITY = CONFIG_DRV_MCPWM_CHANNEL_FAULT_INPUT_POLARITY_IDX5
MCPWM_FAULT_OVERRIDE_PWMxH_VALUE = CONFIG_DRV_MCPWM_CHANNEL_FAULT_OVERRIDE_PWMxH_VALUE_IDX5
MCPWM_FAULT_OVERRIDE_PWMxL_VALUE = CONFIG_DRV_MCPWM_CHANNEL_FAULT_OVERRIDE_PWMxL_VALUE_IDX5
MCPWM_FAULT_MODE = CONFIG_DRV_MCPWM_CHANNEL_FAULT_MODE_IDX5
MCPWM_FAULT_INTERRUPT_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_FAULT_INTERRUPT_ENABLE_IDX5
MCPWM_CURRENTLIMIT_SOURCE = CONFIG_DRV_MCPWM_CHANNEL_CURRENTLIMIT_SOURCE_IDX5
MCPWM_CURRENTLIMIT_INPUT_POLARITY = CONFIG_DRV_MCPWM_CHANNEL_CURRENTLIMIT_INPUT_POLARITY_IDX5
MCPWM_CURRENTLIMIT_OVERRIDE_PWMxH_VALUE =CONFIG_DRV_MCPWM_CHANNEL_CURRENTLIMIT_OVERRIDE_PWMxH_VALUE_IDX5
MCPWM_CURRENTLIMIT_OVERRIDE_PWMxL_VALUE =CONFIG_DRV_MCPWM_CHANNEL_CURRENTLIMIT_OVERRIDE_PWMxL_VALUE_IDX5
MCPWM_CURRENTLIMIT_MODE = CONFIG_DRV_MCPWM_CHANNEL_CURRENTLIMIT_MODE_IDX5
MCPWM_CURRENTLIMIT_INTERRUPT_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_CURRENTLIMIT_INTERRUPT_ENABLE_IDX5
MCPWM_OVERRIDE_PWMxH_VALUE =CONFIG_DRV_MCPWM_CHANNEL_OVERRIDE_PWMxH_VALUE_IDX5
MCPWM_OVERRIDE_PWMxL_VALUE =CONFIG_DRV_MCPWM_CHANNEL_OVERRIDE_PWMxL_VALUE_IDX5
MCPWM_OVERRIDE_PWMxH_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_OVERRIDE_PWMxH_ENABLE_IDX5
MCPWM_OVERRIDE_PWMxL_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_OVERRIDE_PWMxL_ENABLE_IDX5
MCPWM_SYNC_OVERRIDE_SELECT = CONFIG_DRV_MCPWM_CHANNEL_SYNC_OVERRIDE_SELECT_IDX5
MCPWM_PWMH_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_PWMH_ENABLE_IDX5
MCPWM_PERIOD_MATCH_INTERRUPT_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_PERIOD_MATCH_INTERRUPT_ENABLE_IDX5
MCPWM_PWML_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_PWML_ENABLE_IDX5
MCPWM_PERIOD_RESET_INTERRUPT_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_PERIOD_RESET_INTERRUPT_ENABLE_IDX5
MCPWM_SWAP_PWMH_PWML_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_SWAP_PWMH_PWML_IDX5
MCPWM_PDC_VALUE = CONFIG_DRV_MCPWM_PDC_VALUE_IDX5
MCPWM_SDC_VALUE = CONFIG_DRV_MCPWM_SDC_VALUE_IDX5
MCPWM_PHASE_VALUE = CONFIG_DRV_MCPWM_PHASE_VALUE_IDX5
MCPWM_DTR_VALUE = CONFIG_DRV_MCPWM_DTR_VALUE_IDX5
MCPWM_ALTDTR_VALUE = CONFIG_DRV_MCPWM_ALTDTR_VALUE_IDX5
MCPWM_DTCOMP_VALUE = CONFIG_DRV_MCPWM_DTCOMP_VALUE_IDX5
MCPWM_CHANNEL_INTERRUPT_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_INTERRUPT_ENABLE_IDX5
MCPWM_CHANNEL_INTERRUPT_PRIORITY = CONFIG_DRV_MCPWM_CHANNEL_INTERRUPT_PRIORITY_IDX5
MCPWM_CHANNEL_INTERRUPT_SUBPRIORITY = CONFIG_DRV_MCPWM_CHANNEL_INTERRUPT_SUBPRIORITY_IDX5
MCPWM_CHANNEL_INTERRUPT_VECTOR = CONFIG_DRV_MCPWM_CHANNEL_INTERRUPT_VECTOR_IDX5
MCPWM_CHANNEL_INTERRUPT_SOURCE = CONFIG_DRV_MCPWM_CHANNEL_INTERRUPT_SOURCE_IDX5/>
</#if>

<#if CONFIG_DRV_MCPWM_INST_IDX6 == true>
<@DRV_MCPWM_STATIC_FUNCTIONS MCPWM_CHANNEL_INSTANCE=CONFIG_DRV_MCPWM_CHANNEL_ID_IDX6 
MCPWM_TIME_BASE_SOURCE = CONFIG_DRV_MCPWM_CHANNEL_TIME_BASE_SOURCE_IDX6 
MCPWM_TIME_BASE_MODE = CONFIG_DRV_MCPWM_CHANNEL_TIME_BASE_MODE_IDX6
MCPWM_ALIGNMENT_MODE = CONFIG_DRV_MCPWM_CHANNEL_ALIGNMENT_MODE_IDX6
MCPWM_OUTPUT_MODE = CONFIG_DRV_MCPWM_CHANNEL_OUTPUT_MODE_IDX6
MCPWM_PWMxH_OUTPUT_POLARITY = CONFIG_DRV_MCPWM_CHANNEL_PWMxH_OUTPUT_POLARITY_IDX6
MCPWM_PWMxL_OUTPUT_POLARITY = CONFIG_DRV_MCPWM_CHANNEL_PWMxL_OUTPUT_POLARITY_IDX6
MCPWM_DEADTIME_MODE = CONFIG_DRV_MCPWM_CHANNEL_DEADTIME_MODE_IDX6
MCPWM_DEADTIME_POLARITY = CONFIG_DRV_MCPWM_CHANNEL_DEADTIME_COMPENSATION_POLARITY_IDX6
MCPWM_TRIGGER_POSTSCALER = CONFIG_DRV_MCPWM_CHANNEL_TRIGGER_POSTSCALER_IDX6
MCPWM_PRIMARY_TRIGGER_CYCLE_SELECT = CONFIG_DRV_MCPWM_CHANNEL_PRIMARY_TRIGGER_CYCLE_SELECT_IDX6
MCPWM_SECONDARY_TRIGGER_CYCLE_SELECT = CONFIG_DRV_MCPWM_CHANNEL_SECONDARY_TRIGGER_CYCLE_SELECT_IDX6
MCPWM_ADC_TRIGGER_SOURCE = CONFIG_DRV_MCPWM_CHANNEL_ADC_TRIGGER_SOURCE_IDX6
MCPWM_TRIGGER_INTERRUPT_SOURCE = CONFIG_DRV_MCPWM_CHANNEL_TRIGGER_INTERRUPT_SOURCE_IDX6
MCPWM_PRIMARY_TRIGGER_COMPARE_VALUE = CONFIG_DRV_MCPWM_CHANNEL_PRIMARY_TRIGGER_COMPARE_VALUE_IDX6
MCPWM_SECONDARY_TRIGGER_COMPARE_VALUE = CONFIG_DRV_MCPWM_CHANNEL_SECONDARY_TRIGGER_COMPARE_VALUE_IDX6
MCPWM_TRIGGER_INTERRUPT_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_TRIGGER_INTERRUPT_ENABLE_IDX6
MCPWM_LEB_TRIGGER_PWMxHRISINGEDGE_ENABLE =CONFIG_DRV_MCPWM_CHANNEL_LEB_TRIGGER_PWMxHRISINGEDGE_ENABLE_IDX6
MCPWM_LEB_TRIGGER_PWMxHFALLINGEDGE_ENABLE =CONFIG_DRV_MCPWM_CHANNEL_LEB_TRIGGER_PWMxHFALLINGEDGE_ENABLE_IDX6
MCPWM_LEB_TRIGGER_PWMxLRISINGEDGE_ENABLE =CONFIG_DRV_MCPWM_CHANNEL_LEB_TRIGGER_PWMxLRISINGEDGE_ENABLE_IDX6
MCPWM_LEB_TRIGGER_PWMxLFALLINGEDGE_ENABLE =CONFIG_DRV_MCPWM_CHANNEL_LEB_TRIGGER_PWMxLFALLINGEDGE_ENABLE_IDX6
MCPWM_FAULT_INPUT_LEB_CONTROL = CONFIG_DRV_MCPWM_CHANNEL_FAULT_INPUT_LEB_CONTROL_IDX6
MCPWM_CURRENTLIMIT_INPUT_LEB_CONTROL = CONFIG_DRV_MCPWM_CHANNEL_CURRENTLIMIT_INPUT_LEB_CONTROL_IDX6
MCPWM_LEB_PERIOD_VALUE = CONFIG_DRV_MCPWM_CHANNEL_LEB_PERIOD_VALUE_IDX6
MCPWM_CHOP_CLOCK_SOURCE = CONFIG_DRV_MCPWM_CHANNEL_CHOP_CLOCK_SOURCE_IDX6
MCPWM_PWMxH_CHOP_CONTROL = CONFIG_DRV_MCPWM_CHANNEL_PWMxH_CHOP_CONTROL_IDX6
MCPWM_PWMxL_CHOP_CONTROL = CONFIG_DRV_MCPWM_CHANNEL_PWMxL_CHOP_CONTROL_IDX6
MCPWM_FAULT_SOURCE = CONFIG_DRV_MCPWM_CHANNEL_FAULT_SOURCE_IDX6
MCPWM_FAULT_INPUT_POLARITY = CONFIG_DRV_MCPWM_CHANNEL_FAULT_INPUT_POLARITY_IDX6
MCPWM_FAULT_OVERRIDE_PWMxH_VALUE = CONFIG_DRV_MCPWM_CHANNEL_FAULT_OVERRIDE_PWMxH_VALUE_IDX6
MCPWM_FAULT_OVERRIDE_PWMxL_VALUE = CONFIG_DRV_MCPWM_CHANNEL_FAULT_OVERRIDE_PWMxL_VALUE_IDX6
MCPWM_FAULT_MODE = CONFIG_DRV_MCPWM_CHANNEL_FAULT_MODE_IDX6
MCPWM_FAULT_INTERRUPT_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_FAULT_INTERRUPT_ENABLE_IDX6
MCPWM_CURRENTLIMIT_SOURCE = CONFIG_DRV_MCPWM_CHANNEL_CURRENTLIMIT_SOURCE_IDX6
MCPWM_CURRENTLIMIT_INPUT_POLARITY = CONFIG_DRV_MCPWM_CHANNEL_CURRENTLIMIT_INPUT_POLARITY_IDX6
MCPWM_CURRENTLIMIT_OVERRIDE_PWMxH_VALUE =CONFIG_DRV_MCPWM_CHANNEL_CURRENTLIMIT_OVERRIDE_PWMxH_VALUE_IDX6
MCPWM_CURRENTLIMIT_OVERRIDE_PWMxL_VALUE =CONFIG_DRV_MCPWM_CHANNEL_CURRENTLIMIT_OVERRIDE_PWMxL_VALUE_IDX6
MCPWM_CURRENTLIMIT_MODE = CONFIG_DRV_MCPWM_CHANNEL_CURRENTLIMIT_MODE_IDX6
MCPWM_CURRENTLIMIT_INTERRUPT_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_CURRENTLIMIT_INTERRUPT_ENABLE_IDX6
MCPWM_OVERRIDE_PWMxH_VALUE =CONFIG_DRV_MCPWM_CHANNEL_OVERRIDE_PWMxH_VALUE_IDX6
MCPWM_OVERRIDE_PWMxL_VALUE =CONFIG_DRV_MCPWM_CHANNEL_OVERRIDE_PWMxL_VALUE_IDX6
MCPWM_OVERRIDE_PWMxH_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_OVERRIDE_PWMxH_ENABLE_IDX6
MCPWM_OVERRIDE_PWMxL_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_OVERRIDE_PWMxL_ENABLE_IDX6
MCPWM_SYNC_OVERRIDE_SELECT = CONFIG_DRV_MCPWM_CHANNEL_SYNC_OVERRIDE_SELECT_IDX6
MCPWM_PWMH_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_PWMH_ENABLE_IDX6
MCPWM_PERIOD_MATCH_INTERRUPT_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_PERIOD_MATCH_INTERRUPT_ENABLE_IDX6
MCPWM_PWML_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_PWML_ENABLE_IDX6
MCPWM_PERIOD_RESET_INTERRUPT_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_PERIOD_RESET_INTERRUPT_ENABLE_IDX6
MCPWM_SWAP_PWMH_PWML_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_SWAP_PWMH_PWML_IDX6
MCPWM_PDC_VALUE = CONFIG_DRV_MCPWM_PDC_VALUE_IDX6
MCPWM_SDC_VALUE = CONFIG_DRV_MCPWM_SDC_VALUE_IDX6
MCPWM_PHASE_VALUE = CONFIG_DRV_MCPWM_PHASE_VALUE_IDX6
MCPWM_DTR_VALUE = CONFIG_DRV_MCPWM_DTR_VALUE_IDX6
MCPWM_ALTDTR_VALUE = CONFIG_DRV_MCPWM_ALTDTR_VALUE_IDX6
MCPWM_DTCOMP_VALUE = CONFIG_DRV_MCPWM_DTCOMP_VALUE_IDX6
MCPWM_CHANNEL_INTERRUPT_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_INTERRUPT_ENABLE_IDX6
MCPWM_CHANNEL_INTERRUPT_PRIORITY = CONFIG_DRV_MCPWM_CHANNEL_INTERRUPT_PRIORITY_IDX6
MCPWM_CHANNEL_INTERRUPT_SUBPRIORITY = CONFIG_DRV_MCPWM_CHANNEL_INTERRUPT_SUBPRIORITY_IDX6
MCPWM_CHANNEL_INTERRUPT_VECTOR = CONFIG_DRV_MCPWM_CHANNEL_INTERRUPT_VECTOR_IDX6
MCPWM_CHANNEL_INTERRUPT_SOURCE = CONFIG_DRV_MCPWM_CHANNEL_INTERRUPT_SOURCE_IDX6/>
</#if>


<#if CONFIG_DRV_MCPWM_INST_IDX7 == true>
<@DRV_MCPWM_STATIC_FUNCTIONS MCPWM_CHANNEL_INSTANCE=CONFIG_DRV_MCPWM_CHANNEL_ID_IDX7 
MCPWM_TIME_BASE_SOURCE = CONFIG_DRV_MCPWM_CHANNEL_TIME_BASE_SOURCE_IDX7 
MCPWM_TIME_BASE_MODE = CONFIG_DRV_MCPWM_CHANNEL_TIME_BASE_MODE_IDX7
MCPWM_ALIGNMENT_MODE = CONFIG_DRV_MCPWM_CHANNEL_ALIGNMENT_MODE_IDX7
MCPWM_OUTPUT_MODE = CONFIG_DRV_MCPWM_CHANNEL_OUTPUT_MODE_IDX7
MCPWM_PWMxH_OUTPUT_POLARITY = CONFIG_DRV_MCPWM_CHANNEL_PWMxH_OUTPUT_POLARITY_IDX7
MCPWM_PWMxL_OUTPUT_POLARITY = CONFIG_DRV_MCPWM_CHANNEL_PWMxL_OUTPUT_POLARITY_IDX7
MCPWM_DEADTIME_MODE = CONFIG_DRV_MCPWM_CHANNEL_DEADTIME_MODE_IDX7
MCPWM_DEADTIME_POLARITY = CONFIG_DRV_MCPWM_CHANNEL_DEADTIME_COMPENSATION_POLARITY_IDX7
MCPWM_TRIGGER_POSTSCALER = CONFIG_DRV_MCPWM_CHANNEL_TRIGGER_POSTSCALER_IDX7
MCPWM_PRIMARY_TRIGGER_CYCLE_SELECT = CONFIG_DRV_MCPWM_CHANNEL_PRIMARY_TRIGGER_CYCLE_SELECT_IDX7
MCPWM_SECONDARY_TRIGGER_CYCLE_SELECT = CONFIG_DRV_MCPWM_CHANNEL_SECONDARY_TRIGGER_CYCLE_SELECT_IDX7
MCPWM_ADC_TRIGGER_SOURCE = CONFIG_DRV_MCPWM_CHANNEL_ADC_TRIGGER_SOURCE_IDX7
MCPWM_TRIGGER_INTERRUPT_SOURCE = CONFIG_DRV_MCPWM_CHANNEL_TRIGGER_INTERRUPT_SOURCE_IDX7
MCPWM_PRIMARY_TRIGGER_COMPARE_VALUE = CONFIG_DRV_MCPWM_CHANNEL_PRIMARY_TRIGGER_COMPARE_VALUE_IDX7
MCPWM_SECONDARY_TRIGGER_COMPARE_VALUE = CONFIG_DRV_MCPWM_CHANNEL_SECONDARY_TRIGGER_COMPARE_VALUE_IDX7
MCPWM_TRIGGER_INTERRUPT_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_TRIGGER_INTERRUPT_ENABLE_IDX7
MCPWM_LEB_TRIGGER_PWMxHRISINGEDGE_ENABLE =CONFIG_DRV_MCPWM_CHANNEL_LEB_TRIGGER_PWMxHRISINGEDGE_ENABLE_IDX7
MCPWM_LEB_TRIGGER_PWMxHFALLINGEDGE_ENABLE =CONFIG_DRV_MCPWM_CHANNEL_LEB_TRIGGER_PWMxHFALLINGEDGE_ENABLE_IDX7
MCPWM_LEB_TRIGGER_PWMxLRISINGEDGE_ENABLE =CONFIG_DRV_MCPWM_CHANNEL_LEB_TRIGGER_PWMxLRISINGEDGE_ENABLE_IDX7
MCPWM_LEB_TRIGGER_PWMxLFALLINGEDGE_ENABLE =CONFIG_DRV_MCPWM_CHANNEL_LEB_TRIGGER_PWMxLFALLINGEDGE_ENABLE_IDX7
MCPWM_FAULT_INPUT_LEB_CONTROL = CONFIG_DRV_MCPWM_CHANNEL_FAULT_INPUT_LEB_CONTROL_IDX7
MCPWM_CURRENTLIMIT_INPUT_LEB_CONTROL = CONFIG_DRV_MCPWM_CHANNEL_CURRENTLIMIT_INPUT_LEB_CONTROL_IDX7
MCPWM_LEB_PERIOD_VALUE = CONFIG_DRV_MCPWM_CHANNEL_LEB_PERIOD_VALUE_IDX7
MCPWM_CHOP_CLOCK_SOURCE = CONFIG_DRV_MCPWM_CHANNEL_CHOP_CLOCK_SOURCE_IDX7
MCPWM_PWMxH_CHOP_CONTROL = CONFIG_DRV_MCPWM_CHANNEL_PWMxH_CHOP_CONTROL_IDX7
MCPWM_PWMxL_CHOP_CONTROL = CONFIG_DRV_MCPWM_CHANNEL_PWMxL_CHOP_CONTROL_IDX7
MCPWM_FAULT_SOURCE = CONFIG_DRV_MCPWM_CHANNEL_FAULT_SOURCE_IDX7
MCPWM_FAULT_INPUT_POLARITY = CONFIG_DRV_MCPWM_CHANNEL_FAULT_INPUT_POLARITY_IDX7
MCPWM_FAULT_OVERRIDE_PWMxH_VALUE = CONFIG_DRV_MCPWM_CHANNEL_FAULT_OVERRIDE_PWMxH_VALUE_IDX7
MCPWM_FAULT_OVERRIDE_PWMxL_VALUE = CONFIG_DRV_MCPWM_CHANNEL_FAULT_OVERRIDE_PWMxL_VALUE_IDX7
MCPWM_FAULT_MODE = CONFIG_DRV_MCPWM_CHANNEL_FAULT_MODE_IDX7
MCPWM_FAULT_INTERRUPT_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_FAULT_INTERRUPT_ENABLE_IDX7
MCPWM_CURRENTLIMIT_SOURCE = CONFIG_DRV_MCPWM_CHANNEL_CURRENTLIMIT_SOURCE_IDX7
MCPWM_CURRENTLIMIT_INPUT_POLARITY = CONFIG_DRV_MCPWM_CHANNEL_CURRENTLIMIT_INPUT_POLARITY_IDX7
MCPWM_CURRENTLIMIT_OVERRIDE_PWMxH_VALUE =CONFIG_DRV_MCPWM_CHANNEL_CURRENTLIMIT_OVERRIDE_PWMxH_VALUE_IDX7
MCPWM_CURRENTLIMIT_OVERRIDE_PWMxL_VALUE =CONFIG_DRV_MCPWM_CHANNEL_CURRENTLIMIT_OVERRIDE_PWMxL_VALUE_IDX7
MCPWM_CURRENTLIMIT_MODE = CONFIG_DRV_MCPWM_CHANNEL_CURRENTLIMIT_MODE_IDX7
MCPWM_CURRENTLIMIT_INTERRUPT_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_CURRENTLIMIT_INTERRUPT_ENABLE_IDX7
MCPWM_OVERRIDE_PWMxH_VALUE =CONFIG_DRV_MCPWM_CHANNEL_OVERRIDE_PWMxH_VALUE_IDX7
MCPWM_OVERRIDE_PWMxL_VALUE =CONFIG_DRV_MCPWM_CHANNEL_OVERRIDE_PWMxL_VALUE_IDX7
MCPWM_OVERRIDE_PWMxH_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_OVERRIDE_PWMxH_ENABLE_IDX7
MCPWM_OVERRIDE_PWMxL_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_OVERRIDE_PWMxL_ENABLE_IDX7
MCPWM_SYNC_OVERRIDE_SELECT = CONFIG_DRV_MCPWM_CHANNEL_SYNC_OVERRIDE_SELECT_IDX7
MCPWM_PWMH_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_PWMH_ENABLE_IDX7
MCPWM_PERIOD_MATCH_INTERRUPT_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_PERIOD_MATCH_INTERRUPT_ENABLE_IDX7
MCPWM_PWML_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_PWML_ENABLE_IDX7
MCPWM_PERIOD_RESET_INTERRUPT_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_PERIOD_RESET_INTERRUPT_ENABLE_IDX7
MCPWM_SWAP_PWMH_PWML_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_SWAP_PWMH_PWML_IDX7
MCPWM_PDC_VALUE = CONFIG_DRV_MCPWM_PDC_VALUE_IDX7
MCPWM_SDC_VALUE = CONFIG_DRV_MCPWM_SDC_VALUE_IDX7
MCPWM_PHASE_VALUE = CONFIG_DRV_MCPWM_PHASE_VALUE_IDX7
MCPWM_DTR_VALUE = CONFIG_DRV_MCPWM_DTR_VALUE_IDX7
MCPWM_ALTDTR_VALUE = CONFIG_DRV_MCPWM_ALTDTR_VALUE_IDX7
MCPWM_DTCOMP_VALUE = CONFIG_DRV_MCPWM_DTCOMP_VALUE_IDX7
MCPWM_CHANNEL_INTERRUPT_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_INTERRUPT_ENABLE_IDX7
MCPWM_CHANNEL_INTERRUPT_PRIORITY = CONFIG_DRV_MCPWM_CHANNEL_INTERRUPT_PRIORITY_IDX7
MCPWM_CHANNEL_INTERRUPT_SUBPRIORITY = CONFIG_DRV_MCPWM_CHANNEL_INTERRUPT_SUBPRIORITY_IDX7
MCPWM_CHANNEL_INTERRUPT_VECTOR = CONFIG_DRV_MCPWM_CHANNEL_INTERRUPT_VECTOR_IDX7
MCPWM_CHANNEL_INTERRUPT_SOURCE = CONFIG_DRV_MCPWM_CHANNEL_INTERRUPT_SOURCE_IDX7/>
</#if>


<#if CONFIG_DRV_MCPWM_INST_IDX8 == true>
<@DRV_MCPWM_STATIC_FUNCTIONS MCPWM_CHANNEL_INSTANCE=CONFIG_DRV_MCPWM_CHANNEL_ID_IDX8 
MCPWM_TIME_BASE_SOURCE = CONFIG_DRV_MCPWM_CHANNEL_TIME_BASE_SOURCE_IDX8 
MCPWM_TIME_BASE_MODE = CONFIG_DRV_MCPWM_CHANNEL_TIME_BASE_MODE_IDX8
MCPWM_ALIGNMENT_MODE = CONFIG_DRV_MCPWM_CHANNEL_ALIGNMENT_MODE_IDX8
MCPWM_OUTPUT_MODE = CONFIG_DRV_MCPWM_CHANNEL_OUTPUT_MODE_IDX8
MCPWM_PWMxH_OUTPUT_POLARITY = CONFIG_DRV_MCPWM_CHANNEL_PWMxH_OUTPUT_POLARITY_IDX8
MCPWM_PWMxL_OUTPUT_POLARITY = CONFIG_DRV_MCPWM_CHANNEL_PWMxL_OUTPUT_POLARITY_IDX8
MCPWM_DEADTIME_MODE = CONFIG_DRV_MCPWM_CHANNEL_DEADTIME_MODE_IDX8
MCPWM_DEADTIME_POLARITY = CONFIG_DRV_MCPWM_CHANNEL_DEADTIME_COMPENSATION_POLARITY_IDX8
MCPWM_TRIGGER_POSTSCALER = CONFIG_DRV_MCPWM_CHANNEL_TRIGGER_POSTSCALER_IDX8
MCPWM_PRIMARY_TRIGGER_CYCLE_SELECT = CONFIG_DRV_MCPWM_CHANNEL_PRIMARY_TRIGGER_CYCLE_SELECT_IDX8
MCPWM_SECONDARY_TRIGGER_CYCLE_SELECT = CONFIG_DRV_MCPWM_CHANNEL_SECONDARY_TRIGGER_CYCLE_SELECT_IDX8
MCPWM_ADC_TRIGGER_SOURCE = CONFIG_DRV_MCPWM_CHANNEL_ADC_TRIGGER_SOURCE_IDX8
MCPWM_TRIGGER_INTERRUPT_SOURCE = CONFIG_DRV_MCPWM_CHANNEL_TRIGGER_INTERRUPT_SOURCE_IDX8
MCPWM_PRIMARY_TRIGGER_COMPARE_VALUE = CONFIG_DRV_MCPWM_CHANNEL_PRIMARY_TRIGGER_COMPARE_VALUE_IDX8
MCPWM_SECONDARY_TRIGGER_COMPARE_VALUE = CONFIG_DRV_MCPWM_CHANNEL_SECONDARY_TRIGGER_COMPARE_VALUE_IDX8
MCPWM_TRIGGER_INTERRUPT_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_TRIGGER_INTERRUPT_ENABLE_IDX8
MCPWM_LEB_TRIGGER_PWMxHRISINGEDGE_ENABLE =CONFIG_DRV_MCPWM_CHANNEL_LEB_TRIGGER_PWMxHRISINGEDGE_ENABLE_IDX8
MCPWM_LEB_TRIGGER_PWMxHFALLINGEDGE_ENABLE =CONFIG_DRV_MCPWM_CHANNEL_LEB_TRIGGER_PWMxHFALLINGEDGE_ENABLE_IDX8
MCPWM_LEB_TRIGGER_PWMxLRISINGEDGE_ENABLE =CONFIG_DRV_MCPWM_CHANNEL_LEB_TRIGGER_PWMxLRISINGEDGE_ENABLE_IDX8
MCPWM_LEB_TRIGGER_PWMxLFALLINGEDGE_ENABLE =CONFIG_DRV_MCPWM_CHANNEL_LEB_TRIGGER_PWMxLFALLINGEDGE_ENABLE_IDX8
MCPWM_FAULT_INPUT_LEB_CONTROL = CONFIG_DRV_MCPWM_CHANNEL_FAULT_INPUT_LEB_CONTROL_IDX8
MCPWM_CURRENTLIMIT_INPUT_LEB_CONTROL = CONFIG_DRV_MCPWM_CHANNEL_CURRENTLIMIT_INPUT_LEB_CONTROL_IDX8
MCPWM_LEB_PERIOD_VALUE = CONFIG_DRV_MCPWM_CHANNEL_LEB_PERIOD_VALUE_IDX8
MCPWM_CHOP_CLOCK_SOURCE = CONFIG_DRV_MCPWM_CHANNEL_CHOP_CLOCK_SOURCE_IDX8
MCPWM_PWMxH_CHOP_CONTROL = CONFIG_DRV_MCPWM_CHANNEL_PWMxH_CHOP_CONTROL_IDX8
MCPWM_PWMxL_CHOP_CONTROL = CONFIG_DRV_MCPWM_CHANNEL_PWMxL_CHOP_CONTROL_IDX8
MCPWM_FAULT_SOURCE = CONFIG_DRV_MCPWM_CHANNEL_FAULT_SOURCE_IDX8
MCPWM_FAULT_INPUT_POLARITY = CONFIG_DRV_MCPWM_CHANNEL_FAULT_INPUT_POLARITY_IDX8
MCPWM_FAULT_OVERRIDE_PWMxH_VALUE = CONFIG_DRV_MCPWM_CHANNEL_FAULT_OVERRIDE_PWMxH_VALUE_IDX8
MCPWM_FAULT_OVERRIDE_PWMxL_VALUE = CONFIG_DRV_MCPWM_CHANNEL_FAULT_OVERRIDE_PWMxL_VALUE_IDX8
MCPWM_FAULT_MODE = CONFIG_DRV_MCPWM_CHANNEL_FAULT_MODE_IDX8
MCPWM_FAULT_INTERRUPT_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_FAULT_INTERRUPT_ENABLE_IDX8
MCPWM_CURRENTLIMIT_SOURCE = CONFIG_DRV_MCPWM_CHANNEL_CURRENTLIMIT_SOURCE_IDX8
MCPWM_CURRENTLIMIT_INPUT_POLARITY = CONFIG_DRV_MCPWM_CHANNEL_CURRENTLIMIT_INPUT_POLARITY_IDX8
MCPWM_CURRENTLIMIT_OVERRIDE_PWMxH_VALUE =CONFIG_DRV_MCPWM_CHANNEL_CURRENTLIMIT_OVERRIDE_PWMxH_VALUE_IDX8
MCPWM_CURRENTLIMIT_OVERRIDE_PWMxL_VALUE =CONFIG_DRV_MCPWM_CHANNEL_CURRENTLIMIT_OVERRIDE_PWMxL_VALUE_IDX8
MCPWM_CURRENTLIMIT_MODE = CONFIG_DRV_MCPWM_CHANNEL_CURRENTLIMIT_MODE_IDX8
MCPWM_CURRENTLIMIT_INTERRUPT_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_CURRENTLIMIT_INTERRUPT_ENABLE_IDX8
MCPWM_OVERRIDE_PWMxH_VALUE =CONFIG_DRV_MCPWM_CHANNEL_OVERRIDE_PWMxH_VALUE_IDX8
MCPWM_OVERRIDE_PWMxL_VALUE =CONFIG_DRV_MCPWM_CHANNEL_OVERRIDE_PWMxL_VALUE_IDX8
MCPWM_OVERRIDE_PWMxH_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_OVERRIDE_PWMxH_ENABLE_IDX8
MCPWM_OVERRIDE_PWMxL_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_OVERRIDE_PWMxL_ENABLE_IDX8
MCPWM_SYNC_OVERRIDE_SELECT = CONFIG_DRV_MCPWM_CHANNEL_SYNC_OVERRIDE_SELECT_IDX8
MCPWM_PWMH_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_PWMH_ENABLE_IDX8
MCPWM_PERIOD_MATCH_INTERRUPT_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_PERIOD_MATCH_INTERRUPT_ENABLE_IDX8
MCPWM_PWML_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_PWML_ENABLE_IDX8
MCPWM_PERIOD_RESET_INTERRUPT_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_PERIOD_RESET_INTERRUPT_ENABLE_IDX8
MCPWM_SWAP_PWMH_PWML_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_SWAP_PWMH_PWML_IDX8
MCPWM_PDC_VALUE = CONFIG_DRV_MCPWM_PDC_VALUE_IDX8
MCPWM_SDC_VALUE = CONFIG_DRV_MCPWM_SDC_VALUE_IDX8
MCPWM_PHASE_VALUE = CONFIG_DRV_MCPWM_PHASE_VALUE_IDX8
MCPWM_DTR_VALUE = CONFIG_DRV_MCPWM_DTR_VALUE_IDX8
MCPWM_ALTDTR_VALUE = CONFIG_DRV_MCPWM_ALTDTR_VALUE_IDX8
MCPWM_DTCOMP_VALUE = CONFIG_DRV_MCPWM_DTCOMP_VALUE_IDX8
MCPWM_CHANNEL_INTERRUPT_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_INTERRUPT_ENABLE_IDX8
MCPWM_CHANNEL_INTERRUPT_PRIORITY = CONFIG_DRV_MCPWM_CHANNEL_INTERRUPT_PRIORITY_IDX8
MCPWM_CHANNEL_INTERRUPT_SUBPRIORITY = CONFIG_DRV_MCPWM_CHANNEL_INTERRUPT_SUBPRIORITY_IDX8
MCPWM_CHANNEL_INTERRUPT_VECTOR = CONFIG_DRV_MCPWM_CHANNEL_INTERRUPT_VECTOR_IDX8
MCPWM_CHANNEL_INTERRUPT_SOURCE = CONFIG_DRV_MCPWM_CHANNEL_INTERRUPT_SOURCE_IDX8/>
</#if>


<#if CONFIG_DRV_MCPWM_INST_IDX9 == true>
<@DRV_MCPWM_STATIC_FUNCTIONS MCPWM_CHANNEL_INSTANCE=CONFIG_DRV_MCPWM_CHANNEL_ID_IDX9 
MCPWM_TIME_BASE_SOURCE = CONFIG_DRV_MCPWM_CHANNEL_TIME_BASE_SOURCE_IDX9 
MCPWM_TIME_BASE_MODE = CONFIG_DRV_MCPWM_CHANNEL_TIME_BASE_MODE_IDX9
MCPWM_ALIGNMENT_MODE = CONFIG_DRV_MCPWM_CHANNEL_ALIGNMENT_MODE_IDX9
MCPWM_OUTPUT_MODE = CONFIG_DRV_MCPWM_CHANNEL_OUTPUT_MODE_IDX9
MCPWM_PWMxH_OUTPUT_POLARITY = CONFIG_DRV_MCPWM_CHANNEL_PWMxH_OUTPUT_POLARITY_IDX9
MCPWM_PWMxL_OUTPUT_POLARITY = CONFIG_DRV_MCPWM_CHANNEL_PWMxL_OUTPUT_POLARITY_IDX9
MCPWM_DEADTIME_MODE = CONFIG_DRV_MCPWM_CHANNEL_DEADTIME_MODE_IDX9
MCPWM_DEADTIME_POLARITY = CONFIG_DRV_MCPWM_CHANNEL_DEADTIME_COMPENSATION_POLARITY_IDX9
MCPWM_TRIGGER_POSTSCALER = CONFIG_DRV_MCPWM_CHANNEL_TRIGGER_POSTSCALER_IDX9
MCPWM_PRIMARY_TRIGGER_CYCLE_SELECT = CONFIG_DRV_MCPWM_CHANNEL_PRIMARY_TRIGGER_CYCLE_SELECT_IDX9
MCPWM_SECONDARY_TRIGGER_CYCLE_SELECT = CONFIG_DRV_MCPWM_CHANNEL_SECONDARY_TRIGGER_CYCLE_SELECT_IDX9
MCPWM_ADC_TRIGGER_SOURCE = CONFIG_DRV_MCPWM_CHANNEL_ADC_TRIGGER_SOURCE_IDX9
MCPWM_TRIGGER_INTERRUPT_SOURCE = CONFIG_DRV_MCPWM_CHANNEL_TRIGGER_INTERRUPT_SOURCE_IDX9
MCPWM_PRIMARY_TRIGGER_COMPARE_VALUE = CONFIG_DRV_MCPWM_CHANNEL_PRIMARY_TRIGGER_COMPARE_VALUE_IDX9
MCPWM_SECONDARY_TRIGGER_COMPARE_VALUE = CONFIG_DRV_MCPWM_CHANNEL_SECONDARY_TRIGGER_COMPARE_VALUE_IDX9
MCPWM_TRIGGER_INTERRUPT_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_TRIGGER_INTERRUPT_ENABLE_IDX9
MCPWM_LEB_TRIGGER_PWMxHRISINGEDGE_ENABLE =CONFIG_DRV_MCPWM_CHANNEL_LEB_TRIGGER_PWMxHRISINGEDGE_ENABLE_IDX9
MCPWM_LEB_TRIGGER_PWMxHFALLINGEDGE_ENABLE =CONFIG_DRV_MCPWM_CHANNEL_LEB_TRIGGER_PWMxHFALLINGEDGE_ENABLE_IDX9
MCPWM_LEB_TRIGGER_PWMxLRISINGEDGE_ENABLE =CONFIG_DRV_MCPWM_CHANNEL_LEB_TRIGGER_PWMxLRISINGEDGE_ENABLE_IDX9
MCPWM_LEB_TRIGGER_PWMxLFALLINGEDGE_ENABLE =CONFIG_DRV_MCPWM_CHANNEL_LEB_TRIGGER_PWMxLFALLINGEDGE_ENABLE_IDX9
MCPWM_FAULT_INPUT_LEB_CONTROL = CONFIG_DRV_MCPWM_CHANNEL_FAULT_INPUT_LEB_CONTROL_IDX9
MCPWM_CURRENTLIMIT_INPUT_LEB_CONTROL = CONFIG_DRV_MCPWM_CHANNEL_CURRENTLIMIT_INPUT_LEB_CONTROL_IDX9
MCPWM_LEB_PERIOD_VALUE = CONFIG_DRV_MCPWM_CHANNEL_LEB_PERIOD_VALUE_IDX9
MCPWM_CHOP_CLOCK_SOURCE = CONFIG_DRV_MCPWM_CHANNEL_CHOP_CLOCK_SOURCE_IDX9
MCPWM_PWMxH_CHOP_CONTROL = CONFIG_DRV_MCPWM_CHANNEL_PWMxH_CHOP_CONTROL_IDX9
MCPWM_PWMxL_CHOP_CONTROL = CONFIG_DRV_MCPWM_CHANNEL_PWMxL_CHOP_CONTROL_IDX9
MCPWM_FAULT_SOURCE = CONFIG_DRV_MCPWM_CHANNEL_FAULT_SOURCE_IDX9
MCPWM_FAULT_INPUT_POLARITY = CONFIG_DRV_MCPWM_CHANNEL_FAULT_INPUT_POLARITY_IDX9
MCPWM_FAULT_OVERRIDE_PWMxH_VALUE = CONFIG_DRV_MCPWM_CHANNEL_FAULT_OVERRIDE_PWMxH_VALUE_IDX9
MCPWM_FAULT_OVERRIDE_PWMxL_VALUE = CONFIG_DRV_MCPWM_CHANNEL_FAULT_OVERRIDE_PWMxL_VALUE_IDX9
MCPWM_FAULT_MODE = CONFIG_DRV_MCPWM_CHANNEL_FAULT_MODE_IDX9
MCPWM_FAULT_INTERRUPT_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_FAULT_INTERRUPT_ENABLE_IDX9
MCPWM_CURRENTLIMIT_SOURCE = CONFIG_DRV_MCPWM_CHANNEL_CURRENTLIMIT_SOURCE_IDX9
MCPWM_CURRENTLIMIT_INPUT_POLARITY = CONFIG_DRV_MCPWM_CHANNEL_CURRENTLIMIT_INPUT_POLARITY_IDX9
MCPWM_CURRENTLIMIT_OVERRIDE_PWMxH_VALUE =CONFIG_DRV_MCPWM_CHANNEL_CURRENTLIMIT_OVERRIDE_PWMxH_VALUE_IDX9
MCPWM_CURRENTLIMIT_OVERRIDE_PWMxL_VALUE =CONFIG_DRV_MCPWM_CHANNEL_CURRENTLIMIT_OVERRIDE_PWMxL_VALUE_IDX9
MCPWM_CURRENTLIMIT_MODE = CONFIG_DRV_MCPWM_CHANNEL_CURRENTLIMIT_MODE_IDX9
MCPWM_CURRENTLIMIT_INTERRUPT_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_CURRENTLIMIT_INTERRUPT_ENABLE_IDX9
MCPWM_OVERRIDE_PWMxH_VALUE =CONFIG_DRV_MCPWM_CHANNEL_OVERRIDE_PWMxH_VALUE_IDX9
MCPWM_OVERRIDE_PWMxL_VALUE =CONFIG_DRV_MCPWM_CHANNEL_OVERRIDE_PWMxL_VALUE_IDX9
MCPWM_OVERRIDE_PWMxH_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_OVERRIDE_PWMxH_ENABLE_IDX9
MCPWM_OVERRIDE_PWMxL_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_OVERRIDE_PWMxL_ENABLE_IDX9
MCPWM_SYNC_OVERRIDE_SELECT = CONFIG_DRV_MCPWM_CHANNEL_SYNC_OVERRIDE_SELECT_IDX9
MCPWM_PWMH_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_PWMH_ENABLE_IDX9
MCPWM_PERIOD_MATCH_INTERRUPT_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_PERIOD_MATCH_INTERRUPT_ENABLE_IDX9
MCPWM_PWML_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_PWML_ENABLE_IDX9
MCPWM_PERIOD_RESET_INTERRUPT_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_PERIOD_RESET_INTERRUPT_ENABLE_IDX9
MCPWM_SWAP_PWMH_PWML_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_SWAP_PWMH_PWML_IDX9
MCPWM_PDC_VALUE = CONFIG_DRV_MCPWM_PDC_VALUE_IDX9
MCPWM_SDC_VALUE = CONFIG_DRV_MCPWM_SDC_VALUE_IDX9
MCPWM_PHASE_VALUE = CONFIG_DRV_MCPWM_PHASE_VALUE_IDX9
MCPWM_DTR_VALUE = CONFIG_DRV_MCPWM_DTR_VALUE_IDX9
MCPWM_ALTDTR_VALUE = CONFIG_DRV_MCPWM_ALTDTR_VALUE_IDX9
MCPWM_DTCOMP_VALUE = CONFIG_DRV_MCPWM_DTCOMP_VALUE_IDX9
MCPWM_CHANNEL_INTERRUPT_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_INTERRUPT_ENABLE_IDX9
MCPWM_CHANNEL_INTERRUPT_PRIORITY = CONFIG_DRV_MCPWM_CHANNEL_INTERRUPT_PRIORITY_IDX9
MCPWM_CHANNEL_INTERRUPT_SUBPRIORITY = CONFIG_DRV_MCPWM_CHANNEL_INTERRUPT_SUBPRIORITY_IDX9
MCPWM_CHANNEL_INTERRUPT_VECTOR = CONFIG_DRV_MCPWM_CHANNEL_INTERRUPT_VECTOR_IDX9
MCPWM_CHANNEL_INTERRUPT_SOURCE = CONFIG_DRV_MCPWM_CHANNEL_INTERRUPT_SOURCE_IDX9/>
</#if>


<#if CONFIG_DRV_MCPWM_INST_IDX10 == true>
<@DRV_MCPWM_STATIC_FUNCTIONS MCPWM_CHANNEL_INSTANCE=CONFIG_DRV_MCPWM_CHANNEL_ID_IDX10 
MCPWM_TIME_BASE_SOURCE = CONFIG_DRV_MCPWM_CHANNEL_TIME_BASE_SOURCE_IDX10 
MCPWM_TIME_BASE_MODE = CONFIG_DRV_MCPWM_CHANNEL_TIME_BASE_MODE_IDX10
MCPWM_ALIGNMENT_MODE = CONFIG_DRV_MCPWM_CHANNEL_ALIGNMENT_MODE_IDX10
MCPWM_OUTPUT_MODE = CONFIG_DRV_MCPWM_CHANNEL_OUTPUT_MODE_IDX10
MCPWM_PWMxH_OUTPUT_POLARITY = CONFIG_DRV_MCPWM_CHANNEL_PWMxH_OUTPUT_POLARITY_IDX10
MCPWM_PWMxL_OUTPUT_POLARITY = CONFIG_DRV_MCPWM_CHANNEL_PWMxL_OUTPUT_POLARITY_IDX10
MCPWM_DEADTIME_MODE = CONFIG_DRV_MCPWM_CHANNEL_DEADTIME_MODE_IDX10
MCPWM_DEADTIME_POLARITY = CONFIG_DRV_MCPWM_CHANNEL_DEADTIME_COMPENSATION_POLARITY_IDX10
MCPWM_TRIGGER_POSTSCALER = CONFIG_DRV_MCPWM_CHANNEL_TRIGGER_POSTSCALER_IDX10
MCPWM_PRIMARY_TRIGGER_CYCLE_SELECT = CONFIG_DRV_MCPWM_CHANNEL_PRIMARY_TRIGGER_CYCLE_SELECT_IDX10
MCPWM_SECONDARY_TRIGGER_CYCLE_SELECT = CONFIG_DRV_MCPWM_CHANNEL_SECONDARY_TRIGGER_CYCLE_SELECT_IDX10
MCPWM_ADC_TRIGGER_SOURCE = CONFIG_DRV_MCPWM_CHANNEL_ADC_TRIGGER_SOURCE_IDX10
MCPWM_TRIGGER_INTERRUPT_SOURCE = CONFIG_DRV_MCPWM_CHANNEL_TRIGGER_INTERRUPT_SOURCE_IDX10
MCPWM_PRIMARY_TRIGGER_COMPARE_VALUE = CONFIG_DRV_MCPWM_CHANNEL_PRIMARY_TRIGGER_COMPARE_VALUE_IDX10
MCPWM_SECONDARY_TRIGGER_COMPARE_VALUE = CONFIG_DRV_MCPWM_CHANNEL_SECONDARY_TRIGGER_COMPARE_VALUE_IDX10
MCPWM_TRIGGER_INTERRUPT_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_TRIGGER_INTERRUPT_ENABLE_IDX10
MCPWM_LEB_TRIGGER_PWMxHRISINGEDGE_ENABLE =CONFIG_DRV_MCPWM_CHANNEL_LEB_TRIGGER_PWMxHRISINGEDGE_ENABLE_IDX10
MCPWM_LEB_TRIGGER_PWMxHFALLINGEDGE_ENABLE =CONFIG_DRV_MCPWM_CHANNEL_LEB_TRIGGER_PWMxHFALLINGEDGE_ENABLE_IDX10
MCPWM_LEB_TRIGGER_PWMxLRISINGEDGE_ENABLE =CONFIG_DRV_MCPWM_CHANNEL_LEB_TRIGGER_PWMxLRISINGEDGE_ENABLE_IDX10
MCPWM_LEB_TRIGGER_PWMxLFALLINGEDGE_ENABLE =CONFIG_DRV_MCPWM_CHANNEL_LEB_TRIGGER_PWMxLFALLINGEDGE_ENABLE_IDX10
MCPWM_FAULT_INPUT_LEB_CONTROL = CONFIG_DRV_MCPWM_CHANNEL_FAULT_INPUT_LEB_CONTROL_IDX10
MCPWM_CURRENTLIMIT_INPUT_LEB_CONTROL = CONFIG_DRV_MCPWM_CHANNEL_CURRENTLIMIT_INPUT_LEB_CONTROL_IDX10
MCPWM_LEB_PERIOD_VALUE = CONFIG_DRV_MCPWM_CHANNEL_LEB_PERIOD_VALUE_IDX10
MCPWM_CHOP_CLOCK_SOURCE = CONFIG_DRV_MCPWM_CHANNEL_CHOP_CLOCK_SOURCE_IDX10
MCPWM_PWMxH_CHOP_CONTROL = CONFIG_DRV_MCPWM_CHANNEL_PWMxH_CHOP_CONTROL_IDX10
MCPWM_PWMxL_CHOP_CONTROL = CONFIG_DRV_MCPWM_CHANNEL_PWMxL_CHOP_CONTROL_IDX10
MCPWM_FAULT_SOURCE = CONFIG_DRV_MCPWM_CHANNEL_FAULT_SOURCE_IDX10
MCPWM_FAULT_INPUT_POLARITY = CONFIG_DRV_MCPWM_CHANNEL_FAULT_INPUT_POLARITY_IDX10
MCPWM_FAULT_OVERRIDE_PWMxH_VALUE = CONFIG_DRV_MCPWM_CHANNEL_FAULT_OVERRIDE_PWMxH_VALUE_IDX10
MCPWM_FAULT_OVERRIDE_PWMxL_VALUE = CONFIG_DRV_MCPWM_CHANNEL_FAULT_OVERRIDE_PWMxL_VALUE_IDX10
MCPWM_FAULT_MODE = CONFIG_DRV_MCPWM_CHANNEL_FAULT_MODE_IDX10
MCPWM_FAULT_INTERRUPT_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_FAULT_INTERRUPT_ENABLE_IDX10
MCPWM_CURRENTLIMIT_SOURCE = CONFIG_DRV_MCPWM_CHANNEL_CURRENTLIMIT_SOURCE_IDX10
MCPWM_CURRENTLIMIT_INPUT_POLARITY = CONFIG_DRV_MCPWM_CHANNEL_CURRENTLIMIT_INPUT_POLARITY_IDX10
MCPWM_CURRENTLIMIT_OVERRIDE_PWMxH_VALUE =CONFIG_DRV_MCPWM_CHANNEL_CURRENTLIMIT_OVERRIDE_PWMxH_VALUE_IDX10
MCPWM_CURRENTLIMIT_OVERRIDE_PWMxL_VALUE =CONFIG_DRV_MCPWM_CHANNEL_CURRENTLIMIT_OVERRIDE_PWMxL_VALUE_IDX10
MCPWM_CURRENTLIMIT_MODE = CONFIG_DRV_MCPWM_CHANNEL_CURRENTLIMIT_MODE_IDX10
MCPWM_CURRENTLIMIT_INTERRUPT_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_CURRENTLIMIT_INTERRUPT_ENABLE_IDX10
MCPWM_OVERRIDE_PWMxH_VALUE =CONFIG_DRV_MCPWM_CHANNEL_OVERRIDE_PWMxH_VALUE_IDX10
MCPWM_OVERRIDE_PWMxL_VALUE =CONFIG_DRV_MCPWM_CHANNEL_OVERRIDE_PWMxL_VALUE_IDX10
MCPWM_OVERRIDE_PWMxH_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_OVERRIDE_PWMxH_ENABLE_IDX10
MCPWM_OVERRIDE_PWMxL_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_OVERRIDE_PWMxL_ENABLE_IDX10
MCPWM_SYNC_OVERRIDE_SELECT = CONFIG_DRV_MCPWM_CHANNEL_SYNC_OVERRIDE_SELECT_IDX10
MCPWM_PWMH_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_PWMH_ENABLE_IDX10
MCPWM_PERIOD_MATCH_INTERRUPT_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_PERIOD_MATCH_INTERRUPT_ENABLE_IDX10
MCPWM_PWML_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_PWML_ENABLE_IDX10
MCPWM_PERIOD_RESET_INTERRUPT_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_PERIOD_RESET_INTERRUPT_ENABLE_IDX10
MCPWM_SWAP_PWMH_PWML_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_SWAP_PWMH_PWML_IDX10
MCPWM_PDC_VALUE = CONFIG_DRV_MCPWM_PDC_VALUE_IDX10
MCPWM_SDC_VALUE = CONFIG_DRV_MCPWM_SDC_VALUE_IDX10
MCPWM_PHASE_VALUE = CONFIG_DRV_MCPWM_PHASE_VALUE_IDX10
MCPWM_DTR_VALUE = CONFIG_DRV_MCPWM_DTR_VALUE_IDX10
MCPWM_ALTDTR_VALUE = CONFIG_DRV_MCPWM_ALTDTR_VALUE_IDX10
MCPWM_DTCOMP_VALUE = CONFIG_DRV_MCPWM_DTCOMP_VALUE_IDX10
MCPWM_CHANNEL_INTERRUPT_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_INTERRUPT_ENABLE_IDX10
MCPWM_CHANNEL_INTERRUPT_PRIORITY = CONFIG_DRV_MCPWM_CHANNEL_INTERRUPT_PRIORITY_IDX10
MCPWM_CHANNEL_INTERRUPT_SUBPRIORITY = CONFIG_DRV_MCPWM_CHANNEL_INTERRUPT_SUBPRIORITY_IDX10
MCPWM_CHANNEL_INTERRUPT_VECTOR = CONFIG_DRV_MCPWM_CHANNEL_INTERRUPT_VECTOR_IDX10
MCPWM_CHANNEL_INTERRUPT_SOURCE = CONFIG_DRV_MCPWM_CHANNEL_INTERRUPT_SOURCE_IDX10/>
</#if>


<#if CONFIG_DRV_MCPWM_INST_IDX11 == true>
<@DRV_MCPWM_STATIC_FUNCTIONS MCPWM_CHANNEL_INSTANCE=CONFIG_DRV_MCPWM_CHANNEL_ID_IDX11 
MCPWM_TIME_BASE_SOURCE = CONFIG_DRV_MCPWM_CHANNEL_TIME_BASE_SOURCE_IDX11 
MCPWM_TIME_BASE_MODE = CONFIG_DRV_MCPWM_CHANNEL_TIME_BASE_MODE_IDX11
MCPWM_ALIGNMENT_MODE = CONFIG_DRV_MCPWM_CHANNEL_ALIGNMENT_MODE_IDX11
MCPWM_OUTPUT_MODE = CONFIG_DRV_MCPWM_CHANNEL_OUTPUT_MODE_IDX11
MCPWM_PWMxH_OUTPUT_POLARITY = CONFIG_DRV_MCPWM_CHANNEL_PWMxH_OUTPUT_POLARITY_IDX11
MCPWM_PWMxL_OUTPUT_POLARITY = CONFIG_DRV_MCPWM_CHANNEL_PWMxL_OUTPUT_POLARITY_IDX11
MCPWM_DEADTIME_MODE = CONFIG_DRV_MCPWM_CHANNEL_DEADTIME_MODE_IDX11
MCPWM_DEADTIME_POLARITY = CONFIG_DRV_MCPWM_CHANNEL_DEADTIME_COMPENSATION_POLARITY_IDX11
MCPWM_TRIGGER_POSTSCALER = CONFIG_DRV_MCPWM_CHANNEL_TRIGGER_POSTSCALER_IDX11
MCPWM_PRIMARY_TRIGGER_CYCLE_SELECT = CONFIG_DRV_MCPWM_CHANNEL_PRIMARY_TRIGGER_CYCLE_SELECT_IDX11
MCPWM_SECONDARY_TRIGGER_CYCLE_SELECT = CONFIG_DRV_MCPWM_CHANNEL_SECONDARY_TRIGGER_CYCLE_SELECT_IDX11
MCPWM_ADC_TRIGGER_SOURCE = CONFIG_DRV_MCPWM_CHANNEL_ADC_TRIGGER_SOURCE_IDX11
MCPWM_TRIGGER_INTERRUPT_SOURCE = CONFIG_DRV_MCPWM_CHANNEL_TRIGGER_INTERRUPT_SOURCE_IDX11
MCPWM_PRIMARY_TRIGGER_COMPARE_VALUE = CONFIG_DRV_MCPWM_CHANNEL_PRIMARY_TRIGGER_COMPARE_VALUE_IDX11
MCPWM_SECONDARY_TRIGGER_COMPARE_VALUE = CONFIG_DRV_MCPWM_CHANNEL_SECONDARY_TRIGGER_COMPARE_VALUE_IDX11
MCPWM_TRIGGER_INTERRUPT_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_TRIGGER_INTERRUPT_ENABLE_IDX11
MCPWM_LEB_TRIGGER_PWMxHRISINGEDGE_ENABLE =CONFIG_DRV_MCPWM_CHANNEL_LEB_TRIGGER_PWMxHRISINGEDGE_ENABLE_IDX11
MCPWM_LEB_TRIGGER_PWMxHFALLINGEDGE_ENABLE =CONFIG_DRV_MCPWM_CHANNEL_LEB_TRIGGER_PWMxHFALLINGEDGE_ENABLE_IDX11
MCPWM_LEB_TRIGGER_PWMxLRISINGEDGE_ENABLE =CONFIG_DRV_MCPWM_CHANNEL_LEB_TRIGGER_PWMxLRISINGEDGE_ENABLE_IDX11
MCPWM_LEB_TRIGGER_PWMxLFALLINGEDGE_ENABLE =CONFIG_DRV_MCPWM_CHANNEL_LEB_TRIGGER_PWMxLFALLINGEDGE_ENABLE_IDX11
MCPWM_FAULT_INPUT_LEB_CONTROL = CONFIG_DRV_MCPWM_CHANNEL_FAULT_INPUT_LEB_CONTROL_IDX11
MCPWM_CURRENTLIMIT_INPUT_LEB_CONTROL = CONFIG_DRV_MCPWM_CHANNEL_CURRENTLIMIT_INPUT_LEB_CONTROL_IDX11
MCPWM_LEB_PERIOD_VALUE = CONFIG_DRV_MCPWM_CHANNEL_LEB_PERIOD_VALUE_IDX11
MCPWM_CHOP_CLOCK_SOURCE = CONFIG_DRV_MCPWM_CHANNEL_CHOP_CLOCK_SOURCE_IDX11
MCPWM_PWMxH_CHOP_CONTROL = CONFIG_DRV_MCPWM_CHANNEL_PWMxH_CHOP_CONTROL_IDX11
MCPWM_PWMxL_CHOP_CONTROL = CONFIG_DRV_MCPWM_CHANNEL_PWMxL_CHOP_CONTROL_IDX11
MCPWM_FAULT_SOURCE = CONFIG_DRV_MCPWM_CHANNEL_FAULT_SOURCE_IDX11
MCPWM_FAULT_INPUT_POLARITY = CONFIG_DRV_MCPWM_CHANNEL_FAULT_INPUT_POLARITY_IDX11
MCPWM_FAULT_OVERRIDE_PWMxH_VALUE = CONFIG_DRV_MCPWM_CHANNEL_FAULT_OVERRIDE_PWMxH_VALUE_IDX11
MCPWM_FAULT_OVERRIDE_PWMxL_VALUE = CONFIG_DRV_MCPWM_CHANNEL_FAULT_OVERRIDE_PWMxL_VALUE_IDX11
MCPWM_FAULT_MODE = CONFIG_DRV_MCPWM_CHANNEL_FAULT_MODE_IDX11
MCPWM_FAULT_INTERRUPT_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_FAULT_INTERRUPT_ENABLE_IDX11
MCPWM_CURRENTLIMIT_SOURCE = CONFIG_DRV_MCPWM_CHANNEL_CURRENTLIMIT_SOURCE_IDX11
MCPWM_CURRENTLIMIT_INPUT_POLARITY = CONFIG_DRV_MCPWM_CHANNEL_CURRENTLIMIT_INPUT_POLARITY_IDX11
MCPWM_CURRENTLIMIT_OVERRIDE_PWMxH_VALUE =CONFIG_DRV_MCPWM_CHANNEL_CURRENTLIMIT_OVERRIDE_PWMxH_VALUE_IDX11
MCPWM_CURRENTLIMIT_OVERRIDE_PWMxL_VALUE =CONFIG_DRV_MCPWM_CHANNEL_CURRENTLIMIT_OVERRIDE_PWMxL_VALUE_IDX11
MCPWM_CURRENTLIMIT_MODE = CONFIG_DRV_MCPWM_CHANNEL_CURRENTLIMIT_MODE_IDX11
MCPWM_CURRENTLIMIT_INTERRUPT_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_CURRENTLIMIT_INTERRUPT_ENABLE_IDX11
MCPWM_OVERRIDE_PWMxH_VALUE =CONFIG_DRV_MCPWM_CHANNEL_OVERRIDE_PWMxH_VALUE_IDX11
MCPWM_OVERRIDE_PWMxL_VALUE =CONFIG_DRV_MCPWM_CHANNEL_OVERRIDE_PWMxL_VALUE_IDX11
MCPWM_OVERRIDE_PWMxH_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_OVERRIDE_PWMxH_ENABLE_IDX11
MCPWM_OVERRIDE_PWMxL_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_OVERRIDE_PWMxL_ENABLE_IDX11
MCPWM_SYNC_OVERRIDE_SELECT = CONFIG_DRV_MCPWM_CHANNEL_SYNC_OVERRIDE_SELECT_IDX11
MCPWM_PWMH_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_PWMH_ENABLE_IDX11
MCPWM_PERIOD_MATCH_INTERRUPT_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_PERIOD_MATCH_INTERRUPT_ENABLE_IDX11
MCPWM_PWML_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_PWML_ENABLE_IDX11
MCPWM_PERIOD_RESET_INTERRUPT_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_PERIOD_RESET_INTERRUPT_ENABLE_IDX11
MCPWM_SWAP_PWMH_PWML_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_SWAP_PWMH_PWML_IDX11
MCPWM_PDC_VALUE = CONFIG_DRV_MCPWM_PDC_VALUE_IDX11
MCPWM_SDC_VALUE = CONFIG_DRV_MCPWM_SDC_VALUE_IDX11
MCPWM_PHASE_VALUE = CONFIG_DRV_MCPWM_PHASE_VALUE_IDX11
MCPWM_DTR_VALUE = CONFIG_DRV_MCPWM_DTR_VALUE_IDX11
MCPWM_ALTDTR_VALUE = CONFIG_DRV_MCPWM_ALTDTR_VALUE_IDX11
MCPWM_DTCOMP_VALUE = CONFIG_DRV_MCPWM_DTCOMP_VALUE_IDX11
MCPWM_CHANNEL_INTERRUPT_ENABLE = CONFIG_DRV_MCPWM_CHANNEL_INTERRUPT_ENABLE_IDX11
MCPWM_CHANNEL_INTERRUPT_PRIORITY = CONFIG_DRV_MCPWM_CHANNEL_INTERRUPT_PRIORITY_IDX11
MCPWM_CHANNEL_INTERRUPT_SUBPRIORITY = CONFIG_DRV_MCPWM_CHANNEL_INTERRUPT_SUBPRIORITY_IDX11
MCPWM_CHANNEL_INTERRUPT_VECTOR = CONFIG_DRV_MCPWM_CHANNEL_INTERRUPT_VECTOR_IDX11
MCPWM_CHANNEL_INTERRUPT_SOURCE = CONFIG_DRV_MCPWM_CHANNEL_INTERRUPT_SOURCE_IDX11/>
</#if>

}

/*******************************************************************************
 End of File
*/
